package eu.exeris.tooling.codegen.java.service;

import eu.exeris.tooling.codegen.core.PluggableBackend;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * Generates JPA repository interfaces with framework-specific base classes.
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public final class RepositoryGenerator {

    private final PluggableBackend backend;

    public RepositoryGenerator() {
        this(PluggableBackend.SPRING);
    }

    public RepositoryGenerator(PluggableBackend backend) {
        this.backend = Objects.requireNonNull(backend, "backend cannot be null");
    }

    /**
     * Generates repository interface source code.
     */
    public String generate(DomainMetadata metadata) {
        String entity = metadata.entityName();
        String pkg = buildRepositoryPackage(metadata.packageName());
        String repoName = entity + "Repository";
        String now = DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(OffsetDateTime.now());

        String baseRepo = backend.repositoryBase();
        String specExecutor = backend.specificationExecutor();

        String baseRepoSimple = baseRepo.substring(baseRepo.lastIndexOf('.') + 1);

        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(pkg).append(";\n\n");

        // Imports
        sb.append("import ").append(metadata.fullyQualifiedName()).append(";\n");
        sb.append("import ").append(baseRepo).append(";\n");
        if (!specExecutor.isBlank()) {
            sb.append("import ").append(specExecutor).append(";\n");
        }
        sb.append("import java.util.UUID;\n\n");

        // Header
        sb.append("/**\n");
        sb.append(" * ").append(repoName).append(" - JPA repository for ").append(entity).append(".\n");
        sb.append(" * Generated from: ").append(metadata.fullyQualifiedName()).append("\n");
        sb.append(" * Generated at: ").append(now).append("\n");
        sb.append(" * Backend: ").append(backend.name()).append("\n");
        sb.append(" * \n");
        sb.append(" * DO NOT EDIT - This file is auto-generated by Exeris Tooling.\n");
        sb.append(" */\n");

        // Repository annotation (if needed)
        if (!backend.repositoryAnnotation().isBlank()) {
            sb.append(backend.repositoryAnnotation()).append("\n");
        }

        // Interface declaration
        sb.append("public interface ").append(repoName);
        sb.append(" extends ").append(baseRepoSimple).append("<").append(entity).append(", UUID>");

        if (!specExecutor.isBlank()) {
            String specSimple = specExecutor.substring(specExecutor.lastIndexOf('.') + 1);
            sb.append(", ").append(specSimple).append("<").append(entity).append(">");
        }

        sb.append(" {\n\n");
        sb.append("    // Custom query methods can be added here\n\n");
        sb.append("}\n");

        return sb.toString();
    }

    private String buildRepositoryPackage(String domainPackage) {
        int lastDot = domainPackage.lastIndexOf('.');
        if (lastDot <= 0) {
            return "repository";
        }
        String base = domainPackage.substring(0, lastDot);
        return base + ".repository";
    }
}

