/**
 * Angular Detail View Generator
 *
 * Generates Angular 22+ detail view components with:
 * - Signal-based state management
 * - rxResource (RxJS-interop Resource) for data fetching
 * - Loading/error states
 * - Full a11y support
 * - i18n-ready strings
 *
 * @author Exeris Team
 * @since 0.4.0
 */

import type { DomainMetadata, FieldMetadata, CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { outPath } from '../../core/paths.js';

export class DetailGenerator implements CodeGenerator {
  readonly name = 'DetailGenerator';
  readonly artifactType = 'DETAIL' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 20;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (domain.internalApi?.hidden) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateDetailContent(domain, context);

    return {
      path: outPath('components', `${kebab}-detail.component.ts`),
      content,
      artifactType: 'DETAIL',
      overwritable: true,
    };
  }

  private generateDetailContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName, fields = [] } = domain;
    const kebab = DslMapper.toKebabCase(entityName);
    const displayName = domain.displayName ?? entityName;
    const idField = domain.systemFields?.idField ?? 'id';

    const systemFieldNames = this.getSystemFieldNames(domain);
    const displayFields = fields.filter(f => !systemFieldNames.includes(f.name) && !f.hidden);
    const enumTypes = this.collectEnumTypes(fields);

    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * ${entityName} Detail View Component`);
    lines.push(` * Generated by @exeris/codegen-ts v0.4.0`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` */`);
    lines.push(``);
    lines.push(`import {`);
    lines.push(`  Component,`);
    lines.push(`  ChangeDetectionStrategy,`);
    lines.push(`  inject,`);
    lines.push(`  signal,`);
    lines.push(`  computed,`);
    lines.push(`  input,`);
    lines.push(`} from '@angular/core';`);
    lines.push(`import { rxResource } from '@angular/core/rxjs-interop';`);
    lines.push(`import { CommonModule, DatePipe } from '@angular/common';`);
    lines.push(`import { RouterModule, Router } from '@angular/router';`);
    lines.push(`import { ${entityName}Service } from '../services/${kebab}.service';`);
    lines.push(`import type { ${entityName} } from '../types/${kebab}.types';`);

    if (enumTypes.length > 0) {
      lines.push(`import { ${enumTypes.flatMap(e => [e, `${e}DisplayNames`]).join(', ')} } from '../types/enums';`);
    }
    lines.push(``);

    lines.push(`interface FieldDisplay {`);
    lines.push(`  name: keyof ${entityName};`);
    lines.push(`  label: string;`);
    lines.push(`  type: 'text' | 'number' | 'boolean' | 'date' | 'datetime' | 'enum';`);
    lines.push(`  enumType?: string;`);
    lines.push(`  dataType?: 'currency' | 'percent' | 'url';`);
    lines.push(`}`);
    lines.push(``);

    lines.push(`const DISPLAY_FIELDS: FieldDisplay[] = [`);
    for (const field of displayFields) {
      const mapping = DslMapper.mapField(field);
      const fieldType = this.getDisplayType(field);
      const enumTypeName = this.getEnumTypeName(field);
      // @Field.dataType — front-presentation hint (Wave 1A, additive). Only the
      // currency/percent/url facets drive a distinct render; any other value is
      // ignored and the default formatValue() path applies.
      const dataType = field.dataType === 'currency' || field.dataType === 'percent' || field.dataType === 'url'
        ? field.dataType
        : undefined;
      lines.push(`  { name: '${field.name}' as keyof ${entityName}, label: $localize\`:@@${kebab}.field.${field.name}:${mapping.label}\`, type: '${fieldType}'${enumTypeName ? `, enumType: '${enumTypeName}'` : ''}${dataType ? `, dataType: '${dataType}'` : ''} },`);
    }
    lines.push(`];`);
    lines.push(``);

    lines.push(`@Component({`);
    lines.push(`  selector: 'app-${kebab}-detail',`);
    lines.push(`  standalone: true,`);
    lines.push(`  imports: [CommonModule, RouterModule, DatePipe],`);
    lines.push(`  changeDetection: ChangeDetectionStrategy.OnPush,`);
    lines.push(`  template: \``);
    lines.push(`    <article role="article" [attr.aria-labelledby]="'detail-title'" [attr.aria-busy]="isLoading()" class="max-w-4xl mx-auto">`);
    lines.push(`      @if (isLoading()) {`);
    lines.push(`        <div class="animate-pulse space-y-4" role="status" aria-label="Loading...">`);
    lines.push(`          <div class="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/3"></div>`);
    lines.push(`          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2"></div>`);
    lines.push(`        </div>`);
    lines.push(`      } @else if (error()) {`);
    lines.push(`        <div role="alert" class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-6">`);
    lines.push(`          <p class="text-red-700 dark:text-red-300">{{ error() }}</p>`);
    lines.push(`          <button (click)="reload()" class="mt-4 text-sm font-medium text-red-600">Try again</button>`);
    lines.push(`        </div>`);
    lines.push(`      } @else if (entity()) {`);
    lines.push(`        <header class="mb-8 flex items-center justify-between">`);
    lines.push(`          <h1 id="detail-title" class="text-2xl font-bold text-gray-900 dark:text-white">{{ getTitle() }}</h1>`);
    lines.push(`          <nav class="flex gap-3">`);
    lines.push(`            <a [routerLink]="['edit']" class="px-4 py-2 text-sm font-medium text-white bg-exeris-primary rounded-md hover:bg-exeris-primary-hover">Edit</a>`);
    lines.push(`            <button (click)="onDelete()" class="px-4 py-2 text-sm font-medium text-red-700 bg-red-100 rounded-md hover:bg-red-200">Delete</button>`);
    lines.push(`          </nav>`);
    lines.push(`        </header>`);
    lines.push(`        <section class="bg-white dark:bg-gray-800 shadow rounded-lg overflow-hidden">`);
    lines.push(`          <dl class="divide-y divide-gray-200 dark:divide-gray-700">`);
    lines.push(`            @for (field of displayFields; track field.name) {`);
    lines.push(`              <div class="px-4 py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">`);
    lines.push(`                <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">{{ field.label }}</dt>`);
    lines.push(`                <dd class="mt-1 text-sm text-gray-900 dark:text-white sm:mt-0 sm:col-span-2">`);
    // @Field.dataType render facets (Wave 1A): currency/percent pipes and url anchor
    // operate on the raw entity value; every other field falls through to formatValue().
    lines.push(`                  @switch (field.dataType) {`);
    lines.push(`                    @case ('currency') { {{ rawValue(field, entity()) | currency }} }`);
    lines.push(`                    @case ('percent') { {{ rawValue(field, entity()) | percent }} }`);
    lines.push(`                    @case ('url') { <a [href]="rawValue(field, entity())" class="text-exeris-primary hover:underline">{{ rawValue(field, entity()) }}</a> }`);
    lines.push(`                    @default { {{ formatValue(field, entity()) }} }`);
    lines.push(`                  }`);
    lines.push(`                </dd>`);
    lines.push(`              </div>`);
    lines.push(`            }`);
    lines.push(`          </dl>`);
    lines.push(`        </section>`);
    lines.push(`        <section class="mt-8 bg-gray-50 dark:bg-gray-800/50 rounded-lg p-6">`);
    lines.push(`          <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-4">System Information</h3>`);
    lines.push(`          <dl class="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">`);
    lines.push(`            <div><dt class="text-gray-400">ID</dt><dd class="font-mono text-gray-600 dark:text-gray-300">{{ entity()?.${idField} }}</dd></div>`);
    lines.push(`            @if (entity()?.createdAt) { <div><dt class="text-gray-400">Created</dt><dd>{{ entity()?.createdAt | date:'medium' }}</dd></div> }`);
    lines.push(`            @if (entity()?.updatedAt) { <div><dt class="text-gray-400">Updated</dt><dd>{{ entity()?.updatedAt | date:'medium' }}</dd></div> }`);
    lines.push(`          </dl>`);
    lines.push(`        </section>`);
    lines.push(`      }`);
    lines.push(`    </article>`);
    lines.push(`  \`,`);
    lines.push(`})`);

    lines.push(`export class ${entityName}DetailComponent {`);
    lines.push(`  private readonly router = inject(Router);`);
    lines.push(`  private readonly service = inject(${entityName}Service);`);
    lines.push(``);
    lines.push(`  readonly id = input.required<string>();`);
    lines.push(`  readonly displayFields = DISPLAY_FIELDS;`);
    lines.push(``);
    lines.push(`  private readonly entityResource = rxResource({`);
    lines.push(`    params: () => this.id(),`);
    lines.push(`    stream: ({ params }) => this.service.findById(params),`);
    lines.push(`  });`);
    lines.push(``);
    lines.push(`  readonly entity = computed(() => this.entityResource.value() ?? null);`);
    lines.push(`  readonly isLoading = computed(() => this.entityResource.isLoading());`);
    lines.push(`  readonly error = computed(() => {`);
    lines.push(`    const err = this.entityResource.error();`);
    lines.push(`    return err instanceof Error ? err.message : err ? String(err) : null;`);
    lines.push(`  });`);
    lines.push(``);

    for (const enumType of enumTypes) {
      // Per-enum DisplayNames map exposed as a class field for the
      // formatValue() switch. Identifier mirrors the enum name with
      // the FIRST char lowercased only (camelCase) — using a full
      // .toLowerCase() here would produce `orderstatusDisplayNames`
      // for OrderStatus, breaking the casing convention and making
      // multi-cap enums (e.g. OAuthClient → oauthclientDisplayNames)
      // unreadable. Lower-first preserves all subsequent capitals.
      const fieldName = enumType.charAt(0).toLowerCase() + enumType.slice(1) + 'DisplayNames';
      lines.push(`  private readonly ${fieldName} = ${enumType}DisplayNames;`);
    }
    if (enumTypes.length > 0) lines.push(``);

    const nameField = displayFields.find(f => f.name === 'name' || f.name === 'title');
    lines.push(`  getTitle(): string {`);
    lines.push(`    const entity = this.entity();`);
    lines.push(`    if (!entity) return '';`);
    lines.push(`    return ${nameField ? `entity.${nameField.name} ?? String(entity.${idField})` : `String(entity.${idField})`};`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  rawValue(field: FieldDisplay, entity: ${entityName} | null): unknown {`);
    lines.push(`    if (!entity) return null;`);
    lines.push(`    return entity[field.name as keyof ${entityName}] ?? null;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  formatValue(field: FieldDisplay, entity: ${entityName} | null): string {`);
    lines.push(`    if (!entity) return '';`);
    lines.push(`    const value = entity[field.name as keyof ${entityName}];`);
    lines.push(`    if (value === null || value === undefined) return '—';`);
    lines.push(`    switch (field.type) {`);
    lines.push(`      case 'boolean': return value ? 'Yes' : 'No';`);
    lines.push(`      case 'date': return new Date(value as string).toLocaleDateString();`);
    lines.push(`      case 'datetime': return new Date(value as string).toLocaleString();`);
    lines.push(`      case 'enum': return this.getEnumDisplayName(field.enumType ?? '', value as string);`);
    lines.push(`      default: return String(value);`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  private getEnumDisplayName(enumType: string, value: string): string {`);
    lines.push(`    switch (enumType) {`);
    for (const enumType of enumTypes) {
      lines.push(`      case '${enumType}': return this.${enumType.charAt(0).toLowerCase() + enumType.slice(1)}DisplayNames[value as keyof typeof this.${enumType.charAt(0).toLowerCase() + enumType.slice(1)}DisplayNames] ?? value;`);
    }
    lines.push(`      default: return value;`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  reload(): void { this.entityResource.reload(); }`);
    lines.push(``);

    lines.push(`  onDelete(): void {`);
    lines.push(`    if (confirm('Are you sure you want to delete this ${displayName.toLowerCase()}?')) {`);
    lines.push(`      this.service.delete(this.id()).subscribe({`);
    lines.push(`        next: () => this.router.navigate(['/${kebab}s']),`);
    lines.push(`        error: (err) => alert('Failed to delete'),`);
    lines.push(`      });`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`}`);

    return lines.join('\n');
  }

  private getSystemFieldNames(domain: DomainMetadata): string[] {
    const fields = ['id', 'version', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'tenantId', 'deletedAt', 'deleted'];
    const sf = domain.systemFields;
    if (sf) {
      if (sf.idField) fields.push(sf.idField);
      if (sf.versionField) fields.push(sf.versionField);
      if (sf.createdAtField) fields.push(sf.createdAtField);
      if (sf.updatedAtField) fields.push(sf.updatedAtField);
    }
    return [...new Set(fields)];
  }

  private getDisplayType(field: FieldMetadata): string {
    const type = field.type;
    if (field.enumType || this.isEnumType(type)) return 'enum';
    if (type === 'Boolean' || type === 'boolean') return 'boolean';
    if (type.includes('LocalDate') && !type.includes('DateTime')) return 'date';
    if (type.includes('Instant') || type.includes('DateTime')) return 'datetime';
    if (type.includes('Integer') || type.includes('Long') || type === 'number') return 'number';
    return 'text';
  }

  private isEnumType(type: string): boolean {
    const knownTypes = new Set(['String', 'Integer', 'Long', 'Double', 'Float', 'Boolean', 'BigDecimal', 'UUID', 'Instant', 'LocalDate', 'LocalDateTime']);
    if (knownTypes.has(type)) return false;
    if (type.includes('<') || type.endsWith('[]') || type.startsWith('java.')) return false;
    const simpleName = type.includes('.') ? type.split('.').pop()! : type;
    return /^[A-Z][a-zA-Z0-9]*$/.test(simpleName) &&
      (simpleName.endsWith('Status') || simpleName.endsWith('Type') || simpleName.endsWith('Role') || simpleName.endsWith('State'));
  }

  private getEnumTypeName(field: FieldMetadata): string | undefined {
    if (field.enumType) return field.enumType.includes('.') ? field.enumType.split('.').pop()! : field.enumType;
    if (this.isEnumType(field.type)) return field.type.includes('.') ? field.type.split('.').pop()! : field.type;
    return undefined;
  }

  private collectEnumTypes(fields: FieldMetadata[]): string[] {
    const enums = new Set<string>();
    for (const field of fields) {
      const enumType = this.getEnumTypeName(field);
      if (enumType) enums.add(enumType);
    }
    return [...enums];
  }
}

export function generateDetail(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile {
  const generator = new DetailGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context)!;
}

