/**
 * Angular Detail View Generator
 *
 * Generates Angular 22+ detail view components with:
 * - Signal-based state management
 * - rxResource (RxJS-interop Resource) for data fetching
 * - Loading/error states
 * - Full a11y support
 * - i18n-ready strings
 */

import type { DomainMetadata, CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import { modelTypeName } from '../../models/model-naming.js';
import type { GeneratorConfig } from '../../config.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { outPath } from '../../core/paths.js';
import { tsSingleQuoted } from './ts-literal.js';
import { auditFieldNames, updateVersionField, viewSystemFieldNames } from '../api/type-gen.js';
import { fieldRenderContext, resolveFieldRenders } from './field-render.js';
import { entityExitRoute, entityViews } from './entity-views.js';

export class DetailGenerator implements CodeGenerator {
  readonly name = 'DetailGenerator';
  readonly artifactType = 'DETAIL' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 20;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (!entityViews(domain).detail) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateDetailContent(domain, context);

    return {
      path: outPath('components', `${kebab}-detail.component.ts`),
      content,
      artifactType: 'DETAIL',
      overwritable: true,
    };
  }

  private generateDetailContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName } = domain;
    const modelName = modelTypeName(entityName);
    const kebab = DslMapper.toKebabCase(entityName);
    const displayName = domain.displayName ?? entityName;
    const noun = tsSingleQuoted(displayName.toLowerCase());
    // The literal 'id', deliberately, not systemFields.primaryKeyField. Nothing in the pipeline
    // honours that override: KernelFlywayGenerator emits `id UUID PRIMARY KEY` unconditionally,
    // KernelRepositoryGenerator's WHERE clause is the constant " WHERE id = ?", every by-id
    // handler binds the {id} path variable, and the processor says so outright ("generators leave
    // the primary key as the literal id"). Reading it here would make this the only layer that
    // honours it, and the emitted app would then request the wrong identifier.
    const idField = 'id';

    const renders = resolveFieldRenders(
      domain,
      fieldRenderContext(domain, context.allDomains, context.config.generateDetails !== false),
    );
    const displayFields = renders.filter((r) => r.displayed);
    // Every field's enum is imported, a hidden or system one included, in declaration order.
    const enumTypes = [...new Set(renders.flatMap((r) => (r.detail.enumType ? [r.detail.enumType] : [])))];
    const hasLinks = renders.some((r) => r.link !== undefined);
    const views = entityViews(domain);

    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * ${entityName} Detail View Component`);
    lines.push(` * Generated by @exeris/codegen-ts`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` */`);
    lines.push(``);
    lines.push(`import {`);
    lines.push(`  Component,`);
    lines.push(`  ChangeDetectionStrategy,`);
    lines.push(`  inject,`);
    lines.push(`  signal,`);
    lines.push(`  computed,`);
    lines.push(`  input,`);
    lines.push(`} from '@angular/core';`);
    lines.push(`import { rxResource } from '@angular/core/rxjs-interop';`);
    const panelRows = systemPanelRows(domain);
    const stamps = panelRows.filter((row) => row.kind === 'date');
    const undeclaredRows = panelRows.filter((row) => !row.declared);
    // DatePipe is only imported when something renders a date: Angular reports an unused
    // standalone import against the template.
    lines.push(stamps.length > 0
      ? `import { CommonModule, DatePipe } from '@angular/common';`
      : `import { CommonModule } from '@angular/common';`);
    lines.push(`import { RouterModule, Router } from '@angular/router';`);
    lines.push(`import { ${entityName}Service } from '../services/${kebab}.service';`);
    lines.push(`import { httpErrorMessage } from '../core/http-error';`);
    lines.push(`import type { ${modelName} } from '../types/${kebab}.types';`);

    if (enumTypes.length > 0) {
      lines.push(`import { ${enumTypes.flatMap(e => [e, `${e}DisplayNames`]).join(', ')} } from '../types/enums';`);
    }
    lines.push(``);

    lines.push(`interface FieldDisplay {`);
    lines.push(`  name: keyof ${modelName};`);
    lines.push(`  label: string;`);
    lines.push(`  type: 'text' | 'number' | 'boolean' | 'date' | 'datetime' | 'enum';`);
    lines.push(`  enumType?: string;`);
    lines.push(`  dataType?: 'currency' | 'percent' | 'url';`);
    if (hasLinks) {
      lines.push(`  link?: string;`);
    }
    lines.push(`}`);
    lines.push(``);

    lines.push(`const DISPLAY_FIELDS: FieldDisplay[] = [`);
    for (const field of displayFields) {
      // Only the currency/percent/url facets of @Field.dataType drive a distinct render; any other
      // value is absent here and the default formatValue() path applies.
      const { display, enumType, dataType } = field.detail;
      lines.push(`  { name: '${field.name}' as keyof ${modelName}, label: '${tsSingleQuoted(field.label)}', type: '${display}'${enumType ? `, enumType: '${enumType}'` : ''}${dataType ? `, dataType: '${dataType}'` : ''}${field.link !== undefined ? `, link: '${field.link}'` : ''} },`);
    }
    lines.push(`];`);
    lines.push(``);

    lines.push(`@Component({`);
    lines.push(`  selector: 'app-${kebab}-detail',`);
    lines.push(`  standalone: true,`);
    lines.push(`  imports: [CommonModule, RouterModule${stamps.length > 0 ? ', DatePipe' : ''}],`);
    lines.push(`  changeDetection: ChangeDetectionStrategy.OnPush,`);
    lines.push(`  template: \``);
    lines.push(`    <article role="article" [attr.aria-labelledby]="'detail-title'" [attr.aria-busy]="isLoading()" class="max-w-4xl mx-auto">`);
    lines.push(`      @if (isLoading()) {`);
    lines.push(`        <div class="animate-pulse space-y-4" role="status" aria-label="Loading...">`);
    lines.push(`          <div class="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/3"></div>`);
    lines.push(`          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2"></div>`);
    lines.push(`        </div>`);
    lines.push(`      } @else if (error()) {`);
    lines.push(`        <div role="alert" class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-6">`);
    lines.push(`          <p class="text-red-700 dark:text-red-300">{{ error() }}</p>`);
    lines.push(`          <button (click)="reload()" class="mt-4 text-sm font-medium text-red-600">Try again</button>`);
    lines.push(`        </div>`);
    lines.push(`      } @else if (entity()) {`);
    lines.push(`        @if (deleteError()) {`);
    lines.push(`          <div role="alert" data-testid="delete-error" class="mb-6 rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-800 dark:bg-red-900/20 dark:text-red-300">{{ deleteError() }}</div>`);
    lines.push(`        }`);
    lines.push(`        <header class="mb-8 flex items-center justify-between">`);
    lines.push(`          <h1 id="detail-title" class="text-2xl font-bold text-gray-900 dark:text-white">{{ getTitle() }}</h1>`);
    lines.push(`          <nav class="flex gap-3">`);
    if (views.edit) {
      lines.push(`            <a [routerLink]="['edit']" class="px-4 py-2 text-sm font-medium text-white bg-exeris-primary rounded-md hover:bg-exeris-primary-hover">Edit</a>`);
    }
    lines.push(`            <button (click)="onDelete()" class="px-4 py-2 text-sm font-medium text-red-700 bg-red-100 rounded-md hover:bg-red-200">Delete</button>`);
    lines.push(`          </nav>`);
    lines.push(`        </header>`);
    lines.push(`        <section class="bg-white dark:bg-gray-800 shadow rounded-lg overflow-hidden">`);
    lines.push(`          <dl class="divide-y divide-gray-200 dark:divide-gray-700">`);
    lines.push(`            @for (field of displayFields; track field.name) {`);
    lines.push(`              <div class="px-4 py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">`);
    lines.push(`                <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">{{ field.label }}</dt>`);
    lines.push(`                <dd class="mt-1 text-sm text-gray-900 dark:text-white sm:mt-0 sm:col-span-2">`);
    // @Field.dataType render facets (Wave 1A): currency/percent pipes and url anchor
    // operate on the raw entity value; every other field falls through to formatValue().
    // A foreign key links to the target's detail page; an empty one falls through to the
    // switch, so it renders exactly as an unlinked field does.
    const sw = hasLinks ? '  ' : '';
    if (hasLinks) {
      lines.push(`                  @if (field.link && rawValue(field, entity()) !== null) {`);
      lines.push(`                    <a [routerLink]="[field.link, rawValue(field, entity())]" [attr.data-testid]="'link-' + field.name" class="font-mono text-exeris-primary hover:underline">{{ rawValue(field, entity()) }}</a>`);
      lines.push(`                  } @else {`);
    }
    lines.push(`${sw}                  @switch (field.dataType) {`);
    lines.push(`${sw}                    @case ('currency') { {{ numericValue(field, entity()) | currency }} }`);
    lines.push(`${sw}                    @case ('percent') { {{ numericValue(field, entity()) | percent }} }`);
    lines.push(`${sw}                    @case ('url') { <a [href]="rawValue(field, entity())" class="text-exeris-primary hover:underline">{{ rawValue(field, entity()) }}</a> }`);
    lines.push(`${sw}                    @default { {{ formatValue(field, entity()) }} }`);
    lines.push(`${sw}                  }`);
    if (hasLinks) {
      lines.push(`                  }`);
    }
    lines.push(`                </dd>`);
    lines.push(`              </div>`);
    lines.push(`            }`);
    lines.push(`          </dl>`);
    lines.push(`        </section>`);
    lines.push(`        <section class="mt-8 bg-gray-50 dark:bg-gray-800/50 rounded-lg p-6">`);
    lines.push(`          <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-4">System Information</h3>`);
    lines.push(`          <dl class="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">`);
    lines.push(`            <div><dt class="text-gray-400">ID</dt><dd class="font-mono text-gray-600 dark:text-gray-300">{{ entity()?.${idField} }}</dd></div>`);
    // A row the entity interface does not declare is read off systemInfo(), the narrowing cast
    // emitted below, so the template type-checks under strictTemplates.
    for (const row of panelRows) {
      const read = `${row.declared ? 'entity()' : 'systemInfo()'}?.${row.name}`;
      if (row.kind === 'date') {
        lines.push(`            @if (${read}) { <div><dt class="text-gray-400">${row.label}</dt><dd>{{ ${read} | date:'medium' }}</dd></div> }`);
      } else {
        // A version of 0 is a value, so the guard is a null check rather than truthiness.
        lines.push(`            @if (${read} != null) { <div><dt class="text-gray-400">${row.label}</dt><dd class="font-mono text-gray-600 dark:text-gray-300">{{ ${read} }}</dd></div> }`);
      }
    }
    lines.push(`          </dl>`);
    lines.push(`        </section>`);
    lines.push(`      }`);
    lines.push(`    </article>`);
    lines.push(`  \`,`);
    lines.push(`})`);

    lines.push(`export class ${entityName}DetailComponent {`);
    lines.push(`  private readonly router = inject(Router);`);
    lines.push(`  private readonly service = inject(${entityName}Service);`);
    lines.push(``);
    lines.push(`  readonly id = input.required<string>();`);
    lines.push(`  readonly displayFields = DISPLAY_FIELDS;`);
    if (undeclaredRows.length > 0) {
      const members = undeclaredRows
        .map((row) => `${row.name}?: ${row.kind === 'date' ? 'string' : 'number'}`)
        .join('; ');
      lines.push(`  /** The server-owned fields the ${modelName} interface does not declare, read through a narrowing cast. */`);
      lines.push(`  readonly systemInfo = computed(() => this.entity() as unknown as { ${members} } | null);`);
    }
    lines.push(``);
    lines.push(`  private readonly entityResource = rxResource({`);
    lines.push(`    params: () => this.id(),`);
    lines.push(`    stream: ({ params }) => this.service.findById(params),`);
    lines.push(`  });`);
    lines.push(``);
    lines.push(`  readonly entity = computed(() => this.entityResource.value() ?? null);`);
    lines.push(`  readonly isLoading = computed(() => this.entityResource.isLoading());`);
    lines.push(`  readonly error = computed(() => {`);
    lines.push(`    const err = this.entityResource.error();`);
    lines.push(`    return err ? httpErrorMessage(err, { entity: '${noun}', action: 'load' }) : null;`);
    lines.push(`  });`);
    lines.push(`  readonly deleteError = signal<string | null>(null);`);
    lines.push(``);

    for (const enumType of enumTypes) {
      // Per-enum DisplayNames map exposed as a class field for the
      // formatValue() switch. Identifier mirrors the enum name with
      // the FIRST char lowercased only (camelCase) — using a full
      // .toLowerCase() here would produce `orderstatusDisplayNames`
      // for OrderStatus, breaking the casing convention and making
      // multi-cap enums (e.g. OAuthClient → oauthclientDisplayNames)
      // unreadable. Lower-first preserves all subsequent capitals.
      const fieldName = enumType.charAt(0).toLowerCase() + enumType.slice(1) + 'DisplayNames';
      lines.push(`  private readonly ${fieldName} = ${enumType}DisplayNames;`);
    }
    if (enumTypes.length > 0) lines.push(``);

    const nameField = displayFields.find((f) => f.name === 'name' || f.name === 'title');
    lines.push(`  getTitle(): string {`);
    lines.push(`    const entity = this.entity();`);
    lines.push(`    if (!entity) return '';`);
    lines.push(`    return ${nameField ? `entity.${nameField.name} ?? String(entity.${idField})` : `String(entity.${idField})`};`);
    lines.push(`  }`);
    lines.push(``);

    // The currency/percent pipes accept `string | number | null | undefined`, never `unknown`.
    // Angular type-checks every @switch branch whether or not a field selects it, so `rawValue`
    // feeding those two pipes made EVERY emitted detail component fail with TS2769 — six errors
    // in the three-entity sample, none of which anything had ever compiled.
    lines.push(`  numericValue(field: FieldDisplay, entity: ${modelName} | null): number | null {`);
    lines.push(`    const value = this.rawValue(field, entity);`);
    // Null/absent stays null so the pipes render nothing, rather than Number(null) === 0
    // turning a missing amount into $0.00 — formatValue shows an em-dash for the same case.
    lines.push(`    if (value === null || value === undefined || value === '') return null;`);
    lines.push(`    const numeric = Number(value);`);
    lines.push(`    return Number.isFinite(numeric) ? numeric : null;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  rawValue(field: FieldDisplay, entity: ${modelName} | null): unknown {`);
    lines.push(`    if (!entity) return null;`);
    lines.push(`    return entity[field.name as keyof ${modelName}] ?? null;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  formatValue(field: FieldDisplay, entity: ${modelName} | null): string {`);
    lines.push(`    if (!entity) return '';`);
    lines.push(`    const value = entity[field.name as keyof ${modelName}];`);
    lines.push(`    if (value === null || value === undefined) return '—';`);
    lines.push(`    switch (field.type) {`);
    lines.push(`      case 'boolean': return value ? 'Yes' : 'No';`);
    lines.push(`      case 'date': return new Date(value as string).toLocaleDateString();`);
    lines.push(`      case 'datetime': return new Date(value as string).toLocaleString();`);
    lines.push(`      case 'enum': return this.getEnumDisplayName(field.enumType ?? '', value as string);`);
    lines.push(`      default: return String(value);`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  private getEnumDisplayName(enumType: string, value: string): string {`);
    lines.push(`    switch (enumType) {`);
    for (const enumType of enumTypes) {
      lines.push(`      case '${enumType}': return this.${enumType.charAt(0).toLowerCase() + enumType.slice(1)}DisplayNames[value as keyof typeof this.${enumType.charAt(0).toLowerCase() + enumType.slice(1)}DisplayNames] ?? value;`);
    }
    lines.push(`      default: return value;`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  reload(): void { this.entityResource.reload(); }`);
    lines.push(``);

    lines.push(`  onDelete(): void {`);
    lines.push(`    if (confirm('Are you sure you want to delete this ${displayName.toLowerCase()}?')) {`);
    lines.push(`      this.deleteError.set(null);`);
    lines.push(`      this.service.delete(this.id()).subscribe({`);
    // The list route, or the app root when the list is switched off: a route the table declares.
    lines.push(`        next: () => this.router.navigate(['${entityExitRoute(domain, views)}']),`);
    lines.push(`        error: (err) => this.deleteError.set(httpErrorMessage(err, { entity: '${noun}', action: 'delete' })),`);
    lines.push(`      });`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`}`);

    return lines.join('\n');
  }
}

/** A row of the detail view's system panel, after the id. */
interface SystemPanelRow {
  name: string;
  label: string;
  kind: 'date' | 'number';
  /** Whether the entity interface carries the property; an undeclared one is read through a cast. */
  declared: boolean;
}

/**
 * The audit stamps and the version the system panel shows, in that order.
 *
 * An `audited` entity always shows both stamps under the names `auditFieldNames` resolves: the
 * generated repository writes them on every row whether or not the entity declares them. On any
 * other entity a stamp shows only when the entity declares it and it is a system field, so a field
 * the field table leaves out appears here instead of nowhere. A `versioned` entity shows its version.
 */
function systemPanelRows(metadata: DomainMetadata): SystemPanelRow[] {
  const declared = new Set(metadata.fields.map((f) => f.name));
  const system = viewSystemFieldNames(metadata);
  const audit = auditFieldNames(metadata);
  const rows: SystemPanelRow[] = [];
  const stamps: Array<[string, string]> = [[audit.createdAt, 'Created'], [audit.updatedAt, 'Updated']];
  for (const [name, label] of stamps) {
    if (metadata.audited || (declared.has(name) && system.includes(name))) {
      rows.push({ name, label, kind: 'date', declared: declared.has(name) });
    }
  }
  const version = updateVersionField(metadata);
  if (version) rows.push({ name: version.name, label: 'Version', kind: 'number', declared: version.declared });
  return rows;
}

export function generateDetail(
  metadata: DomainMetadata,
  config: GeneratorConfig,
  allDomains: DomainMetadata[] = [metadata],
): GeneratedFile | null {
  const generator = new DetailGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains, enums: [] };
  return generator.generate(metadata, context);
}

