/**
 * Angular Event Subscription Handler Generator
 *
 * Generates event subscription handlers for real-time updates.
 * Features:
 * - SSE/WebSocket/WebTransport support
 * - Automatic reconnection
 * - Toast notifications
 * - Screen reader announcements (a11y)
 * - i18n-ready messages
 *
 * @author Exeris Team
 * @since 0.3.0
 */

import type { DomainMetadata, DomainEventMetadata } from '../../models/domain-model.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { DslMapper } from '../../models/dsl-mapper.js';


export class EventHandlerGenerator implements CodeGenerator {
  readonly name = 'EventHandlerGenerator';
  readonly artifactType = 'EVENT' as const;
  readonly supportedBackends: BackendType[] = ['KERNEL', 'SPRING', 'QUARKUS', 'MICRONAUT'];

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    // Only generate for domains with events
    if (!domain.events || domain.events.length === 0) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateEventHandlerContent(domain, context);

    return {
      path: `events/${kebab}.events.ts`,
      content,
      artifactType: 'EVENT',
      overwritable: true,
    };
  }

  generateAggregate(domains: DomainMetadata[], context: GeneratorContext): GeneratedFile[] {
    // Generate central event bus service
    const domainsWithEvents = domains.filter(d => d.events && d.events.length > 0);

    if (domainsWithEvents.length === 0) {
      return [];
    }

    return [
      {
        path: 'events/event-bus.service.ts',
        content: this.generateEventBusService(domainsWithEvents, context),
        artifactType: 'EVENT',
        overwritable: true,
      },
    ];
  }

  private generateEventHandlerContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName, events = [] } = domain;
    const kebab = DslMapper.toKebabCase(entityName);
    const camel = DslMapper.toCamelCase(entityName);

    const eventTypes = events.map(e => `'${e.name}'`).join(' | ');
    const eventInterfaces = this.generateEventInterfaces(events);
    const eventHandlers = this.generateEventHandlers(events, entityName);

    return `/**
 * ${entityName} Event Handlers
 * 
 * Handles domain events for ${entityName} entity.
 * Provides real-time UI updates via SSE/WebSocket.
 * 
 * Generated by @exeris/codegen-ts v0.3.0
 * DO NOT EDIT - This file is auto-generated
 */

import { 
  Injectable, 
  inject, 
  signal, 
  computed,
  DestroyRef,
  NgZone,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { LiveAnnouncer } from '@angular/cdk/a11y';
import { Subject, Observable, filter, map } from 'rxjs';
import { EventBusService, DomainEvent } from './event-bus.service';

// ============================================================================
// Event Types
// ============================================================================

export type ${entityName}EventType = ${eventTypes || "'UNKNOWN'"};

${eventInterfaces}

export type ${entityName}Event = 
${events.map(e => `  | ${entityName}${this.toPascalCase(e.name)}Event`).join('\n') || '  | never'};

// ============================================================================
// Event Handler Service
// ============================================================================

@Injectable({ providedIn: 'root' })
export class ${entityName}EventHandler {
  private readonly eventBus = inject(EventBusService);
  private readonly liveAnnouncer = inject(LiveAnnouncer);
  private readonly destroyRef = inject(DestroyRef);
  private readonly zone = inject(NgZone);

  // ═══════════════════════════════════════════════════════════════════════════
  // Event Subjects
  // ═══════════════════════════════════════════════════════════════════════════

${events.map(e => `  private readonly _${DslMapper.toCamelCase(e.name)} = new Subject<${entityName}${this.toPascalCase(e.name)}Event>();`).join('\n')}

  // ═══════════════════════════════════════════════════════════════════════════
  // Public Event Observables
  // ═══════════════════════════════════════════════════════════════════════════

${events.map(e => `  /** Observable for ${e.name} events */
  readonly ${DslMapper.toCamelCase(e.name)}$ = this._${DslMapper.toCamelCase(e.name)}.asObservable();`).join('\n\n')}

  // ═══════════════════════════════════════════════════════════════════════════
  // State Signals
  // ═══════════════════════════════════════════════════════════════════════════

  /** Total events received count */
  private readonly _eventCount = signal(0);
  readonly eventCount = this._eventCount.asReadonly();

  /** Last received event */
  private readonly _lastEvent = signal<${entityName}Event | null>(null);
  readonly lastEvent = this._lastEvent.asReadonly();

  /** Events received in current session */
  private readonly _recentEvents = signal<${entityName}Event[]>([]);
  readonly recentEvents = this._recentEvents.asReadonly();

  /** Maximum recent events to keep */
  private readonly maxRecentEvents = 50;

  // ═══════════════════════════════════════════════════════════════════════════
  // Initialization
  // ═══════════════════════════════════════════════════════════════════════════

  constructor() {
    this.subscribeToEvents();
  }

  private subscribeToEvents(): void {
    // Subscribe to all ${entityName} events
    this.eventBus.events$
      .pipe(
        filter(event => event.aggregateType === '${entityName}'),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe(event => {
        this.zone.run(() => {
          this.handleEvent(event);
        });
      });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Event Handling
  // ═══════════════════════════════════════════════════════════════════════════

  private handleEvent(event: DomainEvent): void {
    const typedEvent = this.parseEvent(event);
    if (!typedEvent) return;

    // Update state
    this._eventCount.update(n => n + 1);
    this._lastEvent.set(typedEvent);
    this._recentEvents.update(events => {
      const updated = [typedEvent, ...events];
      return updated.slice(0, this.maxRecentEvents);
    });

    // Dispatch to specific subject
    this.dispatchEvent(typedEvent);
  }

  private parseEvent(event: DomainEvent): ${entityName}Event | null {
    const baseEvent = {
      id: event.id,
      aggregateId: event.aggregateId,
      aggregateType: event.aggregateType,
      occurredAt: new Date(event.occurredAt),
      userId: event.userId,
      correlationId: event.correlationId,
    };

    switch (event.eventType) {
${eventHandlers}
      default:
        console.warn(\`Unknown ${entityName} event type: \${event.eventType}\`);
        return null;
    }
  }

  private dispatchEvent(event: ${entityName}Event): void {
    switch (event.type) {
${events.map(e => `      case '${e.name}':
        this._${DslMapper.toCamelCase(e.name)}.next(event as ${entityName}${this.toPascalCase(e.name)}Event);
        this.announce${this.toPascalCase(e.name)}(event as ${entityName}${this.toPascalCase(e.name)}Event);
        break;`).join('\n')}
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Accessibility Announcements
  // ═══════════════════════════════════════════════════════════════════════════

${events.map(e => this.generateAnnouncementMethod(e, entityName)).join('\n\n')}

  // ═══════════════════════════════════════════════════════════════════════════
  // Public API
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Get observable for specific event type.
   */
  on<T extends ${entityName}EventType>(
    eventType: T
  ): Observable<Extract<${entityName}Event, { type: T }>> {
    switch (eventType) {
${events.map(e => `      case '${e.name}':
        return this._${DslMapper.toCamelCase(e.name)}.asObservable() as Observable<Extract<${entityName}Event, { type: T }>>;`).join('\n')}
      default:
        throw new Error(\`Unknown event type: \${eventType}\`);
    }
  }

  /**
   * Clear recent events history.
   */
  clearHistory(): void {
    this._recentEvents.set([]);
    this._eventCount.set(0);
  }
}
`;
  }

  private generateEventInterfaces(events: DomainEventMetadata[]): string {
    return events.map(event => {
      const pascalName = this.toPascalCase(event.name);
      const fields = event.fields || [];

      const payloadFields = fields
        .map(f => `    ${f.name}: ${DslMapper.mapType(f.type).tsType};`)
        .join('\n');

      return `export interface ${pascalName}Payload {
${payloadFields || '    // No additional payload fields'}
}

export interface ${pascalName}Event {
  type: '${event.name}';
  id: string;
  aggregateId: string;
  aggregateType: string;
  occurredAt: Date;
  userId?: string;
  correlationId?: string;
  payload: ${pascalName}Payload;
}`;
    }).join('\n\n');
  }

  private generateEventHandlers(events: DomainEventMetadata[], entityName: string): string {
    return events.map(event => {
      const pascalName = this.toPascalCase(event.name);
      return `      case '${event.name}':
        return {
          ...baseEvent,
          type: '${event.name}' as const,
          payload: event.payload as ${pascalName}Payload,
        };`;
    }).join('\n');
  }

  private generateAnnouncementMethod(event: DomainEventMetadata, entityName: string): string {
    const pascalName = this.toPascalCase(event.name);
    const camelName = DslMapper.toCamelCase(event.name);

    // Determine announcement priority based on event name
    const isDestructive = event.name.toLowerCase().includes('deleted') ||
                         event.name.toLowerCase().includes('removed') ||
                         event.name.toLowerCase().includes('failed');
    const priority = isDestructive ? 'assertive' : 'polite';

    return `  private announce${pascalName}(event: ${entityName}${pascalName}Event): void {
    const message = $localize\`:@@${entityName.toLowerCase()}.event.${camelName}:${this.humanize(event.name)}\`;
    this.liveAnnouncer.announce(message, '${priority}');
  }`;
  }

  private generateEventBusService(domains: DomainMetadata[], context: GeneratorContext): string {
    const allEventTypes = domains
      .flatMap(d => d.events || [])
      .map(e => `'${e.name}'`)
      .filter((v, i, a) => a.indexOf(v) === i); // Unique

    return `/**
 * Central Event Bus Service
 * 
 * Manages real-time event subscriptions via SSE/WebSocket/WebTransport.
 * Provides a unified event stream for all domain events.
 * 
 * Generated by @exeris/codegen-ts v0.3.0
 * DO NOT EDIT - This file is auto-generated
 */

import { 
  Injectable, 
  inject, 
  signal, 
  computed,
  DestroyRef,
  NgZone,
  OnDestroy,
} from '@angular/core';
import { Subject, BehaviorSubject, Observable, timer, retry, takeUntil } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { LiveAnnouncer } from '@angular/cdk/a11y';

// ============================================================================
// Types
// ============================================================================

export type ConnectionState = 'DISCONNECTED' | 'CONNECTING' | 'CONNECTED' | 'RECONNECTING' | 'ERROR';

export interface DomainEvent {
  /** Event ID */
  id: string;
  /** Event type name */
  eventType: string;
  /** Aggregate ID (entity ID) */
  aggregateId: string;
  /** Aggregate type (entity name) */
  aggregateType: string;
  /** Event occurred timestamp (ISO string) */
  occurredAt: string;
  /** User ID who triggered the event */
  userId?: string;
  /** Correlation ID for tracing */
  correlationId?: string;
  /** Event payload */
  payload: unknown;
}

export interface EventBusConfig {
  /** Event stream endpoint */
  endpoint: string;
  /** Reconnection attempts */
  reconnectAttempts: number;
  /** Initial reconnect delay in ms */
  reconnectDelay: number;
  /** Heartbeat interval in ms */
  heartbeatInterval: number;
}

// ============================================================================
// Default Configuration
// ============================================================================

const DEFAULT_CONFIG: EventBusConfig = {
  endpoint: '/api/v1/events/stream',
  reconnectAttempts: 5,
  reconnectDelay: 1000,
  heartbeatInterval: 30000,
};

// ============================================================================
// Event Bus Service
// ============================================================================

@Injectable({ providedIn: 'root' })
export class EventBusService implements OnDestroy {
  private readonly http = inject(HttpClient);
  private readonly destroyRef = inject(DestroyRef);
  private readonly zone = inject(NgZone);
  private readonly liveAnnouncer = inject(LiveAnnouncer);

  private readonly config = DEFAULT_CONFIG;

  // ═══════════════════════════════════════════════════════════════════════════
  // State
  // ═══════════════════════════════════════════════════════════════════════════

  private eventSource: EventSource | null = null;
  private readonly destroy$ = new Subject<void>();
  private reconnectAttempt = 0;

  // Event subjects
  private readonly _events = new Subject<DomainEvent>();
  private readonly _connectionState = new BehaviorSubject<ConnectionState>('DISCONNECTED');
  private readonly _lastEventTime = signal<Date | null>(null);
  private readonly _eventCount = signal(0);

  // ═══════════════════════════════════════════════════════════════════════════
  // Public API
  // ═══════════════════════════════════════════════════════════════════════════

  /** Stream of all domain events */
  readonly events$ = this._events.asObservable();

  /** Current connection state */
  readonly connectionState$ = this._connectionState.asObservable();

  /** Current connection state as signal */
  readonly connectionState = computed(() => this._connectionState.getValue());

  /** Last event received time */
  readonly lastEventTime = this._lastEventTime.asReadonly();

  /** Total events received */
  readonly eventCount = this._eventCount.asReadonly();

  /** Whether connected */
  readonly isConnected = computed(() => this._connectionState.getValue() === 'CONNECTED');

  // ═══════════════════════════════════════════════════════════════════════════
  // Connection Management
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Connect to event stream.
   */
  connect(): void {
    if (this.eventSource) {
      return; // Already connected
    }

    this._connectionState.next('CONNECTING');

    try {
      this.eventSource = new EventSource(this.config.endpoint, {
        withCredentials: true,
      });

      this.eventSource.onopen = () => {
        this.zone.run(() => {
          this._connectionState.next('CONNECTED');
          this.reconnectAttempt = 0;
          this.liveAnnouncer.announce(
            $localize\`:@@events.connected:Connected to event stream\`,
            'polite'
          );
        });
      };

      this.eventSource.onmessage = (event) => {
        this.zone.run(() => {
          try {
            const domainEvent = JSON.parse(event.data) as DomainEvent;
            this._events.next(domainEvent);
            this._lastEventTime.set(new Date());
            this._eventCount.update(n => n + 1);
          } catch (err) {
            console.error('Failed to parse event:', err);
          }
        });
      };

      this.eventSource.onerror = (error) => {
        this.zone.run(() => {
          console.error('EventSource error:', error);
          this.handleConnectionError();
        });
      };

      // Handle specific event types
      this.eventSource.addEventListener('heartbeat', () => {
        // Heartbeat received - connection is alive
      });

    } catch (err) {
      console.error('Failed to create EventSource:', err);
      this._connectionState.next('ERROR');
    }
  }

  /**
   * Disconnect from event stream.
   */
  disconnect(): void {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }
    this._connectionState.next('DISCONNECTED');
  }

  /**
   * Force reconnection.
   */
  reconnect(): void {
    this.disconnect();
    this.connect();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Subscription Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Subscribe to events for a specific aggregate type.
   */
  forAggregate(aggregateType: string): Observable<DomainEvent> {
    return this.events$.pipe(
      takeUntil(this.destroy$),
      filter((event): event is DomainEvent => event.aggregateType === aggregateType)
    );
  }

  /**
   * Subscribe to events for a specific aggregate instance.
   */
  forAggregateInstance(aggregateType: string, aggregateId: string): Observable<DomainEvent> {
    return this.events$.pipe(
      takeUntil(this.destroy$),
      filter((event): event is DomainEvent => 
        event.aggregateType === aggregateType && event.aggregateId === aggregateId
      )
    );
  }

  /**
   * Subscribe to a specific event type.
   */
  forEventType(eventType: string): Observable<DomainEvent> {
    return this.events$.pipe(
      takeUntil(this.destroy$),
      filter((event): event is DomainEvent => event.eventType === eventType)
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Private Methods
  // ═══════════════════════════════════════════════════════════════════════════

  private handleConnectionError(): void {
    this.disconnect();

    if (this.reconnectAttempt < this.config.reconnectAttempts) {
      this._connectionState.next('RECONNECTING');
      this.reconnectAttempt++;
      
      const delay = this.config.reconnectDelay * Math.pow(2, this.reconnectAttempt - 1);
      
      setTimeout(() => {
        this.connect();
      }, delay);
    } else {
      this._connectionState.next('ERROR');
      this.liveAnnouncer.announce(
        $localize\`:@@events.connection.failed:Failed to connect to event stream\`,
        'assertive'
      );
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Lifecycle
  // ═══════════════════════════════════════════════════════════════════════════

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    this.disconnect();
  }
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Filter operator for specific event types.
 */
function filter<T>(predicate: (value: T) => boolean): (source: Observable<T>) => Observable<T> {
  return (source: Observable<T>) => new Observable(subscriber => {
    return source.subscribe({
      next: value => {
        if (predicate(value)) {
          subscriber.next(value);
        }
      },
      error: err => subscriber.error(err),
      complete: () => subscriber.complete(),
    });
  });
}
`;
  }

  private toPascalCase(name: string): string {
    return name
      .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
      .replace(/^(.)/, (_, c) => c.toUpperCase());
  }

  private humanize(name: string): string {
    return name
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, s => s.toUpperCase())
      .trim();
  }
}

// ============================================================================
// Factory Function
// ============================================================================

export function generateEventHandler(
  domain: DomainMetadata,
  config: GeneratorConfig
): GeneratedFile | null {
  const generator = new EventHandlerGenerator();
  const context: GeneratorContext = {
    config,
    backend: 'KERNEL',
    allDomains: [domain],
    enums: [],
  };

  return generator.generate(domain, context);
}

