/**
 * Angular Form Generator
 * Generates Angular 22+ form components with Signals from domain metadata.
 */

import type { DomainMetadata } from '../../models/domain-model.js';
import { modelTypeName } from '../../models/model-naming.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { outPath } from '../../core/paths.js';
import { updateVersionField } from '../api/type-gen.js';
import { fieldRenderContext, resolveFieldRenders, toTitleCase } from './field-render.js';
import { tsSingleQuoted } from './ts-literal.js';
import { entityExitRoute, entityViews, hasFormPage } from './entity-views.js';

export { GeneratedFile };

export class FormGenerator implements CodeGenerator {
  readonly name = 'FormGenerator';
  readonly artifactType = 'FORM' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 20;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    // One component serves both the create and the edit route, so it is dropped only when both are off.
    if (domain.internalApi?.hidden || !hasFormPage(entityViews(domain))) {
      return null;
    }

    const content = this.generateFormContent(domain, context);
    const fileName = `${DslMapper.toKebabCase(domain.entityName)}-form.component.ts`;
    const filePath = outPath('components', fileName);

    return {
      path: filePath,
      content,
      artifactType: 'FORM',
      overwritable: true,
    };
  }

  private generateFormContent(domain: DomainMetadata, context: GeneratorContext): string {
    // A versioned entity's lock field is never a control: the edit form holds the loaded
    // entity's value aside and sends it with the update (type-gen's updateVersionField names it).
    const version = updateVersionField(domain);
    // The expression reading the version off a loaded entity. When the metadata does not declare
    // the field, the entity interface has no such property, so it is read through a narrowing cast.
    const readVersion = (entityExpr: string): string => {
      const name = version!.name;
      return version!.declared
        ? `${entityExpr}.${name} ?? null`
        : `(${entityExpr} as unknown as { ${name}?: number }).${name} ?? null`;
    };
    const entityName = domain.entityName;

    const modelName = modelTypeName(entityName);
    const kebabName = DslMapper.toKebabCase(entityName);
    const noun = tsSingleQuoted((domain.displayName ?? entityName).toLowerCase());
    // The literal 'id', deliberately, not systemFields.primaryKeyField. Nothing in the pipeline
    // honours that override: KernelFlywayGenerator emits `id UUID PRIMARY KEY` unconditionally,
    // KernelRepositoryGenerator's WHERE clause is the constant " WHERE id = ?", every by-id
    // handler binds the {id} path variable, and the processor says so outright ("generators leave
    // the primary key as the literal id"). Reading it here would make this the only layer that
    // honours it, and the emitted app would then request the wrong identifier.
    const idField = 'id';

    // No control for a system field (type-gen's viewSystemFieldNames). That includes a UNIVERSE
    // entity's shared-scope key, which is server-owned like its tenant: the repository stamps it
    // from the bound storage context and the create DTO omits it, so the form never sends it.
    // The form renders no link, so the context resolves none.
    const renders = resolveFieldRenders(domain, fieldRenderContext(domain, [], false));
    const createFields = renders.filter((r) => r.form.placement === 'control');
    // Computed fields render read-only, for information, and are kept out of the submitted DTO.
    const computedFields = renders.filter((r) => r.form.placement === 'computed');

    const lines: string[] = [];
    lines.push('/**');
    lines.push(` * ${entityName} Form Component`);
    lines.push(' * Generated by @exeris/codegen-ts');
    lines.push(' * Uses Angular 22 standalone components + signals');
    lines.push(' */');
    lines.push('');
    const plural = DslMapper.routePlural(entityName);
    // A routed form returns to the saved instance's detail page; without one, it leaves the entity.
    const views = entityViews(domain);
    const exitRoute = entityExitRoute(domain, views);

    lines.push("import { Component, ChangeDetectionStrategy, input, output, signal, computed, effect, inject } from '@angular/core';");
    lines.push("import { rxResource } from '@angular/core/rxjs-interop';");
    lines.push("import { CommonModule } from '@angular/common';");
    lines.push("import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';");
    lines.push("import { ActivatedRoute, Router } from '@angular/router';");
    lines.push(`import { ${modelName}, ${modelName}Create, ${modelName}Update, ${entityName}Service } from '../services/${kebabName}.service';`);
    lines.push("import { httpErrorMessage } from '../core/http-error';");

    // Collect enum types used in create fields
    const enumTypes = new Set<string>();
    for (const f of createFields) {
      if (f.form.enumType) {
        enumTypes.add(f.form.enumType);
      }
    }

    if (enumTypes.size > 0) {
      const enumImports = Array.from(enumTypes).flatMap(e => [e, `${e}DisplayNames`]);
      lines.push(`import { ${enumImports.join(', ')} } from '../types/enums';`);
    }

    lines.push('');
    lines.push('@Component({');
    lines.push(`  selector: 'app-${kebabName}-form',`);
    lines.push('  standalone: true,');
    lines.push('  imports: [CommonModule, FormsModule, ReactiveFormsModule],');
    lines.push('  changeDetection: ChangeDetectionStrategy.OnPush,');
    lines.push('  template: `');
    // Loading and error of the by-id load mirror the detail view's markup.
    lines.push('    @if (isLoading()) {');
    lines.push('      <div class="animate-pulse space-y-4 mb-6" role="status" aria-label="Loading...">');
    lines.push('        <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2"></div>');
    lines.push('      </div>');
    lines.push('    } @else if (loadError()) {');
    lines.push('      <div role="alert" class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-6 mb-6">');
    lines.push('        <p class="text-red-700 dark:text-red-300">{{ loadError() }}</p>');
    lines.push('        <button type="button" (click)="reload()" class="mt-4 text-sm font-medium text-red-600">Try again</button>');
    lines.push('      </div>');
    lines.push('    }');
    lines.push('    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-6">');

    for (const f of createFields) {
      const { label, control, inputType, inputMode, enumType: enumTypeName } = f.form;
      const requiredMark = f.form.required ? '<span class="text-red-500" aria-hidden="true">*</span>' : '';
      const disabledBinding = f.form.readOnly ? ' [disabled]="true"' : '';
      const readonlyBinding = f.form.readOnly ? ' [readonly]="true"' : '';

      lines.push('      <div class="form-group">');

      if (control === 'select') {
        lines.push(`        <label for="${f.name}" class="block text-sm font-medium text-gray-700 dark:text-gray-300">${label} ${requiredMark}</label>`);
        lines.push(`        <select id="${f.name}" data-testid="field-${f.name}" formControlName="${f.name}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-exeris-primary focus:ring-exeris-primary dark:bg-gray-800 dark:border-gray-600 dark:text-white sm:text-sm"${disabledBinding}>`);
        lines.push('          <option value="">Select...</option>');
        lines.push(`          @for (value of ${enumTypeName}Values; track value) {`);
        lines.push(`            <option [value]="value">{{ ${enumTypeName}DisplayNames[value] }}</option>`);
        lines.push('          }');
        lines.push('        </select>');
      } else if (control === 'checkbox') {
        lines.push('        <div class="flex items-center gap-2">');
        lines.push(`          <input id="${f.name}" data-testid="field-${f.name}" type="checkbox" formControlName="${f.name}" class="h-4 w-4 rounded border-gray-300 text-exeris-primary focus:ring-exeris-primary"${disabledBinding}>`);
        lines.push(`          <label for="${f.name}" class="text-sm text-gray-700 dark:text-gray-300">${label} ${requiredMark}</label>`);
        lines.push('        </div>');
      } else {
        const inputExtra = inputMode ? ` inputmode="${inputMode}"` : '';
        lines.push(`        <label for="${f.name}" class="block text-sm font-medium text-gray-700 dark:text-gray-300">${label} ${requiredMark}</label>`);
        lines.push(`        <input id="${f.name}" data-testid="field-${f.name}" type="${inputType}" formControlName="${f.name}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-exeris-primary focus:ring-exeris-primary dark:bg-gray-800 dark:border-gray-600 dark:text-white sm:text-sm"${disabledBinding}${inputExtra}${readonlyBinding}>`);
      }
      lines.push(`        <p class="mt-1 text-xs text-gray-500" *ngIf="form.get('${f.name}')?.invalid && form.get('${f.name}')?.touched" data-testid="error-${f.name}">`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['required']) { <span>${label} is required.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['pattern']) { <span>Invalid format.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['minlength']) { <span>Too short.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['maxlength']) { <span>Too long.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['min']) { <span>Too low.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['max']) { <span>Too high.</span> }`);
      lines.push('        </p>');
      lines.push('      </div>');
    }

    // Render computed fields (readonly, displayed for info)
    for (const f of computedFields) {
      const label = f.form.label;
      const dependsOn = f.form.computedFrom.join(', ');

      lines.push('      <div class="form-group">');
      lines.push(`        <label for="${f.name}" class="block text-sm font-medium text-gray-700 dark:text-gray-300">${label} <span class="text-xs text-gray-500">(Auto)</span></label>`);
      lines.push(`        <input id="${f.name}" data-testid="field-${f.name}" type="${f.form.inputType}" formControlName="${f.name}" readonly class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-exeris-primary focus:ring-exeris-primary dark:bg-gray-800 dark:border-gray-600 dark:text-white sm:text-sm bg-gray-100 dark:bg-gray-700 cursor-not-allowed opacity-75">`);
      if (dependsOn) {
        lines.push(`        <p class="mt-1 text-xs text-gray-500">Computed from: ${dependsOn}</p>`);
      }
      lines.push('      </div>');
    }

    lines.push('      @if (error()) {');
    lines.push('        <div role="alert" data-testid="submit-error" class="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-800 dark:bg-red-900/20 dark:text-red-300">{{ error() }}</div>');
    lines.push('      }');
    if (version) {
      // The server answers a stale update with 409 and no body; the only recovery is to load
      // the row as it now stands, which also picks up its current version.
      lines.push('      @if (conflict()) {');
      lines.push('        <div role="alert" data-testid="conflict-message" class="rounded-md border border-amber-300 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-700 dark:bg-amber-900/30 dark:text-amber-200">');
      lines.push('          <p>This record was changed by someone else. Reload to see the latest version.</p>');
      lines.push('          <button type="button" (click)="reload()" data-testid="reload-button" class="mt-2 rounded-md bg-white px-3 py-1.5 text-sm font-medium text-amber-800 shadow-sm border border-amber-300 hover:bg-amber-100 dark:bg-gray-800 dark:text-amber-200 dark:border-amber-700">Reload</button>');
      lines.push('        </div>');
      lines.push('      }');
    }
    lines.push('      <div class="flex justify-end gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">');
    lines.push('        <button type="button" (click)="onCancel()" data-testid="cancel-button" class="rounded-md bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm border border-gray-300 hover:bg-gray-50 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600">Cancel</button>');
    lines.push('        <button type="submit" [disabled]="form.invalid || saving() || (editMode() && !current())" data-testid="submit-button" class="rounded-md bg-exeris-primary px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-exeris-primary-hover disabled:opacity-50">');
    lines.push(`          @if (saving()) { Saving... } @else { {{ editMode() ? 'Update' : 'Create' }} ${entityName} }`);
    lines.push('        </button>');
    lines.push('      </div>');
    lines.push('    </form>');
    lines.push('  `,');
    lines.push('})');

    lines.push(`export class ${entityName}FormComponent {`);
    lines.push('  private readonly fb = inject(FormBuilder);');
    lines.push(`  private readonly service = inject(${entityName}Service);`);
    lines.push('  private readonly router = inject(Router);');
    // The form is a page when its activated route's component is this class; embedded in a
    // host template it sees the host's route instead (or none), and leaves the next step to
    // the host listening on `saved` / `cancelled`.
    lines.push(`  private readonly routed = inject(ActivatedRoute, { optional: true })?.component === ${entityName}FormComponent;`);
    lines.push('');

    // Generate enum arrays
    for (const enumType of Array.from(enumTypes)) {
      lines.push(`  readonly ${enumType}Values = Object.values(${enumType});`);
      lines.push(`  readonly ${enumType}DisplayNames = ${enumType}DisplayNames;`);
      lines.push('');
    }

    lines.push(`  readonly mode = input<'create' | 'edit'>('create');`);
    lines.push(`  readonly entity = input<${modelName} | null>(null);`);
    // Bound from the `:id` route parameter by withComponentInputBinding on the edit route.
    lines.push('  readonly id = input<string | undefined>();');
    lines.push('');
    lines.push('  private readonly entityResource = rxResource({');
    lines.push('    params: () => this.id(),');
    lines.push('    stream: ({ params }) => this.service.findById(params),');
    lines.push('  });');
    lines.push('');
    // An embedding host's `entity` wins over the by-id load; an `id` always means edit.
    lines.push(`  readonly current = computed<${modelName} | null>(() => this.entity() ?? this.entityResource.value() ?? null);`);
    lines.push("  readonly editMode = computed(() => this.id() !== undefined || this.mode() === 'edit');");
    lines.push('  readonly isLoading = computed(() => this.entityResource.isLoading());');
    lines.push('  readonly loadError = computed(() => {');
    lines.push('    const err = this.entityResource.error();');
    lines.push(`    return err ? httpErrorMessage(err, { entity: '${noun}', action: 'load' }) : null;`);
    lines.push('  });');
    lines.push('');
    lines.push(`  readonly saved = output<${modelName}>();`);
    lines.push('  readonly cancelled = output<void>();');
    lines.push('');
    lines.push('  readonly saving = signal(false);');
    lines.push('  readonly error = signal<string | null>(null);');
    if (version) {
      lines.push('  readonly conflict = signal(false);');
      lines.push('');
      lines.push(`  /** The ${version.name} the edited entity was loaded at; the update sends it back as the expected version. */`);
      const versionType = version.tsType.endsWith('| null') ? version.tsType : `${version.tsType} | null`;
      lines.push(`  private readonly loadedVersion = signal<${versionType}>(null);`);
    }
    lines.push('');
    lines.push('  readonly form = this.fb.group({');
    for (const { name, form, field: f } of createFields) {
      const validators: string[] = [];
      if (f.required) validators.push('Validators.required');
      if (f.minLength) validators.push(`Validators.minLength(${f.minLength})`);
      if (f.maxLength) validators.push(`Validators.maxLength(${f.maxLength})`);
      if (f.pattern) validators.push(`Validators.pattern(/${f.pattern}/)`);
      if (f.min !== undefined) validators.push(`Validators.min(${f.min})`);
      if (f.max !== undefined) validators.push(`Validators.max(${f.max})`);
      const validatorsArray = validators.length ? `[${validators.join(', ')}]` : '[]';
      lines.push(`    ${name}: [${form.initialValue}, ${validatorsArray}],`);
    }
    lines.push('  });');
    lines.push('');
    lines.push('  constructor() {');

    // Generate effects for computed fields
    if (computedFields.length > 0) {
      for (const cf of computedFields) {
        const deps = cf.form.computedFrom;
        if (deps.length > 0) {
          lines.push(`    // Auto-sync ${cf.name} based on ${deps.join(', ')}`);
          lines.push('    effect(() => {');
          lines.push('      const values = {');
          for (const dep of deps) {
            lines.push(`        ${dep}: this.form.get('${dep}')?.value,`);
          }
          lines.push('      };');
          lines.push(`      const computed${toTitleCase(cf.name)} = this.compute${toTitleCase(cf.name)}(values);`);
          lines.push(`      this.form.get('${cf.name}')?.setValue(computed${toTitleCase(cf.name)}, { emitEvent: false });`);
          lines.push('    });');
          lines.push('');
        }
      }
    }

    lines.push('    effect(() => {');
    lines.push('      const entity = this.current();');
    lines.push('      if (entity && this.editMode()) {');
    lines.push('        this.form.patchValue(entity as any);');
    if (version) {
      lines.push(`        this.loadedVersion.set(${readVersion('entity')});`);
    }
    lines.push('      }');
    lines.push('    });');
    lines.push('  }');
    lines.push('');
    lines.push('  onSubmit(): void {');
    lines.push('    if (this.form.invalid) {');
    lines.push('      this.form.markAllAsTouched();');
    lines.push('      return;');
    lines.push('    }');
    // Edit mode without a loaded entity would overwrite a row it never read.
    lines.push('    const current = this.current();');
    lines.push('    if (this.editMode() && !current) {');
    lines.push('      return;');
    lines.push('    }');
    lines.push('');
    lines.push('    this.saving.set(true);');
    lines.push('    this.error.set(null);');
    if (version) lines.push('    this.conflict.set(false);');
    lines.push('');
    // A numeric control is seeded '' and getRawValue() is statically string-typed, so it is
    // coerced on submit to match the DTO's number type.
    const numericCreateFields = createFields.filter((f) => f.form.value === 'number');
    if (numericCreateFields.length > 0) {
      // Coerce string-typed numeric controls to numbers so the payload matches
      // the *Create/*Update DTO type.
      lines.push('    const raw = this.form.getRawValue();');
      lines.push('    const data = {');
      lines.push('      ...raw,');
      for (const f of numericCreateFields) {
        lines.push(`      ${f.name}: raw.${f.name} === null || raw.${f.name} === '' ? null : Number(raw.${f.name}),`);
      }
      lines.push('    };');
    } else {
      lines.push('    const data = this.form.getRawValue();');
    }
    const updatePayload = version
      ? `{ ...data, ${version.name}: this.loadedVersion() } as ${modelName}Update`
      : `data as ${modelName}Update`;
    lines.push(`    const request$ = this.editMode() && current ? this.service.update(String(current.${idField}), ${updatePayload}) : this.service.create(data as ${modelName}Create);`);
    lines.push('');
    lines.push('    request$.subscribe({');
    lines.push('      next: (result) => {');
    lines.push('        this.saving.set(false);');
    lines.push('        this.saved.emit(result);');
    lines.push('        if (this.routed) {');
    lines.push(views.detail
      ? `          void this.router.navigate(['/${plural}', String(result.${idField})]);`
      : `          void this.router.navigate(['${exitRoute}']);`);
    lines.push('        }');
    lines.push('      },');
    lines.push('      error: (err) => {');
    lines.push('        this.saving.set(false);');
    if (version) {
      lines.push("        if (this.editMode() && err?.status === 409) {");
      lines.push('          this.conflict.set(true);');
      lines.push('          return;');
      lines.push('        }');
    }
    lines.push(`        this.error.set(httpErrorMessage(err, { entity: '${noun}', action: 'save' }));`);
    lines.push('      },');
    lines.push('    });');
    lines.push('  }');
    lines.push('');
    lines.push('  onCancel(): void {');
    lines.push('    this.cancelled.emit();');
    lines.push('    if (this.routed) {');
    // Back to the entity being edited, or to the list when nothing was.
    if (views.detail) {
      lines.push('      const id = this.id();');
      lines.push(`      void this.router.navigate(id !== undefined ? ['/${plural}', id] : ['${exitRoute}']);`);
    } else {
      lines.push(`      void this.router.navigate(['${exitRoute}']);`);
    }
    lines.push('    }');
    lines.push('  }');
    lines.push('');
    if (!version) {
      lines.push('  reload(): void { this.entityResource.reload(); }');
    } else {
      // A form loaded by id reloads its resource, and the patch effect picks up the fresh
      // values and version. A host-supplied entity has no resource behind it, so the row is
      // fetched directly.
      lines.push('  /** Loads the row as it now stands, replacing the edited values and the expected version. */');
      lines.push('  reload(): void {');
      lines.push('    this.conflict.set(false);');
      lines.push('    if (this.id() !== undefined) {');
      lines.push('      this.entityResource.reload();');
      lines.push('      return;');
      lines.push('    }');
      lines.push('    const current = this.current();');
      lines.push('    if (!current) return;');
      lines.push(`    this.service.findById(String(current.${idField})).subscribe({`);
      lines.push('      next: (fresh) => {');
      lines.push('        this.form.reset(fresh as any);');
      lines.push(`        this.loadedVersion.set(${readVersion('fresh')});`);
      lines.push('      },');
      lines.push(`      error: (err) => this.error.set(httpErrorMessage(err, { entity: '${noun}', action: 'load' })),`);
      lines.push('    });');
      lines.push('  }');
    }

    // Generate compute methods for computed fields
    for (const cf of computedFields) {
      const deps = cf.form.computedFrom;
      const methodName = `compute${toTitleCase(cf.name)}`;
      lines.push('');
      lines.push(`  private ${methodName}(values: { ${deps.map(d => `${d}: any`).join(', ')} }): any {`);
      lines.push('    // TODO: Implement computation logic');
      lines.push(`    // Depends on: ${deps.join(', ')}`);
      lines.push('    return null;');
      lines.push('  }');
    }

    lines.push('}');

    return lines.join('\n');
  }
}

export function generateForm(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile | null {
  const generator = new FormGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context);
}



