/**
 * Angular Form Generator
 * Generates Angular 21+ form components with Signals from domain metadata.
 *
 * @author Exeris Team
 * @since 0.2.0
 */

import type { DomainMetadata, FieldMetadata } from '../../models/domain-model.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { join } from 'node:path';

export { GeneratedFile };

export class FormGenerator implements CodeGenerator {
  readonly name = 'FormGenerator';
  readonly artifactType = 'FORM' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 20;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (domain.internalApi?.hidden) {
      return null;
    }

    const content = this.generateFormContent(domain, context);
    const fileName = `${DslMapper.toKebabCase(domain.entityName)}-form.component.ts`;
    const filePath = join('components', fileName);

    return {
      path: filePath,
      content,
      artifactType: 'FORM',
      overwritable: true,
    };
  }

  private generateFormContent(domain: DomainMetadata, context: GeneratorContext): string {
    // Helper functions
    const getEnumTypeName = (fqcn: string): string => {
      const parts = fqcn.split('.');
      return parts[parts.length - 1];
    };

    const toTitleCase = (value: string): string => {
      return value.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase());
    };

    const mapInputType = (field: FieldMetadata): string => {
      const type = field.type;
      if (type === 'java.lang.Boolean') return 'checkbox';
      if (type === 'java.lang.Integer' || type === 'java.lang.Long' || type === 'java.lang.Double' || type === 'java.lang.Float') return 'number';
      if (type === 'java.time.Instant' || type === 'java.time.LocalDateTime') return 'datetime-local';
      if (type === 'java.time.LocalDate') return 'date';
      return 'text';
    };

    const isLifecycleField = (name: string): boolean => {
      return ['active', 'onboardingStatus', 'onboardingStartedAt', 'onboardingCompletedAt', 'hierarchyLevel', 'parentTenantId', 'createdAt', 'updatedAt', 'deleted', 'version'].includes(name);
    };

    const isSystemField = (name: string): boolean => {
      return ['id', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'version', 'deleted', 'deletedAt', 'tenantId'].includes(name);
    };

    const isEnumField = (field: FieldMetadata): boolean => {
      // Check explicit enumType first
      if (field.enumType) return true;
      // Fallback: detect enum from type pattern (e.g., "eu.exeris.foundation.domain.TenantPlan")
      const type = field.type;
      return type.includes('.') && !type.startsWith('java.') && !type.includes('Entity') && !type.includes('DTO');
    };

    const getEnumTypeFromField = (field: FieldMetadata): string | null => {
      if (field.enumType) return field.enumType;
      // Extract enum name from FQCN (e.g., "eu.exeris.foundation.domain.TenantPlan" -> "TenantPlan")
      const type = field.type;
      if (isEnumField(field)) {
        const parts = type.split('.');
        return parts[parts.length - 1];
      }
      return null;
    };

    const entityName = domain.entityName;
    const kebabName = DslMapper.toKebabCase(entityName);
    const idField = domain.systemFields?.idField ?? 'id';

    const fields = domain.fields;
    const createFields = fields.filter((f) =>
      f.inCreate !== false &&
      f.hidden !== true &&
      f.readOnly !== true &&
      !f.computed &&  // Exclude computed fields
      !isLifecycleField(f.name) &&
      !isSystemField(f.name)
    );

    // Collect computed fields that depend on create fields
    const computedFields = fields.filter((f) =>
      f.computed &&
      f.inCreate !== false &&
      !isLifecycleField(f.name) &&
      !isSystemField(f.name)
    );

    const lines: string[] = [];
    lines.push('/**');
    lines.push(` * ${entityName} Form Component`);
    lines.push(' * Generated by @exeris/codegen-ts v0.4.0');
    lines.push(' * Uses Angular 21 standalone components + signals');
    lines.push(' */');
    lines.push('');
    lines.push("import { Component, ChangeDetectionStrategy, input, output, signal, effect, inject } from '@angular/core';");
    lines.push("import { CommonModule } from '@angular/common';");
    lines.push("import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';");
    lines.push(`import { ${entityName}, ${entityName}Create, ${entityName}Update, ${entityName}Service } from '../services/${kebabName}.service';`);

    // Collect enum types used in create fields
    const enumTypes = new Set<string>();
    for (const f of createFields) {
      const enumType = getEnumTypeFromField(f);
      if (enumType) {
        enumTypes.add(enumType);
      }
    }

    if (enumTypes.size > 0) {
      const enumImports = Array.from(enumTypes).flatMap(e => [e, `${e}DisplayNames`]);
      lines.push(`import { ${enumImports.join(', ')} } from '../types/enums';`);
    }

    lines.push('');
    lines.push('@Component({');
    lines.push(`  selector: 'app-${kebabName}-form',`);
    lines.push('  standalone: true,');
    lines.push('  imports: [CommonModule, FormsModule, ReactiveFormsModule],');
    lines.push('  changeDetection: ChangeDetectionStrategy.OnPush,');
    lines.push('  template: `');
    lines.push('    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-6">');

    for (const f of createFields.sort((a, b) => (a.order ?? 999) - (b.order ?? 999))) {
      const label = f.displayName ?? toTitleCase(f.name);
      const requiredMark = f.required ? '<span class="text-red-500" aria-hidden="true">*</span>' : '';
      const disabledBinding = f.readOnly ? ' [disabled]="true"' : '';
      const readonlyBinding = f.readOnly ? ' [readonly]="true"' : '';

      lines.push('      <div class="form-group">');

      const enumTypeName = getEnumTypeFromField(f);
      if (enumTypeName) {
        lines.push(`        <label for="${f.name}" class="block text-sm font-medium text-gray-700 dark:text-gray-300">${label} ${requiredMark}</label>`);
        lines.push(`        <select id="${f.name}" data-testid="field-${f.name}" formControlName="${f.name}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-800 dark:border-gray-600 dark:text-white sm:text-sm"${disabledBinding}>`);
        lines.push('          <option value="">Select...</option>');
        lines.push(`          @for (value of ${enumTypeName}Values; track value) {`);
        lines.push(`            <option [value]="value">{{ ${enumTypeName}DisplayNames[value] }}</option>`);
        lines.push('          }');
        lines.push('        </select>');
      } else if (mapInputType(f) === 'checkbox') {
        lines.push('        <div class="flex items-center gap-2">');
        lines.push(`          <input id="${f.name}" data-testid="field-${f.name}" type="checkbox" formControlName="${f.name}" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"${disabledBinding}>`);
        lines.push(`          <label for="${f.name}" class="text-sm text-gray-700 dark:text-gray-300">${label} ${requiredMark}</label>`);
        lines.push('        </div>');
      } else {
        const inputType = mapInputType(f);
        const inputExtra = inputType === 'number' ? ' inputmode="decimal"' : '';
        lines.push(`        <label for="${f.name}" class="block text-sm font-medium text-gray-700 dark:text-gray-300">${label} ${requiredMark}</label>`);
        lines.push(`        <input id="${f.name}" data-testid="field-${f.name}" type="${inputType}" formControlName="${f.name}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-800 dark:border-gray-600 dark:text-white sm:text-sm"${disabledBinding}${inputExtra}${readonlyBinding}>`);
      }
      lines.push(`        <p class="mt-1 text-xs text-gray-500" *ngIf="form.get('${f.name}')?.invalid && form.get('${f.name}')?.touched" data-testid="error-${f.name}">`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['required']) { <span>${label} is required.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['pattern']) { <span>Invalid format.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['minlength']) { <span>Too short.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['maxlength']) { <span>Too long.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['min']) { <span>Too low.</span> }`);
      lines.push(`          @if (form.get('${f.name}')?.errors?.['max']) { <span>Too high.</span> }`);
      lines.push('        </p>');
      lines.push('      </div>');
    }

    // Render computed fields (readonly, displayed for info)
    for (const f of computedFields.sort((a, b) => (a.order ?? 999) - (b.order ?? 999))) {
      const label = f.displayName ?? toTitleCase(f.name);
      const dependsOn = (f.computedFrom || f.dependencies || []).join(', ');

      lines.push('      <div class="form-group">');
      lines.push(`        <label for="${f.name}" class="block text-sm font-medium text-gray-700 dark:text-gray-300">${label} <span class="text-xs text-gray-500">(Auto)</span></label>`);
      lines.push(`        <input id="${f.name}" data-testid="field-${f.name}" type="${mapInputType(f)}" formControlName="${f.name}" readonly class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-800 dark:border-gray-600 dark:text-white sm:text-sm bg-gray-100 dark:bg-gray-700 cursor-not-allowed opacity-75">`);
      if (dependsOn) {
        lines.push(`        <p class="mt-1 text-xs text-gray-500">Computed from: ${dependsOn}</p>`);
      }
      lines.push('      </div>');
    }

    lines.push('      <div class="flex justify-end gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">');
    lines.push('        <button type="button" (click)="cancelled.emit()" data-testid="cancel-button" class="rounded-md bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm border border-gray-300 hover:bg-gray-50 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600">Cancel</button>');
    lines.push('        <button type="submit" [disabled]="form.invalid || saving()" data-testid="submit-button" class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50">');
    lines.push(`          @if (saving()) { Saving... } @else { {{ mode() === 'create' ? 'Create' : 'Update' }} ${entityName} }`);
    lines.push('        </button>');
    lines.push('      </div>');
    lines.push('    </form>');
    lines.push('  `,');
    lines.push('})');

    lines.push(`export class ${entityName}FormComponent {`);
    lines.push('  private readonly fb = inject(FormBuilder);');
    lines.push(`  private readonly service = inject(${entityName}Service);`);
    lines.push('');

    // Generate enum arrays
    for (const enumType of Array.from(enumTypes)) {
      lines.push(`  readonly ${enumType}Values = Object.values(${enumType});`);
      lines.push(`  readonly ${enumType}DisplayNames = ${enumType}DisplayNames;`);
      lines.push('');
    }

    lines.push(`  readonly mode = input<'create' | 'edit'>('create');`);
    lines.push(`  readonly entity = input<${entityName} | null>(null);`);
    lines.push('');
    lines.push(`  readonly saved = output<${entityName}>();`);
    lines.push('  readonly cancelled = output<void>();');
    lines.push('');
    lines.push('  readonly saving = signal(false);');
    lines.push('  readonly error = signal<string | null>(null);');
    lines.push('');
    lines.push('  readonly form = this.fb.group({');
    for (const f of createFields) {
      const validators: string[] = [];
      if (f.required) validators.push('Validators.required');
      if (f.minLength) validators.push(`Validators.minLength(${f.minLength})`);
      if (f.maxLength) validators.push(`Validators.maxLength(${f.maxLength})`);
      if (f.pattern) validators.push(`Validators.pattern(/${f.pattern}/)`);
      if (f.min !== undefined) validators.push(`Validators.min(${f.min})`);
      if (f.max !== undefined) validators.push(`Validators.max(${f.max})`);
      const validatorsArray = validators.length ? `[${validators.join(', ')}]` : '[]';
      const defaultValue = f.defaultValue ? `'${f.defaultValue}'` : (f.type === 'java.lang.Boolean' ? 'false' : "''");
      lines.push(`    ${f.name}: [${defaultValue}, ${validatorsArray}],`);
    }
    lines.push('  });');
    lines.push('');
    lines.push('  constructor() {');

    // Generate effects for computed fields
    if (computedFields.length > 0) {
      for (const cf of computedFields) {
        const deps = cf.computedFrom || cf.dependencies || [];
        if (deps.length > 0) {
          lines.push(`    // Auto-sync ${cf.name} based on ${deps.join(', ')}`);
          lines.push('    effect(() => {');
          lines.push('      const values = {');
          for (const dep of deps) {
            lines.push(`        ${dep}: this.form.get('${dep}')?.value,`);
          }
          lines.push('      };');
          lines.push(`      const computed${toTitleCase(cf.name)} = this.compute${toTitleCase(cf.name)}(values);`);
          lines.push(`      this.form.get('${cf.name}')?.setValue(computed${toTitleCase(cf.name)}, { emitEvent: false });`);
          lines.push('    });');
          lines.push('');
        }
      }
    }

    lines.push('    effect(() => {');
    lines.push('      const entity = this.entity();');
    lines.push('      if (entity && this.mode() === "edit") {');
    lines.push('        this.form.patchValue(entity as any);');
    lines.push('      }');
    lines.push('    });');
    lines.push('  }');
    lines.push('');
    lines.push('  onSubmit(): void {');
    lines.push('    if (this.form.invalid) {');
    lines.push('      this.form.markAllAsTouched();');
    lines.push('      return;');
    lines.push('    }');
    lines.push('');
    lines.push('    this.saving.set(true);');
    lines.push('    this.error.set(null);');
    lines.push('');
    lines.push('    const data = this.form.getRawValue();');
    lines.push(`    const request$ = this.mode() === 'create' ? this.service.create(data as ${entityName}Create) : this.service.update(String(this.entity()!.${idField}), data as ${entityName}Update);`);
    lines.push('');
    lines.push('    request$.subscribe({');
    lines.push('      next: (result) => {');
    lines.push('        this.saving.set(false);');
    lines.push('        this.saved.emit(result);');
    lines.push('      },');
    lines.push('      error: (err) => {');
    lines.push('        this.saving.set(false);');
    lines.push("        this.error.set(err?.message ?? 'An error occurred');");
    lines.push('      },');
    lines.push('    });');
    lines.push('  }');

    // Generate compute methods for computed fields
    for (const cf of computedFields) {
      const deps = cf.computedFrom || cf.dependencies || [];
      const methodName = `compute${toTitleCase(cf.name)}`;
      lines.push('');
      lines.push(`  private ${methodName}(values: { ${deps.map(d => `${d}: any`).join(', ')} }): any {`);
      lines.push('    // TODO: Implement computation logic');
      lines.push(`    // Depends on: ${deps.join(', ')}`);
      lines.push('    return null;');
      lines.push('  }');
    }

    lines.push('}');

    return lines.join('\n');
  }
}

export function generateForm(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile | null {
  const generator = new FormGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context);
}



