/**
 * Angular Form Generator
 * Generates Angular 22+ form components with Signals from domain metadata.
 */

import type { DomainMetadata } from '../../models/domain-model.js';
import { modelTypeName } from '../../models/model-naming.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, EnumMetadata, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { outPath } from '../../core/paths.js';
import { updateVersionField } from '../api/type-gen.js';
import { fieldRenderContext, resolveFieldRenders, toTitleCase, type FieldRenderModel } from './field-render.js';
import { tsSingleQuoted } from './ts-literal.js';
import { entityExitRoute, entityViews, hasFormPage } from './entity-views.js';

export { GeneratedFile };

export class FormGenerator implements CodeGenerator {
  readonly name = 'FormGenerator';
  readonly artifactType = 'FORM' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 20;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    // One component serves both the create and the edit route, so it is dropped only when both are off.
    if (!hasFormPage(entityViews(domain))) {
      return null;
    }

    const content = this.generateFormContent(domain, context);
    const fileName = `${DslMapper.toKebabCase(domain.entityName)}-form.component.ts`;
    const filePath = outPath('components', fileName);

    return {
      path: filePath,
      content,
      artifactType: 'FORM',
      overwritable: true,
    };
  }

  private generateFormContent(domain: DomainMetadata, context: GeneratorContext): string {
    // A versioned entity's lock field is never a control: the edit form holds the loaded
    // entity's value aside and sends it with the update (type-gen's updateVersionField names it).
    const version = updateVersionField(domain);
    // The expression reading the version off a loaded entity. When the metadata does not declare
    // the field, the entity interface has no such property, so it is read through a narrowing cast.
    const readVersion = (entityExpr: string): string => {
      const name = version!.name;
      return version!.declared
        ? `${entityExpr}.${name} ?? null`
        : `(${entityExpr} as unknown as { ${name}?: number }).${name} ?? null`;
    };
    const entityName = domain.entityName;

    const modelName = modelTypeName(entityName);
    const kebabName = DslMapper.toKebabCase(entityName);
    const noun = tsSingleQuoted((domain.displayName ?? entityName).toLowerCase());
    // The literal 'id', deliberately, not systemFields.primaryKeyField. Nothing in the pipeline
    // honours that override: KernelFlywayGenerator emits `id UUID PRIMARY KEY` unconditionally,
    // KernelRepositoryGenerator's WHERE clause is the constant " WHERE id = ?", every by-id
    // handler binds the {id} path variable, and the processor says so outright ("generators leave
    // the primary key as the literal id"). Reading it here would make this the only layer that
    // honours it, and the emitted app would then request the wrong identifier.
    const idField = 'id';

    // No control for a system field (type-gen's viewSystemFieldNames). That includes a UNIVERSE
    // entity's shared-scope key, which is server-owned like its tenant: the repository stamps it
    // from the bound storage context and the create DTO omits it, so the form never sends it.
    // The form renders no link, so the context resolves none.
    const renders = resolveFieldRenders(domain, fieldRenderContext(domain, [], false, context.enums ?? []));
    const createFields = renders.filter((r) => r.form.placement === 'control');
    // Computed fields render read-only, for information, and are kept out of the submitted DTO.
    const computedFields = renders.filter((r) => r.form.placement === 'computed');

    const lines: string[] = [];
    lines.push('/**');
    lines.push(` * ${entityName} Form Component`);
    lines.push(' * Generated by @exeris/codegen-ts');
    lines.push(' * Uses Angular 22 standalone components + signals');
    lines.push(' */');
    lines.push('');
    const plural = DslMapper.routePlural(entityName);
    // A routed form returns to the saved instance's detail page; without one, it leaves the entity.
    const views = entityViews(domain);
    const exitRoute = entityExitRoute(domain, views);
    const formModelName = `${entityName}FormModel`;
    const validation = formValidation(createFields);

    lines.push("import { Component, ChangeDetectionStrategy, input, output, signal, computed, effect, inject } from '@angular/core';");
    lines.push("import { rxResource } from '@angular/core/rxjs-interop';");
    lines.push(`import { ${signalFormsImports(validation).join(', ')} } from '@angular/forms/signals';`);
    lines.push("import { ActivatedRoute, Router } from '@angular/router';");
    lines.push(`import { ${modelName}, ${modelName}Create, ${modelName}Update, ${entityName}Service } from '../services/${kebabName}.service';`);
    lines.push("import { httpErrorMessage } from '../core/http-error';");

    // Collect enum types used in create fields
    const enumTypes = new Set<string>();
    for (const f of createFields) {
      if (f.form.enumType) {
        enumTypes.add(f.form.enumType);
      }
    }

    if (enumTypes.size > 0) {
      const enumImports = Array.from(enumTypes).flatMap(e => [e, `${e}DisplayNames`]);
      lines.push(`import { ${enumImports.join(', ')} } from '../types/enums';`);
    }

    lines.push('');
    // The value the form edits: one property per control, typed as the control holds it.
    lines.push(`interface ${formModelName} {`);
    for (const f of createFields) {
      lines.push(`  ${f.name}: ${f.form.modelType};`);
    }
    lines.push('}');
    lines.push('');
    lines.push('@Component({');
    lines.push(`  selector: 'app-${kebabName}-form',`);
    lines.push('  standalone: true,');
    lines.push('  imports: [FormField],');
    lines.push('  changeDetection: ChangeDetectionStrategy.OnPush,');
    lines.push('  template: `');
    // Loading and error of the by-id load mirror the detail view's markup.
    lines.push('    @if (isLoading()) {');
    lines.push('      <div class="animate-pulse space-y-4 mb-6" role="status" aria-label="Loading...">');
    lines.push('        <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded-sm w-1/2"></div>');
    lines.push('      </div>');
    lines.push('    } @else if (loadError()) {');
    lines.push('      <div role="alert" class="exeris-alert exeris-alert-danger mb-6">');
    lines.push('        <p>{{ loadError() }}</p>');
    lines.push('        <button type="button" (click)="reload()" class="exeris-btn exeris-btn-secondary exeris-btn-sm mt-4">Try again</button>');
    lines.push('      </div>');
    lines.push('    }');
    // The form validates itself, so the browser's own validation of the bound attributes is off.
    lines.push('    <form (submit)="onSubmit($event)" novalidate class="space-y-6">');

    for (const f of createFields) {
      const { label, control, inputType, inputMode, enumType: enumTypeName } = f.form;
      const requiredMark = f.form.required ? '<span class="text-red-500" aria-hidden="true">*</span>' : '';
      const binding = `[formField]="form.${f.name}"`;
      const state = `form.${f.name}()`;
      // The kit's error border marks a field the error text below it describes.
      const errorClass = `[class.exeris-input-error]="${state}.invalid() && ${state}.touched()"`;

      lines.push('      <div class="form-group">');

      if (control === 'select') {
        lines.push(`        <label for="${f.name}" class="exeris-label">${label} ${requiredMark}</label>`);
        lines.push(`        <select id="${f.name}" data-testid="field-${f.name}" ${binding} class="exeris-select mt-1" ${errorClass}>`);
        lines.push('          <option value="">Select...</option>');
        lines.push(`          @for (value of ${enumTypeName}Values; track value) {`);
        lines.push(`            <option [value]="value">{{ ${enumTypeName}DisplayNames[value] }}</option>`);
        lines.push('          }');
        lines.push('        </select>');
      } else if (control === 'checkbox') {
        lines.push('        <div class="flex items-center gap-2">');
        lines.push(`          <input id="${f.name}" data-testid="field-${f.name}" type="checkbox" ${binding} class="exeris-checkbox">`);
        lines.push(`          <label for="${f.name}" class="exeris-label">${label} ${requiredMark}</label>`);
        lines.push('        </div>');
      } else {
        const inputExtra = inputMode ? ` inputmode="${inputMode}"` : '';
        lines.push(`        <label for="${f.name}" class="exeris-label">${label} ${requiredMark}</label>`);
        lines.push(`        <input id="${f.name}" data-testid="field-${f.name}" type="${inputType}" ${binding} class="exeris-input mt-1" ${errorClass}${inputExtra}>`);
      }
      lines.push(`        @if (${state}.invalid() && ${state}.touched()) {`);
      lines.push(`          <p class="exeris-error-text" data-testid="error-${f.name}">`);
      lines.push(`            @if (${state}.getError('required')) { <span>${label} is required.</span> }`);
      // A value the native control cannot parse (a partial date, a non-number) reads as a format error.
      lines.push(`            @if (${state}.getError('pattern') || ${state}.getError('parse')) { <span>Invalid format.</span> }`);
      lines.push(`            @if (${state}.getError('minLength')) { <span>Too short.</span> }`);
      lines.push(`            @if (${state}.getError('maxLength')) { <span>Too long.</span> }`);
      lines.push(`            @if (${state}.getError('min')) { <span>Too low.</span> }`);
      lines.push(`            @if (${state}.getError('max')) { <span>Too high.</span> }`);
      lines.push('          </p>');
      lines.push('        }');
      lines.push('      </div>');
    }

    // Computed fields are shown for information: read-only, and not part of the form model.
    for (const f of computedFields) {
      const label = f.form.label;
      const dependsOn = f.form.computedFrom.join(', ');

      lines.push('      <div class="form-group">');
      lines.push(`        <label for="${f.name}" class="exeris-label">${label} <span class="text-xs text-gray-500">(Auto)</span></label>`);
      // Read-only: the field takes the kit's muted surface instead of the editable one.
      lines.push(`        <input id="${f.name}" data-testid="field-${f.name}" type="${f.form.inputType}" [value]="${computedSignalName(f.name)}() ?? ''" readonly class="exeris-input mt-1 bg-[rgb(var(--exeris-bg-tertiary))] cursor-not-allowed opacity-75">`);
      if (dependsOn) {
        lines.push(`        <p class="exeris-help-text">Computed from: ${dependsOn}</p>`);
      }
      lines.push('      </div>');
    }

    lines.push('      @if (error()) {');
    lines.push('        <div role="alert" data-testid="submit-error" class="exeris-alert exeris-alert-danger text-sm">{{ error() }}</div>');
    lines.push('      }');
    if (version) {
      // The server answers a stale update with 409 and no body; the only recovery is to load
      // the row as it now stands, which also picks up its current version.
      lines.push('      @if (conflict()) {');
      lines.push('        <div role="alert" data-testid="conflict-message" class="exeris-alert exeris-alert-warning text-sm">');
      lines.push('          <p>This record was changed by someone else. Reload to see the latest version.</p>');
      lines.push('          <button type="button" (click)="reload()" data-testid="reload-button" class="exeris-btn exeris-btn-secondary exeris-btn-sm mt-2">Reload</button>');
      lines.push('        </div>');
      lines.push('      }');
    }
    lines.push('      <div class="flex justify-end gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">');
    lines.push('        <button type="button" (click)="onCancel()" data-testid="cancel-button" class="exeris-btn exeris-btn-secondary">Cancel</button>');
    lines.push('        <button type="submit" [disabled]="form().invalid() || saving() || (editMode() && !current())" data-testid="submit-button" class="exeris-btn exeris-btn-primary">');
    lines.push(`          @if (saving()) { Saving... } @else { {{ editMode() ? 'Update' : 'Create' }} ${entityName} }`);
    lines.push('        </button>');
    lines.push('      </div>');
    lines.push('    </form>');
    lines.push('  `,');
    lines.push('})');

    lines.push(`export class ${entityName}FormComponent {`);
    lines.push(`  private readonly service = inject(${entityName}Service);`);
    lines.push('  private readonly router = inject(Router);');
    // The form is a page when its activated route's component is this class; embedded in a
    // host template it sees the host's route instead (or none), and leaves the next step to
    // the host listening on `saved` / `cancelled`.
    lines.push(`  private readonly routed = inject(ActivatedRoute, { optional: true })?.component === ${entityName}FormComponent;`);
    lines.push('');

    // Generate enum arrays
    for (const enumType of Array.from(enumTypes)) {
      lines.push(`  readonly ${enumType}Values = Object.values(${enumType});`);
      lines.push(`  readonly ${enumType}DisplayNames = ${enumType}DisplayNames;`);
      lines.push('');
    }

    lines.push(`  readonly mode = input<'create' | 'edit'>('create');`);
    lines.push(`  readonly entity = input<${modelName} | null>(null);`);
    // Bound from the `:id` route parameter by withComponentInputBinding on the edit route.
    lines.push('  readonly id = input<string | undefined>();');
    lines.push('');
    lines.push('  private readonly entityResource = rxResource({');
    lines.push('    params: () => this.id(),');
    lines.push('    stream: ({ params }) => this.service.findById(params),');
    lines.push('  });');
    lines.push('');
    // An embedding host's `entity` wins over the by-id load; an `id` always means edit.
    lines.push(`  readonly current = computed<${modelName} | null>(() => this.entity() ?? this.entityResource.value() ?? null);`);
    lines.push("  readonly editMode = computed(() => this.id() !== undefined || this.mode() === 'edit');");
    lines.push('  readonly isLoading = computed(() => this.entityResource.isLoading());');
    lines.push('  readonly loadError = computed(() => {');
    lines.push('    const err = this.entityResource.error();');
    lines.push(`    return err ? httpErrorMessage(err, { entity: '${noun}', action: 'load' }) : null;`);
    lines.push('  });');
    lines.push('');
    lines.push(`  readonly saved = output<${modelName}>();`);
    lines.push('  readonly cancelled = output<void>();');
    lines.push('');
    lines.push('  readonly saving = signal(false);');
    lines.push('  readonly error = signal<string | null>(null);');
    if (version) {
      lines.push('  readonly conflict = signal(false);');
      lines.push('');
      lines.push(`  /** The ${version.name} the edited entity was loaded at; the update sends it back as the expected version. */`);
      const versionType = version.tsType.endsWith('| null') ? version.tsType : `${version.tsType} | null`;
      lines.push(`  private readonly loadedVersion = signal<${versionType}>(null);`);
    }
    lines.push('');
    lines.push(`  private readonly formModel = signal<${formModelName}>({`);
    for (const f of createFields) {
      lines.push(`    ${f.name}: ${f.form.initialValue},`);
    }
    lines.push('  });');
    if (validation.rules.length > 0) {
      lines.push('  readonly form = form(this.formModel, (path) => {');
      for (const rule of validation.rules) {
        lines.push(`    ${rule}`);
      }
      lines.push('  });');
    } else {
      lines.push('  readonly form = form(this.formModel);');
    }

    // A computed field is derived from the values it depends on, read from the form model when
    // the dependency is a control and from the loaded entity otherwise.
    const controlNames = new Set(createFields.map((f) => f.name));
    const declaredNames = new Set((domain.fields ?? []).map((f) => f.name));
    for (const cf of computedFields) {
      const deps = cf.form.computedFrom;
      const values = deps.map((dep) => {
        const source = controlNames.has(dep)
          ? `this.formModel().${dep}`
          : declaredNames.has(dep) ? `this.current()?.${dep}` : 'undefined';
        return `${dep}: ${source}`;
      });
      lines.push('');
      if (deps.length > 0) {
        lines.push(`  // Auto-sync ${cf.name} based on ${deps.join(', ')}`);
      }
      const argument = values.length > 0 ? `{ ${values.join(', ')} }` : '{}';
      lines.push(`  readonly ${computedSignalName(cf.name)} = computed(() => this.${computeMethodName(cf.name)}(${argument}));`);
    }
    lines.push('');
    lines.push('  constructor() {');
    lines.push('    effect(() => {');
    lines.push('      const entity = this.current();');
    lines.push('      if (entity && this.editMode()) {');
    lines.push('        this.formModel.set(this.toFormModel(entity));');
    if (version) {
      lines.push(`        this.loadedVersion.set(${readVersion('entity')});`);
    }
    lines.push('      }');
    lines.push('    });');
    lines.push('  }');
    lines.push('');
    // A loaded value the control cannot show (null, or absent) becomes the control's empty value.
    lines.push(`  private toFormModel(entity: ${modelName}): ${formModelName} {`);
    lines.push('    return {');
    for (const f of createFields) {
      lines.push(`      ${f.name}: entity.${f.name} ?? ${f.form.emptyValue},`);
    }
    lines.push('    };');
    lines.push('  }');
    lines.push('');
    // submit() marks every field touched and runs the action only when the form is valid.
    lines.push('  onSubmit(event: Event): void {');
    lines.push('    event.preventDefault();');
    lines.push('    void submit(this.form, () => this.save());');
    lines.push('  }');
    lines.push('');
    // The generated server names no field in a failed response, so a save resolves to no field
    // error: every failure is reported at form level.
    lines.push('  private save(): Promise<undefined> {');
    // Edit mode without a loaded entity would overwrite a row it never read.
    lines.push('    const current = this.current();');
    lines.push('    if (this.editMode() && !current) {');
    lines.push('      return Promise.resolve(undefined);');
    lines.push('    }');
    lines.push('');
    lines.push('    this.saving.set(true);');
    lines.push('    this.error.set(null);');
    if (version) lines.push('    this.conflict.set(false);');
    lines.push('');
    // A number control holds `number | null`, the DTO's own type, so the model is the payload.
    lines.push('    const data = this.formModel();');
    // The generated update writes every column of the row, so the edit payload is the loaded record
    // with the form's values over it: a field the form does not offer (read-only, hidden, create-only)
    // keeps its stored value. An `inUpdate = false` field is taken from the loaded record itself, not
    // from the model, whose seed turns a stored null into the control's empty value.
    const fixedInEdit = createFields
      .filter((r) => !r.form.inUpdate)
      .map((r) => `, ${r.name}: current.${r.name}`)
      .join('');
    const updatePayload = version
      ? `{ ...current, ...data${fixedInEdit}, ${version.name}: this.loadedVersion() } as ${modelName}Update`
      : `{ ...current, ...data${fixedInEdit} } as ${modelName}Update`;
    lines.push(`    const request$ = this.editMode() && current ? this.service.update(String(current.${idField}), ${updatePayload}) : this.service.create(data as ${modelName}Create);`);
    lines.push('');
    lines.push('    return new Promise((resolve) => {');
    lines.push('      request$.subscribe({');
    lines.push('        next: (result) => {');
    lines.push('          this.saving.set(false);');
    lines.push('          resolve(undefined);');
    lines.push('          this.saved.emit(result);');
    lines.push('          if (this.routed) {');
    lines.push(views.detail
      ? `            void this.router.navigate(['/${plural}', String(result.${idField})]);`
      : `            void this.router.navigate(['${exitRoute}']);`);
    lines.push('          }');
    lines.push('        },');
    lines.push('        error: (err) => {');
    lines.push('          this.saving.set(false);');
    lines.push('          resolve(undefined);');
    if (version) {
      // A conflict is about the whole row, never one field.
      lines.push("          if (this.editMode() && err?.status === 409) {");
      lines.push('            this.conflict.set(true);');
      lines.push('            return;');
      lines.push('          }');
    }
    lines.push(`          this.error.set(httpErrorMessage(err, { entity: '${noun}', action: 'save' }));`);
    lines.push('        },');
    lines.push('      });');
    lines.push('    });');
    lines.push('  }');
    lines.push('');
    lines.push('  onCancel(): void {');
    lines.push('    this.cancelled.emit();');
    lines.push('    if (this.routed) {');
    // Back to the entity being edited, or to the list when nothing was.
    if (views.detail) {
      lines.push('      const id = this.id();');
      lines.push(`      void this.router.navigate(id !== undefined ? ['/${plural}', id] : ['${exitRoute}']);`);
    } else {
      lines.push(`      void this.router.navigate(['${exitRoute}']);`);
    }
    lines.push('    }');
    lines.push('  }');
    lines.push('');
    if (!version) {
      lines.push('  reload(): void { this.entityResource.reload(); }');
    } else {
      // A form loaded by id reloads its resource, and the patch effect picks up the fresh
      // values and version. A host-supplied entity has no resource behind it, so the row is
      // fetched directly.
      lines.push('  /** Loads the row as it now stands, replacing the edited values and the expected version. */');
      lines.push('  reload(): void {');
      lines.push('    this.conflict.set(false);');
      lines.push('    if (this.id() !== undefined) {');
      lines.push('      this.entityResource.reload();');
      lines.push('      return;');
      lines.push('    }');
      lines.push('    const current = this.current();');
      lines.push('    if (!current) return;');
      lines.push(`    this.service.findById(String(current.${idField})).subscribe({`);
      lines.push('      next: (fresh) => {');
      lines.push('        this.form().reset(this.toFormModel(fresh));');
      lines.push(`        this.loadedVersion.set(${readVersion('fresh')});`);
      lines.push('      },');
      lines.push(`      error: (err) => this.error.set(httpErrorMessage(err, { entity: '${noun}', action: 'load' })),`);
      lines.push('    });');
      lines.push('  }');
    }

    // Generate compute methods for computed fields
    for (const cf of computedFields) {
      const deps = cf.form.computedFrom;
      lines.push('');
      lines.push(`  private ${computeMethodName(cf.name)}(values: { ${deps.map(d => `${d}: any`).join(', ')} }): any {`);
      lines.push('    // TODO: Implement computation logic');
      lines.push(`    // Depends on: ${deps.join(', ')}`);
      lines.push('    return null;');
      lines.push('  }');
    }

    lines.push('}');

    return lines.join('\n');
  }
}

export function generateForm(
  metadata: DomainMetadata,
  config: GeneratorConfig,
  enums: EnumMetadata[] = [],
): GeneratedFile | null {
  const generator = new FormGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums };
  return generator.generate(metadata, context);
}




/** The validation rules of a form schema, and the `@angular/forms/signals` functions they call. */
interface FormValidation {
  readonly rules: string[];
  readonly used: ReadonlySet<string>;
}

/**
 * The schema rules `FieldMetadata` declares, field by field in declaration order, each field's
 * rules in the order required, minLength, maxLength, pattern, min, max, disabled.
 *
 * - `required` is not applied to a checkbox. Signal Forms counts `false` as empty, which would
 *   force the box to be ticked; a required boolean only has to hold a boolean, which it always does.
 * - length and pattern apply to text controls only: a number control holds a number, and a
 *   length or pattern constraint is declared on character sequences.
 * - min and max bound a number control directly. A text control holding a decimal string is bounded
 *   by its parsed value; a blank or unparseable value passes.
 * - `disabled` applies to a field with `inUpdate = false` while the form edits. A disabled field
 *   takes no input and is not validated, so a required field the edit cannot change never blocks it.
 */
function formValidation(fields: readonly FieldRenderModel[]): FormValidation {
  const rules: string[] = [];
  const used = new Set<string>();
  const add = (rule: string, ...fns: string[]): void => {
    rules.push(rule);
    for (const fn of fns) used.add(fn);
  };
  for (const { name, form, field: f } of fields) {
    const path = `path.${name}`;
    if (f.required && form.value !== 'boolean') add(`required(${path});`, 'required');
    if (form.value === 'text') {
      if (f.minLength) add(`minLength(${path}, ${f.minLength});`, 'minLength');
      if (f.maxLength) add(`maxLength(${path}, ${f.maxLength});`, 'maxLength');
      if (f.pattern) add(`pattern(${path}, /${f.pattern}/);`, 'pattern');
      if (f.min !== undefined) {
        add(`validate(${path}, ({ value }) => (parseFloat(value()) < ${f.min} ? minError(${f.min}) : undefined));`, 'validate', 'minError');
      }
      if (f.max !== undefined) {
        add(`validate(${path}, ({ value }) => (parseFloat(value()) > ${f.max} ? maxError(${f.max}) : undefined));`, 'validate', 'maxError');
      }
    } else if (form.value === 'number') {
      if (f.min !== undefined) add(`min(${path}, ${f.min});`, 'min');
      if (f.max !== undefined) add(`max(${path}, ${f.max});`, 'max');
    }
    if (!form.inUpdate) add(`disabled(${path}, { when: () => this.editMode() });`, 'disabled');
  }
  return { rules, used };
}

/**
 * The `@angular/forms/signals` imports of a form, in a fixed order. Every one is stable in the
 * Angular major the emitted `package.json` pins (ADR-093): no experimental or developer-preview
 * symbol is emitted.
 */
const SIGNAL_FORMS_IMPORT_ORDER = [
  'form', 'FormField', 'submit',
  'required', 'minLength', 'maxLength', 'pattern', 'min', 'max', 'validate', 'minError', 'maxError',
  'disabled',
] as const;

function signalFormsImports(validation: FormValidation): string[] {
  const always = new Set(['form', 'FormField', 'submit']);
  return SIGNAL_FORMS_IMPORT_ORDER.filter((name) => always.has(name) || validation.used.has(name));
}

/** `fullName` to `FullName`, the suffix of a computed field's member names. */
function memberSuffix(name: string): string {
  return toTitleCase(name).replace(/ /g, '');
}

function computedSignalName(name: string): string {
  return `computed${memberSuffix(name)}`;
}

function computeMethodName(name: string): string {
  return `compute${memberSuffix(name)}`;
}
