/**
 * Angular Route Guard Generator
 *
 * Generates Angular 21+ functional route guards with:
 * - Permission-based access control
 * - Role-based access control
 * - Authentication checks
 *
 * @author Exeris Team
 * @since 0.4.0
 */

import type { DomainMetadata, ActionMetadata, CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { join } from 'node:path';

export class GuardGenerator implements CodeGenerator {
  readonly name = 'GuardGenerator';
  readonly artifactType = 'GUARD' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 15;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (domain.internalApi?.hidden) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateGuardContent(domain, context);

    return {
      path: join('guards', `${kebab}.guard.ts`),
      content,
      artifactType: 'GUARD',
      overwritable: true,
    };
  }

  generateAggregate(domains: DomainMetadata[], context: GeneratorContext): GeneratedFile[] {
    return [
      {
        path: 'core/auth.service.ts',
        content: this.generateAuthService(),
        artifactType: 'GUARD',
        overwritable: false,
      },
      {
        path: 'guards/index.ts',
        content: this.generateBarrelExport(domains),
        artifactType: 'GUARD',
        overwritable: true,
      },
    ];
  }

  private generateGuardContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName } = domain;
    const kebab = DslMapper.toKebabCase(entityName);
    const permission = kebab.replace(/-/g, '_');
    const isReadOnly = domain.internalApi?.readOnly ?? false;

    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * ${entityName} Route Guards`);
    lines.push(` * Generated by @exeris/codegen-ts v0.4.0`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` */`);
    lines.push(``);
    lines.push(`import { inject } from '@angular/core';`);
    lines.push(`import { Router, type CanActivateFn, type ActivatedRouteSnapshot, type RouterStateSnapshot } from '@angular/router';`);
    lines.push(`import { AuthService } from '../core/auth.service';`);
    lines.push(``);

    lines.push(`export const ${entityName.toUpperCase()}_PERMISSIONS = {`);
    lines.push(`  READ: '${permission}:read',`);
    lines.push(`  CREATE: '${permission}:create',`);
    lines.push(`  UPDATE: '${permission}:update',`);
    lines.push(`  DELETE: '${permission}:delete',`);
    lines.push(`} as const;`);
    lines.push(``);

    lines.push(`export const canView${entityName}: CanActivateFn = (route, state) => {`);
    lines.push(`  const auth = inject(AuthService);`);
    lines.push(`  const router = inject(Router);`);
    lines.push(`  if (!auth.isAuthenticated()) return router.createUrlTree(['/login'], { queryParams: { returnUrl: state.url } });`);
    lines.push(`  if (!auth.hasPermission(${entityName.toUpperCase()}_PERMISSIONS.READ) && !auth.hasRole('ADMIN')) return router.createUrlTree(['/forbidden']);`);
    lines.push(`  return true;`);
    lines.push(`};`);
    lines.push(``);

    if (!isReadOnly) {
      lines.push(`export const canCreate${entityName}: CanActivateFn = (route, state) => {`);
      lines.push(`  const auth = inject(AuthService);`);
      lines.push(`  const router = inject(Router);`);
      lines.push(`  if (!auth.isAuthenticated()) return router.createUrlTree(['/login'], { queryParams: { returnUrl: state.url } });`);
      lines.push(`  if (!auth.hasPermission(${entityName.toUpperCase()}_PERMISSIONS.CREATE) && !auth.hasRole('ADMIN')) return router.createUrlTree(['/forbidden']);`);
      lines.push(`  return true;`);
      lines.push(`};`);
      lines.push(``);

      lines.push(`export const canEdit${entityName}: CanActivateFn = (route, state) => {`);
      lines.push(`  const auth = inject(AuthService);`);
      lines.push(`  const router = inject(Router);`);
      lines.push(`  if (!auth.isAuthenticated()) return router.createUrlTree(['/login'], { queryParams: { returnUrl: state.url } });`);
      lines.push(`  if (!auth.hasPermission(${entityName.toUpperCase()}_PERMISSIONS.UPDATE) && !auth.hasRole('ADMIN')) return router.createUrlTree(['/forbidden']);`);
      lines.push(`  return true;`);
      lines.push(`};`);
      lines.push(``);

      lines.push(`export const canDelete${entityName}: CanActivateFn = (route, state) => {`);
      lines.push(`  const auth = inject(AuthService);`);
      lines.push(`  const router = inject(Router);`);
      lines.push(`  if (!auth.isAuthenticated()) return router.createUrlTree(['/login'], { queryParams: { returnUrl: state.url } });`);
      lines.push(`  if (!auth.hasPermission(${entityName.toUpperCase()}_PERMISSIONS.DELETE) && !auth.hasRole('ADMIN')) return router.createUrlTree(['/forbidden']);`);
      lines.push(`  return true;`);
      lines.push(`};`);
    }

    return lines.join('\n');
  }

  private generateAuthService(): string {
    return `/**
 * Authentication Service
 * Generated by @exeris/codegen-ts v0.4.0
 * NOTE: This file will NOT be overwritten. Implement actual auth logic.
 */

import { Injectable, signal, computed } from '@angular/core';

export interface User {
  id: string;
  username: string;
  email: string;
  roles: string[];
  permissions: string[];
}

@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly _user = signal<User | null>(null);
  private readonly _token = signal<string | null>(null);

  readonly user = this._user.asReadonly();
  readonly token = this._token.asReadonly();
  readonly isAuthenticated = computed(() => this._user() !== null);
  readonly roles = computed(() => this._user()?.roles ?? []);
  readonly permissions = computed(() => this._user()?.permissions ?? []);

  hasRole(role: string): boolean {
    return this.roles().includes(role);
  }

  hasPermission(permission: string): boolean {
    return this.permissions().includes(permission);
  }

  hasAnyPermission(permissions: string[]): boolean {
    return permissions.some(p => this.hasPermission(p));
  }

  setUser(user: User, token: string): void {
    this._user.set(user);
    this._token.set(token);
  }

  clearUser(): void {
    this._user.set(null);
    this._token.set(null);
  }

  getToken(): string | null {
    return this._token();
  }
}
`;
  }

  private generateBarrelExport(domains: DomainMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * Route Guards - Barrel Export`,
      ` * Generated by @exeris/codegen-ts v0.4.0`,
      ` */`,
      ``,
    ];

    for (const domain of domains) {
      if (domain.internalApi?.hidden) continue;
      const kebab = DslMapper.toKebabCase(domain.entityName);
      lines.push(`export * from './${kebab}.guard';`);
    }

    return lines.join('\n');
  }
}

export function generateGuard(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile {
  const generator = new GuardGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context)!;
}

