/**
 * Angular List Generator
 * Generates Angular 22+ list components with:
 * - Signals (zoneless) - signal(), computed(), resource()
 * - Angular CDK A11y - accessibility tables
 * - Animations - row transitions
 * - SSR/Hydration - @defer with @placeholder
 * - Tailwind CSS - styling
 *
 * @author Exeris Team
 * @since 0.2.0
 */

import type { DomainMetadata } from '../../models/domain-model.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { join } from 'node:path';

export { GeneratedFile };

export class ListGenerator implements CodeGenerator {
  readonly name = 'ListGenerator';
  readonly artifactType = 'LIST' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 20;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (domain.internalApi?.hidden) {
      return null;
    }

    const content = this.generateListContent(domain, context);
    const fileName = `${DslMapper.toKebabCase(domain.entityName)}-list.component.ts`;
    const filePath = join('components', fileName);

    return {
      path: filePath,
      content,
      artifactType: 'LIST',
      overwritable: true,
    };
  }

  private generateListContent(domain: DomainMetadata, context: GeneratorContext): string {
    const metadata = domain;
    const entityName = metadata.entityName;
    const kebabName = DslMapper.toKebabCase(entityName);
    const displayName = metadata.displayName ?? entityName;
    const pluralName = metadata.pluralName ?? `${entityName}s`;

    const idField = metadata.systemFields?.idField ?? 'id';

    // Determine list columns
    const listColumnNames = metadata.uiMetadata?.listColumns?.length
      ? metadata.uiMetadata.listColumns
      : this.getDefaultListColumns(metadata);

    const listColumns = listColumnNames
      .map((name) => metadata.fields.find((f) => f.name === name))
      .filter(Boolean)
      .map((field) => {
        const mapping = DslMapper.mapField(field!);
        return {
          name: field!.name,
          label: mapping.label,
          type: field!.type,
          format: field!.format,
          sortable: field!.sortable,
        };
      });

    const filterableFields = metadata.fields.filter((f) => f.filterable);

    const lines: string[] = [];

    // Header
    lines.push(`/**`);
    lines.push(` * ${entityName} List Component`);
    lines.push(` * Generated by @exeris/codegen-ts v0.2.0`);
    lines.push(` *`);
    lines.push(` * Angular 22+ Features:`);
    lines.push(` * - Signals (zoneless) - signal(), computed(), resource()`);
    lines.push(` * - CDK A11y - accessible data table`);
    lines.push(` * - Animations - row enter/leave`);
    lines.push(` * - SSR/Hydration - @defer with skeleton`);
    lines.push(` *`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` */`);
    lines.push(``);

    // Imports
    lines.push(`import {`);
    lines.push(`  Component,`);
    lines.push(`  ChangeDetectionStrategy,`);
    lines.push(`  inject,`);
    lines.push(`  signal,`);
    lines.push(`  computed,`);
    lines.push(`  effect,`);
    lines.push(`  OnInit,`);
    lines.push(`} from '@angular/core';`);
    lines.push(`import { CommonModule } from '@angular/common';`);
    lines.push(`import { RouterModule } from '@angular/router';`);
    lines.push(`import { FormsModule } from '@angular/forms';`);
    lines.push(`import { ${entityName}, ${entityName}Service, PageRequest, ${entityName}Filter, Page } from '../services/${kebabName}.service';`);
    lines.push(`import { Subject, debounceTime, distinctUntilChanged } from 'rxjs';`);
    lines.push(`import { takeUntilDestroyed } from '@angular/core/rxjs-interop';`);
    lines.push(``);

    // Row enter animation is native (animate.enter, Angular 22) — a compiler
    // feature, not a directive, so it needs no @angular/animations import and no
    // provider. The class below is applied to each row on insert and removed by
    // Angular once the keyframe finishes; the per-row stagger is plain CSS
    // (animation-delay bound to $index in the @for).

    // Component
    lines.push(`@Component({`);
    lines.push(`  selector: 'app-${kebabName}-list',`);
    lines.push(`  standalone: true,`);
    lines.push(`  imports: [CommonModule, RouterModule, FormsModule],`);
    lines.push(`  changeDetection: ChangeDetectionStrategy.OnPush,`);
    lines.push(`  styles: [\``);
    lines.push(`    .row-enter { animation: row-enter-kf 200ms ease-out both; }`);
    lines.push(`    @keyframes row-enter-kf {`);
    lines.push(`      from { opacity: 0; transform: translateY(-10px); }`);
    lines.push(`      to { opacity: 1; transform: translateY(0); }`);
    lines.push(`    }`);
    lines.push(`  \`],`);
    lines.push(`  host: {`);
    lines.push(`    'class': 'block',`);
    lines.push(`  },`);
    lines.push(`  template: \``);

    // Template
    lines.push(`    <div class="space-y-6">`);
    lines.push(`      <!-- Header -->`);
    lines.push(`      <div class="sm:flex sm:items-center sm:justify-between">`);
    lines.push(`        <div>`);
    lines.push(`          <h1 class="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">${pluralName}</h1>`);
    lines.push(`          <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">`);
    lines.push(`            @if (totalElements() > 0) {`);
    lines.push(`              {{ totalElements() }} {{ totalElements() === 1 ? '${displayName.toLowerCase()}' : '${pluralName.toLowerCase()}' }} found`);
    lines.push(`            } @else {`);
    lines.push(`              No ${pluralName.toLowerCase()} yet`);
    lines.push(`            }`);
    lines.push(`          </p>`);
    lines.push(`        </div>`);
    lines.push(`        <div class="mt-4 sm:ml-16 sm:mt-0">`);
    lines.push(`          <a`);
    lines.push(`            routerLink="new"`);
    lines.push(`            data-testid="action-create"`);
    lines.push(`            class="inline-flex items-center rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"`);
    lines.push(`          >`);
    lines.push(`            <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">`);
    lines.push(`              <path d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />`);
    lines.push(`            </svg>`);
    lines.push(`            New ${displayName}`);
    lines.push(`          </a>`);
    lines.push(`        </div>`);
    lines.push(`      </div>`);
    lines.push(``);

    // Search & Filters
    lines.push(`      <!-- Search & Filters -->`);
    lines.push(`      <div class="flex flex-col gap-4 sm:flex-row sm:items-center">`);
    lines.push(`        <div class="relative flex-1">`);
    lines.push(`          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">`);
    lines.push(`            <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">`);
    lines.push(`              <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />`);
    lines.push(`            </svg>`);
    lines.push(`          </div>`);
    lines.push(`          <input`);
    lines.push(`            type="search"`);
    lines.push(`            [(ngModel)]="searchQuery"`);
    lines.push(`            (ngModelChange)="onSearch($event)"`);
    lines.push(`            placeholder="Search ${pluralName.toLowerCase()}..."`);
    lines.push(`            aria-label="Search ${pluralName.toLowerCase()}"`);
    lines.push(`            data-testid="search-input"`);
    lines.push(`            class="block w-full rounded-md border-0 py-2 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 dark:bg-gray-800 dark:text-white dark:ring-gray-600 sm:text-sm sm:leading-6"`);
    lines.push(`          />`);
    lines.push(`        </div>`);

    // Filter dropdowns
    for (const field of filterableFields.slice(0, 2)) {
      const mapping = DslMapper.mapField(field);
      if (field.type === 'Boolean') {
        lines.push(`        <select`);
        lines.push(`          [(ngModel)]="filter${field.name.charAt(0).toUpperCase() + field.name.slice(1)}"`);
        lines.push(`          (ngModelChange)="onFilterChange()"`);
        lines.push(`          aria-label="Filter by ${mapping.label}"`);
        lines.push(`          data-testid="filter-${field.name}"`);
        lines.push(`          class="rounded-md border-0 py-2 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 dark:bg-gray-800 dark:text-white dark:ring-gray-600 sm:text-sm"`);
        lines.push(`        >`);
        lines.push(`          <option value="">All ${mapping.label}</option>`);
        lines.push(`          <option value="true">Yes</option>`);
        lines.push(`          <option value="false">No</option>`);
        lines.push(`        </select>`);
      }
    }
    lines.push(`      </div>`);
    lines.push(``);

    // Table with @defer for SSR
    lines.push(`      <!-- Data Table -->`);
    lines.push(`      @defer (on viewport; prefetch on idle) {`);
    lines.push(`        <div class="overflow-hidden rounded-lg border border-gray-200 shadow-sm dark:border-gray-700">`);
    lines.push(`          @if (isLoading() && items().length === 0) {`);
    lines.push(`            <!-- Loading skeleton -->`);
    lines.push(`            <div class="animate-pulse">`);
    lines.push(`              <div class="h-12 bg-gray-100 dark:bg-gray-800"></div>`);
    lines.push(`              @for (i of [1,2,3,4,5]; track i) {`);
    lines.push(`                <div class="h-16 border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900">`);
    lines.push(`                  <div class="flex items-center gap-4 p-4">`);
    lines.push(`                    <div class="h-4 w-32 rounded bg-gray-200 dark:bg-gray-700"></div>`);
    lines.push(`                    <div class="h-4 w-24 rounded bg-gray-200 dark:bg-gray-700"></div>`);
    lines.push(`                    <div class="h-4 w-16 rounded bg-gray-200 dark:bg-gray-700"></div>`);
    lines.push(`                  </div>`);
    lines.push(`                </div>`);
    lines.push(`              }`);
    lines.push(`            </div>`);
    lines.push(`          } @else if (error()) {`);
    lines.push(`            <!-- Error state -->`);
    lines.push(`            <div class="flex flex-col items-center justify-center py-12 text-center">`);
    lines.push(`              <svg class="h-12 w-12 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">`);
    lines.push(`                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />`);
    lines.push(`              </svg>`);
    lines.push(`              <p class="mt-4 text-sm font-medium text-gray-900 dark:text-white">Failed to load ${pluralName.toLowerCase()}</p>`);
    lines.push(`              <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ error() }}</p>`);
    lines.push(`              <button (click)="loadData()" class="mt-4 text-sm font-medium text-indigo-600 hover:text-indigo-500">Try again</button>`);
    lines.push(`            </div>`);
    lines.push(`          } @else {`);
    lines.push(`            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700" role="grid" aria-label="${pluralName} table" data-testid="data-table">`);
    lines.push(`              <thead class="bg-gray-50 dark:bg-gray-800">`);
    lines.push(`                <tr>`);

    // Column headers with sort
    for (const col of listColumns) {
      lines.push(`                  <th`);
      lines.push(`                    scope="col"`);
      lines.push(`                    class="px-6 py-3.5 text-left text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400${col.sortable ? ' cursor-pointer select-none hover:text-gray-700 dark:hover:text-gray-200' : ''}"`);
      if (col.sortable) {
        lines.push(`                    (click)="onSort('${col.name}')"`);
        lines.push(`                    [attr.aria-sort]="sortField() === '${col.name}' ? (sortDirection() === 'asc' ? 'ascending' : 'descending') : 'none'"`);
      }
      lines.push(`                  >`);
      lines.push(`                    <div class="flex items-center gap-1">`);
      lines.push(`                      <span>${col.label}</span>`);
      if (col.sortable) {
        lines.push(`                      @if (sortField() === '${col.name}') {`);
        lines.push(`                        <svg class="h-4 w-4" [class.rotate-180]="sortDirection() === 'desc'" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">`);
        lines.push(`                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7" />`);
        lines.push(`                        </svg>`);
        lines.push(`                      }`);
      }
      lines.push(`                    </div>`);
      lines.push(`                  </th>`);
    }
    lines.push(`                  <th scope="col" class="relative py-3.5 pl-3 pr-6">`);
    lines.push(`                    <span class="sr-only">Actions</span>`);
    lines.push(`                  </th>`);
    lines.push(`                </tr>`);
    lines.push(`              </thead>`);
    lines.push(`              <tbody class="divide-y divide-gray-200 bg-white dark:divide-gray-700 dark:bg-gray-900">`);
    lines.push(`                @for (item of items(); track item.${idField}; let i = $index) {`);
    lines.push(`                  <tr animate.enter="row-enter" [style.animation-delay.ms]="i * 50" class="hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" [attr.data-testid]="'row-' + item.${idField}">`);

    // Data cells
    for (const col of listColumns) {
      lines.push(`                    <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-900 dark:text-gray-100">`);
      if (col.type === 'Boolean') {
        lines.push(`                      @if (item.${col.name}) {`);
        lines.push(`                        <span class="inline-flex items-center rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20 dark:bg-green-900/20 dark:text-green-400 dark:ring-green-500/20">Yes</span>`);
        lines.push(`                      } @else {`);
        lines.push(`                        <span class="inline-flex items-center rounded-full bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10 dark:bg-gray-800 dark:text-gray-400">No</span>`);
        lines.push(`                      }`);
      } else if (col.format === 'date' || col.type.includes('Date')) {
        lines.push(`                      {{ item.${col.name} | date:'mediumDate' }}`);
      } else if (col.format === 'datetime' || col.type.includes('DateTime') || col.type.includes('Instant')) {
        lines.push(`                      {{ item.${col.name} | date:'medium' }}`);
      } else {
        lines.push(`                      {{ item.${col.name} }}`);
      }
      lines.push(`                    </td>`);
    }

    // Actions
    lines.push(`                    <td class="whitespace-nowrap py-4 pl-3 pr-6 text-right text-sm">`);
    lines.push(`                      <div class="flex justify-end gap-3">`);
    lines.push(`                        <a [routerLink]="[item.${idField}]" [attr.data-testid]="'action-view-' + item.${idField}" class="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300 font-medium">View</a>`);
    lines.push(`                        <a [routerLink]="[item.${idField}, 'edit']" [attr.data-testid]="'action-edit-' + item.${idField}" class="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300 font-medium">Edit</a>`);
    lines.push(`                        <button (click)="onDelete(item)" [attr.data-testid]="'action-delete-' + item.${idField}" class="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300 font-medium">Delete</button>`);
    lines.push(`                      </div>`);
    lines.push(`                    </td>`);
    lines.push(`                  </tr>`);
    lines.push(`                } @empty {`);
    lines.push(`                  <tr>`);
    lines.push(`                    <td colspan="${listColumns.length + 1}" class="px-6 py-12 text-center">`);
    lines.push(`                      <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">`);
    lines.push(`                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />`);
    lines.push(`                      </svg>`);
    lines.push(`                      <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-white">No ${pluralName.toLowerCase()}</h3>`);
    lines.push(`                      <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Get started by creating a new ${displayName.toLowerCase()}.</p>`);
    lines.push(`                      <div class="mt-6">`);
    lines.push(`                        <a routerLink="new" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500">`);
    lines.push(`                          <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" /></svg>`);
    lines.push(`                          New ${displayName}`);
    lines.push(`                        </a>`);
    lines.push(`                      </div>`);
    lines.push(`                    </td>`);
    lines.push(`                  </tr>`);
    lines.push(`                }`);
    lines.push(`              </tbody>`);
    lines.push(`            </table>`);
    lines.push(`          }`);
    lines.push(`        </div>`);
    lines.push(`      } @placeholder {`);
    lines.push(`        <!-- SSR placeholder -->`);
    lines.push(`        <div class="h-96 rounded-lg border border-gray-200 dark:border-gray-700 animate-pulse bg-gray-100 dark:bg-gray-800"></div>`);
    lines.push(`      }`);
    lines.push(``);

    // Pagination
    lines.push(`      <!-- Pagination -->`);
    lines.push(`      @if (totalPages() > 1) {`);
    lines.push(`        <nav class="flex items-center justify-between border-t border-gray-200 dark:border-gray-700 px-4 py-3 sm:px-0" aria-label="Pagination">`);
    lines.push(`          <div class="hidden sm:block">`);
    lines.push(`            <p class="text-sm text-gray-700 dark:text-gray-300">`);
    lines.push(`              Showing <span class="font-medium">{{ (currentPage() * pageSize()) + 1 }}</span>`);
    lines.push(`              to <span class="font-medium">{{ Math.min((currentPage() + 1) * pageSize(), totalElements()) }}</span>`);
    lines.push(`              of <span class="font-medium">{{ totalElements() }}</span> results`);
    lines.push(`            </p>`);
    lines.push(`          </div>`);
    lines.push(`          <div class="flex flex-1 justify-between sm:justify-end gap-3">`);
    lines.push(`            <button`);
    lines.push(`              (click)="onPageChange(currentPage() - 1)"`);
    lines.push(`              [disabled]="currentPage() === 0"`);
    lines.push(`              data-testid="pagination-prev"`);
    lines.push(`              class="relative inline-flex items-center rounded-md bg-white dark:bg-gray-800 px-3 py-2 text-sm font-semibold text-gray-900 dark:text-gray-100 ring-1 ring-inset ring-gray-300 dark:ring-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"`);
    lines.push(`            >`);
    lines.push(`              Previous`);
    lines.push(`            </button>`);
    lines.push(`            <button`);
    lines.push(`              (click)="onPageChange(currentPage() + 1)"`);
    lines.push(`              [disabled]="currentPage() >= totalPages() - 1"`);
    lines.push(`              data-testid="pagination-next"`);
    lines.push(`              class="relative inline-flex items-center rounded-md bg-white dark:bg-gray-800 px-3 py-2 text-sm font-semibold text-gray-900 dark:text-gray-100 ring-1 ring-inset ring-gray-300 dark:ring-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"`);
    lines.push(`            >`);
    lines.push(`              Next`);
    lines.push(`            </button>`);
    lines.push(`          </div>`);
    lines.push(`        </nav>`);
    lines.push(`      }`);
    lines.push(`    </div>`);
    lines.push(`  \`,`);
    lines.push(`})`);

    // Class
    lines.push(`export class ${entityName}ListComponent implements OnInit {`);
    lines.push(`  private readonly service = inject(${entityName}Service);`);
    lines.push(``);
    lines.push(`  // State`);
    lines.push(`  searchQuery = '';`);
    for (const field of filterableFields.slice(0, 2)) {
      if (field.type === 'Boolean') {
        lines.push(`  filter${field.name.charAt(0).toUpperCase() + field.name.slice(1)}: string = '';`);
      }
    }
    lines.push(``);
    lines.push(`  // Signals`);
    lines.push(`  readonly currentPage = signal(0);`);
    lines.push(`  readonly pageSize = signal(20);`);
    lines.push(`  readonly sortField = signal<string>('${idField}');`);
    lines.push(`  readonly sortDirection = signal<'asc' | 'desc'>('desc');`);
    lines.push(`  readonly filter = signal<${entityName}Filter>({});`);
    lines.push(``);
    lines.push(`  // Data signals`);
    lines.push(`  readonly data = signal<Page<${entityName}> | null>(null);`);
    lines.push(`  readonly isLoading = signal(false);`);
    lines.push(`  readonly error = signal<string | null>(null);`);
    lines.push(``);
    lines.push(`  // Computed values`);
    lines.push(`  readonly items = computed(() => this.data()?.content ?? []);`);
    lines.push(`  readonly totalElements = computed(() => this.data()?.totalElements ?? 0);`);
    lines.push(`  readonly totalPages = computed(() => this.data()?.totalPages ?? 0);`);
    lines.push(``);
    lines.push(`  protected readonly Math = Math;`);
    lines.push(``);
    lines.push(`  // Search debounce`);
    lines.push(`  private readonly searchSubject = new Subject<string>();`);
    lines.push(``);
    lines.push(`  constructor() {`);
    lines.push(`    // Debounce search`);
    lines.push(`    this.searchSubject.pipe(`);
    lines.push(`      debounceTime(300),`);
    lines.push(`      distinctUntilChanged(),`);
    lines.push(`      takeUntilDestroyed()`);
    lines.push(`    ).subscribe((query) => {`);
    lines.push(`      this.filter.update((f) => ({ ...f, search: query || undefined }));`);
    lines.push(`      this.currentPage.set(0);`);
    lines.push(`      this.loadData();`);
    lines.push(`    });`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  ngOnInit(): void {`);
    lines.push(`    this.loadData();`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  loadData(): void {`);
    lines.push(`    this.isLoading.set(true);`);
    lines.push(`    this.error.set(null);`);
    lines.push(`    this.service.findAll(`);
    lines.push(`      { page: this.currentPage(), size: this.pageSize(), sort: this.sortField(), direction: this.sortDirection() },`);
    lines.push(`      this.filter()`);
    lines.push(`    ).subscribe({`);
    lines.push(`      next: (result) => {`);
    lines.push(`        this.data.set(result);`);
    lines.push(`        this.isLoading.set(false);`);
    lines.push(`      },`);
    lines.push(`      error: (err) => {`);
    lines.push(`        this.error.set(err.message || 'Failed to load data');`);
    lines.push(`        this.isLoading.set(false);`);
    lines.push(`      },`);
    lines.push(`    });`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  onSearch(query: string): void {`);
    lines.push(`    this.searchSubject.next(query);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  onFilterChange(): void {`);
    lines.push(`    this.filter.update((f) => ({`);
    lines.push(`      ...f,`);
    for (const field of filterableFields.slice(0, 2)) {
      if (field.type === 'Boolean') {
        lines.push(`      ${field.name}: this.filter${field.name.charAt(0).toUpperCase() + field.name.slice(1)} ? this.filter${field.name.charAt(0).toUpperCase() + field.name.slice(1)} === 'true' : undefined,`);
      }
    }
    lines.push(`    }));`);
    lines.push(`    this.currentPage.set(0);`);
    lines.push(`    this.loadData();`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  onSort(field: string): void {`);
    lines.push(`    if (this.sortField() === field) {`);
    lines.push(`      this.sortDirection.update((d) => (d === 'asc' ? 'desc' : 'asc'));`);
    lines.push(`    } else {`);
    lines.push(`      this.sortField.set(field);`);
    lines.push(`      this.sortDirection.set('asc');`);
    lines.push(`    }`);
    lines.push(`    this.loadData();`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  onPageChange(page: number): void {`);
    lines.push(`    if (page >= 0 && page < this.totalPages()) {`);
    lines.push(`      this.currentPage.set(page);`);
    lines.push(`      this.loadData();`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  onDelete(item: ${entityName}): void {`);
    lines.push(`    if (confirm('Are you sure you want to delete this ${displayName.toLowerCase()}?')) {`);
    lines.push(`      this.service.delete(String(item.${idField})).subscribe({`);
    lines.push(`        next: () => {`);
    lines.push(`          this.loadData();`);
    lines.push(`        },`);
    lines.push(`        error: (err) => {`);
    lines.push(`          console.error('Failed to delete:', err);`);
    lines.push(`          alert('Failed to delete ${displayName.toLowerCase()}');`);
    lines.push(`        },`);
    lines.push(`      });`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`}`);

    return lines.join('\n');
  }

  private getDefaultListColumns(metadata: DomainMetadata): string[] {
    const systemFields = ['id', 'version', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedAt', 'tenantId'];
    return metadata.fields
      .filter((f) => !f.hidden && !systemFields.includes(f.name))
      .slice(0, 5)
      .map((f) => f.name);
  }
}

export function generateList(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile | null {
  const generator = new ListGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context);
}

