/**
 * Angular Saga UI State Machine Generator
 *
 * Emits, per entity declaring `@Saga`, a signal-based state machine that tracks a saga run for
 * display: the declared steps in order, their status, progress, and screen-reader announcements.
 *
 * <b>The emitted machine carries no transport, deliberately.</b> Until this generator was wired
 * (0.8.0) it emitted an `HttpClient` bound to `/api/v1/sagas/&lt;entity&gt;` with `/start`,
 * `/{id}/cancel`, `/{id}/retry` and `/{id}/status`, plus a 1-second polling loop. No layer of
 * this stack serves that contract: `KernelApplicationGenerator` registers no saga route (its own
 * Javadoc hands saga routing to the consumer), `KernelOpenApiGenerator` documents no saga path,
 * and the kernel flow SPI has no per-execution handle at all — `FlowEngine` exposes
 * `plans/scheduler/registry/capabilities/stats`, with no execution id, status read, cancel or
 * retry. Emitting a client for it would have shipped four dead URLs into every generated app and
 * polled a 404 once a second. So the transitions are local and the consumer drives them from
 * whatever it does serve — the TS analogue of the ADR-070 composition-root seam.
 *
 * <b>No `$localize` in emitted output.</b> Fourteen `$localize` sites (announcements, the
 * unknown-error fallback, and one per declared step) failed `ng build` with `TS2304` the moment
 * the flag was honoured: `$localize` is a global that exists only once the consumer adds
 * `@angular/localize` and a polyfills entry, and the emitted app declares `"polyfills": []`.
 * Emitting a symbol that requires an undeclared consumer dependency is the rule ADR-060 settled
 * on the Java side for slf4j; `store-gen.ts` recorded it for the TS side and `detail-gen` and
 * `event-gen` followed.
 *
 * @author Exeris Team
 * @since 0.3.0
 */

import type { DomainMetadata, SagaMetadata, SagaStepMetadata } from '../../models/domain-model.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import { tsSingleQuoted } from './ts-literal.js';


/**
 * The class name the emitted state machine binds, or null for a domain that declares no saga.
 *
 * Exported because the barrel needs the same answer and deriving it twice is how `routePlural`
 * came to disagree with itself (T40 follow-up, #192).
 */
export function sagaMachineName(domain: DomainMetadata): string | null {
  if (!domain.sagaMetadata) return null;
  const sagaName = domain.sagaMetadata.name || `${domain.entityName}Saga`;
  return `${toPascalCase(sagaName)}StateMachine`;
}

function toPascalCase(name: string): string {
  return name
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

export class SagaGenerator implements CodeGenerator {
  readonly name = 'SagaGenerator';
  readonly artifactType = 'SAGA' as const;
  readonly supportedBackends: BackendType[] = []; // All backends

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    // Only generate for domains with saga metadata
    if (!domain.sagaMetadata) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateSagaContent(domain, domain.sagaMetadata);

    return {
      path: `sagas/${kebab}.saga.ts`,
      content,
      artifactType: 'SAGA',
      overwritable: true,
    };
  }

  private generateSagaContent(domain: DomainMetadata, saga: SagaMetadata): string {
    const { entityName } = domain;
    const sagaName = saga.name || `${entityName}Saga`;
    const pascalSagaName = toPascalCase(sagaName);
    const kebab = DslMapper.toKebabCase(entityName);
    const steps = saga.steps || [];

    return `/**
 * ${pascalSagaName} UI State Machine
 * 
 * Manages UI state for ${sagaName} saga orchestration.
 * Provides step-by-step progress visualization with a11y support.
 * 
 * Generated by @exeris/codegen-ts v0.3.0
 * DO NOT EDIT - This file is auto-generated
 */

import { 
  Injectable, 
  inject, 
  signal, 
  computed,
} from '@angular/core';
import { LiveAnnouncer } from '@angular/cdk/a11y';

// ============================================================================
// Types
// ============================================================================

export type SagaState = 
  | 'IDLE' 
  | 'RUNNING' 
  | 'COMPLETED' 
  | 'FAILED' 
  | 'COMPENSATING'
  | 'COMPENSATED';

export type StepStatus = 
  | 'PENDING' 
  | 'RUNNING' 
  | 'COMPLETED' 
  | 'FAILED' 
  | 'COMPENSATING'
  | 'COMPENSATED'
  | 'SKIPPED';

export interface SagaStep {
  /** Step identifier */
  name: string;
  /** Human-readable label */
  label: string;
  /** Current status */
  status: StepStatus;
  /** Step started timestamp */
  startedAt?: Date;
  /** Step completed timestamp */
  completedAt?: Date;
  /** Error message if failed */
  error?: string;
  /** Compensation action name */
  compensatingAction?: string;
  /** Progress percentage (0-100) for long-running steps */
  progress?: number;
}

export interface SagaExecution {
  /** Execution ID */
  id: string;
  /** Entity ID this saga operates on */
  entityId: string;
  /** Overall saga state */
  state: SagaState;
  /** Individual step states */
  steps: SagaStep[];
  /** Saga start time */
  startedAt: Date;
  /** Saga completion time */
  completedAt?: Date;
  /** Error that caused failure */
  error?: string;
}

/**
 * The shape this machine folds into its state. The consumer produces it from whatever it
 * actually serves — a poll, an SSE frame, a websocket message, or an in-process call — and
 * hands it to \`applyStatus\`. Emitting a fetch for it here would mean inventing an endpoint
 * (see this file's generator header).
 */
export interface SagaStatusSnapshot {
  /** Overall saga state as the backing run reports it. */
  state: SagaState;
  /** Per-step status; steps absent from the snapshot keep their current local status. */
  steps: Array<{
    name: string;
    status: StepStatus;
    /** ISO-8601 instants — parsed here so the caller can pass the wire value through. */
    startedAt?: string;
    completedAt?: string;
    error?: string;
    progress?: number;
  }>;
  /** Failure detail, when the run reports one. */
  error?: string;
}

// ============================================================================
// Saga Steps Definition
// ============================================================================

${this.generateStepDefinitions(steps)}

// ============================================================================
// Saga State Machine
// ============================================================================

@Injectable({ providedIn: 'root' })
export class ${pascalSagaName}StateMachine {
  private readonly liveAnnouncer = inject(LiveAnnouncer);

  // ═══════════════════════════════════════════════════════════════════════════
  // Private State Signals
  // ═══════════════════════════════════════════════════════════════════════════

  private readonly _executionId = signal<string | null>(null);
  private readonly _entityId = signal<string | null>(null);
  private readonly _state = signal<SagaState>('IDLE');
  private readonly _steps = signal<SagaStep[]>(${this.generateInitialSteps(steps)});
  private readonly _currentStepIndex = signal<number>(-1);
  private readonly _error = signal<string | null>(null);
  private readonly _startedAt = signal<Date | null>(null);
  private readonly _completedAt = signal<Date | null>(null);

  // ═══════════════════════════════════════════════════════════════════════════
  // Public Read-Only Signals
  // ═══════════════════════════════════════════════════════════════════════════

  /** Current execution ID */
  readonly executionId = this._executionId.asReadonly();

  /** Entity ID being processed */
  readonly entityId = this._entityId.asReadonly();

  /** Overall saga state */
  readonly state = this._state.asReadonly();

  /** All saga steps with their status */
  readonly steps = this._steps.asReadonly();

  /** Current step index (-1 if not started) */
  readonly currentStepIndex = this._currentStepIndex.asReadonly();

  /** Error message */
  readonly error = this._error.asReadonly();

  /** Saga start time */
  readonly startedAt = this._startedAt.asReadonly();

  /** Saga completion time */
  readonly completedAt = this._completedAt.asReadonly();

  // ═══════════════════════════════════════════════════════════════════════════
  // Computed State
  // ═══════════════════════════════════════════════════════════════════════════

  /** Current step (or null if not running) */
  readonly currentStep = computed(() => {
    const idx = this._currentStepIndex();
    return idx >= 0 ? this._steps()[idx] : null;
  });

  /** Overall progress percentage (0-100) */
  readonly progress = computed(() => {
    const steps = this._steps();
    if (steps.length === 0) return 0;
    
    const completed = steps.filter(s => 
      s.status === 'COMPLETED' || s.status === 'COMPENSATED'
    ).length;
    
    return Math.round((completed / steps.length) * 100);
  });

  /** Number of completed steps */
  readonly completedSteps = computed(() => 
    this._steps().filter(s => s.status === 'COMPLETED').length
  );

  /** Number of failed steps */
  readonly failedSteps = computed(() => 
    this._steps().filter(s => s.status === 'FAILED').length
  );

  /** Whether saga is currently running */
  readonly isRunning = computed(() => 
    this._state() === 'RUNNING' || this._state() === 'COMPENSATING'
  );

  /** Whether saga completed successfully */
  readonly isCompleted = computed(() => this._state() === 'COMPLETED');

  /** Whether saga failed */
  readonly isFailed = computed(() => this._state() === 'FAILED');

  /** Whether saga was compensated */
  readonly isCompensated = computed(() => this._state() === 'COMPENSATED');

  /** Whether saga can be started */
  readonly canStart = computed(() => 
    this._state() === 'IDLE' || this._state() === 'COMPLETED' || 
    this._state() === 'FAILED' || this._state() === 'COMPENSATED'
  );

  /** Estimated time remaining (in seconds) */
  readonly estimatedTimeRemaining = computed(() => {
    if (!this.isRunning()) return null;
    
    const steps = this._steps();
    const completedCount = steps.filter(s => s.status === 'COMPLETED').length;
    const remainingCount = steps.length - completedCount;
    
    // Calculate average step duration from completed steps
    const completedWithDuration = steps.filter(s => 
      s.status === 'COMPLETED' && s.startedAt && s.completedAt
    );
    
    if (completedWithDuration.length === 0) {
      return remainingCount * 5; // Default 5 seconds per step
    }
    
    const totalDuration = completedWithDuration.reduce((sum, s) => {
      const duration = (s.completedAt!.getTime() - s.startedAt!.getTime()) / 1000;
      return sum + duration;
    }, 0);
    
    const avgDuration = totalDuration / completedWithDuration.length;
    return Math.ceil(avgDuration * remainingCount);
  });

  /** Full execution snapshot */
  readonly execution = computed<SagaExecution | null>(() => {
    const execId = this._executionId();
    const entId = this._entityId();
    if (!execId || !entId) return null;
    
    return {
      id: execId,
      entityId: entId,
      state: this._state(),
      steps: this._steps(),
      startedAt: this._startedAt()!,
      completedAt: this._completedAt() ?? undefined,
      error: this._error() ?? undefined,
    };
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Enter the RUNNING state for a saga the caller has started.
   *
   * The caller owns the start itself — this stack serves no saga route to call (see the
   * generator header) — and passes back the execution id its own backend assigned, so every
   * later snapshot can be matched to a run.
   */
  begin(entityId: string, executionId: string): void {
    if (!this.canStart()) {
      throw new Error(\`Cannot start saga in state: \${this._state()}\`);
    }

    this.reset();
    this._entityId.set(entityId);
    this._executionId.set(executionId);
    this._state.set('RUNNING');
    this._startedAt.set(new Date());

    this.announce('Saga started', 'polite');
  }

  /**
   * Record that the run failed before it could report a single step — the caller's start
   * attempt itself errored.
   */
  failToStart(error: string): void {
    this._state.set('FAILED');
    this._error.set(error);
    this.announce('Saga failed to start', 'assertive');
  }

  /**
   * Enter the COMPENSATING state. The caller performs the cancellation against its own backend;
   * the resulting step statuses arrive through \`applyStatus\` like any others.
   */
  cancelling(): void {
    if (!this._executionId()) {
      throw new Error('No saga execution to cancel');
    }

    this._state.set('COMPENSATING');
    this.announce('Cancelling saga...', 'polite');
  }

  /**
   * Return a FAILED run to RUNNING for a retry the caller is performing.
   */
  retrying(): void {
    if (!this._executionId() || this._state() !== 'FAILED') {
      throw new Error('Cannot retry saga');
    }

    this._state.set('RUNNING');
    this._error.set(null);
    this.announce('Retrying saga...', 'polite');
  }

  /**
   * Reset saga state to initial.
   */
  reset(): void {
    this._executionId.set(null);
    this._entityId.set(null);
    this._state.set('IDLE');
    this._steps.set(${this.generateInitialSteps(steps)});
    this._currentStepIndex.set(-1);
    this._error.set(null);
    this._startedAt.set(null);
    this._completedAt.set(null);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Status
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Fold a status snapshot into the machine: step statuses and timings, the current step, the
   * announcements that go with a step change, and the terminal transition.
   *
   * The caller decides when to call this and where the snapshot comes from. Nothing here polls:
   * the previous version ran a one-second timer against an endpoint no part of this stack
   * serves, from a \`providedIn: 'root'\` service that outlives every component that might have
   * stopped it.
   */
  applyStatus(status: SagaStatusSnapshot): void {
    this._state.set(status.state);

    if (status.error) {
      this._error.set(status.error);
    }

    // Update steps
    const updatedSteps = this._steps().map(step => {
      const serverStep = status.steps.find(s => s.name === step.name);
      if (!serverStep) return step;

      return {
        ...step,
        status: serverStep.status,
        startedAt: serverStep.startedAt ? new Date(serverStep.startedAt) : undefined,
        completedAt: serverStep.completedAt ? new Date(serverStep.completedAt) : undefined,
        error: serverStep.error,
        progress: serverStep.progress,
      };
    });

    this._steps.set(updatedSteps);

    // Update current step index. Capture the PREVIOUS index BEFORE
    // the set so the step-change announcement below compares
    // against the actual previous state. The earlier version
    // compared the new index against this._currentStepIndex()
    // AFTER calling .set() on it — which always returned the
    // just-set value, making the !== check trivially false and
    // silently dropping every step-running announcement.
    const prevIdx = this._currentStepIndex();
    const runningIdx = updatedSteps.findIndex(s => s.status === 'RUNNING');
    this._currentStepIndex.set(runningIdx);

    // Announce step changes
    if (runningIdx >= 0 && runningIdx !== prevIdx) {
      const step = updatedSteps[runningIdx];
      this.announce(\`Running step: \${step.label}\`, 'polite');
    }

    // Check if saga finished
    if (status.state === 'COMPLETED' || 
        status.state === 'FAILED' || 
        status.state === 'COMPENSATED') {
      this._completedAt.set(new Date());

      if (status.state === 'COMPLETED') {
        this.announce('Saga completed successfully', 'polite');
      } else if (status.state === 'FAILED') {
        this.announce('Saga failed', 'assertive');
      } else {
        this.announce('Saga was compensated', 'polite');
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Accessibility
  // ═══════════════════════════════════════════════════════════════════════════

  private announce(message: string, priority: 'polite' | 'assertive'): void {
    this.liveAnnouncer.announce(message, priority);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Normalise a thrown value to a message. Public because the caller owns the transport now and
   * so is the one holding the rejection to feed \`failToStart\`.
   */
  extractErrorMessage(err: unknown): string {
    if (err instanceof Error) {
      return err.message;
    }
    if (typeof err === 'object' && err !== null && 'message' in err) {
      return String((err as { message: unknown }).message);
    }
    return 'An unknown error occurred';
  }
}

// ============================================================================
// Saga Progress Component (Optional Usage)
// ============================================================================

/**
 * Example usage in a component:
 * 
 * \`\`\`typescript
 * @Component({
 *   template: \`
 *     <div role="progressbar" 
 *          [attr.aria-valuenow]="saga.progress()"
 *          aria-valuemin="0" 
 *          aria-valuemax="100"
 *          aria-label="Saga progress">
 *       
 *       @for (step of saga.steps(); track step.name) {
 *         <div class="step" 
 *              [class.completed]="step.status === 'COMPLETED'"
 *              [class.running]="step.status === 'RUNNING'"
 *              [class.failed]="step.status === 'FAILED'">
 *           <span class="step-label">{{ step.label }}</span>
 *           <span class="step-status" [attr.aria-live]="step.status === 'RUNNING' ? 'polite' : 'off'">
 *             {{ step.status }}
 *           </span>
 *         </div>
 *       }
 *     </div>
 *   \`
 * })
 * export class SagaProgressComponent {
 *   readonly saga = inject(${pascalSagaName}StateMachine);
 * }
 * \`\`\`
 *
 * Driving it — the machine tracks a run, it does not perform one. This stack serves no saga
 * route, so the calls below are yours:
 *
 * \`\`\`typescript
 * const { executionId } = await this.myBackend.startFulfilment(orderId);
 * this.saga.begin(orderId, executionId);
 * // then, on each update you receive (poll, SSE frame, websocket message, in-process call):
 * this.saga.applyStatus(snapshot);
 * \`\`\`
 */
`;
  }


  private generateStepDefinitions(steps: SagaStepMetadata[]): string {
    if (steps.length === 0) {
      return `const SAGA_STEPS: SagaStep[] = [];`;
    }

    const stepDefs = steps.map(step => {
      const label = this.humanize(step.name);
      return `  {
    name: '${tsSingleQuoted(step.name)}',
    label: '${tsSingleQuoted(label)}',
    status: 'PENDING',
    compensatingAction: ${step.compensatingAction ? `'${tsSingleQuoted(step.compensatingAction)}'` : 'undefined'},
  }`;
    }).join(',\n');

    return `const SAGA_STEPS: SagaStep[] = [
${stepDefs}
];`;
  }

  private generateInitialSteps(steps: SagaStepMetadata[]): string {
    if (steps.length === 0) {
      return '[]';
    }

    return 'SAGA_STEPS.map(s => ({ ...s }))';
  }

  private humanize(name: string): string {
    return name
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, s => s.toUpperCase())
      .trim();
  }
}

// ============================================================================
// Factory Function
// ============================================================================

export function generateSaga(
  domain: DomainMetadata,
  config: GeneratorConfig
): GeneratedFile | null {
  const generator = new SagaGenerator();
  const context: GeneratorContext = {
    config,
    backend: 'KERNEL',
    allDomains: [domain],
    enums: [],
  };

  return generator.generate(domain, context);
}

