/**
 * Angular Saga UI State Machine Generator
 *
 * Generates UI state machines for saga visualization and progress tracking.
 * Features:
 * - Step-by-step progress display
 * - Error handling with compensation
 * - Screen reader announcements (a11y)
 * - i18n-ready messages
 *
 * @author Exeris Team
 * @since 0.3.0
 */

import type { DomainMetadata, SagaMetadata, SagaStepMetadata } from '../../models/domain-model.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { DslMapper } from '../../models/dsl-mapper.js';


export class SagaGenerator implements CodeGenerator {
  readonly name = 'SagaGenerator';
  readonly artifactType = 'SAGA' as const;
  readonly supportedBackends: BackendType[] = []; // All backends

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    // Only generate for domains with saga metadata
    if (!domain.sagaMetadata) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateSagaContent(domain, domain.sagaMetadata);

    return {
      path: `sagas/${kebab}.saga.ts`,
      content,
      artifactType: 'SAGA',
      overwritable: true,
    };
  }

  private generateSagaContent(domain: DomainMetadata, saga: SagaMetadata): string {
    const { entityName } = domain;
    const sagaName = saga.name || `${entityName}Saga`;
    const pascalSagaName = this.toPascalCase(sagaName);
    const kebab = DslMapper.toKebabCase(entityName);
    const steps = saga.steps || [];

    return `/**
 * ${pascalSagaName} UI State Machine
 * 
 * Manages UI state for ${sagaName} saga orchestration.
 * Provides step-by-step progress visualization with a11y support.
 * 
 * Generated by @exeris/codegen-ts v0.3.0
 * DO NOT EDIT - This file is auto-generated
 */

import { 
  Injectable, 
  inject, 
  signal, 
  computed,
  effect,
} from '@angular/core';
import { LiveAnnouncer } from '@angular/cdk/a11y';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

// ============================================================================
// Types
// ============================================================================

export type SagaState = 
  | 'IDLE' 
  | 'RUNNING' 
  | 'COMPLETED' 
  | 'FAILED' 
  | 'COMPENSATING'
  | 'COMPENSATED';

export type StepStatus = 
  | 'PENDING' 
  | 'RUNNING' 
  | 'COMPLETED' 
  | 'FAILED' 
  | 'COMPENSATING'
  | 'COMPENSATED'
  | 'SKIPPED';

export interface SagaStep {
  /** Step identifier */
  name: string;
  /** Human-readable label */
  label: string;
  /** Current status */
  status: StepStatus;
  /** Step started timestamp */
  startedAt?: Date;
  /** Step completed timestamp */
  completedAt?: Date;
  /** Error message if failed */
  error?: string;
  /** Compensation action name */
  compensatingAction?: string;
  /** Progress percentage (0-100) for long-running steps */
  progress?: number;
}

export interface SagaExecution {
  /** Execution ID */
  id: string;
  /** Entity ID this saga operates on */
  entityId: string;
  /** Overall saga state */
  state: SagaState;
  /** Individual step states */
  steps: SagaStep[];
  /** Saga start time */
  startedAt: Date;
  /** Saga completion time */
  completedAt?: Date;
  /** Error that caused failure */
  error?: string;
}

// ============================================================================
// Saga Steps Definition
// ============================================================================

${this.generateStepDefinitions(steps)}

// ============================================================================
// Saga State Machine
// ============================================================================

@Injectable({ providedIn: 'root' })
export class ${pascalSagaName}StateMachine {
  private readonly http = inject(HttpClient);
  private readonly liveAnnouncer = inject(LiveAnnouncer);

  private readonly baseUrl = '/api/v1/sagas/${kebab}';

  // ═══════════════════════════════════════════════════════════════════════════
  // Private State Signals
  // ═══════════════════════════════════════════════════════════════════════════

  private readonly _executionId = signal<string | null>(null);
  private readonly _entityId = signal<string | null>(null);
  private readonly _state = signal<SagaState>('IDLE');
  private readonly _steps = signal<SagaStep[]>(${this.generateInitialSteps(steps)});
  private readonly _currentStepIndex = signal<number>(-1);
  private readonly _error = signal<string | null>(null);
  private readonly _startedAt = signal<Date | null>(null);
  private readonly _completedAt = signal<Date | null>(null);

  // Polling state
  private pollingInterval: ReturnType<typeof setInterval> | null = null;

  // ═══════════════════════════════════════════════════════════════════════════
  // Public Read-Only Signals
  // ═══════════════════════════════════════════════════════════════════════════

  /** Current execution ID */
  readonly executionId = this._executionId.asReadonly();

  /** Entity ID being processed */
  readonly entityId = this._entityId.asReadonly();

  /** Overall saga state */
  readonly state = this._state.asReadonly();

  /** All saga steps with their status */
  readonly steps = this._steps.asReadonly();

  /** Current step index (-1 if not started) */
  readonly currentStepIndex = this._currentStepIndex.asReadonly();

  /** Error message */
  readonly error = this._error.asReadonly();

  /** Saga start time */
  readonly startedAt = this._startedAt.asReadonly();

  /** Saga completion time */
  readonly completedAt = this._completedAt.asReadonly();

  // ═══════════════════════════════════════════════════════════════════════════
  // Computed State
  // ═══════════════════════════════════════════════════════════════════════════

  /** Current step (or null if not running) */
  readonly currentStep = computed(() => {
    const idx = this._currentStepIndex();
    return idx >= 0 ? this._steps()[idx] : null;
  });

  /** Overall progress percentage (0-100) */
  readonly progress = computed(() => {
    const steps = this._steps();
    if (steps.length === 0) return 0;
    
    const completed = steps.filter(s => 
      s.status === 'COMPLETED' || s.status === 'COMPENSATED'
    ).length;
    
    return Math.round((completed / steps.length) * 100);
  });

  /** Number of completed steps */
  readonly completedSteps = computed(() => 
    this._steps().filter(s => s.status === 'COMPLETED').length
  );

  /** Number of failed steps */
  readonly failedSteps = computed(() => 
    this._steps().filter(s => s.status === 'FAILED').length
  );

  /** Whether saga is currently running */
  readonly isRunning = computed(() => 
    this._state() === 'RUNNING' || this._state() === 'COMPENSATING'
  );

  /** Whether saga completed successfully */
  readonly isCompleted = computed(() => this._state() === 'COMPLETED');

  /** Whether saga failed */
  readonly isFailed = computed(() => this._state() === 'FAILED');

  /** Whether saga was compensated */
  readonly isCompensated = computed(() => this._state() === 'COMPENSATED');

  /** Whether saga can be started */
  readonly canStart = computed(() => 
    this._state() === 'IDLE' || this._state() === 'COMPLETED' || 
    this._state() === 'FAILED' || this._state() === 'COMPENSATED'
  );

  /** Estimated time remaining (in seconds) */
  readonly estimatedTimeRemaining = computed(() => {
    if (!this.isRunning()) return null;
    
    const steps = this._steps();
    const completedCount = steps.filter(s => s.status === 'COMPLETED').length;
    const remainingCount = steps.length - completedCount;
    
    // Calculate average step duration from completed steps
    const completedWithDuration = steps.filter(s => 
      s.status === 'COMPLETED' && s.startedAt && s.completedAt
    );
    
    if (completedWithDuration.length === 0) {
      return remainingCount * 5; // Default 5 seconds per step
    }
    
    const totalDuration = completedWithDuration.reduce((sum, s) => {
      const duration = (s.completedAt!.getTime() - s.startedAt!.getTime()) / 1000;
      return sum + duration;
    }, 0);
    
    const avgDuration = totalDuration / completedWithDuration.length;
    return Math.ceil(avgDuration * remainingCount);
  });

  /** Full execution snapshot */
  readonly execution = computed<SagaExecution | null>(() => {
    const execId = this._executionId();
    const entId = this._entityId();
    if (!execId || !entId) return null;
    
    return {
      id: execId,
      entityId: entId,
      state: this._state(),
      steps: this._steps(),
      startedAt: this._startedAt()!,
      completedAt: this._completedAt() ?? undefined,
      error: this._error() ?? undefined,
    };
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Start the saga for a given entity.
   */
  async start(entityId: string, params?: Record<string, unknown>): Promise<string> {
    if (!this.canStart()) {
      throw new Error(\`Cannot start saga in state: \${this._state()}\`);
    }

    this.reset();
    this._entityId.set(entityId);
    this._state.set('RUNNING');
    this._startedAt.set(new Date());

    this.announce($localize\`:@@saga.started:Saga started\`, 'polite');

    try {
      // Call backend to start saga
      const response = await firstValueFrom(
        this.http.post<{ executionId: string }>(
          \`\${this.baseUrl}/start\`,
          { entityId, ...params }
        )
      );

      this._executionId.set(response.executionId);

      // Start polling for updates
      this.startPolling();

      return response.executionId;
    } catch (err) {
      this._state.set('FAILED');
      this._error.set(this.extractErrorMessage(err));
      this.announce($localize\`:@@saga.failed:Saga failed to start\`, 'assertive');
      throw err;
    }
  }

  /**
   * Cancel a running saga (triggers compensation).
   */
  async cancel(): Promise<void> {
    const execId = this._executionId();
    if (!execId) {
      throw new Error('No saga execution to cancel');
    }

    this._state.set('COMPENSATING');
    this.announce($localize\`:@@saga.cancelling:Cancelling saga...\`, 'polite');

    try {
      await firstValueFrom(
        this.http.post(\`\${this.baseUrl}/\${execId}/cancel\`, {})
      );
    } catch (err) {
      this._error.set(this.extractErrorMessage(err));
      this.announce($localize\`:@@saga.cancel.failed:Failed to cancel saga\`, 'assertive');
      throw err;
    }
  }

  /**
   * Retry a failed saga.
   */
  async retry(): Promise<void> {
    const execId = this._executionId();
    if (!execId || this._state() !== 'FAILED') {
      throw new Error('Cannot retry saga');
    }

    this._state.set('RUNNING');
    this._error.set(null);
    this.announce($localize\`:@@saga.retrying:Retrying saga...\`, 'polite');

    try {
      await firstValueFrom(
        this.http.post(\`\${this.baseUrl}/\${execId}/retry\`, {})
      );
      
      this.startPolling();
    } catch (err) {
      this._state.set('FAILED');
      this._error.set(this.extractErrorMessage(err));
      this.announce($localize\`:@@saga.retry.failed:Retry failed\`, 'assertive');
      throw err;
    }
  }

  /**
   * Reset saga state to initial.
   */
  reset(): void {
    this.stopPolling();
    this._executionId.set(null);
    this._entityId.set(null);
    this._state.set('IDLE');
    this._steps.set(${this.generateInitialSteps(steps)});
    this._currentStepIndex.set(-1);
    this._error.set(null);
    this._startedAt.set(null);
    this._completedAt.set(null);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Polling
  // ═══════════════════════════════════════════════════════════════════════════

  private startPolling(): void {
    this.stopPolling();
    
    this.pollingInterval = setInterval(() => {
      this.pollStatus();
    }, 1000); // Poll every second
  }

  private stopPolling(): void {
    if (this.pollingInterval) {
      clearInterval(this.pollingInterval);
      this.pollingInterval = null;
    }
  }

  private async pollStatus(): Promise<void> {
    const execId = this._executionId();
    if (!execId) {
      this.stopPolling();
      return;
    }

    try {
      const status = await firstValueFrom(
        this.http.get<{
          state: SagaState;
          steps: Array<{
            name: string;
            status: StepStatus;
            startedAt?: string;
            completedAt?: string;
            error?: string;
            progress?: number;
          }>;
          error?: string;
        }>(\`\${this.baseUrl}/\${execId}/status\`)
      );

      // Update state
      const previousState = this._state();
      this._state.set(status.state);
      
      if (status.error) {
        this._error.set(status.error);
      }

      // Update steps
      const updatedSteps = this._steps().map(step => {
        const serverStep = status.steps.find(s => s.name === step.name);
        if (!serverStep) return step;

        return {
          ...step,
          status: serverStep.status,
          startedAt: serverStep.startedAt ? new Date(serverStep.startedAt) : undefined,
          completedAt: serverStep.completedAt ? new Date(serverStep.completedAt) : undefined,
          error: serverStep.error,
          progress: serverStep.progress,
        };
      });

      this._steps.set(updatedSteps);

      // Update current step index
      const runningIdx = updatedSteps.findIndex(s => s.status === 'RUNNING');
      this._currentStepIndex.set(runningIdx);

      // Announce step changes
      if (runningIdx >= 0 && runningIdx !== this._currentStepIndex()) {
        const step = updatedSteps[runningIdx];
        this.announce(
          $localize\`:@@saga.step.running:Running step: \${step.label}\`,
          'polite'
        );
      }

      // Check if saga finished
      if (status.state === 'COMPLETED' || 
          status.state === 'FAILED' || 
          status.state === 'COMPENSATED') {
        this._completedAt.set(new Date());
        this.stopPolling();

        if (status.state === 'COMPLETED') {
          this.announce($localize\`:@@saga.completed:Saga completed successfully\`, 'polite');
        } else if (status.state === 'FAILED') {
          this.announce($localize\`:@@saga.failed:Saga failed\`, 'assertive');
        } else {
          this.announce($localize\`:@@saga.compensated:Saga was compensated\`, 'polite');
        }
      }
    } catch (err) {
      console.error('Failed to poll saga status:', err);
      // Don't stop polling on transient errors
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Accessibility
  // ═══════════════════════════════════════════════════════════════════════════

  private announce(message: string, priority: 'polite' | 'assertive'): void {
    this.liveAnnouncer.announce(message, priority);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  private extractErrorMessage(err: unknown): string {
    if (err instanceof Error) {
      return err.message;
    }
    if (typeof err === 'object' && err !== null && 'message' in err) {
      return String((err as { message: unknown }).message);
    }
    return $localize\`:@@error.unknown:An unknown error occurred\`;
  }
}

// ============================================================================
// Saga Progress Component (Optional Usage)
// ============================================================================

/**
 * Example usage in a component:
 * 
 * \`\`\`typescript
 * @Component({
 *   template: \`
 *     <div role="progressbar" 
 *          [attr.aria-valuenow]="saga.progress()"
 *          aria-valuemin="0" 
 *          aria-valuemax="100"
 *          [attr.aria-label]="$localize\\\`:@@saga.progress:Saga progress\\\`">
 *       
 *       @for (step of saga.steps(); track step.name) {
 *         <div class="step" 
 *              [class.completed]="step.status === 'COMPLETED'"
 *              [class.running]="step.status === 'RUNNING'"
 *              [class.failed]="step.status === 'FAILED'">
 *           <span class="step-label">{{ step.label }}</span>
 *           <span class="step-status" [attr.aria-live]="step.status === 'RUNNING' ? 'polite' : 'off'">
 *             {{ step.status }}
 *           </span>
 *         </div>
 *       }
 *     </div>
 *   \`
 * })
 * export class SagaProgressComponent {
 *   readonly saga = inject(${pascalSagaName}StateMachine);
 * }
 * \`\`\`
 */
`;
  }

  private toPascalCase(name: string): string {
    return name
      .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
      .replace(/^(.)/, (_, c) => c.toUpperCase());
  }

  private generateStepDefinitions(steps: SagaStepMetadata[]): string {
    if (steps.length === 0) {
      return `const SAGA_STEPS: SagaStep[] = [];`;
    }

    const stepDefs = steps.map((step, index) => {
      const label = this.humanize(step.name);
      return `  {
    name: '${step.name}',
    label: $localize\`:@@saga.step.${step.name}:${label}\`,
    status: 'PENDING',
    compensatingAction: ${step.compensatingAction ? `'${step.compensatingAction}'` : 'undefined'},
  }`;
    }).join(',\n');

    return `const SAGA_STEPS: SagaStep[] = [
${stepDefs}
];`;
  }

  private generateInitialSteps(steps: SagaStepMetadata[]): string {
    if (steps.length === 0) {
      return '[]';
    }

    return 'SAGA_STEPS.map(s => ({ ...s }))';
  }

  private humanize(name: string): string {
    return name
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, s => s.toUpperCase())
      .trim();
  }
}

// ============================================================================
// Factory Function
// ============================================================================

export function generateSaga(
  domain: DomainMetadata,
  config: GeneratorConfig
): GeneratedFile | null {
  const generator = new SagaGenerator();
  const context: GeneratorContext = {
    config,
    backend: 'KERNEL',
    allDomains: [domain],
    enums: [],
  };

  return generator.generate(domain, context);
}

