/**
 * Generated specs for the generated surface — the FE half of T2 (ADR-058).
 *
 * <p><b>Two rules carry over from the Java half and shape everything here.</b>
 *
 * <p>1. <b>Doubles, never mocks.</b> The service spec drives the real service through Angular's own
 * `provideHttpClientTesting()`, which lives in `@angular/common/http/testing` — part of a package
 * the emitted app already depends on. No mocking library is required, so emitting these specs adds
 * no dependency beyond the runner itself. On the Java side the same rule produced an emitted
 * `HttpExchange` recorder rather than a Mockito stub.
 *
 * <p>2. <b>The gate runs them.</b> A spec that is only type-checked proves nothing; `ng test` on the
 * generated sample is the gate, exactly as `GeneratedTestsE2ETest` executes the Java half.
 *
 * <p><b>Assertions are derived from metadata, never assumed.</b> The first hand-written probe for
 * this slice asserted that an empty object fails the entity schema — and it passed the schema,
 * because that entity declares no required field. A spec emitter that guesses at shape emits
 * failing tests into a consumer's project, so every assertion below is conditioned on what the
 * metadata actually says.
 *
 * @author Exeris Team
 * @since 0.8.0
 */

import { outPath } from '../../core/paths.js';
import type { DomainMetadata, FieldMetadata } from '../../models/domain-model.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import { modelTypeName } from '../../models/model-naming.js';
import type { GeneratorConfig } from '../../config.js';
import { serviceApiPath } from './service-gen.js';

/** An emitted file, in the (path, content) shape the orchestrator composes. */
export interface SpecOutputFile {
  path: string;
  content: string;
}

const HEADER = (what: string): string[] => [
  '/**',
  ` * ${what}`,
  ' * Generated by @exeris/codegen-ts',
  ' * DO NOT EDIT - This file is auto-generated',
  ' */',
  '',
];

/**
 * A literal the field's **zod** type accepts.
 *
 * Keyed off `zodType`, not `tsType`: they disagree, and the schema is the thing being asserted
 * against. A `BigDecimal` is `string` in TypeScript but `z.string().regex(/^-?\d+(\.\d+)?$/)` in
 * the schema, so a plain `'x'` type-checks and then fails to parse — which is exactly how the first
 * run of this emitter produced a failing spec in the sample app.
 *
 * Returns `null` when no literal can be produced generically (enums, blobs, patterned strings the
 * mapper does not own). Those fields are left out of the fixture rather than guessed at; every
 * field the schema marks optional tolerates absence, and inventing a value that fails is worse
 * than omitting one.
 */
function sampleLiteral(field: FieldMetadata): string | null {
  if (field.enumType) return null;
  if (field.pattern) return null;
  if (field.format === 'email') return "'sample@example.com'";
  if (field.format === 'url') return "'https://example.com'";

  const zod = DslMapper.mapType(field.type).zodType;
  if (zod.startsWith('z.boolean')) return 'true';
  if (zod.startsWith('z.number')) return '1';
  if (zod.startsWith('z.array')) return '[]';
  if (zod.startsWith('z.record')) return '{}';
  if (zod.startsWith('z.string().uuid')) return "'00000000-0000-0000-0000-000000000000'";
  if (zod.startsWith('z.string().datetime')) return "'2026-01-01T00:00:00Z'";
  if (zod.startsWith('z.string().date')) return "'2026-01-01'";
  if (zod.startsWith('z.string().time')) return "'00:00:00'";
  // The two numeric-string mappings (BigInteger / BigDecimal) — a digit satisfies both regexes.
  if (zod.startsWith('z.string().regex')) return "'1'";
  if (zod.startsWith('z.string')) {
    const min = field.minLength ?? 1;
    const max = field.maxLength ?? Math.max(min, 1);
    return `'${'x'.repeat(Math.min(Math.max(min, 1), Math.max(max, 1)))}'`;
  }
  return null;
}

/**
 * The zod-schema spec. Only emitted under `generateZod`, since the schemas it exercises are.
 *
 * Every assertion is metadata-conditioned: the required-field case is emitted only for a field the
 * entity actually marks required, and the create-schema case only when a system field is present
 * to be omitted. An entity that supports neither gets the round-trip assertion alone rather than
 * an invented one.
 */
export function generateSchemaSpec(metadata: DomainMetadata, _config: GeneratorConfig): SpecOutputFile {
  const name = modelTypeName(metadata.entityName);
  const kebab = DslMapper.toKebabCase(metadata.entityName);
  const required = metadata.fields.filter((f) => f.required);

  const lines = HEADER(`${metadata.entityName} schema spec`);
  lines.push("import { describe, expect, it } from 'vitest';");
  lines.push(`import { ${name}Schema, ${name}CreateSchema } from './${kebab}.schema';`);
  lines.push('');
  lines.push(`describe('${name}Schema', () => {`);

  const fixture = metadata.fields
    .map((f) => ({ f, literal: sampleLiteral(f) }))
    .filter((e): e is { f: FieldMetadata; literal: string } => e.literal !== null);
  lines.push(`  const valid = {`);
  for (const { f, literal } of fixture) lines.push(`    ${f.name}: ${literal},`);
  lines.push(`  };`);
  lines.push('');
  lines.push(`  it('accepts a well-formed ${metadata.entityName}', () => {`);
  lines.push(`    expect(${name}Schema.safeParse(valid).success).toBe(true);`);
  lines.push(`  });`);

  if (required.length > 0) {
    lines.push('');
    lines.push(`  it.each(${JSON.stringify(required.map((f) => f.name))})('rejects a ${metadata.entityName} missing %s', (field) => {`);
    lines.push(`    const { [field]: _omitted, ...rest } = valid as Record<string, unknown>;`);
    lines.push(`    expect(${name}Schema.safeParse(rest).success).toBe(false);`);
    lines.push(`  });`);
  }

  lines.push('');
  lines.push(`  it('drops server-owned fields from the create schema', () => {`);
  lines.push(`    expect(Object.keys(${name}CreateSchema.shape)).not.toContain('id');`);
  lines.push(`  });`);
  lines.push(`});`);
  lines.push('');

  return { path: outPath('schemas', `${kebab}.schema.spec.ts`), content: lines.join('\n') };
}

/**
 * The service spec: the real service, Angular's testing HTTP backend, and assertions on the URL
 * and verb each method issues.
 *
 * <p>This is the regression test for the defect class that shipped twice — an emitted client
 * calling a path the emitted server does not serve. It asserts the exact `baseUrl` the generator
 * computed, so a prefix reintroduced by a default nobody typed fails here rather than at runtime.
 */
export function generateServiceSpec(metadata: DomainMetadata, config: GeneratorConfig): SpecOutputFile {
  const entity = metadata.entityName;
  const name = modelTypeName(entity);
  const kebab = DslMapper.toKebabCase(entity);
  // Same authority the service itself uses — a re-derived path would agree only until
  // one of the two changed, which is the drift ADR-058 forbids for emitted doubles.
  const baseUrl = `${config.apiBasePath}${serviceApiPath(metadata)}`;

  const lines = HEADER(`${entity} service spec`);
  lines.push("import { TestBed } from '@angular/core/testing';");
  lines.push("import { provideHttpClient } from '@angular/common/http';");
  lines.push("import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';");
  lines.push("import { afterEach, beforeEach, describe, expect, it } from 'vitest';");
  lines.push(`import { ${entity}Service } from './${kebab}.service';`);
  lines.push('');
  lines.push(`describe('${entity}Service', () => {`);
  lines.push(`  let service: ${entity}Service;`);
  lines.push(`  let http: HttpTestingController;`);
  lines.push('');
  lines.push(`  beforeEach(() => {`);
  lines.push(`    TestBed.configureTestingModule({`);
  lines.push(`      providers: [provideHttpClient(), provideHttpClientTesting()],`);
  lines.push(`    });`);
  lines.push(`    service = TestBed.inject(${entity}Service);`);
  lines.push(`    http = TestBed.inject(HttpTestingController);`);
  lines.push(`  });`);
  lines.push('');
  lines.push(`  afterEach(() => http.verify());`);
  lines.push('');

  // The URL the emitted server actually serves. A prefix the client invents fails here.
  lines.push(`  it('requests the path the generated server serves', () => {`);
  lines.push(`    service.findById('42').subscribe();`);
  lines.push(`    http.expectOne('${baseUrl}/42').flush({});`);
  lines.push(`  });`);
  lines.push('');
  lines.push(`  it('creates with POST on the collection', () => {`);
  lines.push(`    service.create({} as never).subscribe();`);
  lines.push(`    const request = http.expectOne('${baseUrl}');`);
  lines.push(`    expect(request.request.method).toBe('POST');`);
  lines.push(`    request.flush({});`);
  lines.push(`  });`);
  lines.push('');
  lines.push(`  it('updates with PATCH on the instance', () => {`);
  lines.push(`    service.update('42', {} as never).subscribe();`);
  lines.push(`    const request = http.expectOne('${baseUrl}/42');`);
  lines.push(`    expect(request.request.method).toBe('PATCH');`);
  lines.push(`    request.flush({});`);
  lines.push(`  });`);
  lines.push('');
  lines.push(`  it('deletes with DELETE on the instance', () => {`);
  lines.push(`    service.delete('42').subscribe();`);
  lines.push(`    const request = http.expectOne('${baseUrl}/42');`);
  lines.push(`    expect(request.request.method).toBe('DELETE');`);
  lines.push(`    request.flush(null);`);
  lines.push(`  });`);
  lines.push(`});`);
  lines.push('');

  return { path: outPath('services', `${kebab}.service.spec.ts`), content: lines.join('\n') };
}
