/**
 * Angular Signal Store Generator
 *
 * Generates Angular v22 Signal-based stores for entity state management.
 * Features:
 * - Signal-based reactive state
 * - Computed derived state
 * - CRUD operations with loading/error tracking
 * - Filter/search support
 * - Optimistic updates
 *
 * **No `$localize` in emitted output.** The fallback error message does not use
 * `$localize` tagged templates. `$localize` is a global that only exists when the consumer
 * adds `@angular/localize` to their devDependencies and to `polyfills` in `angular.json`,
 * but the emitted app declares `"polyfills": []`. Tooling emits no dependency the consumer
 * did not ask for, so code that silently requires an undeclared dependency violates ADR-060
 * (the rule applied to slf4j on the Java side). Nothing else in the emitted app is
 * internationalised; making it so is a deliberate change, not a side effect.
 */

import type { DomainMetadata } from '../../models/domain-model.js';
import { modelTypeName } from '../../models/model-naming.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import { RESTORE_UNSUPPORTED } from './service-gen.js';
import { tsSingleQuoted } from './ts-literal.js';

export class StoreGenerator implements CodeGenerator {
  readonly name = 'StoreGenerator';
  readonly artifactType = 'STORE' as const;
  readonly supportedBackends: BackendType[] = []; // All backends

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    const kebab = DslMapper.toKebabCase(domain.entityName);
    const camel = DslMapper.toCamelCase(domain.entityName);
    const content = this.generateStoreContent(domain, context);

    return {
      path: `stores/${kebab}.store.ts`,
      content,
      artifactType: 'STORE',
      overwritable: true,
    };
  }

  private generateStoreContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName, fields = [], softDelete } = domain;
    const modelName = modelTypeName(entityName);
    const kebab = DslMapper.toKebabCase(entityName);
    const camel = DslMapper.toCamelCase(entityName);
    const pluralCamel = camel + 's';
    const noun = tsSingleQuoted((domain.displayName ?? entityName).toLowerCase());
    const pluralNoun = tsSingleQuoted((domain.pluralName ?? DslMapper.pluralName(entityName)).toLowerCase());

    // Identify searchable and filterable fields
    const searchableFields = fields.filter(f => f.searchable);
    const filterableFields = fields.filter(f => f.filterable);
    // The literal 'id', deliberately, not systemFields.primaryKeyField. Nothing in the pipeline
    // honours that override: KernelFlywayGenerator emits `id UUID PRIMARY KEY` unconditionally,
    // KernelRepositoryGenerator's WHERE clause is the constant " WHERE id = ?", every by-id
    // handler binds the {id} path variable, and the processor says so outright ("generators leave
    // the primary key as the literal id"). Reading it here would make this the only layer that
    // honours it, and the emitted app would then request the wrong identifier.
    const idField = 'id';

    return `/**
 * ${entityName} Signal Store
 * 
 * Signal-based state management for ${entityName} entities.
 * Angular v22+ with Zoneless change detection.
 * 
 * Generated by @exeris/codegen-ts
 * DO NOT EDIT - This file is auto-generated
 */

import { 
  Injectable, 
  inject, 
  signal, 
  computed,
  effect,
  DestroyRef,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { firstValueFrom } from 'rxjs';
import { ${entityName}Service } from '../services/${kebab}.service';
import { httpErrorMessage, type HttpErrorAction } from '../core/http-error';
import type { Page, PageRequest, ${modelName}Filter } from '../services/${kebab}.service';
import type { ${modelName}, ${modelName}Create, ${modelName}Update } from '../types/${kebab}.types';

// The filter is the service's: one declaration, typed against the enums the service imports.
export type { ${modelName}Filter };

// ============================================================================
// Store State Interface
// ============================================================================

export interface ${entityName}StoreState {
  entities: ${modelName}[];
  selected: ${modelName} | null;
  loading: boolean;
  saving: boolean;
  error: string | null;
  filter: ${modelName}Filter;
  pagination: {
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
  };
  sort: {
    field: string;
    direction: 'asc' | 'desc';
  };
}

// ============================================================================
// Signal Store
// ============================================================================

@Injectable({ providedIn: 'root' })
export class ${entityName}Store {
  private readonly service = inject(${entityName}Service);
  private readonly destroyRef = inject(DestroyRef);

  // ═══════════════════════════════════════════════════════════════════════════
  // Private State Signals
  // ═══════════════════════════════════════════════════════════════════════════

  private readonly _entities = signal<${modelName}[]>([]);
  private readonly _selected = signal<${modelName} | null>(null);
  private readonly _loading = signal(false);
  private readonly _saving = signal(false);
  private readonly _error = signal<string | null>(null);
  private readonly _filter = signal<${modelName}Filter>({});
  private readonly _page = signal(0);
  private readonly _size = signal(20);
  private readonly _totalElements = signal(0);
  private readonly _totalPages = signal(0);
  private readonly _sortField = signal<string>('${idField}');
  private readonly _sortDirection = signal<'asc' | 'desc'>('desc');

  // ═══════════════════════════════════════════════════════════════════════════
  // Public Read-Only Signals
  // ═══════════════════════════════════════════════════════════════════════════

  /** All loaded entities */
  readonly entities = this._entities.asReadonly();
  
  /** Currently selected entity */
  readonly selected = this._selected.asReadonly();
  
  /** Loading state for list operations */
  readonly loading = this._loading.asReadonly();
  
  /** Saving state for create/update/delete operations */
  readonly saving = this._saving.asReadonly();
  
  /** Current error message */
  readonly error = this._error.asReadonly();
  
  /** Current filter */
  readonly filter = this._filter.asReadonly();

  /** Current page (0-indexed) */
  readonly page = this._page.asReadonly();
  
  /** Page size */
  readonly size = this._size.asReadonly();
  
  /** Total elements count */
  readonly totalElements = this._totalElements.asReadonly();
  
  /** Total pages count */
  readonly totalPages = this._totalPages.asReadonly();
  
  /** Current sort field */
  readonly sortField = this._sortField.asReadonly();
  
  /** Current sort direction */
  readonly sortDirection = this._sortDirection.asReadonly();

  // ═══════════════════════════════════════════════════════════════════════════
  // Computed Derived State
  // ═══════════════════════════════════════════════════════════════════════════

  /** Filtered entities (client-side filtering for already loaded data) */
  readonly filteredEntities = computed(() => {
    const entities = this._entities();
    const filter = this._filter();
    
    if (!filter.search && Object.keys(filter).length <= 1) {
      return entities;
    }

    return entities.filter(entity => {
      // Full-text search
      if (filter.search) {
        const searchLower = filter.search.toLowerCase();
        const searchable = this.getSearchableText(entity);
        if (!searchable.toLowerCase().includes(searchLower)) {
          return false;
        }
      }
      
      // Field-specific filters
      ${this.generateFieldFilters(filterableFields)}
      
      return true;
    });
  });

  /** Count of loaded entities */
  readonly count = computed(() => this._entities().length);
  
  /** Count of filtered entities */
  readonly filteredCount = computed(() => this.filteredEntities().length);
  
  /** Whether entity list is empty */
  readonly isEmpty = computed(() => this._entities().length === 0);
  
  /** Whether there is an active filter */
  readonly hasActiveFilter = computed(() => {
    const filter = this._filter();
    return !!filter.search || Object.keys(filter).some(k => k !== 'search' && filter[k as keyof ${modelName}Filter] !== undefined);
  });

  /** Whether there are more pages to load */
  readonly hasNextPage = computed(() => this._page() < this._totalPages() - 1);
  
  /** Whether there is a previous page */
  readonly hasPrevPage = computed(() => this._page() > 0);

  /** Full state snapshot (for debugging/devtools) */
  readonly state = computed<${entityName}StoreState>(() => ({
    entities: this._entities(),
    selected: this._selected(),
    loading: this._loading(),
    saving: this._saving(),
    error: this._error(),
    filter: this._filter(),
    pagination: {
      page: this._page(),
      size: this._size(),
      totalElements: this._totalElements(),
      totalPages: this._totalPages(),
    },
    sort: {
      field: this._sortField(),
      direction: this._sortDirection(),
    },
  }));

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - CRUD Operations
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Load entities from server with current pagination/filter/sort.
   */
  async loadAll(): Promise<void> {
    this._loading.set(true);
    this._error.set(null);

    try {
      const pageRequest: PageRequest = {
        page: this._page(),
        size: this._size(),
        sort: this._sortField(),
        direction: this._sortDirection(),
      };

      // The server answers the list route with a JSON array; a paged envelope is read through
      // its content and totals.
      const response: Page<${modelName}> | ${modelName}[] = await firstValueFrom(
        this.service.findAll(pageRequest, this._filter()),
      );
      const rows = Array.isArray(response) ? response : (response.content ?? []);
      this._entities.set(rows);
      this._totalElements.set(Array.isArray(response) ? rows.length : response.totalElements);
      this._totalPages.set(Array.isArray(response) ? (rows.length > 0 ? 1 : 0) : response.totalPages);
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'load', '${pluralNoun}'));
      throw err;
    } finally {
      this._loading.set(false);
    }
  }

  /**
   * Load a single entity by ID.
   */
  async loadById(id: string): Promise<${modelName}> {
    this._loading.set(true);
    this._error.set(null);

    try {
      const entity = await firstValueFrom(this.service.findById(id));
      this._selected.set(entity);
      
      // Update in list if present
      this._entities.update(entities => 
        entities.map(e => e.${idField} === id ? entity : e)
      );
      
      return entity;
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'load'));
      throw err;
    } finally {
      this._loading.set(false);
    }
  }

  /**
   * Create a new entity.
   * Performs optimistic update on success.
   */
  async create(data: ${modelName}Create): Promise<${modelName}> {
    this._saving.set(true);
    this._error.set(null);

    try {
      const created = await firstValueFrom(this.service.create(data));
      
      // Add to list (at beginning for latest-first sort)
      this._entities.update(entities => [created, ...entities]);
      this._totalElements.update(n => n + 1);
      
      return created;
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'save'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

  /**
   * Update an existing entity.
   * Performs optimistic update.
   */
  async update(id: string, data: ${modelName}Update): Promise<${modelName}> {
    this._saving.set(true);
    this._error.set(null);

    // Optimistic update
    const previousEntities = this._entities();
    this._entities.update(entities =>
      entities.map(e => e.${idField} === id ? { ...e, ...data } as ${modelName} : e)
    );

    try {
      const updated = await firstValueFrom(this.service.update(id, data));
      
      // Replace with server response
      this._entities.update(entities =>
        entities.map(e => e.${idField} === id ? updated : e)
      );
      
      if (this._selected()?.${idField} === id) {
        this._selected.set(updated);
      }
      
      return updated;
    } catch (err) {
      // Rollback on error
      this._entities.set(previousEntities);
      this._error.set(this.extractErrorMessage(err, 'save'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

  /**
   * Delete an entity.
   */
  async delete(id: string): Promise<void> {
    this._saving.set(true);
    this._error.set(null);

    // Optimistic removal
    const previousEntities = this._entities();
    this._entities.update(entities => entities.filter(e => e.${idField} !== id));

    try {
      await firstValueFrom(this.service.delete(id));
      this._totalElements.update(n => Math.max(0, n - 1));
      
      if (this._selected()?.${idField} === id) {
        this._selected.set(null);
      }
    } catch (err) {
      // Rollback on error
      this._entities.set(previousEntities);
      this._error.set(this.extractErrorMessage(err, 'delete'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

${softDelete ? this.generateSoftDeleteMethods(entityName, idField) : ''}

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Selection
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Select an entity by ID.
   */
  select(id: string | null): void {
    if (id === null) {
      this._selected.set(null);
      return;
    }
    
    const entity = this._entities().find(e => e.${idField} === id);
    this._selected.set(entity ?? null);
  }

  /**
   * Clear selection.
   */
  clearSelection(): void {
    this._selected.set(null);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Filtering & Pagination
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Set filter and reload data.
   */
  async setFilter(filter: ${modelName}Filter): Promise<void> {
    this._filter.set(filter);
    this._page.set(0); // Reset to first page
    await this.loadAll();
  }

  /**
   * Update a single filter field.
   */
  async updateFilter<K extends keyof ${modelName}Filter>(
    key: K, 
    value: ${modelName}Filter[K]
  ): Promise<void> {
    this._filter.update(f => ({ ...f, [key]: value }));
    this._page.set(0);
    await this.loadAll();
  }

  /**
   * Clear all filters.
   */
  async clearFilter(): Promise<void> {
    this._filter.set({});
    this._page.set(0);
    await this.loadAll();
  }

  /**
   * Set search query.
   */
  async setSearch(query: string): Promise<void> {
    await this.updateFilter('search', query || undefined);
  }

  /**
   * Go to specific page.
   */
  async goToPage(page: number): Promise<void> {
    if (page < 0 || page >= this._totalPages()) return;
    this._page.set(page);
    await this.loadAll();
  }

  /**
   * Go to next page.
   */
  async nextPage(): Promise<void> {
    if (this.hasNextPage()) {
      await this.goToPage(this._page() + 1);
    }
  }

  /**
   * Go to previous page.
   */
  async prevPage(): Promise<void> {
    if (this.hasPrevPage()) {
      await this.goToPage(this._page() - 1);
    }
  }

  /**
   * Change page size.
   */
  async setPageSize(size: number): Promise<void> {
    this._size.set(size);
    this._page.set(0);
    await this.loadAll();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Sorting
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Set sort field and direction.
   */
  async setSort(field: string, direction: 'asc' | 'desc' = 'asc'): Promise<void> {
    this._sortField.set(field);
    this._sortDirection.set(direction);
    this._page.set(0);
    await this.loadAll();
  }

  /**
   * Toggle sort direction for a field.
   */
  async toggleSort(field: string): Promise<void> {
    if (this._sortField() === field) {
      this._sortDirection.update(d => d === 'asc' ? 'desc' : 'asc');
    } else {
      this._sortField.set(field);
      this._sortDirection.set('asc');
    }
    this._page.set(0);
    await this.loadAll();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - State Management
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Clear error message.
   */
  clearError(): void {
    this._error.set(null);
  }

  /**
   * Reset store to initial state.
   */
  reset(): void {
    this._entities.set([]);
    this._selected.set(null);
    this._loading.set(false);
    this._saving.set(false);
    this._error.set(null);
    this._filter.set({});
    this._page.set(0);
    this._size.set(20);
    this._totalElements.set(0);
    this._totalPages.set(0);
    this._sortField.set('${idField}');
    this._sortDirection.set('desc');
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Private Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  private getSearchableText(entity: ${modelName}): string {
    // Combine searchable fields for full-text search
    const parts: string[] = [];
${this.generateSearchableFieldAccess(searchableFields)}
    return parts.join(' ');
  }

  private extractErrorMessage(err: unknown, action: HttpErrorAction, entity = '${noun}'): string {
    return httpErrorMessage(err, { entity, action });
  }
}
`;
  }

  private generateFieldFilters(fields: { name: string; type: string }[]): string {
    if (fields.length === 0) return '// No filterable fields';

    return fields.map(f => {
      return `      if (filter.${f.name} !== undefined && entity.${f.name} !== filter.${f.name}) {
        return false;
      }`;
    }).join('\n');
  }

  private generateSearchableFieldAccess(fields: { name: string }[]): string {
    if (fields.length === 0) {
      return '    // No searchable fields defined';
    }

    return fields.map(f =>
      `    if (entity.${f.name}) parts.push(String(entity.${f.name}));`
    ).join('\n');
  }

  private generateSoftDeleteMethods(entityName: string, idField: string): string {
    // The generated server has no route, handler or repository method that un-sets the
    // soft-delete flag. restore() stays for one release, deprecated, so a call site keeps
    // compiling; it reaches no service call, sets the error and rejects. 0.10.0 stops emitting it.
    const modelName = modelTypeName(entityName);
    return `
  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Soft Delete
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Soft delete (archive) an entity.
   */
  async archive(id: string): Promise<void> {
    this._saving.set(true);
    this._error.set(null);

    try {
      await firstValueFrom(this.service.softDelete(id));
      
      // Remove from list (or mark as deleted depending on UI needs)
      this._entities.update(entities => entities.filter(e => e.${idField} !== id));
      this._totalElements.update(n => Math.max(0, n - 1));
      
      if (this._selected()?.${idField} === id) {
        this._selected.set(null);
      }
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'delete'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

  /**
   * @deprecated The server has no route that restores an archived row, so this calls nothing,
   * sets the error and rejects with that reason. exeris-tooling 0.10.0 stops emitting it.
   */
  async restore(id: string): Promise<${modelName}> {
    const message = \`${entityName}Store.restore(\${id}): ${RESTORE_UNSUPPORTED}\`;
    this._error.set(message);
    throw new Error(message);
  }
`;
  }
}

// ============================================================================
// Factory Function
// ============================================================================

export function generateStore(
  domain: DomainMetadata,
  config: GeneratorConfig
): GeneratedFile {
  const generator = new StoreGenerator();
  const context: GeneratorContext = {
    config,
    backend: 'KERNEL',
    allDomains: [domain],
    enums: [],
  };

  const result = generator.generate(domain, context);
  if (!result) {
    throw new Error(`Failed to generate store for ${domain.entityName}`);
  }

  return result;
}

