/**
 * Angular Signal Store Generator
 *
 * Generates Angular v22 Signal-based stores for entity state management.
 * Features:
 * - Signal-based reactive state
 * - Computed derived state
 * - CRUD operations with loading/error tracking
 * - Server-side paging, sorting and equality filters (ADR-096)
 * - Optimistic updates
 *
 * **No `$localize` in emitted output.** The fallback error message does not use
 * `$localize` tagged templates. `$localize` is a global that only exists when the consumer
 * adds `@angular/localize` to their devDependencies and to `polyfills` in `angular.json`,
 * but the emitted app declares `"polyfills": []`. Tooling emits no dependency the consumer
 * did not ask for, so code that silently requires an undeclared dependency violates ADR-060
 * (the rule applied to slf4j on the Java side). Nothing else in the emitted app is
 * internationalised; making it so is a deliberate change, not a side effect.
 */

import type { DomainMetadata } from '../../models/domain-model.js';
import { modelTypeName } from '../../models/model-naming.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import { tsSingleQuoted } from './ts-literal.js';
import { DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE } from './list-query.js';

export class StoreGenerator implements CodeGenerator {
  readonly name = 'StoreGenerator';
  readonly artifactType = 'STORE' as const;
  readonly supportedBackends: BackendType[] = []; // All backends

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    const kebab = DslMapper.toKebabCase(domain.entityName);
    const camel = DslMapper.toCamelCase(domain.entityName);
    const content = this.generateStoreContent(domain, context);

    return {
      path: `stores/${kebab}.store.ts`,
      content,
      artifactType: 'STORE',
      overwritable: true,
    };
  }

  private generateStoreContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName, softDelete } = domain;
    const modelName = modelTypeName(entityName);
    const kebab = DslMapper.toKebabCase(entityName);
    const camel = DslMapper.toCamelCase(entityName);
    const pluralCamel = camel + 's';
    const noun = tsSingleQuoted((domain.displayName ?? entityName).toLowerCase());
    const pluralNoun = tsSingleQuoted((domain.pluralName ?? DslMapper.pluralName(entityName)).toLowerCase());

    // The literal 'id', deliberately, not systemFields.primaryKeyField. Nothing in the pipeline
    // honours that override: KernelFlywayGenerator emits `id UUID PRIMARY KEY` unconditionally,
    // KernelRepositoryGenerator's WHERE clause is the constant " WHERE id = ?", every by-id
    // handler binds the {id} path variable, and the processor says so outright ("generators leave
    // the primary key as the literal id"). Reading it here would make this the only layer that
    // honours it, and the emitted app would then request the wrong identifier.
    const idField = 'id';

    return `/**
 * ${entityName} Signal Store
 * 
 * Signal-based state management for ${entityName} entities.
 * Angular v22+ with Zoneless change detection.
 * 
 * Generated by @exeris/codegen-ts
 * DO NOT EDIT - This file is auto-generated
 */

import { 
  Injectable, 
  inject, 
  signal, 
  computed,
  effect,
  DestroyRef,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { firstValueFrom } from 'rxjs';
import { ${entityName}Service } from '../services/${kebab}.service';
import { httpErrorMessage, type HttpErrorAction } from '../core/http-error';
import type { PageRequest, ${modelName}Filter, ${modelName}SortField } from '../services/${kebab}.service';
import type { ${modelName}, ${modelName}Create, ${modelName}Update } from '../types/${kebab}.types';

// The filter and the sort keys are the service's: one declaration each, the list route's own.
export type { ${modelName}Filter, ${modelName}SortField };

/** The page sizes the list route serves. */
const MIN_PAGE_SIZE = 1;
const MAX_PAGE_SIZE = ${MAX_PAGE_SIZE};

// ============================================================================
// Store State Interface
// ============================================================================

export interface ${entityName}StoreState {
  entities: ${modelName}[];
  selected: ${modelName} | null;
  loading: boolean;
  saving: boolean;
  error: string | null;
  filter: ${modelName}Filter;
  pagination: {
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
  };
  sort: {
    /** The sorted property; \`null\` leaves the rows in id order. */
    field: ${modelName}SortField | null;
    direction: 'asc' | 'desc';
  };
}

// ============================================================================
// Signal Store
// ============================================================================

@Injectable({ providedIn: 'root' })
export class ${entityName}Store {
  private readonly service = inject(${entityName}Service);
  private readonly destroyRef = inject(DestroyRef);

  // ═══════════════════════════════════════════════════════════════════════════
  // Private State Signals
  // ═══════════════════════════════════════════════════════════════════════════

  private readonly _entities = signal<${modelName}[]>([]);
  private readonly _selected = signal<${modelName} | null>(null);
  private readonly _loading = signal(false);
  private readonly _saving = signal(false);
  private readonly _error = signal<string | null>(null);
  private readonly _filter = signal<${modelName}Filter>({});
  private readonly _page = signal(0);
  private readonly _size = signal(${DEFAULT_PAGE_SIZE});
  private readonly _totalElements = signal(0);
  private readonly _totalPages = signal(0);
  private readonly _sortField = signal<${modelName}SortField | null>(null);
  private readonly _sortDirection = signal<'asc' | 'desc'>('asc');

  // ═══════════════════════════════════════════════════════════════════════════
  // Public Read-Only Signals
  // ═══════════════════════════════════════════════════════════════════════════

  /** All loaded entities */
  readonly entities = this._entities.asReadonly();
  
  /** Currently selected entity */
  readonly selected = this._selected.asReadonly();
  
  /** Loading state for list operations */
  readonly loading = this._loading.asReadonly();
  
  /** Saving state for create/update/delete operations */
  readonly saving = this._saving.asReadonly();
  
  /** Current error message */
  readonly error = this._error.asReadonly();
  
  /** Current filter */
  readonly filter = this._filter.asReadonly();

  /** Current page (0-indexed) */
  readonly page = this._page.asReadonly();
  
  /** Page size */
  readonly size = this._size.asReadonly();
  
  /** Total elements count */
  readonly totalElements = this._totalElements.asReadonly();
  
  /** Total pages count */
  readonly totalPages = this._totalPages.asReadonly();
  
  /** Current sort field */
  readonly sortField = this._sortField.asReadonly();
  
  /** Current sort direction */
  readonly sortDirection = this._sortDirection.asReadonly();

  // ═══════════════════════════════════════════════════════════════════════════
  // Computed Derived State
  // ═══════════════════════════════════════════════════════════════════════════

  /** Count of loaded entities */
  readonly count = computed(() => this._entities().length);
  
  /** Whether entity list is empty */
  readonly isEmpty = computed(() => this._entities().length === 0);
  
  /** Whether there is an active filter */
  readonly hasActiveFilter = computed(() => {
    const filter = this._filter();
    return Object.values(filter).some((value) => value !== undefined && value !== null && value !== '');
  });

  /** Whether there are more pages to load */
  readonly hasNextPage = computed(() => this._page() < this._totalPages() - 1);
  
  /** Whether there is a previous page */
  readonly hasPrevPage = computed(() => this._page() > 0);

  /** Full state snapshot (for debugging/devtools) */
  readonly state = computed<${entityName}StoreState>(() => ({
    entities: this._entities(),
    selected: this._selected(),
    loading: this._loading(),
    saving: this._saving(),
    error: this._error(),
    filter: this._filter(),
    pagination: {
      page: this._page(),
      size: this._size(),
      totalElements: this._totalElements(),
      totalPages: this._totalPages(),
    },
    sort: {
      field: this._sortField(),
      direction: this._sortDirection(),
    },
  }));

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - CRUD Operations
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Load the current page from the server: the list route pages, sorts and filters, and answers
   * the page envelope.
   */
  async loadAll(): Promise<void> {
    this._loading.set(true);
    this._error.set(null);

    try {
      const sort = this._sortField();
      const pageRequest: PageRequest & { sort?: ${modelName}SortField } = {
        page: this._page(),
        size: this._size(),
        ...(sort !== null ? { sort, direction: this._sortDirection() } : {}),
      };

      const response = await firstValueFrom(this.service.findAll(pageRequest, this._filter()));
      this._entities.set(response.content);
      this._totalElements.set(response.totalElements);
      this._totalPages.set(response.totalPages);
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'load', '${pluralNoun}'));
      throw err;
    } finally {
      this._loading.set(false);
    }
  }

  /**
   * Load a single entity by ID.
   */
  async loadById(id: string): Promise<${modelName}> {
    this._loading.set(true);
    this._error.set(null);

    try {
      const entity = await firstValueFrom(this.service.findById(id));
      this._selected.set(entity);
      
      // Update in list if present
      this._entities.update(entities => 
        entities.map(e => e.${idField} === id ? entity : e)
      );
      
      return entity;
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'load'));
      throw err;
    } finally {
      this._loading.set(false);
    }
  }

  /**
   * Create a new entity.
   * Performs optimistic update on success.
   */
  async create(data: ${modelName}Create): Promise<${modelName}> {
    this._saving.set(true);
    this._error.set(null);

    try {
      const created = await firstValueFrom(this.service.create(data));
      
      // Add to list (at beginning for latest-first sort)
      this._entities.update(entities => [created, ...entities]);
      this._totalElements.update(n => n + 1);
      
      return created;
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'save'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

  /**
   * Update an existing entity.
   * Performs optimistic update.
   */
  async update(id: string, data: ${modelName}Update): Promise<${modelName}> {
    this._saving.set(true);
    this._error.set(null);

    // Optimistic update
    const previousEntities = this._entities();
    this._entities.update(entities =>
      entities.map(e => e.${idField} === id ? { ...e, ...data } as ${modelName} : e)
    );

    try {
      const updated = await firstValueFrom(this.service.update(id, data));
      
      // Replace with server response
      this._entities.update(entities =>
        entities.map(e => e.${idField} === id ? updated : e)
      );
      
      if (this._selected()?.${idField} === id) {
        this._selected.set(updated);
      }
      
      return updated;
    } catch (err) {
      // Rollback on error
      this._entities.set(previousEntities);
      this._error.set(this.extractErrorMessage(err, 'save'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

  /**
   * Delete an entity.
   */
  async delete(id: string): Promise<void> {
    this._saving.set(true);
    this._error.set(null);

    // Optimistic removal
    const previousEntities = this._entities();
    this._entities.update(entities => entities.filter(e => e.${idField} !== id));

    try {
      await firstValueFrom(this.service.delete(id));
      this._totalElements.update(n => Math.max(0, n - 1));
      
      if (this._selected()?.${idField} === id) {
        this._selected.set(null);
      }
    } catch (err) {
      // Rollback on error
      this._entities.set(previousEntities);
      this._error.set(this.extractErrorMessage(err, 'delete'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }

${softDelete ? this.generateSoftDeleteMethods(idField) : ''}

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Selection
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Select an entity by ID.
   */
  select(id: string | null): void {
    if (id === null) {
      this._selected.set(null);
      return;
    }
    
    const entity = this._entities().find(e => e.${idField} === id);
    this._selected.set(entity ?? null);
  }

  /**
   * Clear selection.
   */
  clearSelection(): void {
    this._selected.set(null);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Filtering & Pagination
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Set filter and reload data.
   */
  async setFilter(filter: ${modelName}Filter): Promise<void> {
    this._filter.set(filter);
    this._page.set(0); // Reset to first page
    await this.loadAll();
  }

  /**
   * Update a single filter field.
   */
  async updateFilter<K extends keyof ${modelName}Filter>(
    key: K, 
    value: ${modelName}Filter[K]
  ): Promise<void> {
    this._filter.update(f => ({ ...f, [key]: value }));
    this._page.set(0);
    await this.loadAll();
  }

  /**
   * Clear all filters.
   */
  async clearFilter(): Promise<void> {
    this._filter.set({});
    this._page.set(0);
    await this.loadAll();
  }

  /**
   * Go to specific page.
   */
  async goToPage(page: number): Promise<void> {
    if (page < 0 || page >= this._totalPages()) return;
    this._page.set(page);
    await this.loadAll();
  }

  /**
   * Go to next page.
   */
  async nextPage(): Promise<void> {
    if (this.hasNextPage()) {
      await this.goToPage(this._page() + 1);
    }
  }

  /**
   * Go to previous page.
   */
  async prevPage(): Promise<void> {
    if (this.hasPrevPage()) {
      await this.goToPage(this._page() - 1);
    }
  }

  /**
   * Change page size, held within the sizes the list route serves.
   */
  async setPageSize(size: number): Promise<void> {
    this._size.set(Math.min(Math.max(Math.trunc(size), MIN_PAGE_SIZE), MAX_PAGE_SIZE));
    this._page.set(0);
    await this.loadAll();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Sorting
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Set sort field and direction.
   */
  async setSort(field: ${modelName}SortField | null, direction: 'asc' | 'desc' = 'asc'): Promise<void> {
    this._sortField.set(field);
    this._sortDirection.set(direction);
    this._page.set(0);
    await this.loadAll();
  }

  /**
   * Toggle sort direction for a field.
   */
  async toggleSort(field: ${modelName}SortField): Promise<void> {
    if (this._sortField() === field) {
      this._sortDirection.update(d => d === 'asc' ? 'desc' : 'asc');
    } else {
      this._sortField.set(field);
      this._sortDirection.set('asc');
    }
    this._page.set(0);
    await this.loadAll();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - State Management
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Clear error message.
   */
  clearError(): void {
    this._error.set(null);
  }

  /**
   * Reset store to initial state.
   */
  reset(): void {
    this._entities.set([]);
    this._selected.set(null);
    this._loading.set(false);
    this._saving.set(false);
    this._error.set(null);
    this._filter.set({});
    this._page.set(0);
    this._size.set(${DEFAULT_PAGE_SIZE});
    this._totalElements.set(0);
    this._totalPages.set(0);
    this._sortField.set(null);
    this._sortDirection.set('asc');
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Private Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  private extractErrorMessage(err: unknown, action: HttpErrorAction, entity = '${noun}'): string {
    return httpErrorMessage(err, { entity, action });
  }
}
`;
  }

  private generateSoftDeleteMethods(idField: string): string {
    // The generated server has no route, handler or repository method that un-sets the
    // soft-delete flag, so the store emits archive and no restore.
    return `
  // ═══════════════════════════════════════════════════════════════════════════
  // Actions - Soft Delete
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Soft delete (archive) an entity.
   */
  async archive(id: string): Promise<void> {
    this._saving.set(true);
    this._error.set(null);

    try {
      await firstValueFrom(this.service.softDelete(id));
      
      // Remove from list (or mark as deleted depending on UI needs)
      this._entities.update(entities => entities.filter(e => e.${idField} !== id));
      this._totalElements.update(n => Math.max(0, n - 1));
      
      if (this._selected()?.${idField} === id) {
        this._selected.set(null);
      }
    } catch (err) {
      this._error.set(this.extractErrorMessage(err, 'delete'));
      throw err;
    } finally {
      this._saving.set(false);
    }
  }
`;
  }
}

// ============================================================================
// Factory Function
// ============================================================================

export function generateStore(
  domain: DomainMetadata,
  config: GeneratorConfig
): GeneratedFile {
  const generator = new StoreGenerator();
  const context: GeneratorContext = {
    config,
    backend: 'KERNEL',
    allDomains: [domain],
    enums: [],
  };

  const result = generator.generate(domain, context);
  if (!result) {
    throw new Error(`Failed to generate store for ${domain.entityName}`);
  }

  return result;
}

