/**
 * Angular Stream Client Generator (SSE live-view, ADR-043 Slice 1).
 *
 * Parity twin of the Java {@code KernelStreamHandlerGenerator}: for every
 * entity annotated {@code @ExerisDomain(realTimeApi = true)} the Java side emits
 * an {@code HttpStreamHandler} registered at {@code GET {base}/stream} via the
 * kernel router's {@code streamRoute(...)}. This generator emits the matching
 * browser client — a native {@code EventSource} (RFC-2026-06-22 Axis 4a:
 * smallest, idiomatic SSE; GET-only, no custom headers) hitting the SAME
 * {@code {base}/stream} route, so the Java handler and the TS client are
 * route-identical (strong-default #4 parity).
 *
 * The generated client is a thin Angular service that opens an
 * {@code EventSource}, surfaces messages as an RxJS {@code Observable<MessageEvent>}
 * (so it composes with the rest of the v22 emitter's RxJS idiom), and closes the
 * connection on unsubscribe. It is deterministic: no timestamps / UUIDs / random
 * — same {@code DomainMetadata} yields byte-identical output (hard-constraint #3).
 *
 * Like the Java scaffold, this is forward-compatible with the EV1 producer: when
 * the server emits real {@code StreamEvent}s (named events + JSON data), the
 * client already delivers {@code MessageEvent} (with {@code .data} / {@code .type}),
 * so no client reshape is needed.
 *
 * @author Exeris Team
 * @since 0.6.0
 */

import { join } from 'node:path';
import type { DomainMetadata } from '../../models/index.js';
import { DslMapper } from '../../models/index.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';

export { GeneratedFile };

export class StreamClientGenerator implements CodeGenerator {
  readonly name = 'StreamClientGenerator';
  readonly artifactType = 'STREAM' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 6;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    // Driver parity with the Java side: only @ExerisDomain(realTimeApi) entities
    // get a stream client. Hidden internal APIs are excluded like every other
    // Angular emitter.
    if (!domain.realTimeApi || domain.internalApi?.hidden) {
      return null;
    }

    const content = this.renderStreamClient(domain, context);
    const fileName = `${DslMapper.toKebabCase(domain.entityName)}.stream.ts`;
    const filePath = join('services', fileName);

    return {
      path: filePath,
      content,
      artifactType: 'STREAM',
      overwritable: true,
    };
  }

  generateAggregate(domains: DomainMetadata[], context: GeneratorContext): GeneratedFile[] {
    const streamingDomains = domains.filter(d => d.realTimeApi && !d.internalApi?.hidden);
    if (streamingDomains.length === 0) {
      return [];
    }
    return [
      {
        path: 'services/streams.index.ts',
        content: this.renderBarrel(streamingDomains),
        artifactType: 'STREAM',
        overwritable: true,
      },
    ];
  }

  private renderBarrel(domains: DomainMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * SSE Stream Clients - Barrel Export`,
      ` * Generated by @exeris/codegen-ts (ADR-043 Slice 1)`,
      ` * DO NOT EDIT - This file is auto-generated`,
      ` */`,
      ``,
    ];
    for (const domain of domains) {
      const kebab = DslMapper.toKebabCase(domain.entityName);
      lines.push(`export * from './${kebab}.stream';`);
    }
    return lines.join('\n');
  }

  /**
   * Builds the SSE route, byte-for-byte parity with the kernel route the Java
   * handler is registered under: {@code {base}/stream}. The {@code {base}}
   * derivation mirrors the ServiceGenerator's {@code baseUrl}
   * ({@code apiBasePath + apiPath}).
   */
  private streamUrl(domain: DomainMetadata, context: GeneratorContext): string {
    const kebabName = DslMapper.toKebabCase(domain.entityName);
    const apiVersion = domain.apiVersion ?? '';
    const pathSegment = domain.path ?? `/${kebabName}s`;
    const apiPath = domain.apiPath ?? (apiVersion ? `/${apiVersion}${pathSegment}` : pathSegment);
    return `${context.config.apiBasePath}${apiPath}/stream`;
  }

  private renderStreamClient(domain: DomainMetadata, context: GeneratorContext): string {
    const entityName = domain.entityName;
    const streamUrl = this.streamUrl(domain, context);
    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * ${entityName} SSE Live-View Stream Client`);
    lines.push(` * Generated by @exeris/codegen-ts (ADR-043 Slice 1)`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` *`);
    lines.push(` * Parity twin of the kernel ${entityName}StreamHandler, registered at`);
    lines.push(` * GET ${streamUrl} via the router's streamRoute(...). Uses the native`);
    lines.push(` * EventSource (GET-only, no custom headers — auth via cookie/session).`);
    lines.push(` */`);
    lines.push(``);
    lines.push(`import { Injectable } from '@angular/core';`);
    lines.push(`import { Observable } from 'rxjs';`);
    lines.push(``);
    lines.push(`@Injectable({ providedIn: 'root' })`);
    lines.push(`export class ${entityName}StreamClient {`);
    lines.push(`  private readonly streamUrl = '${streamUrl}';`);
    lines.push(``);
    lines.push(`  /**`);
    lines.push(`   * Opens the ${entityName} live-view SSE stream and surfaces each`);
    lines.push(`   * server-sent message as a MessageEvent. The EventSource is closed`);
    lines.push(`   * automatically when the subscription is torn down.`);
    lines.push(`   */`);
    lines.push(`  stream(): Observable<MessageEvent> {`);
    lines.push(`    return new Observable<MessageEvent>((subscriber) => {`);
    lines.push(`      const source = new EventSource(this.streamUrl, { withCredentials: true });`);
    lines.push(`      source.onmessage = (event) => subscriber.next(event);`);
    lines.push(`      source.onerror = (error) => subscriber.error(error);`);
    lines.push(`      return () => source.close();`);
    lines.push(`    });`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push(``);

    return lines.join('\n');
  }
}

export function generateStreamClient(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile | null {
  const generator = new StreamClientGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context);
}
