/**
 * Angular Stream Client Generator (SSE live-view, ADR-043 Slice 1, ADR-044).
 *
 * Parity twin of the Java `KernelStreamHandlerGenerator`: for every
 * entity annotated `@ExerisDomain(realTimeApi = true)` the Java side emits
 * an `HttpStreamHandler` registered at `GET {base}/stream` via the
 * kernel router's `streamRoute(...)`. This generator emits the matching
 * browser client — a native `EventSource` (GET-only, no custom headers)
 * hitting the SAME `{base}/stream` route.
 *
 * Wire contract (ADR-044 obligations 2 and 5): every frame the handler emits is
 * NAMED. A domain event arrives as `event: <@DomainEvent name>` (the entity
 * name + `Event` when the name is blank) with the codec-encoded payload JSON
 * as `data:`; the keep-alive fallback, for an entity with no
 * `@DomainEvent`, sends `event: keep-alive` with empty data.
 * `EventSource.onmessage` never fires for a named frame, so the client
 * registers one `addEventListener` per declared event name and surfaces
 * each as a `MessageEvent` whose `type` is that name. The heartbeat
 * has no listener: it carries nothing to process.
 *
 * Reconnection: the server closes the stream on its own (the keep-alive fallback
 * closes after a fixed window, and a stream opened before the application is
 * composed is closed at once), and the browser reconnects on its own. An
 * `error` while the source is reconnecting is therefore not terminal; only
 * a source the browser has given up on (`readyState === CLOSED`) errors the
 * Observable.
 *
 * Deterministic: no timestamps / UUIDs / random — same `DomainMetadata`
 * yields byte-identical output; event names keep declaration order.
 */

import { outPath } from '../../core/paths.js';
import type { DomainMetadata } from '../../models/index.js';
import { DslMapper } from '../../models/index.js';
import { isTenantPartitioned } from '../../models/domain-model.js';
import { tsSingleQuoted } from './ts-literal.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';

export { GeneratedFile };

/**
 * Whether the entity gets a live-view stream client.
 *
 * Not for a tenant-partitioned entity: the kernel stream routes carry no tenant guard and the
 * handler's producer subscribes to the event bus unfiltered, so a tenant-partitioned entity's
 * stream would deliver every tenant's events to every subscriber. The client is emitted once the
 * server guards the route.
 */
export function hasLiveViewClient(domain: DomainMetadata): boolean {
  return domain.realTimeApi && !isTenantPartitioned(domain);
}

export class StreamClientGenerator implements CodeGenerator {
  readonly name = 'StreamClientGenerator';
  readonly artifactType = 'STREAM' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 6;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (!hasLiveViewClient(domain)) {
      return null;
    }

    const content = this.renderStreamClient(domain, context);
    const fileName = `${DslMapper.toKebabCase(domain.entityName)}.stream.ts`;
    const filePath = outPath('services', fileName);

    return {
      path: filePath,
      content,
      artifactType: 'STREAM',
      overwritable: true,
    };
  }

  generateAggregate(domains: DomainMetadata[], context: GeneratorContext): GeneratedFile[] {
    const streamingDomains = domains.filter(hasLiveViewClient);
    if (streamingDomains.length === 0) {
      return [];
    }
    return [
      {
        path: 'services/streams.index.ts',
        content: this.renderBarrel(streamingDomains),
        artifactType: 'STREAM',
        overwritable: true,
      },
    ];
  }

  private renderBarrel(domains: DomainMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * SSE Stream Clients - Barrel Export`,
      ` * Generated by @exeris/codegen-ts (ADR-043 Slice 1)`,
      ` * DO NOT EDIT - This file is auto-generated`,
      ` */`,
      ``,
    ];
    for (const domain of domains) {
      const kebab = DslMapper.toKebabCase(domain.entityName);
      lines.push(`export * from './${kebab}.stream';`);
    }
    return lines.join('\n');
  }

  /**
   * Builds the SSE route, byte-for-byte parity with the kernel route the Java
   * handler is registered under: `{base}/stream`. The `{base}`
   * derivation mirrors the ServiceGenerator's `baseUrl`
   * (`apiBasePath + apiPath`).
   *
   * `apiVersion` is deliberately NOT folded in. The router registers
   * `streamRoute` at `effectivePath() + "/stream"` with no version
   * segment, so a domain that declares `@ExerisDomain(apiVersion = …)`
   * must not include that version in the client's route.
   */
  private streamUrl(domain: DomainMetadata, context: GeneratorContext): string {
    const pathSegment = domain.path ?? `/${DslMapper.routePlural(domain.entityName)}`;
    const apiPath = domain.apiPath ?? pathSegment;
    return `${context.config.apiBasePath}${apiPath}/stream`;
  }

  /**
   * The SSE `event:` names the kernel handler emits for this entity, in
   * declaration order: the raw `@DomainEvent` name, or the entity name +
   * `Event` when the name is blank — the same choice
   * `KernelStreamHandlerGenerator.eventBindings` makes.
   */
  private streamEventNames(domain: DomainMetadata): string[] {
    const names: string[] = [];
    for (const event of domain.events ?? []) {
      const name = event.name.trim().length > 0 ? event.name : `${domain.entityName}Event`;
      if (!names.includes(name)) {
        names.push(name);
      }
    }
    return names;
  }

  private renderStreamClient(domain: DomainMetadata, context: GeneratorContext): string {
    const entityName = domain.entityName;
    const streamUrl = this.streamUrl(domain, context);
    const eventNames = this.streamEventNames(domain);
    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * ${entityName} SSE Live-View Stream Client`);
    lines.push(` * Generated by @exeris/codegen-ts (ADR-043 Slice 1)`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` *`);
    lines.push(` * Parity twin of the kernel ${entityName}StreamHandler, registered at`);
    lines.push(` * GET ${streamUrl} via the router's streamRoute(...). Uses the native`);
    lines.push(` * EventSource (GET-only, no custom headers — auth via cookie/session).`);
    lines.push(` */`);
    lines.push(``);
    lines.push(`import { Injectable } from '@angular/core';`);
    lines.push(`import { Observable } from 'rxjs';`);
    lines.push(``);
    lines.push(`@Injectable({ providedIn: 'root' })`);
    lines.push(`export class ${entityName}StreamClient {`);
    lines.push(`  /**`);
    lines.push(`   * The named SSE events the kernel ${entityName}StreamHandler emits: one per`);
    lines.push(`   * @DomainEvent, with the event payload JSON as data.`);
    if (eventNames.length === 0) {
      lines.push(`   * ${entityName} declares no @DomainEvent, so the handler sends only its`);
      lines.push(`   * 'keep-alive' heartbeat and this stream delivers no message.`);
    }
    lines.push(`   */`);
    lines.push(`  static readonly STREAM_EVENT_TYPES: readonly string[] = [${eventNames.map(n => `'${tsSingleQuoted(n)}'`).join(', ')}];`);
    lines.push(``);
    lines.push(`  private readonly streamUrl = '${streamUrl}';`);
    lines.push(``);
    lines.push(`  /**`);
    lines.push(`   * Opens the ${entityName} live-view SSE stream and surfaces each domain event`);
    lines.push(`   * as a MessageEvent: \`type\` is the event name (one of STREAM_EVENT_TYPES),`);
    lines.push(`   * \`data\` the payload JSON. Every server frame is named, so each name gets its`);
    lines.push(`   * own addEventListener — onmessage would see none of them. The 'keep-alive'`);
    lines.push(`   * heartbeat is not delivered. The browser reconnects when the server closes`);
    lines.push(`   * the stream; the Observable errors only once the EventSource gives up`);
    lines.push(`   * (readyState CLOSED). The EventSource is closed when the subscription is`);
    lines.push(`   * torn down.`);
    lines.push(`   */`);
    lines.push(`  stream(): Observable<MessageEvent<string>> {`);
    lines.push(`    return new Observable<MessageEvent<string>>((subscriber) => {`);
    lines.push(`      const source = new EventSource(this.streamUrl, { withCredentials: true });`);
    lines.push(`      const forward = (event: MessageEvent<string>): void => subscriber.next(event);`);
    lines.push(`      for (const type of ${entityName}StreamClient.STREAM_EVENT_TYPES) {`);
    lines.push(`        source.addEventListener(type, forward);`);
    lines.push(`      }`);
    lines.push(`      source.onerror = () => {`);
    lines.push(`        if (source.readyState === EventSource.CLOSED) {`);
    lines.push(`          subscriber.error(new Error(\`${entityName} stream closed: \${this.streamUrl}\`));`);
    lines.push(`        }`);
    lines.push(`      };`);
    lines.push(`      return () => source.close();`);
    lines.push(`    });`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push(``);

    return lines.join('\n');
  }
}

export function generateStreamClient(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile | null {
  const generator = new StreamClientGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context);
}
