/**
 * Enum Generator - Full Implementation
 *
 * Generates TypeScript enums with:
 * - Enum values
 * - Display names (i18n)
 * - Descriptions (i18n)
 * - Icons/colors (optional)
 * - Zod schemas
 *
 * @author Exeris Team
 * @since 0.4.0
 */

import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext, EnumMetadata } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';

export interface EnumValueMetadata {
  name: string;
  displayName: string;
  ordinal: number;
  description?: string;
  deprecated?: boolean;
  icon?: string;
  color?: string;
}

export interface FullEnumMetadata extends EnumMetadata {
  values: EnumValueMetadata[];
}

export class EnumGenerator implements CodeGenerator {
  readonly name = 'EnumGenerator';
  readonly artifactType = 'ENUM' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 1;

  generate(): GeneratedFile | null {
    return null;
  }

  generateAggregate(
    domains: unknown[],
    context: GeneratorContext
  ): GeneratedFile[] {
    const enums = context.enums ?? [];

    if (enums.length === 0) {
      return [
        {
          path: 'types/enums.ts',
          content: this.generatePlaceholder(),
          artifactType: 'ENUM',
          overwritable: true,
        },
      ];
    }

    return [
      {
        path: 'types/enums.ts',
        content: this.generateEnumsFile(enums as FullEnumMetadata[]),
        artifactType: 'ENUM',
        overwritable: true,
      },
    ];
  }

  private generatePlaceholder(): string {
    return `/**
 * Enum Definitions
 * Generated by @exeris/codegen-ts v0.4.0
 * DO NOT EDIT - This file is auto-generated
 */

import { z } from 'zod';

// Placeholder - No enums defined
export {};
`;
  }

  private generateEnumsFile(enums: FullEnumMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * Enum Definitions`,
      ` * Generated by @exeris/codegen-ts v0.4.0`,
      ` * DO NOT EDIT - This file is auto-generated`,
      ` */`,
      ``,
      `import { z } from 'zod';`,
      ``,
    ];

    for (const enumMeta of enums) {
      lines.push(...this.generateEnumBlock(enumMeta));
      lines.push(``);
    }

    lines.push(`// Utility function`);
    lines.push(`export function enumOptions<T extends string>(`);
    lines.push(`  enumObj: Record<string, T>,`);
    lines.push(`  displayNames: Record<T, string>`);
    lines.push(`): Array<{ value: T; label: string }> {`);
    lines.push(`  return Object.values(enumObj)`);
    lines.push(`    .filter((v): v is T => typeof v === 'string')`);
    lines.push(`    .map((value) => ({ value, label: displayNames[value] ?? value }));`);
    lines.push(`}`);

    return lines.join('\n');
  }

  private generateEnumBlock(enumMeta: FullEnumMetadata): string[] {
    const lines: string[] = [];
    const { name, values = [], description } = enumMeta;

    lines.push(`// === ${name} ===`);
    if (description) {
      lines.push(`/** ${description} */`);
    }

    lines.push(`export enum ${name} {`);
    for (const value of values) {
      if (value.deprecated) lines.push(`  /** @deprecated */`);
      lines.push(`  ${value.name} = '${value.name}',`);
    }
    lines.push(`}`);
    lines.push(``);

    lines.push(`export const ${name}DisplayNames: Record<${name}, string> = {`);
    for (const value of values) {
      const displayName = value.displayName || this.humanize(value.name);
      lines.push(`  [${name}.${value.name}]: $localize\`:@@enum.${name}.${value.name}:${displayName}\`,`);
    }
    lines.push(`};`);
    lines.push(``);

    lines.push(`export const ${name}Schema = z.nativeEnum(${name});`);
    lines.push(``);

    lines.push(`export const ${name}Options = Object.values(${name})`);
    lines.push(`  .filter((v): v is ${name} => typeof v === 'string')`);
    lines.push(`  .map((value) => ({ value, label: ${name}DisplayNames[value] }));`);

    return lines;
  }

  private humanize(name: string): string {
    return name
      .replace(/_/g, ' ')
      .replace(/([A-Z])/g, ' $1')
      .trim()
      .split(' ')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
      .join(' ');
  }
}

export function generateEnums(
  enums: FullEnumMetadata[],
  config: GeneratorConfig
): GeneratedFile {
  const generator = new EnumGenerator();
  const context: GeneratorContext = {
    config,
    backend: config.backend ?? 'KERNEL',
    allDomains: [],
    enums: enums as EnumMetadata[],
  };

  const files = generator.generateAggregate([], context);
  return files[0]!;
}

