/**
 * The enum module (`types/enums.ts`) — one emitter, two callers.
 *
 * Lifted out of `orchestrator.ts` unchanged when the peer-types slice (T42, ADR-048)
 * needed the same emitter for a peer's own enum module. Leaving it in the orchestrator
 * would have made the peer generator import the module that imports it; the alternative —
 * a second enum emitter for peers — is the drift this repository already carries once
 * (`enum-gen.ts` emits an enum module nothing composes) and is not worth carrying twice.
 *
 * `orchestrator.ts` re-exports both symbols, so existing importers are unaffected.
 *
 * @author Exeris Team
 * @since 0.8.0
 */

export interface EnumMetadataForGen {
  name: string;
  qualifiedName: string;
  packageName: string;
  description?: string;
  values: Array<{ name: string; displayName: string; ordinal: number; description?: string }>;
}

/**
 * Emits the enum module (`types/enums.ts`): per enum a const-object value, its
 * literal-union type, a `*DisplayNames` lookup, and (when `includeZod`) a Zod
 * `*Schema` — the real members the entity types and Zod schemas reference. (The
 * former stub shipped an empty `enum {}`.)
 *
 * Always returns a valid module: with zero enums it emits `export {};` so the
 * type/app barrels' `export * from './enums'` re-exports still resolve (a missing
 * file is TS2307). The Zod schema + its `zod` import are gated by `includeZod`
 * (config.generateZod) so a `--no-zod` build doesn't ship an unused import.
 */
export function generateEnumTypes(enums: EnumMetadataForGen[], includeZod: boolean): string {
  const header = [
    '/**',
    ' * Generated Enum Types',
    ' * Generated by @exeris/codegen-ts',
    ' * DO NOT EDIT - This file is auto-generated',
    ' */',
    '',
  ];

  if (enums.length === 0) {
    // No enums — a valid empty module so `export * from './enums'` resolves.
    return [...header, 'export {};', ''].join('\n');
  }

  const lines = [...header];
  if (includeZod) {
    lines.push("import { z } from 'zod';", '');
  }

  for (const enumDef of enums) {
    if (enumDef.description) {
      lines.push(`/** ${enumDef.description} */`);
    }
    lines.push(`export const ${enumDef.name} = {`);
    for (const value of enumDef.values) {
      if (value.description) {
        lines.push(`  /** ${value.description} */`);
      }
      lines.push(`  ${value.name}: '${value.name}',`);
    }
    lines.push('} as const;');
    lines.push('');
    lines.push(`export type ${enumDef.name} = typeof ${enumDef.name}[keyof typeof ${enumDef.name}];`);
    lines.push('');

    lines.push(`export const ${enumDef.name}DisplayNames: Record<${enumDef.name}, string> = {`);
    for (const value of enumDef.values) {
      lines.push(`  [${enumDef.name}.${value.name}]: '${value.displayName}',`);
    }
    lines.push('};');
    lines.push('');

    if (includeZod) {
      lines.push(`export const ${enumDef.name}Schema = z.enum([`);
      for (const value of enumDef.values) {
        lines.push(`  '${value.name}',`);
      }
      lines.push(']);');
      lines.push('');
    }
  }

  return lines.join('\n');
}
