/**
 * Peer DTOs — the first thing generated from a peer's contract (T42, ADR-048).
 *
 * A mesh consumer retypes a peer's vocabulary by hand, across a language boundary, with no
 * compiler in between; the first symptom of drift is a field that silently stopped
 * arriving. These types put a compiler there.
 *
 * Three shape decisions, all from ADR-048:
 *
 * - **Per peer, never merged** (§3). Each peer gets its own directory, its own enum module
 *   and its own barrel. Two peers may both call an entity `Order`, and T40 is this
 *   repository's own record of what happens when two identifiers meet in one namespace: an
 *   emitted app that does not compile, found by `ng build` and by no unit test. A merged
 *   barrel would reproduce that at mesh scale.
 * - **A copy per consumer** (§4). Publishing a shared package on a producer's behalf is a
 *   distribution decision; this pipeline generates into one app's tree.
 * - **DTOs only.** The entity interface, its `Create`/`Update` shapes and (under
 *   `generateZod`) its schemas. Deliberately *not* the `Filter` and `ListResponse` shapes
 *   the local emitter also writes: those describe this app's own list and query surface,
 *   and for a peer whose client is not emitted until the 0.9.0 slice they would describe a
 *   query nobody can make — the inert-emitted-surface failure mode D10, D11 and the
 *   unwired templates each record.
 *
 * Field mapping, the create-DTO field selection, enum detection and the Zod expressions are
 * imported from `type-gen.ts` rather than re-implemented, so a peer's types and this app's
 * own cannot drift apart.
 *
 * @author Exeris Team
 * @since 0.8.0
 */

import { outPath } from '../../core/paths.js';
import type { DomainMetadata } from '../../models/domain-model.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import { modelTypeName } from '../../models/model-naming.js';
import type { GeneratorConfig } from '../../config.js';
import type { PeerContract } from '../../peers/peer-contract.js';
import { generateEnumTypes } from './enum-module-gen.js';
import { buildZodType, collectEnumTypes, createDtoFields, systemFieldNames } from './type-gen.js';

/** An emitted file, in the same (path, content) shape the orchestrator composes. */
export interface PeerOutputFile {
  path: string;
  content: string;
}

/** The app-relative root of one peer's tree. Peer names are validated at load. */
export function peerRoot(peerName: string): string {
  return outPath('peers', peerName);
}

/**
 * Everything emitted for one peer, in a stable order: the enum module, one file per entity
 * (entities arrive sorted by the loader), the Zod schemas when enabled, then the barrel.
 */
export function generatePeerTypes(peer: PeerContract, config: GeneratorConfig): PeerOutputFile[] {
  const root = peerRoot(peer.name);
  const visible = peer.domains.filter((d) => !d.internalApi?.hidden);
  const files: PeerOutputFile[] = [
    { path: outPath(root, 'types', 'enums.ts'), content: generateEnumTypes(peer.enums, config.generateZod) },
  ];

  for (const domain of visible) {
    files.push({
      path: outPath(root, 'types', `${DslMapper.toKebabCase(domain.entityName)}.types.ts`),
      content: peerInterface(peer.name, domain),
    });
  }

  if (config.generateZod) {
    for (const domain of visible) {
      files.push({
        path: outPath(root, 'schemas', `${DslMapper.toKebabCase(domain.entityName)}.schema.ts`),
        content: peerZodSchema(peer.name, domain),
      });
    }
  }

  files.push({ path: outPath(root, 'index.ts'), content: peerBarrel(peer.name, visible, config.generateZod) });
  return files;
}

/** The header every peer file carries: whose vocabulary this is, and that it is a copy. */
function header(peerName: string, what: string): string[] {
  return [
    '/**',
    ` * ${what}`,
    ` * Peer contract: '${peerName}' — generated from that peer's published contract artifact.`,
    ' * Generated by @exeris/codegen-ts',
    ' * DO NOT EDIT - This file is auto-generated',
    ' */',
    '',
  ];
}

function peerInterface(peerName: string, metadata: DomainMetadata): string {
  const typeName = modelTypeName(metadata.entityName);
  const enumTypes = collectEnumTypes(metadata.fields);

  const lines = header(peerName, `${metadata.displayName ?? metadata.entityName} — peer DTO`);

  if (enumTypes.length > 0) {
    lines.push(`import { ${enumTypes.join(', ')} } from './enums';`, '');
  }

  lines.push(`export interface ${typeName} {`);
  for (const field of metadata.fields) {
    const optional = field.required ? '' : '?';
    const comment = field.description ? ` // ${field.description}` : '';
    lines.push(`  ${field.name}${optional}: ${DslMapper.mapType(field.type).tsType};${comment}`);
  }
  lines.push('}', '');

  lines.push(`export interface ${typeName}Create {`);
  for (const field of createDtoFields(metadata)) {
    const optional = field.required ? '' : '?';
    lines.push(`  ${field.name}${optional}: ${DslMapper.mapType(field.type).tsType};`);
  }
  lines.push('}', '');

  lines.push(`export type ${typeName}Update = Partial<${typeName}Create>;`);

  return lines.join('\n');
}

function peerZodSchema(peerName: string, metadata: DomainMetadata): string {
  const typeName = modelTypeName(metadata.entityName);
  const enumSchemas = collectEnumTypes(metadata.fields).map((e) => `${e}Schema`);

  const lines = header(peerName, `${metadata.displayName ?? metadata.entityName} — peer DTO schemas`);
  lines.push("import { z } from 'zod';");
  if (enumSchemas.length > 0) {
    lines.push(`import { ${enumSchemas.join(', ')} } from '../types/enums';`);
  }
  lines.push('');

  lines.push(`export const ${typeName}Schema = z.object({`);
  for (const field of metadata.fields) {
    lines.push(`  ${field.name}: ${buildZodType(field)},`);
  }
  lines.push('});', '');

  // `z.omit()` rejects a key the object does not declare (TS2322), so only system fields
  // the peer actually declares are omitted — the same rule the local emitter follows.
  const declared = new Set(metadata.fields.map((f) => f.name));
  lines.push(`export const ${typeName}CreateSchema = ${typeName}Schema.omit({`);
  for (const name of systemFieldNames(metadata).filter((f) => declared.has(f))) {
    lines.push(`  ${name}: true,`);
  }
  lines.push('});', '');

  lines.push(`export const ${typeName}UpdateSchema = ${typeName}CreateSchema.partial();`);

  return lines.join('\n');
}

/**
 * One barrel per peer, and only per peer. It is never re-exported from the app's own
 * `types/index.ts` or from `src/app/index.ts`: a consumer reaches a peer's `Order` through
 * `./peers/<peer>`, which is what keeps it distinct from its own `Order` and from the next
 * peer's.
 */
function peerBarrel(peerName: string, domains: DomainMetadata[], includeZod: boolean): string {
  const lines = header(peerName, 'Barrel export');
  lines.push("export * from './types/enums';");
  for (const domain of domains) {
    lines.push(`export * from './types/${DslMapper.toKebabCase(domain.entityName)}.types';`);
  }
  if (includeZod) {
    for (const domain of domains) {
      lines.push(`export * from './schemas/${DslMapper.toKebabCase(domain.entityName)}.schema';`);
    }
  }
  return lines.join('\n') + '\n';
}
