/**
 * Query Builder Generator
 *
 * Generates fluent query builder classes for each domain entity.
 * Features:
 * - Type-safe filter methods
 * - Pagination support
 * - Sorting support
 * - Full-text search
 *
 * @author Exeris Team
 * @since 0.4.0
 */

import type { DomainMetadata, FieldMetadata, CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { BackendType } from '../../core/backend-strategy.js';
import { outPath } from '../../core/paths.js';

export class QueryBuilderGenerator implements CodeGenerator {
  readonly name = 'QueryBuilderGenerator';
  readonly artifactType = 'QUERY_BUILDER' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 5;

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (domain.internalApi?.hidden) {
      return null;
    }

    const kebab = DslMapper.toKebabCase(domain.entityName);
    const content = this.generateQueryBuilderContent(domain, context);

    return {
      path: outPath('queries', `${kebab}.query.ts`),
      content,
      artifactType: 'QUERY_BUILDER',
      overwritable: true,
    };
  }

  generateAggregate(domains: DomainMetadata[], context: GeneratorContext): GeneratedFile[] {
    const visibleDomains = domains.filter(d => !d.internalApi?.hidden);
    return [
      {
        path: 'queries/index.ts',
        content: this.generateBarrelExport(visibleDomains),
        artifactType: 'QUERY_BUILDER',
        overwritable: true,
      },
    ];
  }

  private generateQueryBuilderContent(domain: DomainMetadata, context: GeneratorContext): string {
    const { entityName, fields = [] } = domain;
    const kebab = DslMapper.toKebabCase(domain.entityName);

    const filterableFields = fields.filter(f => f.filterable);
    const sortableFields = fields.filter(f => f.sortable);
    const idField = domain.systemFields?.idField ?? 'id';
    const enumTypes = this.collectEnumTypes(filterableFields);

    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * ${entityName} Query Builder`);
    lines.push(` * Generated by @exeris/codegen-ts v0.4.0`);
    lines.push(` * DO NOT EDIT - This file is auto-generated`);
    lines.push(` */`);
    lines.push(``);
    lines.push(`import { HttpParams } from '@angular/common/http';`);
    lines.push(`import type { ${entityName} } from '../types/${kebab}.types';`);

    if (enumTypes.length > 0) {
      lines.push(`import { ${enumTypes.join(', ')} } from '../types/enums';`);
    }
    lines.push(``);

    const sortFields = sortableFields.length > 0
      ? sortableFields.map(f => `'${f.name}'`).join(' | ')
      : `'${idField}'`;

    lines.push(`export type ${entityName}SortField = ${sortFields};`);
    lines.push(`export type SortDirection = 'asc' | 'desc';`);
    lines.push(``);

    lines.push(`export interface ${entityName}QueryParams {`);
    lines.push(`  page?: number;`);
    lines.push(`  size?: number;`);
    lines.push(`  sort?: ${entityName}SortField;`);
    lines.push(`  direction?: SortDirection;`);
    lines.push(`  search?: string;`);
    for (const field of filterableFields) {
      const tsType = this.getFilterType(field);
      lines.push(`  ${field.name}?: ${tsType};`);
    }
    lines.push(`}`);
    lines.push(``);

    lines.push(`export class ${entityName}QueryBuilder {`);
    lines.push(`  private readonly params: ${entityName}QueryParams = {};`);
    lines.push(``);

    lines.push(`  page(page: number, size: number = 20): this {`);
    lines.push(`    this.params.page = page;`);
    lines.push(`    this.params.size = size;`);
    lines.push(`    return this;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  size(size: number): this {`);
    lines.push(`    this.params.size = size;`);
    lines.push(`    return this;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  sortBy(field: ${entityName}SortField, direction: SortDirection = 'asc'): this {`);
    lines.push(`    this.params.sort = field;`);
    lines.push(`    this.params.direction = direction;`);
    lines.push(`    return this;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  asc(field: ${entityName}SortField): this { return this.sortBy(field, 'asc'); }`);
    lines.push(`  desc(field: ${entityName}SortField): this { return this.sortBy(field, 'desc'); }`);
    lines.push(``);

    lines.push(`  search(query: string): this {`);
    lines.push(`    this.params.search = query;`);
    lines.push(`    return this;`);
    lines.push(`  }`);
    lines.push(``);

    for (const field of filterableFields) {
      const tsType = this.getFilterType(field);
      lines.push(`  ${field.name}(value: ${tsType}): this {`);
      lines.push(`    this.params.${field.name} = value;`);
      lines.push(`    return this;`);
      lines.push(`  }`);
      lines.push(``);
    }

    lines.push(`  build(): string {`);
    lines.push(`    return this.toHttpParams().toString();`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  toHttpParams(): HttpParams {`);
    lines.push(`    let params = new HttpParams();`);
    lines.push(`    if (this.params.page !== undefined) params = params.set('page', String(this.params.page));`);
    lines.push(`    if (this.params.size !== undefined) params = params.set('size', String(this.params.size));`);
    lines.push(`    if (this.params.sort) params = params.set('sort', \`\${this.params.sort},\${this.params.direction ?? 'asc'}\`);`);
    lines.push(`    if (this.params.search) params = params.set('search', this.params.search);`);
    lines.push(`    const skipKeys = ['page', 'size', 'sort', 'direction', 'search'];`);
    lines.push(`    for (const [key, value] of Object.entries(this.params)) {`);
    lines.push(`      if (skipKeys.includes(key) || value === undefined || value === null || value === '') continue;`);
    lines.push(`      params = params.set(key, String(value));`);
    lines.push(`    }`);
    lines.push(`    return params;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  getParams(): ${entityName}QueryParams { return { ...this.params }; }`);
    lines.push(``);

    lines.push(`  reset(): this {`);
    lines.push(`    Object.keys(this.params).forEach(k => delete (this.params as Record<string, unknown>)[k]);`);
    lines.push(`    return this;`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  clone(): ${entityName}QueryBuilder {`);
    lines.push(`    const cloned = new ${entityName}QueryBuilder();`);
    lines.push(`    Object.assign(cloned.params, this.params);`);
    lines.push(`    return cloned;`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push(``);

    lines.push(`export function ${entityName.charAt(0).toLowerCase() + entityName.slice(1)}Query(): ${entityName}QueryBuilder {`);
    lines.push(`  return new ${entityName}QueryBuilder();`);
    lines.push(`}`);

    return lines.join('\n');
  }

  private generateBarrelExport(domains: DomainMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * Query Builders - Barrel Export`,
      ` * Generated by @exeris/codegen-ts v0.4.0`,
      ` */`,
      ``,
    ];

    for (const domain of domains) {
      const kebab = DslMapper.toKebabCase(domain.entityName);
      lines.push(`export * from './${kebab}.query';`);
    }

    return lines.join('\n');
  }

  private getFilterType(field: FieldMetadata): string {
    if (field.enumType) {
      const simpleName = field.enumType.includes('.') ? field.enumType.split('.').pop()! : field.enumType;
      return simpleName;
    }
    const type = field.type;
    if (type === 'Boolean' || type === 'boolean') return 'boolean';
    if (type.includes('Integer') || type.includes('Long') || type.includes('Double')) return 'number';
    return 'string';
  }

  private collectEnumTypes(fields: FieldMetadata[]): string[] {
    const enums = new Set<string>();
    for (const field of fields) {
      if (field.enumType) {
        const simpleName = field.enumType.includes('.') ? field.enumType.split('.').pop()! : field.enumType;
        enums.add(simpleName);
      }
    }
    return [...enums];
  }
}

export function generateQueryBuilder(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile {
  const generator = new QueryBuilderGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  return generator.generate(metadata, context)!;
}

