/**
 * TypeScript Type/Interface Generator
 * Generates TypeScript interfaces and Zod schemas from domain metadata.
 *
 * @author Exeris Team
 * @since 0.2.0
 */

import { join } from 'node:path';
import type { DomainMetadata, FieldMetadata } from '../../models/domain-model.js';
import { DslMapper } from '../../models/dsl-mapper.js';
import type { GeneratorConfig } from '../../config.js';
import type { CodeGenerator, GeneratedFile, GeneratorContext } from '../../core/generator-registry.js';
import type { BackendType } from '../../core/backend-strategy.js';

export { GeneratedFile };

export class TypeGenerator implements CodeGenerator {
  readonly name = 'TypeGenerator';
  readonly artifactType = 'TYPE' as const;
  readonly supportedBackends: BackendType[] = [];
  readonly priority = 2; // After enums

  generate(domain: DomainMetadata, context: GeneratorContext): GeneratedFile | null {
    if (domain.internalApi?.hidden) {
      return null;
    }

    const content = this.generateInterface(domain, context);
    const kebabName = DslMapper.toKebabCase(domain.entityName);

    return {
      path: join('types', `${kebabName}.types.ts`),
      content,
      artifactType: 'TYPE',
      overwritable: true,
    };
  }

  generateAggregate(domains: DomainMetadata[], context: GeneratorContext): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const visibleDomains = domains.filter(d => !d.internalApi?.hidden);

    // Generate Zod schemas if enabled
    if (context.config.generateZod) {
      for (const domain of visibleDomains) {
        files.push(this.generateZodSchema(domain, context));
      }
    }

    // Generate barrel export for types
    files.push({
      path: 'types/index.ts',
      content: this.generateTypesBarrel(visibleDomains),
      artifactType: 'TYPE',
      overwritable: true,
    });

    // Generate barrel export for schemas
    if (context.config.generateZod) {
      files.push({
        path: 'schemas/index.ts',
        content: this.generateSchemasBarrel(visibleDomains),
        artifactType: 'SCHEMA',
        overwritable: true,
      });
    }

    return files;
  }

  private generateInterface(metadata: DomainMetadata, context: GeneratorContext): string {
    const interfaceName = DslMapper.toInterfaceName(metadata.entityName);
    const kebabName = DslMapper.toKebabCase(metadata.entityName);

    // Collect enum types used in fields
    const enumTypes = this.collectEnumTypes(metadata.fields);

    const lines: string[] = [
      `/**`,
      ` * ${metadata.displayName ?? metadata.entityName} Interface`,
      ` * Generated by @exeris/codegen-ts v0.2.0`,
      ` * DO NOT EDIT - This file is auto-generated`,
      ` */`,
      ``,
    ];

    // Add enum imports if needed
    if (enumTypes.length > 0) {
      lines.push(`import { ${enumTypes.join(', ')} } from './enums';`);
      lines.push(``);
    }

    // Main interface
    lines.push(`export interface ${interfaceName} {`);
    for (const field of metadata.fields) {
      const mapping = DslMapper.mapType(field.type);
      const optional = !field.required ? '?' : '';
      const comment = field.description ? ` // ${field.description}` : '';
      lines.push(`  ${field.name}${optional}: ${mapping.tsType};${comment}`);
    }
    lines.push(`}`);
    lines.push(``);

    // Create DTO (without system fields and lifecycle fields)
    const systemFields = this.getSystemFieldNames(metadata);
    const lifecycleFields = ['active', 'onboardingStatus', 'onboardingStartedAt', 'onboardingCompletedAt', 'hierarchyLevel', 'createdAt', 'updatedAt', 'deleted', 'version', 'parentTenantId'];
    const createFields = metadata.fields.filter(f => !systemFields.includes(f.name) && !lifecycleFields.includes(f.name) && f.inCreate !== false);

    lines.push(`export interface ${interfaceName}Create {`);
    for (const field of createFields) {
      const mapping = DslMapper.mapType(field.type);
      const optional = !field.required ? '?' : '';
      lines.push(`  ${field.name}${optional}: ${mapping.tsType};`);
    }
    lines.push(`}`);
    lines.push(``);

    // Update DTO (all fields optional, excluding lifecycle and read-only)
    lines.push(`export type ${interfaceName}Update = Partial<${interfaceName}Create>;`);
    lines.push(``);

    // Filter type
    const filterableFields = metadata.fields.filter(f => f.filterable);
    if (filterableFields.length > 0) {
      lines.push(`export interface ${interfaceName}Filter {`);
      for (const field of filterableFields) {
        const mapping = DslMapper.mapType(field.type);
        lines.push(`  ${field.name}?: ${mapping.tsType};`);
      }
      lines.push(`  search?: string;`);
      lines.push(`}`);
      lines.push(``);
    }

    // List response type
    lines.push(`export interface ${interfaceName}ListResponse {`);
    lines.push(`  content: ${interfaceName}[];`);
    lines.push(`  totalElements: number;`);
    lines.push(`  totalPages: number;`);
    lines.push(`  size: number;`);
    lines.push(`  number: number;`);
    lines.push(`  first: boolean;`);
    lines.push(`  last: boolean;`);
    lines.push(`}`);

    return lines.join('\n');
  }

  private generateZodSchema(metadata: DomainMetadata, context: GeneratorContext): GeneratedFile {
    const interfaceName = DslMapper.toInterfaceName(metadata.entityName);
    const kebabName = DslMapper.toKebabCase(metadata.entityName);

    // Collect enum types used in fields
    const enumTypes = this.collectEnumTypes(metadata.fields);
    const enumSchemaImports = enumTypes.map(e => `${e}Schema`);

    const lines: string[] = [
      `/**`,
      ` * ${metadata.displayName ?? metadata.entityName} Zod Schemas`,
      ` * Generated by @exeris/codegen-ts v0.2.0`,
      ` * DO NOT EDIT - This file is auto-generated`,
      ` */`,
      ``,
      `import { z } from 'zod';`,
    ];

    // Add enum schema imports if needed
    if (enumSchemaImports.length > 0) {
      lines.push(`import { ${enumSchemaImports.join(', ')} } from '../types/enums';`);
    }
    lines.push(``);

    // Main schema
    lines.push(`export const ${interfaceName}Schema = z.object({`);
    for (const field of metadata.fields) {
      const zodType = this.buildZodType(field);
      lines.push(`  ${field.name}: ${zodType},`);
    }
    lines.push(`});`);
    lines.push(``);

    // Create schema (without system fields)
    const systemFields = this.getSystemFieldNames(metadata);

    lines.push(`export const ${interfaceName}CreateSchema = ${interfaceName}Schema.omit({`);
    for (const sf of systemFields) {
      lines.push(`  ${sf}: true,`);
    }
    lines.push(`});`);
    lines.push(``);

    // Update schema
    lines.push(`export const ${interfaceName}UpdateSchema = ${interfaceName}CreateSchema.partial();`);

    return {
      path: join('schemas', `${kebabName}.schema.ts`),
      content: lines.join('\n'),
      artifactType: 'SCHEMA',
      overwritable: true,
    };
  }

  private generateTypesBarrel(domains: DomainMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * Type Definitions - Barrel Export`,
      ` * Generated by @exeris/codegen-ts v0.4.0`,
      ` */`,
      ``,
      `export * from './enums';`,
    ];

    for (const domain of domains) {
      const kebab = DslMapper.toKebabCase(domain.entityName);
      lines.push(`export * from './${kebab}.types';`);
    }

    return lines.join('\n');
  }

  private generateSchemasBarrel(domains: DomainMetadata[]): string {
    const lines: string[] = [
      `/**`,
      ` * Zod Schemas - Barrel Export`,
      ` * Generated by @exeris/codegen-ts v0.4.0`,
      ` */`,
      ``,
    ];

    for (const domain of domains) {
      const kebab = DslMapper.toKebabCase(domain.entityName);
      lines.push(`export * from './${kebab}.schema';`);
    }

    return lines.join('\n');
  }

  private buildZodType(field: FieldMetadata): string {
    const baseMapping = DslMapper.mapType(field.type);
    let zodType = baseMapping.zodType;

    // Apply validations
    if (field.minLength && zodType.includes('z.string')) {
      zodType = zodType.replace('z.string()', `z.string().min(${field.minLength})`);
    }
    if (field.maxLength && zodType.includes('z.string')) {
      zodType += `.max(${field.maxLength})`;
    }
    if (field.min !== undefined && zodType.includes('z.number')) {
      zodType += `.min(${field.min})`;
    }
    if (field.max !== undefined && zodType.includes('z.number')) {
      zodType += `.max(${field.max})`;
    }
    if (field.format === 'email') {
      zodType = 'z.string().email()';
    }
    if (field.format === 'url') {
      zodType = 'z.string().url()';
    }
    if (field.pattern) {
      zodType = `z.string().regex(/${field.pattern}/)`;
    }

    // Optional handling
    if (!field.required) {
      zodType += '.optional()';
    }

    return zodType;
  }

  private getSystemFieldNames(metadata: DomainMetadata): string[] {
    const fields = ['id'];
    const sf = metadata.systemFields;

    if (sf) {
      if (sf.idField && sf.idField !== 'id') fields.push(sf.idField);
      if (sf.versionField) fields.push(sf.versionField);
      if (sf.createdAtField) fields.push(sf.createdAtField);
      if (sf.updatedAtField) fields.push(sf.updatedAtField);
      if (sf.createdByField) fields.push(sf.createdByField);
      if (sf.updatedByField) fields.push(sf.updatedByField);
      if (sf.tenantIdField) fields.push(sf.tenantIdField);
      if (sf.deletedAtField) fields.push(sf.deletedAtField);
    } else {
      // Default system fields
      fields.push('version', 'createdAt', 'updatedAt');
    }

    return [...new Set(fields)];
  }

  /**
   * Collects enum type names from fields that reference enums.
   * Detects enum types by checking if the field type is not a known Java type.
   */
  private collectEnumTypes(fields: FieldMetadata[]): string[] {
    const enumTypes = new Set<string>();

    // Known Java types that should NOT be treated as enums
    const knownJavaTypes = new Set([
      'String', 'java.lang.String',
      'Integer', 'java.lang.Integer', 'int',
      'Long', 'java.lang.Long', 'long',
      'Double', 'java.lang.Double', 'double',
      'Float', 'java.lang.Float', 'float',
      'Boolean', 'java.lang.Boolean', 'boolean',
      'BigDecimal', 'java.math.BigDecimal',
      'BigInteger', 'java.math.BigInteger',
      'UUID', 'java.util.UUID',
      'Instant', 'java.time.Instant',
      'LocalDate', 'java.time.LocalDate',
      'LocalDateTime', 'java.time.LocalDateTime',
      'LocalTime', 'java.time.LocalTime',
      'ZonedDateTime', 'java.time.ZonedDateTime',
      'Duration', 'java.time.Duration',
      'Period', 'java.time.Period',
      'Date', 'java.util.Date',
      'byte[]', 'Object', 'java.lang.Object',
    ]);

    for (const field of fields) {
      const javaType = field.type;

      // Check if field has explicit enumType metadata
      if (field.enumType) {
        const simpleName = field.enumType.includes('.')
          ? field.enumType.substring(field.enumType.lastIndexOf('.') + 1)
          : field.enumType;
        enumTypes.add(simpleName);
        continue;
      }

      // Skip known Java types
      if (knownJavaTypes.has(javaType)) {
        continue;
      }

      // Skip generics (List, Map, Set, etc.)
      if (javaType.includes('<') || javaType.endsWith('[]')) {
        continue;
      }

      // Extract simple name from qualified name
      const simpleName = javaType.includes('.')
        ? javaType.substring(javaType.lastIndexOf('.') + 1)
        : javaType;

      // Skip if simple name is a known type
      if (knownJavaTypes.has(simpleName)) {
        continue;
      }

      // If it's a PascalCase name that's not a known type, it's likely an enum or entity
      // For now, we assume types ending with common enum suffixes or in "domain" package are enums
      if (/^[A-Z][a-zA-Z0-9]*$/.test(simpleName)) {
        // Check if it looks like an enum (typically short names or ends with Role, Status, Type, Plan, etc.)
        if (simpleName.endsWith('Role') || simpleName.endsWith('Status') ||
            simpleName.endsWith('Type') || simpleName.endsWith('Plan') ||
            simpleName.endsWith('State') || simpleName.endsWith('Level') ||
            simpleName.endsWith('Kind') || simpleName.endsWith('Mode') ||
            simpleName.endsWith('Category') || javaType.includes('.domain.')) {
          enumTypes.add(simpleName);
        }
      }
    }

    return [...enumTypes];
  }
}

export function generateTypes(metadata: DomainMetadata, config: GeneratorConfig): GeneratedFile[] {
  const generator = new TypeGenerator();
  const context: GeneratorContext = { config, backend: config.backend ?? 'KERNEL', allDomains: [metadata], enums: [] };
  const file = generator.generate(metadata, context);
  return file ? [file] : [];
}

