package eu.exeris.tooling.codegen.core;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

/**
 * Loads domain metadata from JSON files generated by the annotation processor.
 * <p>
 * Metadata files are expected in the {@code exeris-metadata/} directory
 * within the build output (typically {@code target/classes/}).
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * var loader = new MetadataLoader(Path.of("target/classes"));
 * List<DomainMetadata> domains = loader.loadAll();
 * }</pre>
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public final class MetadataLoader {

    /**
     * Default metadata directory name.
     */
    public static final String METADATA_DIR = "exeris-metadata";

    private final Path classesDir;
    private final ObjectMapper objectMapper;

    /**
     * Creates a new MetadataLoader.
     *
     * @param classesDir Path to compiled classes directory (e.g., target/classes)
     */
    public MetadataLoader(Path classesDir) {
        this.classesDir = Objects.requireNonNull(classesDir, "classesDir must not be null");
        this.objectMapper = createObjectMapper();
    }

    /**
     * Loads all domain metadata files from the metadata directory.
     *
     * @param <T> Metadata type
     * @param metadataClass Class of metadata to deserialize
     * @return List of loaded metadata objects
     * @throws IOException if loading fails
     */
    public <T> List<T> loadAll(Class<T> metadataClass) throws IOException {
        Path metadataDir = classesDir.resolve(METADATA_DIR);

        if (!Files.exists(metadataDir)) {
            return List.of();
        }

        List<T> result = new ArrayList<>();

        try (Stream<Path> files = Files.list(metadataDir)) {
            List<Path> jsonFiles = files
                    .filter(p -> p.toString().endsWith(".json"))
                    .toList();

            for (Path jsonFile : jsonFiles) {
                T metadata = objectMapper.readValue(jsonFile.toFile(), metadataClass);
                result.add(metadata);
            }
        }

        return result;
    }

    /**
     * Loads a single metadata file by entity name.
     *
     * @param <T> Metadata type
     * @param entityName Simple entity name (e.g., "Order")
     * @param metadataClass Class of metadata to deserialize
     * @return Loaded metadata
     * @throws IOException if loading fails or file not found
     */
    public <T> T load(String entityName, Class<T> metadataClass) throws IOException {
        Path metadataFile = classesDir
                .resolve(METADATA_DIR)
                .resolve(entityName + ".json");

        if (!Files.exists(metadataFile)) {
            throw new IOException("Metadata file not found: " + metadataFile);
        }

        return objectMapper.readValue(metadataFile.toFile(), metadataClass);
    }

    /**
     * Checks if metadata exists for an entity.
     *
     * @param entityName Simple entity name
     * @return true if metadata file exists
     */
    public boolean exists(String entityName) {
        Path metadataFile = classesDir
                .resolve(METADATA_DIR)
                .resolve(entityName + ".json");
        return Files.exists(metadataFile);
    }

    /**
     * Lists all available entity names with metadata.
     *
     * @return List of entity names
     * @throws IOException if reading directory fails
     */
    public List<String> listEntities() throws IOException {
        Path metadataDir = classesDir.resolve(METADATA_DIR);

        if (!Files.exists(metadataDir)) {
            return List.of();
        }

        try (Stream<Path> files = Files.list(metadataDir)) {
            return files
                    .filter(p -> p.toString().endsWith(".json"))
                    .map(p -> p.getFileName().toString())
                    .map(name -> name.substring(0, name.length() - 5)) // Remove .json
                    .toList();
        }
    }

    private ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        return mapper;
    }
}

