package eu.exeris.tooling.codegen.core;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

/**
 * Loads domain metadata from JSON files generated by the annotation processor.
 * <p>
 * Metadata files are expected in the {@code exeris-metadata/} directory
 * within the build output (typically {@code target/classes/}).
 *
 * <h2>Usage</h2>
 * {@snippet lang="java" :
 * var loader = new MetadataLoader(Path.of("target/classes"));
 * List<DomainMetadata> domains = loader.loadAll();
 * }
 *
 * @since 0.1
 */
public final class MetadataLoader {

    /**
     * Default metadata directory name.
     */
    public static final String METADATA_DIR = "exeris-metadata";

    /** Directory listing order differs between filesystems; file-name order does not. */
    private static final Comparator<Path> FILE_NAME_ORDER =
            Comparator.comparing(p -> p.getFileName().toString());

    private final Path classesDir;
    private final ObjectMapper objectMapper;

    /**
     * Creates a new MetadataLoader.
     *
     * @param classesDir Path to compiled classes directory (e.g., target/classes)
     */
    public MetadataLoader(Path classesDir) {
        this.classesDir = Objects.requireNonNull(classesDir, "classesDir must not be null");
        this.objectMapper = createObjectMapper();
    }

    /**
     * Loads all domain metadata files from the metadata directory, in file-name order.
     *
     * @param <T> Metadata type
     * @param metadataClass Class of metadata to deserialize
     * @return List of loaded metadata objects, ordered by the name of the file each came from
     * @throws IOException if loading fails
     */
    public <T> List<T> loadAll(Class<T> metadataClass) throws IOException {
        Path metadataDir = classesDir.resolve(METADATA_DIR);

        if (!Files.exists(metadataDir)) {
            return List.of();
        }

        List<T> result = new ArrayList<>();

        try (Stream<Path> files = Files.list(metadataDir)) {
            List<Path> jsonFiles = files
                    .filter(p -> p.toString().endsWith(".json"))
                    .sorted(FILE_NAME_ORDER)
                    .toList();

            for (Path jsonFile : jsonFiles) {
                T metadata = read(jsonFile, metadataClass);
                result.add(metadata);
            }
        }

        return result;
    }

    /**
     * Loads a single metadata file by entity name.
     *
     * @param <T> Metadata type
     * @param entityName Simple entity name (e.g., "Order")
     * @param metadataClass Class of metadata to deserialize
     * @return Loaded metadata
     * @throws IOException if loading fails or file not found
     */
    public <T> T load(String entityName, Class<T> metadataClass) throws IOException {
        Path metadataFile = classesDir
                .resolve(METADATA_DIR)
                .resolve(entityName + ".json");

        if (!Files.exists(metadataFile)) {
            throw new IOException("Metadata file not found: " + metadataFile);
        }

        return read(metadataFile, metadataClass);
    }

    /**
     * Reads one metadata file. A field that carries no {@code inCreate} or {@code inUpdate} key is
     * offered by that form and body, as {@code @Field} defaults both to {@code true}: the record
     * components are primitive, so an absent key would otherwise read as {@code false}.
     */
    private <T> T read(Path file, Class<T> metadataClass) throws IOException {
        JsonNode root = objectMapper.readTree(file.toFile());
        JsonNode fields = root == null ? null : root.get("fields");
        if (fields != null && fields.isArray()) {
            for (JsonNode field : fields) {
                if (field instanceof ObjectNode object) {
                    for (String flag : List.of("inCreate", "inUpdate")) {
                        if (!object.has(flag)) {
                            object.put(flag, true);
                        }
                    }
                }
            }
        }
        return objectMapper.treeToValue(root, metadataClass);
    }

    /**
     * Checks if metadata exists for an entity.
     *
     * @param entityName Simple entity name
     * @return true if metadata file exists
     */
    public boolean exists(String entityName) {
        Path metadataFile = classesDir
                .resolve(METADATA_DIR)
                .resolve(entityName + ".json");
        return Files.exists(metadataFile);
    }

    /**
     * Lists all available entity names with metadata.
     *
     * @return List of entity names, in file-name order
     * @throws IOException if reading directory fails
     */
    public List<String> listEntities() throws IOException {
        Path metadataDir = classesDir.resolve(METADATA_DIR);

        if (!Files.exists(metadataDir)) {
            return List.of();
        }

        try (Stream<Path> files = Files.list(metadataDir)) {
            return files
                    .filter(p -> p.toString().endsWith(".json"))
                    .sorted(FILE_NAME_ORDER)
                    .map(p -> p.getFileName().toString())
                    .map(name -> name.substring(0, name.length() - 5)) // Remove .json
                    .toList();
        }
    }

    private ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        return mapper;
    }
}

