package eu.exeris.tooling.codegen.core;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

/**
 * Utility for writing generated code to files.
 * <p>
 * Handles:
 * <ul>
 *   <li>Directory creation</li>
 *   <li>Package-to-path conversion</li>
 *   <li>File headers with generation metadata</li>
 *   <li>Output-tree ownership: tracks every file it writes and, on
 *       {@link #pruneOrphansAndWriteManifest()}, deletes files emitted by a
 *       previous run that this run no longer produces (T13)</li>
 * </ul>
 *
 * <h2>Generation owns its output tree (T13)</h2>
 * Each run records the relative path of every file it writes. A manifest
 * ({@value #MANIFEST_NAME}) under the output directory persists that set across
 * runs. On the next run, any path that was in the previous manifest but is not
 * re-emitted is an <em>orphan</em> (the entity was removed or re-homed) and is
 * deleted, then now-empty directories are pruned. Only files this tool emitted
 * before are ever deleted — a user-authored file never appears in the manifest,
 * so it is never touched. The manifest is sorted, so its content is
 * deterministic for the same set of generated files (hard-constraint #3).
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public final class OutputWriter {

    /**
     * Name of the per-output-tree manifest file. Records the relative paths this
     * tool emitted, so the next run can prune orphans. Committed alongside the
     * generated tree (L1) — a stale orphan removal is a reviewable diff (D3).
     */
    public static final String MANIFEST_NAME = ".exeris-codegen-manifest";

    private static final String MANIFEST_HEADER =
            "# Exeris Tooling generated-output manifest - DO NOT EDIT MANUALLY";

    private static final String GENERATED_HEADER = """
            /*
             * Generated by Exeris Tooling - DO NOT EDIT MANUALLY
             * Source: %s
             */
            """;

    private final Path outputDir;
    private final boolean addHeader;

    /** Relative paths (forward-slash) written during this run, in write order. */
    private final Set<String> writtenPaths = new LinkedHashSet<>();

    /**
     * Creates a new OutputWriter.
     *
     * @param outputDir Target directory for generated files
     */
    public OutputWriter(Path outputDir) {
        this(outputDir, true);
    }

    /**
     * Creates a new OutputWriter with header option.
     *
     * @param outputDir Target directory for generated files
     * @param addHeader Whether to add generation header to files
     */
    public OutputWriter(Path outputDir, boolean addHeader) {
        this.outputDir = Objects.requireNonNull(outputDir, "outputDir must not be null");
        this.addHeader = addHeader;
    }

    /**
     * Writes a Java source file.
     *
     * @param packageName Package name (e.g., "eu.exeris.domain.order")
     * @param className   Simple class name (e.g., "OrderController")
     * @param source      Java source code
     * @param sourceInfo  Source entity info for header (e.g., "Order.java")
     * @throws IOException if writing fails
     */
    public void writeJavaSource(String packageName, String className, String source, String sourceInfo)
            throws IOException {
        Path packageDir = packageToPath(packageName);
        Path targetDir = outputDir.resolve(packageDir);
        Files.createDirectories(targetDir);

        Path targetFile = targetDir.resolve(className + ".java");

        String content = addHeader
                ? GENERATED_HEADER.formatted(sourceInfo) + "\n" + source
                : source;

        Files.writeString(targetFile, content, StandardCharsets.UTF_8);
        track(targetFile);
    }

    /**
     * Writes a resource file (JSON, YAML, etc.).
     *
     * @param relativePath Relative path within output directory
     * @param content      File content
     * @throws IOException if writing fails
     */
    public void writeResource(String relativePath, String content) throws IOException {
        Path targetFile = outputDir.resolve(relativePath);
        Files.createDirectories(targetFile.getParent());
        Files.writeString(targetFile, content, StandardCharsets.UTF_8);
        track(targetFile);
    }

    /**
     * Writes a binary resource file.
     *
     * @param relativePath Relative path within output directory
     * @param content      Binary content
     * @throws IOException if writing fails
     */
    public void writeResourceBytes(String relativePath, byte[] content) throws IOException {
        Path targetFile = outputDir.resolve(relativePath);
        Files.createDirectories(targetFile.getParent());
        Files.write(targetFile, content);
        track(targetFile);
    }

    /**
     * Counts the files a {@link #pruneOrphansAndWriteManifest()} call would
     * delete right now — the previous-manifest paths this run did not re-emit —
     * <b>without</b> deleting anything. Backs the T18 masked-compile-failure
     * guard: a run that would orphan files it generated nothing to replace is
     * almost always a build that failed before the annotation processor emitted
     * metadata, not an intentional teardown — wiping the committed tree on that
     * signal is the data-loss footgun the guard prevents.
     *
     * @return the number of orphans the next prune would remove
     * @throws IOException if reading the previous manifest fails
     * @since 0.6.0
     */
    public int countOrphans() throws IOException {
        Set<String> previous = readManifest();
        int orphans = 0;
        for (String rel : previous) {
            if (writtenPaths.contains(rel) || MANIFEST_NAME.equals(rel)) {
                continue;
            }
            orphans++;
        }
        return orphans;
    }

    /**
     * Deletes files this tool emitted on a previous run that the current run did
     * not re-emit (orphans), prunes any directories left empty by that removal,
     * and writes the manifest of the current run's files (T13).
     *
     * <p>Safe by construction: only paths listed in the previous manifest are
     * eligible for deletion, so user-authored files (never in the manifest) are
     * never removed. Call once, after all files for a run have been written.
     *
     * @return the number of orphaned files deleted
     * @throws IOException if reading the old manifest or writing the new one fails
     */
    public int pruneOrphansAndWriteManifest() throws IOException {
        Set<String> previous = readManifest();
        int pruned = 0;
        Set<Path> touchedDirs = new LinkedHashSet<>();

        for (String rel : previous) {
            if (writtenPaths.contains(rel) || MANIFEST_NAME.equals(rel)) {
                continue;
            }
            Path orphan = outputDir.resolve(rel).normalize();
            // Defence in depth: never delete outside the output tree.
            if (!orphan.startsWith(outputDir)) {
                continue;
            }
            if (Files.deleteIfExists(orphan)) {
                pruned++;
                touchedDirs.add(orphan.getParent());
            }
        }

        pruneEmptyDirs(touchedDirs);
        writeManifest();
        return pruned;
    }

    /**
     * Relative paths written during this run (forward-slash, sorted).
     * Package-private — test-visibility only; not part of the public API surface
     * before the 1.0.0 freeze.
     */
    Set<String> writtenPaths() {
        return new TreeSet<>(writtenPaths);
    }

    private void track(Path targetFile) {
        writtenPaths.add(relativize(targetFile));
    }

    private String relativize(Path targetFile) {
        return outputDir.relativize(targetFile.normalize()).toString().replace('\\', '/');
    }

    private Set<String> readManifest() throws IOException {
        Path manifest = outputDir.resolve(MANIFEST_NAME);
        if (!Files.exists(manifest)) {
            return Set.of();
        }
        Set<String> paths = new LinkedHashSet<>();
        for (String line : Files.readAllLines(manifest, StandardCharsets.UTF_8)) {
            String trimmed = line.strip();
            if (!trimmed.isEmpty() && !trimmed.startsWith("#")) {
                paths.add(trimmed);
            }
        }
        return paths;
    }

    private void writeManifest() throws IOException {
        List<String> lines = new ArrayList<>();
        lines.add(MANIFEST_HEADER);
        lines.addAll(new TreeSet<>(writtenPaths));
        Files.createDirectories(outputDir);
        Files.writeString(outputDir.resolve(MANIFEST_NAME),
                String.join("\n", lines) + "\n", StandardCharsets.UTF_8);
    }

    /** Deletes the given directories (and their now-empty parents) up to, but not including, the output dir. */
    private void pruneEmptyDirs(Set<Path> dirs) throws IOException {
        for (Path start : dirs) {
            Path dir = start;
            while (dir != null && !dir.equals(outputDir) && dir.startsWith(outputDir) && isEmptyDir(dir)) {
                Files.deleteIfExists(dir);
                dir = dir.getParent();
            }
        }
    }

    private static boolean isEmptyDir(Path dir) throws IOException {
        if (!Files.isDirectory(dir)) {
            return false;
        }
        try (var entries = Files.list(dir)) {
            return entries.findAny().isEmpty();
        }
    }

    /**
     * Converts a package name to a file path.
     *
     * @param packageName Java package name
     * @return Relative path
     */
    private Path packageToPath(String packageName) {
        return Path.of(packageName.replace('.', '/'));
    }

    /**
     * Returns the output directory.
     */
    public Path getOutputDir() {
        return outputDir;
    }

    /**
     * Checks if header addition is enabled.
     */
    public boolean isAddHeader() {
        return addHeader;
    }
}
