package eu.exeris.tooling.codegen.core;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Utility for writing generated code to files.
 * <p>
 * Handles:
 * <ul>
 *   <li>Directory creation</li>
 *   <li>Package-to-path conversion</li>
 *   <li>File headers with generation metadata</li>
 * </ul>
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public final class OutputWriter {

    private static final String GENERATED_HEADER = """
            /*
             * Generated by Exeris Tooling - DO NOT EDIT MANUALLY
             * Source: %s
             */
            """;

    private final Path outputDir;
    private final boolean addHeader;

    /**
     * Creates a new OutputWriter.
     *
     * @param outputDir Target directory for generated files
     */
    public OutputWriter(Path outputDir) {
        this(outputDir, true);
    }

    /**
     * Creates a new OutputWriter with header option.
     *
     * @param outputDir Target directory for generated files
     * @param addHeader Whether to add generation header to files
     */
    public OutputWriter(Path outputDir, boolean addHeader) {
        this.outputDir = Objects.requireNonNull(outputDir, "outputDir must not be null");
        this.addHeader = addHeader;
    }

    /**
     * Writes a Java source file.
     *
     * @param packageName Package name (e.g., "eu.exeris.domain.order")
     * @param className   Simple class name (e.g., "OrderController")
     * @param source      Java source code
     * @param sourceInfo  Source entity info for header (e.g., "Order.java")
     * @throws IOException if writing fails
     */
    public void writeJavaSource(String packageName, String className, String source, String sourceInfo)
            throws IOException {
        Path packageDir = packageToPath(packageName);
        Path targetDir = outputDir.resolve(packageDir);
        Files.createDirectories(targetDir);

        Path targetFile = targetDir.resolve(className + ".java");

        String content = addHeader
                ? GENERATED_HEADER.formatted(sourceInfo) + "\n" + source
                : source;

        Files.writeString(targetFile, content, StandardCharsets.UTF_8);
    }

    /**
     * Writes a resource file (JSON, YAML, etc.).
     *
     * @param relativePath Relative path within output directory
     * @param content      File content
     * @throws IOException if writing fails
     */
    public void writeResource(String relativePath, String content) throws IOException {
        Path targetFile = outputDir.resolve(relativePath);
        Files.createDirectories(targetFile.getParent());
        Files.writeString(targetFile, content, StandardCharsets.UTF_8);
    }

    /**
     * Writes a binary resource file.
     *
     * @param relativePath Relative path within output directory
     * @param content      Binary content
     * @throws IOException if writing fails
     */
    public void writeResourceBytes(String relativePath, byte[] content) throws IOException {
        Path targetFile = outputDir.resolve(relativePath);
        Files.createDirectories(targetFile.getParent());
        Files.write(targetFile, content);
    }

    /**
     * Converts a package name to a file path.
     *
     * @param packageName Java package name
     * @return Relative path
     */
    private Path packageToPath(String packageName) {
        return Path.of(packageName.replace('.', '/'));
    }

    /**
     * Returns the output directory.
     */
    public Path getOutputDir() {
        return outputDir;
    }

    /**
     * Checks if header addition is enabled.
     */
    public boolean isAddHeader() {
        return addHeader;
    }
}

