package eu.exeris.tooling.codegen.core;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DisplayName("OutputWriter")
class OutputWriterTest {

    @TempDir Path tempDir;

    @Test
    @DisplayName("Single-arg constructor enables the generation header by default")
    void singleArgConstructorEnablesHeader() {
        OutputWriter writer = new OutputWriter(tempDir);

        assertThat(writer.isAddHeader()).isTrue();
        assertThat(writer.getOutputDir()).isEqualTo(tempDir);
    }

    @Test
    @DisplayName("Constructor rejects null outputDir with NullPointerException")
    void constructorRejectsNullOutputDir() {
        assertThatThrownBy(() -> new OutputWriter(null))
                .isInstanceOf(NullPointerException.class)
                .hasMessageContaining("outputDir");
    }

    @Test
    @DisplayName("writeJavaSource creates the package directory and prepends the generation header")
    void writeJavaSourcePrependsHeaderByDefault() throws IOException {
        OutputWriter writer = new OutputWriter(tempDir);

        writer.writeJavaSource("com.example.foo", "Bar", "class Bar {}", "Bar.java");

        Path file = tempDir.resolve("com/example/foo/Bar.java");
        assertThat(Files.exists(file)).isTrue();

        String content = Files.readString(file, StandardCharsets.UTF_8);
        assertThat(content)
                .startsWith("/*")
                .contains("Generated by Exeris Tooling - DO NOT EDIT MANUALLY")
                .contains("Source: Bar.java")
                .contains("class Bar {}");
    }

    @Test
    @DisplayName("writeJavaSource(..., addHeader=false) writes only the source body")
    void writeJavaSourceSkipsHeaderWhenDisabled() throws IOException {
        OutputWriter writer = new OutputWriter(tempDir, false);

        writer.writeJavaSource("com.example", "Foo", "class Foo {}", "Foo.java");

        String content = Files.readString(tempDir.resolve("com/example/Foo.java"));
        assertThat(content).isEqualTo("class Foo {}");
        assertThat(writer.isAddHeader()).isFalse();
    }

    @Test
    @DisplayName("writeJavaSource creates nested directories on demand (no pre-existing parents)")
    void writeJavaSourceCreatesNestedDirs() throws IOException {
        OutputWriter writer = new OutputWriter(tempDir, false);

        writer.writeJavaSource("a.b.c.d.e", "Deep", "class Deep {}", "src");

        Path file = tempDir.resolve("a/b/c/d/e/Deep.java");
        assertThat(Files.isRegularFile(file)).isTrue();
    }

    @Test
    @DisplayName("writeResource writes text content under the given relative path, creating dirs")
    void writeResourceWritesTextContent() throws IOException {
        OutputWriter writer = new OutputWriter(tempDir);

        writer.writeResource("openapi/orders.yaml", "openapi: 3.1.0\n");

        Path file = tempDir.resolve("openapi/orders.yaml");
        assertThat(Files.readString(file, StandardCharsets.UTF_8))
                .isEqualTo("openapi: 3.1.0\n");
    }

    @Test
    @DisplayName("writeResourceBytes writes raw bytes verbatim")
    void writeResourceBytesWritesRawBytes() throws IOException {
        OutputWriter writer = new OutputWriter(tempDir);
        byte[] payload = new byte[] { 0x00, 0x01, 0x02, (byte) 0xFF };

        writer.writeResourceBytes("bin/payload.dat", payload);

        Path file = tempDir.resolve("bin/payload.dat");
        assertThat(Files.readAllBytes(file)).containsExactly(payload);
    }
}
