/**
 * Codegen orchestrator — the pure "metadata → OutputFile[]" step.
 *
 * Extracted from the CLI (`index.ts`) so the composition is unit-testable without
 * filesystem I/O (the TS analog of the Java `CodegenPipeline` seam). The CLI loads
 * metadata + writes files; this module decides *what* gets emitted *where*.
 *
 * T20 invariant enforced here: the per-entity artefacts and the enum module are the
 * canonical app source and are emitted by the REAL generators under the Angular
 * sourceRoot `src/app/` — exactly one tree. `generateAppStructure` contributes the
 * scaffold only; it must not re-emit per-entity files or a stub enum module (that
 * second, stub-tainted tree was the T20 build break).
 *
 * @author Exeris Team
 * @since 0.6.0
 */

import type { DomainMetadata, ViewMetadata } from './models/domain-model.js';
import type { GeneratorConfig } from './config.js';
import { createGeneratorContext } from './core/generator-registry.js';
import { generateTypes, TypeGenerator } from './generators/api/type-gen.js';
import { generateService } from './generators/angular/service-gen.js';
import { generateForm } from './generators/angular/form-gen.js';
import { generateList } from './generators/angular/list-gen.js';
import { generateAppStructure } from './generators/angular/app-structure-gen.js';
import { generateView, generateViewRoute } from './generators/angular/view-gen.js';

/** Minimal output-file shape the writer consumes (path + content). The per-shape
 *  generators return richer objects (artifactType/overwritable); those are structurally
 *  assignable here, and nothing downstream of composition needs the extra fields. */
export interface OutputFile {
  path: string;
  content: string;
}

export interface EnumMetadataForGen {
  name: string;
  qualifiedName: string;
  packageName: string;
  description?: string;
  values: Array<{ name: string; displayName: string; ordinal: number; description?: string }>;
}

/**
 * Emits the enum module (`types/enums.ts`): per enum a const-object value, its
 * literal-union type, a `*DisplayNames` lookup, and (when `includeZod`) a Zod
 * `*Schema` — the real members the entity types and Zod schemas reference. (The
 * former stub shipped an empty `enum {}`.)
 *
 * Always returns a valid module: with zero enums it emits `export {};` so the
 * type/app barrels' `export * from './enums'` re-exports still resolve (a missing
 * file is TS2307). The Zod schema + its `zod` import are gated by `includeZod`
 * (config.generateZod) so a `--no-zod` build doesn't ship an unused import.
 */
export function generateEnumTypes(enums: EnumMetadataForGen[], includeZod: boolean): string {
  const header = [
    '/**',
    ' * Generated Enum Types',
    ' * Generated by @exeris/codegen-ts',
    ' * DO NOT EDIT - This file is auto-generated',
    ' */',
    '',
  ];

  if (enums.length === 0) {
    // No enums — a valid empty module so `export * from './enums'` resolves.
    return [...header, 'export {};', ''].join('\n');
  }

  const lines = [...header];
  if (includeZod) {
    lines.push("import { z } from 'zod';", '');
  }

  for (const enumDef of enums) {
    if (enumDef.description) {
      lines.push(`/** ${enumDef.description} */`);
    }
    lines.push(`export const ${enumDef.name} = {`);
    for (const value of enumDef.values) {
      if (value.description) {
        lines.push(`  /** ${value.description} */`);
      }
      lines.push(`  ${value.name}: '${value.name}',`);
    }
    lines.push('} as const;');
    lines.push('');
    lines.push(`export type ${enumDef.name} = typeof ${enumDef.name}[keyof typeof ${enumDef.name}];`);
    lines.push('');

    lines.push(`export const ${enumDef.name}DisplayNames: Record<${enumDef.name}, string> = {`);
    for (const value of enumDef.values) {
      lines.push(`  [${enumDef.name}.${value.name}]: '${value.displayName}',`);
    }
    lines.push('};');
    lines.push('');

    if (includeZod) {
      lines.push(`export const ${enumDef.name}Schema = z.enum([`);
      for (const value of enumDef.values) {
        lines.push(`  '${value.name}',`);
      }
      lines.push(']);');
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Compose the full set of files to write from parsed metadata. Per-entity output
 * (types + Zod schemas + services + form/list components), the enum module, and
 * the per-view page components / routes are re-rooted under `src/app/` (the
 * Angular sourceRoot); the scaffold is appended as-is.
 *
 * `views` is the presentation-IR family (RFC-2026-06-28): each parsed
 * `view_*.json` ViewMetadata emits one standalone, signal-first page component
 * (`pages/<kebab>.component.ts`) + its paired lazy route (`pages/<kebab>.route.ts`).
 * It is optional (defaults to none) so existing 3-arg callers stay valid.
 */
export function buildGeneratedFiles(
  domains: DomainMetadata[],
  enums: EnumMetadataForGen[],
  config: GeneratorConfig,
  views: ViewMetadata[] = []
): OutputFile[] {
  const generatedFiles: OutputFile[] = [];

  // The per-entity tree — emitted by the real generators, then re-rooted to src/app.
  const appTree: OutputFile[] = [];

  // Always emit the enum module (even empty) so the type/app barrels' re-export of
  // './enums' resolves whether or not the project declares any @ExerisEnum.
  appTree.push({ path: 'types/enums.ts', content: generateEnumTypes(enums, config.generateZod) });

  for (const domain of domains) {
    if (domain.internalApi?.hidden) {
      continue;
    }
    appTree.push(...generateTypes(domain, config));
    if (config.generateServices) {
      const service = generateService(domain, config);
      if (service) appTree.push(service);
    }
    if (config.generateForms) {
      const form = generateForm(domain, config);
      if (form) appTree.push(form);
    }
    if (config.generateLists) {
      const list = generateList(domain, config);
      if (list) appTree.push(list);
    }
  }

  // Real per-entity Zod schemas + type/schema barrels (gated by config.generateZod).
  // These were a stub before (T20); the schemas reference the real enum module above.
  const ctx = createGeneratorContext(config, domains);
  appTree.push(...new TypeGenerator().generateAggregate(domains, ctx));

  // Presentation IR (@View): one page component + paired route per view, in
  // declaration order (deterministic — the views arrive in directory-scan order
  // from index.ts; the per-view output itself is order-stable).
  for (const view of views) {
    appTree.push(generateView(view, config));
    appTree.push(generateViewRoute(view, config));
  }

  for (const file of appTree) {
    generatedFiles.push({ ...file, path: `src/app/${file.path}` });
  }

  // Scaffold only — no per-entity files, no enum module (those live in appTree above).
  // `views` is threaded through so the app shell's app.routes.ts imports + spreads
  // each per-view route export (RFC-2026-06-28 §5 route-assembly).
  generatedFiles.push(...generateAppStructure(domains, enums, config, views));

  return generatedFiles;
}
