package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainEventMetadata;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.SagaMetadata;

import javax.lang.model.element.Modifier;

/**
 * Generates event handlers that trigger sagas based on domain events.
 *
 * <p>For each entity with both events and saga trigger configuration,
 * generates a {@code Consumer<DomainEvent>} that routes events through a
 * switch on {@code eventType} and calls the corresponding saga entry-point.
 *
 * <p>Phase 4 of ADR-015: emission is JavaPoet-based.
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelEventHandlerGenerator implements KernelArtifactGenerator {

    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName MAP = ClassName.get("java.util", "Map");
    private static final ClassName CONSUMER = ClassName.get("java.util.function", "Consumer");
    private static final ClassName DOMAIN_EVENT = ClassName.get("eu.exeris.kernel.events.store", "DomainEvent");
    private static final ClassName EVENT_STORE = ClassName.get("eu.exeris.kernel.events.store", "EventStore");
    private static final ClassName SLF4J_LOGGER = ClassName.get("org.slf4j", "Logger");
    private static final ClassName SLF4J_LOGGER_FACTORY = ClassName.get("org.slf4j", "LoggerFactory");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        if (!metadata.isSaga() || metadata.sagaMetadata() == null) {
            return null;
        }
        if (!metadata.hasEvents()) {
            return null;
        }

        SagaMetadata saga = metadata.sagaMetadata();
        String packageName = metadata.packageName().replace(".domain", ".event");
        String entity = metadata.entityName();
        String className = entity + "EventHandler";
        String sagaName = saga.name() != null ? saga.name() : entity + "Saga";

        ClassName sagaType = ClassName.get(metadata.packageName().replace(".domain", ".saga"), sagaName);
        ClassName selfType = ClassName.get(packageName, className);
        TypeName consumerOfDomainEvent = ParameterizedTypeName.get(CONSUMER, DOMAIN_EVENT);

        TypeSpec.Builder builder = KernelScaffold.publicClass(className)
                .addJavadoc("Event handler for $L domain events.\n", entity)
                .addJavadoc("<p>Triggers sagas and other reactions to domain events.\n")
                .addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addJavadoc("\n")
                .addJavadoc("@see $L\n", metadata.fullyQualifiedName())
                .addJavadoc("@see $T\n", sagaType)
                .addSuperinterface(consumerOfDomainEvent)
                .addField(FieldSpec.builder(SLF4J_LOGGER, "LOG",
                                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$T.getLogger($T.class)", SLF4J_LOGGER_FACTORY, selfType)
                        .build())
                .addField(FieldSpec.builder(sagaType, "saga", Modifier.PRIVATE, Modifier.FINAL).build())
                .addField(FieldSpec.builder(EVENT_STORE, "eventStore", Modifier.PRIVATE, Modifier.FINAL).build())
                .addMethod(MethodSpec.constructorBuilder()
                        .addModifiers(Modifier.PUBLIC)
                        .addParameter(sagaType, "saga")
                        .addParameter(EVENT_STORE, "eventStore")
                        .addStatement("this.saga = saga")
                        .addStatement("this.eventStore = eventStore")
                        .build())
                .addMethod(buildAccept(entity, metadata));

        for (DomainEventMetadata eventMeta : metadata.events()) {
            builder.addMethod(buildEventHandler(eventMeta, metadata, sagaName));
        }

        // Event-type constants
        for (DomainEventMetadata eventMeta : metadata.events()) {
            String eventName = getEventName(eventMeta, metadata);
            String constName = toConstantCase(eventName);
            builder.addField(FieldSpec.builder(String.class, constName,
                            Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", eventName)
                    .build());
        }
        // Topic constants (only those with a topic)
        for (DomainEventMetadata eventMeta : metadata.events()) {
            if (eventMeta.topic() != null && !eventMeta.topic().isBlank()) {
                String eventName = getEventName(eventMeta, metadata);
                String constName = toConstantCase(eventName) + "_TOPIC";
                builder.addField(FieldSpec.builder(String.class, constName,
                                Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$S", eventMeta.topic())
                        .build());
            }
        }

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, builder.build()), ArtifactType.EVENT_HANDLER);
    }

    private MethodSpec buildAccept(String entity, DomainMetadata metadata) {
        MethodSpec.Builder accept = MethodSpec.methodBuilder("accept")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(DOMAIN_EVENT, "event")
                .beginControlFlow("if (!$S.equals(event.aggregateType()))", entity)
                .addStatement("return")
                .endControlFlow()
                .addStatement("LOG.debug($S, event.eventType(), event.aggregateId())",
                        "Handling event: {} for aggregate: {}")
                .beginControlFlow("switch (event.eventType())");
        for (DomainEventMetadata eventMeta : metadata.events()) {
            String eventName = getEventName(eventMeta, metadata);
            String handlerMethod = "handle" + eventName;
            accept.addStatement("case $S -> $L(event)", eventName, handlerMethod);
        }
        accept.addStatement("default -> LOG.trace($S, event.eventType())",
                "Unhandled event type: {}");
        return accept.endControlFlow().build();
    }

    private MethodSpec buildEventHandler(DomainEventMetadata eventMeta, DomainMetadata metadata, String sagaName) {
        String eventName = getEventName(eventMeta, metadata);
        String handlerMethod = "handle" + eventName;

        MethodSpec.Builder handler = MethodSpec.methodBuilder(handlerMethod)
                .addJavadoc("Handles $L.\n", eventName);
        if (eventMeta.description() != null && !eventMeta.description().isBlank()) {
            handler.addJavadoc("<p>$L\n", eventMeta.description());
        }
        handler.addModifiers(Modifier.PRIVATE)
                .returns(TypeName.VOID)
                .addParameter(DOMAIN_EVENT, "event")
                .addStatement("LOG.info($S, event.eventType(), event.aggregateId())",
                        "Processing {}: aggregateId={}");

        if (eventName.endsWith("CreatedEvent")) {
            handler.addStatement("$T entityId = event.aggregateId()", UUID)
                    .addStatement("$T tenantId = event.tenantId()", UUID)
                    .beginControlFlow("try")
                    .addStatement("$T sagaId = saga.start(entityId, tenantId != null ? tenantId : entityId)", UUID)
                    .beginControlFlow("if (sagaId != null)")
                    .addStatement("LOG.info($S, $S, sagaId, entityId)",
                            "Started saga '{}' with ID: {} for entity: {}", sagaName)
                    .nextControlFlow("else")
                    .addStatement("LOG.warn($S, $S, entityId)",
                            "Saga '{}' already exists or could not be started for entity: {}", sagaName)
                    .endControlFlow()
                    .nextControlFlow("catch (Exception e)")
                    .addStatement("LOG.error($S, event.eventType(), e)",
                            "Failed to start saga for event: {}")
                    .endControlFlow();
        } else {
            handler.addStatement("$T<String, Object> payload = event.payload()", MAP)
                    .addStatement("LOG.debug($S, payload)", "Event payload: {}")
                    .addCode("// TODO: Add custom handling for $L\n", eventName);
        }
        return handler.build();
    }

    private String getEventName(DomainEventMetadata event, DomainMetadata metadata) {
        String eventName = event.name();
        if (eventName == null || eventName.isBlank()) {
            eventName = metadata.entityName() + "Event";
        }
        if (!eventName.endsWith("Event")) {
            eventName = eventName + "Event";
        }
        return eventName;
    }

    private String toConstantCase(String s) {
        if (s == null || s.isEmpty()) return s;
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                result.append('_');
            }
            result.append(Character.toUpperCase(c));
        }
        return result.toString();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.EVENT_HANDLER;
    }
}
