package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;

import javax.lang.model.element.Modifier;

/**
 * Kernel Client Generator.
 *
 * <p>Generates clients for service-to-service communication. The generated
 * code uses {@code KernelWebClient}; the underlying transport (H1/H2/H3) is
 * an internal detail of the Kernel runtime and tier-dependent — Community
 * runs over H1/H2, the H3 path is Enterprise-only.
 *
 * <p>FQN target updated per ADR-034 (Client-Side Body Codec SPI +
 * {@code KernelWebClient} facade), which supersedes ADR-026. The facade
 * lives in {@code eu.exeris.kernel.core.http.client} — tier-neutral by
 * design so generated application source never encodes Community /
 * Enterprise tier identity.
 *
 * <p>Client-side retry (ADR-045) is a composition-root concern: the policy is
 * constructor-injected into {@code KernelWebClient} like the ADR-032 enricher,
 * so the emitted per-entity client carries no retry code. The emitted
 * constructor Javadoc shows the {@code CommunityHttpRetryPolicy} wiring as
 * documentation only — plain Javadoc text, never an import — so the generated
 * source stays tier-neutral (The Wall).
 *
 * <p>Peer addressing (kernel ADR-074) is the same kind of concern and gets the same
 * treatment. The emitted client names no address, because the peer is deployment data and not
 * domain metadata. The constructor Javadoc shows the caller binding one with
 * {@code KernelWebClient.withAuthority(host:port)}, or configuring the engine's
 * default ({@code http.client.defaultAuthority} / {@code HttpConfig.defaultAuthority}). It
 * matters because a CLIENT-mode {@code HttpConfig}'s {@code bindHost}/{@code port} is a listen
 * address and is never dialled, so wiring that sets only those compiles and is refused at its
 * first request.
 *
 * <p>Every call sends the verb the generated router serves for its operation; update is
 * {@code PUT}, as the router and the OpenAPI document state it. {@code CrudRouteParityE2ETest}
 * holds each client call to the router's routes.
 *
 * @implNote Emission is JavaPoet-based (ADR-015).
 *
 * @see "docs/adr/ADR-034.link.md — link stub; kernel-side
 *      authoritative copy in exeris-kernel/docs/adr/. Target symbol:
 *      KernelWebClient (eu.exeris.kernel.core.http.client)."
 * @see "docs/adr/ADR-045.link.md — link stub; kernel-side
 *      authoritative copy in exeris-kernel/docs/adr/. Target symbol:
 *      HttpRetryPolicy (eu.exeris.kernel.spi.http), wired at the
 *      composition root, not per entity."
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelClientGenerator implements KernelArtifactGenerator {

    private static final ClassName WEB_CLIENT =
            ClassName.get("eu.exeris.kernel.core.http.client", "KernelWebClient");
    private static final ClassName WEB_CLIENT_EXCEPTION =
            ClassName.get("eu.exeris.kernel.core.http.client", "KernelWebClient", "WebClientException");
    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName OPTIONAL = ClassName.get("java.util", "Optional");
    private static final ClassName VOID = ClassName.get("java.lang", "Void");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        String packageName = metadata.packageName().replace(".domain", ".client");
        String entity = metadata.entityName();
        String className = entity + "Client";
        String apiPath = buildApiPath(metadata);

        ClassName entityType = ClassName.get(metadata.packageName(), entity);
        TypeName optionalOfEntity = ParameterizedTypeName.get(OPTIONAL, entityType);

        TypeSpec client = KernelScaffold.publicClass(className)
                .addJavadoc("Generated client for the $L API.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addJavadoc("\n")
                .addJavadoc("<p>Uses {@link $T} for service-to-service communication\n", WEB_CLIENT)
                .addJavadoc("with automatic JSON serialization and Virtual Thread support.\n")
                .addJavadoc("Requests go to the peer the injected client addresses, which this\n")
                .addJavadoc("class never names (kernel ADR-074) — see the constructor.\n")
                .addJavadoc("\n")
                .addJavadoc("@see $T\n", WEB_CLIENT)
                .addField(FieldSpec.builder(String.class, "BASE_PATH",
                                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$S", apiPath)
                        .build())
                .addField(FieldSpec.builder(WEB_CLIENT, "client", Modifier.PRIVATE, Modifier.FINAL).build())
                .addMethod(buildConstructor(className))
                .addMethod(buildFindById(entity, entityType, optionalOfEntity))
                .addMethod(buildFindAllPaged(entity, metadata))
                .addMethod(buildFindAll(entity, metadata))
                .addMethod(buildCreate(entity, entityType))
                .addMethod(buildUpdate(entity, entityType))
                .addMethod(buildDelete(entity))
                .build();

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, client), ArtifactType.CLIENT);
    }

    private MethodSpec buildConstructor(String className) {
        // ADR-045 composition-root example: retry is opt-in on the shared
        // KernelWebClient, never per-entity. CommunityHttpRetryPolicy and
        // HttpRetryPolicy appear as plain Javadoc text (no $T) so no import —
        // and no tier identity — lands in the compiled surface (The Wall).
        //
        // Kernel ADR-074: the same example has to address the peer. A CLIENT-mode
        // HttpConfig(bindHost, port) is a listen address only, and the compatibility constructor
        // builds a client with no peer, so code that sets only those compiles and fails at its
        // first request.
        // HttpConfig and the config key are plain text for the same reason as the retry
        // types: an import used only by Javadoc would be a consumer-build requirement that
        // nothing in the compiled surface needs.
        return MethodSpec.constructorBuilder()
                .addJavadoc("Creates a new $L.\n", className)
                .addJavadoc("\n")
                .addJavadoc("<p>Composition-root example (ADR-045): construct one shared\n")
                .addJavadoc("{@link $T} with a retry policy and every generated client\n", WEB_CLIENT)
                .addJavadoc("inherits retry semantics — no per-entity retry configuration —\n")
                .addJavadoc("then address the peer that serves this API:\n")
                .addJavadoc("<pre>{@code\n")
                .addJavadoc("var webClient = new KernelWebClient(engine, allocator,\n")
                .addJavadoc("        requestEncoders, responseDecoders,\n")
                .addJavadoc("        HttpClientRequestEnricher.noop(),\n")
                .addJavadoc("        new eu.exeris.kernel.community.http.CommunityHttpRetryPolicy());\n")
                .addJavadoc("var client = new $L(webClient.withAuthority(\"peer-host:8080\"));\n",
                        className)
                .addJavadoc("}</pre>\n")
                .addJavadoc("The policy parameter is opt-in — the shorter {@code KernelWebClient}\n")
                .addJavadoc("constructors delegate to {@code HttpRetryPolicy.none()}, keeping the\n")
                .addJavadoc("no-implicit-retry default (ADR-026).\n")
                .addJavadoc("\n")
                .addJavadoc("<p>Addressing the peer (kernel ADR-074): every path this client\n")
                .addJavadoc("requests is relative to the peer the injected client addresses.\n")
                .addJavadoc("Bind one per client with {@code withAuthority(\"host:port\")}, as\n")
                .addJavadoc("above, so one engine serves several peers; or give the client engine\n")
                .addJavadoc("a default peer through the {@code http.client.defaultAuthority}\n")
                .addJavadoc("configuration key, or the {@code defaultAuthority} component of\n")
                .addJavadoc("{@code HttpConfig} when the engine is built by hand. The port is\n")
                .addJavadoc("required. A CLIENT-mode {@code HttpConfig}'s {@code bindHost} and\n")
                .addJavadoc("{@code port} are a listen address and are never dialled: with neither\n")
                .addJavadoc("set, a request is refused rather than sent (the Community engine\n")
                .addJavadoc("throws {@code IllegalStateException} naming\n")
                .addJavadoc("{@code http.client.defaultAuthority}).\n")
                .addJavadoc("\n")
                .addJavadoc("@param client the web client (injected from CompositionRoot)\n")
                .addModifiers(Modifier.PUBLIC)
                .addParameter(WEB_CLIENT, "client")
                .addStatement("this.client = client")
                .build();
    }

    private MethodSpec buildFindById(String entity, ClassName entityType, TypeName optionalOfEntity) {
        return MethodSpec.methodBuilder("findById")
                .addJavadoc("Finds a $L by ID.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param id the entity ID\n")
                .addJavadoc("@return the entity or empty if not found\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(optionalOfEntity)
                .addParameter(UUID, "id")
                .beginControlFlow("try")
                .addStatement("return $T.ofNullable(client.get(BASE_PATH + $S + id, $T.class))",
                        OPTIONAL, "/", entityType)
                .nextControlFlow("catch ($T e)", WEB_CLIENT_EXCEPTION)
                .beginControlFlow("if (e.isNotFound())")
                .addStatement("return $T.empty()", OPTIONAL)
                .endControlFlow()
                .addStatement("throw e")
                .endControlFlow()
                .build();
    }

    /**
     * {@code findAll(page, size)} — the first {@code size}-row page at {@code page}, unsorted and
     * unfiltered. A convenience over {@link #buildFindAll}; it makes no request of its own.
     */
    private MethodSpec buildFindAllPaged(String entity, DomainMetadata metadata) {
        ClassName queryType = KernelListQueryGenerator.listQueryType(metadata);
        return MethodSpec.methodBuilder("findAll")
                .addJavadoc("Finds one page of $L entities, unsorted and unfiltered.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param page page number (0-based)\n")
                .addJavadoc("@param size page size, 1 to {@link $T#MAX_SIZE}\n", queryType)
                .addJavadoc("@return the page\n")
                .addJavadoc("@throws IllegalArgumentException if either is out of range — refused here\n")
                .addJavadoc("        rather than sent, since the server would answer 400\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(KernelListQueryGenerator.pageType(metadata))
                .addParameter(TypeName.INT, "page")
                .addParameter(TypeName.INT, "size")
                .addStatement("return findAll($T.of(page, size))", queryType)
                .build();
    }

    /**
     * {@code findAll(query)} — the list route with the query's page, sort and filters, decoded into
     * the per-entity page record. The query string is the one {@code <Entity>ListQuery.parse} reads
     * on the server, written by the same type.
     */
    private MethodSpec buildFindAll(String entity, DomainMetadata metadata) {
        ClassName queryType = KernelListQueryGenerator.listQueryType(metadata);
        ClassName pageType = KernelListQueryGenerator.pageType(metadata);
        return MethodSpec.methodBuilder("findAll")
                .addJavadoc("Finds one page of $L entities: the query's page, sort and filters.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param query the page, sort and filters\n")
                .addJavadoc("@return the page\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(pageType)
                .addParameter(queryType, "query")
                .addStatement("return client.get(BASE_PATH + $S + query.toQueryString(), $T.class)", "?", pageType)
                .build();
    }

    private MethodSpec buildCreate(String entity, ClassName entityType) {
        return MethodSpec.methodBuilder("create")
                .addJavadoc("Creates a new $L.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param entity the entity to create\n")
                .addJavadoc("@return the created entity\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(entityType, "entity")
                .addStatement("return client.post(BASE_PATH, entity, $T.class)", entityType)
                .build();
    }

    private MethodSpec buildUpdate(String entity, ClassName entityType) {
        return MethodSpec.methodBuilder("update")
                .addJavadoc("Updates an existing $L.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param id the entity ID\n")
                .addJavadoc("@param entity the entity with updated data\n")
                .addJavadoc("@return the updated entity\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(UUID, "id")
                .addParameter(entityType, "entity")
                .addStatement("return client.put(BASE_PATH + $S + id, entity, $T.class)", "/", entityType)
                .build();
    }

    private MethodSpec buildDelete(String entity) {
        return MethodSpec.methodBuilder("delete")
                .addJavadoc("Deletes a $L by ID.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param id the entity ID\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(UUID, "id")
                .addStatement("client.delete(BASE_PATH + $S + id, $T.class)", "/", VOID)
                .build();
    }

    /**
     * The base path the generated client requests — which must be the path the generated
     * <em>server</em> serves, because these two are the only pair in the suite that talk to each other.
     *
     * <p><b>Open design question:</b> {@code @ExerisDomain.apiVersion} reaches no emitted artifact.
     * The server serves routes at {@link DomainMetadata#effectivePath()}, and this client requests
     * the same, aligning with the OpenAPI document. Serving {@code /api/<version>/…} instead would
     * change every emitted route. Until the design is settled, {@code apiVersion} is inert and
     * declared in {@code ExerisDomainProcessor.INERT_ATTRIBUTES}.
     *
     * <p>The TypeScript stream clients ({@code stream-client-gen}, {@code action-stream-client-gen})
     * request the same unversioned routes, which is what keeps that registry entry from being a
     * false "no effect" warning.
     */
    private String buildApiPath(DomainMetadata metadata) {
        // effectivePath() is the SDK-canonical derivation shared by every other generator (OpenAPI,
        // Application): explicit path, else "/" + the kebab-cased pluralName().
        return metadata.effectivePath();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.CLIENT;
    }
}
