package eu.exeris.tooling.codegen.java.kernel;

import eu.exeris.tooling.codegen.core.generator.BackendGenerator;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.FieldMetadata;
import eu.exeris.sdk.sourcemodel.ast.GraphMetadata;
import eu.exeris.sdk.sourcemodel.ast.GraphEdgeMetadata;
import eu.exeris.sdk.sourcemodel.ast.GraphPropertyMetadata;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates graph synchronization service for Exeris Kernel.
 *
 * <p>For entities annotated with {@code @Graph}, generates:
 * <ul>
 *   <li>Graph sync service (maintains consistency between SQL and graph)</li>
 *   <li>Node mapping (entity fields to graph properties)</li>
 *   <li>Edge synchronization (relationships as graph edges)</li>
 * </ul>
 *
 * <p>Integrates with {@code eu.exeris.kernel.graph} module using PostgreSQL
 * SQL/PGQ for graph operations.
 *
 * @author Exeris Team
 * @since 0.1.0
 * @see eu.exeris.kernel.graph.sync.GraphSyncService
 */
public class KernelGraphSyncGenerator implements BackendGenerator {

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        if (!metadata.hasGraphMetadata()) {
            return null; // No graph metadata - skip
        }

        GraphMetadata graph = metadata.graphMetadata();
        String packageName = metadata.packageName().replace(".domain", ".graph");
        String className = metadata.entityName() + "GraphSync";
        String entity = metadata.entityName();
        String nodeLabel = graph.label() != null ? graph.label() : entity;

        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");

        // Imports
        code.append("import ").append(metadata.packageName()).append(".").append(entity).append(";\n");
        code.append("import eu.exeris.kernel.graph.GraphService;\n");
        code.append("import eu.exeris.kernel.graph.model.GraphNodeMetadata;\n");
        code.append("import eu.exeris.kernel.graph.model.GraphEdgeMetadata;\n");
        code.append("import eu.exeris.kernel.graph.sync.GraphSyncService;\n");
        code.append("import eu.exeris.kernel.graph.spi.GraphSession;\n");
        code.append("import org.slf4j.Logger;\n");
        code.append("import org.slf4j.LoggerFactory;\n\n");
        code.append("import java.util.HashMap;\n");
        code.append("import java.util.Map;\n");
        code.append("import java.util.UUID;\n\n");

        // Class header
        code.append("/**\n");
        code.append(" * Graph synchronization for ").append(entity).append(" entities.\n");
        code.append(" * <p>Maintains consistency between SQL table and graph representation.\n");
        code.append(" *\n");
        code.append(" * <p>Node label: {@code ").append(nodeLabel).append("}\n");
        code.append(" * <p>Generated by Exeris Codegen. DO NOT EDIT.\n");
        code.append(" *\n");
        code.append(" * @see ").append(metadata.fullyQualifiedName()).append("\n");
        code.append(" * @see GraphSyncService\n");
        code.append(" */\n");
        code.append("public class ").append(className).append(" {\n\n");

        code.append("    private static final Logger LOG = LoggerFactory.getLogger(").append(className).append(".class);\n");
        code.append("    private static final String NODE_LABEL = \"").append(nodeLabel).append("\";\n\n");

        code.append("    private final GraphService graphService;\n\n");

        // Constructor
        code.append("    public ").append(className).append("(GraphService graphService) {\n");
        code.append("        this.graphService = graphService;\n");
        code.append("    }\n\n");

        // syncToGraph method
        generateSyncToGraph(code, metadata, graph);

        // deleteFromGraph method
        generateDeleteFromGraph(code, metadata);

        // syncEdges method (if edges defined)
        if (graph.edges() != null && !graph.edges().isEmpty()) {
            generateSyncEdges(code, metadata, graph);
        }

        // buildNodeProperties method
        generateBuildNodeProperties(code, metadata, graph);

        // Static metadata
        generateNodeMetadata(code, metadata, graph);

        code.append("}\n");

        return new GeneratedFile(packageName, className, code.toString(), ArtifactType.GRAPH_SYNC);
    }

    private void generateSyncToGraph(StringBuilder code, DomainMetadata metadata, GraphMetadata graph) {
        String entity = metadata.entityName();

        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Sync Operations\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Synchronizes entity to graph as a node.\n");
        code.append("     * Creates node if not exists, updates properties if exists.\n");
        code.append("     *\n");
        code.append("     * @param entity the entity to sync\n");
        code.append("     */\n");
        code.append("    public void syncToGraph(").append(entity).append(" entity) {\n");
        code.append("        LOG.debug(\"Syncing {} to graph: id={}\", NODE_LABEL, entity.getId());\n\n");

        code.append("        try (var session = graphService.openSession()) {\n");
        code.append("            Map<String, Object> properties = buildNodeProperties(entity);\n\n");

        code.append("            // Upsert node (MERGE in SQL/PGQ)\n");
        code.append("            session.upsertNode(\n");
        code.append("                    NODE_LABEL,\n");
        code.append("                    entity.getId().toString(),\n");
        code.append("                    properties\n");
        code.append("            );\n\n");

        // Sync edges if defined
        if (graph.edges() != null && !graph.edges().isEmpty()) {
            code.append("            // Sync edges/relationships\n");
            code.append("            syncEdges(session, entity);\n\n");
        }

        code.append("            LOG.debug(\"Successfully synced {} to graph\", entity.getId());\n");
        code.append("        } catch (Exception e) {\n");
        code.append("            LOG.error(\"Failed to sync {} to graph: id={}\", NODE_LABEL, entity.getId(), e);\n");
        code.append("            throw new RuntimeException(\"Graph sync failed\", e);\n");
        code.append("        }\n");
        code.append("    }\n\n");
    }

    private void generateDeleteFromGraph(StringBuilder code, DomainMetadata metadata) {
        code.append("    /**\n");
        code.append("     * Removes entity from graph (deletes node and connected edges).\n");
        code.append("     *\n");
        code.append("     * @param entityId the entity ID to remove\n");
        code.append("     */\n");
        code.append("    public void deleteFromGraph(UUID entityId) {\n");
        code.append("        LOG.debug(\"Deleting {} from graph: id={}\", NODE_LABEL, entityId);\n\n");

        code.append("        try (var session = graphService.openSession()) {\n");
        code.append("            session.deleteNode(NODE_LABEL, entityId.toString());\n");
        code.append("            LOG.debug(\"Successfully deleted {} from graph\", entityId);\n");
        code.append("        } catch (Exception e) {\n");
        code.append("            LOG.error(\"Failed to delete {} from graph: id={}\", NODE_LABEL, entityId, e);\n");
        code.append("            throw new RuntimeException(\"Graph delete failed\", e);\n");
        code.append("        }\n");
        code.append("    }\n\n");
    }

    private void generateSyncEdges(StringBuilder code, DomainMetadata metadata, GraphMetadata graph) {
        String entity = metadata.entityName();

        code.append("    /**\n");
        code.append("     * Synchronizes edges for the entity.\n");
        code.append("     */\n");
        code.append("    private void syncEdges(GraphSession session, ").append(entity).append(" entity) {\n");

        for (GraphEdgeMetadata edge : graph.edges()) {
            String edgeType = edge.relationType() != null ? edge.relationType() : "RELATES_TO";
            String edgeName = edge.name();
            String targetLabel = edge.targetLabel() != null ? edge.targetLabel() : "Node";

            code.append("        // Edge: ").append(edgeType).append(" (").append(edgeName).append(")\n");
            code.append("        if (entity.get").append(capitalize(edgeName)).append("() != null) {\n");
            code.append("            session.upsertEdge(\n");
            code.append("                    NODE_LABEL,\n");
            code.append("                    entity.getId().toString(),\n");
            code.append("                    \"").append(edgeType).append("\",\n");
            code.append("                    \"").append(targetLabel).append("\",\n");
            code.append("                    entity.get").append(capitalize(edgeName)).append("().toString(),\n");
            code.append("                    Map.of()\n");
            code.append("            );\n");
            code.append("        }\n\n");
        }

        code.append("    }\n\n");
    }

    private void generateBuildNodeProperties(StringBuilder code, DomainMetadata metadata, GraphMetadata graph) {
        String entity = metadata.entityName();

        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Property Mapping\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Builds node properties from entity.\n");
        code.append("     */\n");
        code.append("    private Map<String, Object> buildNodeProperties(").append(entity).append(" entity) {\n");
        code.append("        Map<String, Object> props = new HashMap<>();\n\n");

        // Map entity fields to graph properties
        List<FieldMetadata> graphFields = getGraphFields(metadata, graph);
        for (FieldMetadata field : graphFields) {
            String getter = "get" + capitalize(field.name()) + "()";
            String propName = toSnakeCase(field.name());

            code.append("        if (entity.").append(getter).append(" != null) {\n");

            // Handle special types
            if (isTemporalType(field.type())) {
                code.append("            props.put(\"").append(propName).append("\", entity.").append(getter).append(".toString());\n");
            } else if (field.type().equalsIgnoreCase("uuid")) {
                code.append("            props.put(\"").append(propName).append("\", entity.").append(getter).append(".toString());\n");
            } else {
                code.append("            props.put(\"").append(propName).append("\", entity.").append(getter).append(");\n");
            }
            code.append("        }\n");
        }

        code.append("\n        return props;\n");
        code.append("    }\n\n");
    }

    private void generateNodeMetadata(StringBuilder code, DomainMetadata metadata, GraphMetadata graph) {
        String nodeLabel = graph.label() != null ? graph.label() : metadata.entityName();

        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Metadata\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Returns node metadata for schema initialization.\n");
        code.append("     */\n");
        code.append("    public static GraphNodeMetadata nodeMetadata() {\n");
        code.append("        return GraphNodeMetadata.builder()\n");
        code.append("                .nodeLabel(\"").append(nodeLabel).append("\")\n");

        // Add indexed properties
        List<FieldMetadata> graphFields = getGraphFields(metadata, graph);
        for (FieldMetadata field : graphFields) {
            if (field.indexed() || field.name().equals("id")) {
                code.append("                .property(\"").append(toSnakeCase(field.name())).append("\", true)\n");
            }
        }

        code.append("                .build();\n");
        code.append("    }\n");
    }

    private List<FieldMetadata> getGraphFields(DomainMetadata metadata, GraphMetadata graph) {
        if (metadata.fields() == null) {
            return List.of();
        }

        // If graph has explicit properties, use those
        if (graph.properties() != null && !graph.properties().isEmpty()) {
            List<String> propNames = graph.properties().stream()
                    .map(p -> p.name())
                    .collect(Collectors.toList());
            return metadata.fields().stream()
                    .filter(f -> propNames.contains(f.name()))
                    .collect(Collectors.toList());
        }

        // Otherwise, use searchable/indexed fields
        return metadata.fields().stream()
                .filter(f -> f.searchable() || f.indexed() || f.sortable())
                .filter(f -> !isSystemField(f.name()))
                .collect(Collectors.toList());
    }

    private boolean isSystemField(String name) {
        return name.equals("createdAt") || name.equals("updatedAt")
                || name.equals("createdBy") || name.equals("updatedBy")
                || name.equals("deletedAt") || name.equals("deletedBy") || name.equals("version");
    }

    private boolean isTemporalType(String type) {
        if (type == null) return false;
        String lower = type.toLowerCase();
        return lower.equals("instant") || lower.equals("datetime") || lower.equals("timestamp")
                || lower.equals("localdate") || lower.equals("localdatetime");
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String toSnakeCase(String s) {
        if (s == null || s.isBlank()) return "";
        return s.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.GRAPH_SYNC;
    }
}

