package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;

import javax.lang.model.element.Modifier;

/**
 * Kernel Service Generator.
 *
 * <p>Generates a CRUD service class delegating to the corresponding
 * repository, optionally publishing domain events on lifecycle changes
 * when {@link DomainMetadata#hasEvents()} is true.
 *
 * @implNote Emission is JavaPoet-based (ADR-015).
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelServiceGenerator implements KernelArtifactGenerator {

    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName OPTIONAL = ClassName.get("java.util", "Optional");
    private static final ClassName LIST = ClassName.get("java.util", "List");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        String packageName = metadata.packageName().replace(".domain", ".service");
        String entity = metadata.entityName();
        String className = entity + "Service";
        String repoName = entity + "Repository";
        boolean hasEvents = metadata.hasEvents();

        ClassName entityType = ClassName.get(metadata.packageName(), entity);
        ClassName repoType = ClassName.get(
                metadata.packageName().replace(".domain", ".repository"), repoName);
        TypeName optionalOfEntity = ParameterizedTypeName.get(OPTIONAL, entityType);
        TypeName listOfEntity = ParameterizedTypeName.get(LIST, entityType);

        ClassName publisherType = hasEvents
                ? ClassName.get(metadata.packageName().replace(".domain", ".event"),
                        entity + "Events", "Publisher")
                : null;

        TypeSpec.Builder builder = KernelScaffold.publicClass(className)
                .addJavadoc("Service for $L domain operations.\n", entity);
        if (hasEvents) {
            builder.addJavadoc("<p>Publishes domain events on entity lifecycle changes.\n");
        }
        builder.addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addField(FieldSpec.builder(repoType, "repository",
                        Modifier.PRIVATE, Modifier.FINAL).build());
        if (hasEvents) {
            builder.addField(FieldSpec.builder(publisherType, "eventPublisher",
                    Modifier.PRIVATE, Modifier.FINAL).build());
        }

        builder.addMethod(buildConstructor(repoType, publisherType, hasEvents))
                .addMethod(buildFindById(optionalOfEntity))
                .addMethod(buildFindAll(listOfEntity))
                .addMethod(buildSave(entityType, hasEvents))
                .addMethod(buildUpdate(entityType))
                .addMethod(buildDelete())
                .addMethod(buildCount());

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, builder.build()), ArtifactType.SERVICE);
    }

    private MethodSpec buildConstructor(ClassName repoType, ClassName publisherType, boolean hasEvents) {
        MethodSpec.Builder ctor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(repoType, "repository")
                .addStatement("this.repository = repository");
        if (hasEvents) {
            ctor.addParameter(publisherType, "eventPublisher")
                    .addStatement("this.eventPublisher = eventPublisher");
        }
        return ctor.build();
    }

    private MethodSpec buildFindById(TypeName optionalOfEntity) {
        return MethodSpec.methodBuilder("findById")
                .addModifiers(Modifier.PUBLIC)
                .returns(optionalOfEntity)
                .addParameter(UUID, "id")
                .addStatement("return repository.findById(id)")
                .build();
    }

    private MethodSpec buildFindAll(TypeName listOfEntity) {
        return MethodSpec.methodBuilder("findAll")
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfEntity)
                .addStatement("return repository.findAll()")
                .build();
    }

    private MethodSpec buildSave(ClassName entityType, boolean hasEvents) {
        MethodSpec.Builder save = MethodSpec.methodBuilder("save")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(entityType, "entity")
                .addStatement("$T saved = repository.save(entity)", entityType);
        if (hasEvents) {
            save.addStatement("eventPublisher.publishCreated(saved)");
        }
        return save.addStatement("return saved").build();
    }

    private MethodSpec buildUpdate(ClassName entityType) {
        return MethodSpec.methodBuilder("update")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(UUID, "id")
                .addParameter(entityType, "entity")
                .addStatement("$T updated = repository.update(id, entity)", entityType)
                .addStatement("return updated")
                .build();
    }

    private MethodSpec buildDelete() {
        return MethodSpec.methodBuilder("delete")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(UUID, "id")
                .addStatement("repository.deleteById(id)")
                .build();
    }

    private MethodSpec buildCount() {
        return MethodSpec.methodBuilder("count")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.LONG)
                .addStatement("return repository.count()")
                .build();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.SERVICE;
    }
}
