package eu.exeris.tooling.codegen.java.kernel;

import eu.exeris.tooling.codegen.core.generator.BackendGenerator;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;

/**
 * KernelClientGenerator - Generuje klientów HTTP/3 dla komunikacji service-to-service.
 *
 * <p>Wygenerowany kod używa {@code ExerisWebClient} z pakietu
 * {@code eu.exeris.kernel.transport.http3.client}.
 *
 * @see eu.exeris.kernel.transport.http3.client.ExerisWebClient
 */
public class KernelClientGenerator implements BackendGenerator {

    private static final String WEB_CLIENT_IMPORT = "eu.exeris.kernel.transport.http3.client.ExerisWebClient";
    private static final String WEB_CLIENT_EXCEPTION_IMPORT = "eu.exeris.kernel.transport.http3.client.ExerisWebClient.WebClientException";

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        String packageName = metadata.packageName().replace(".domain", ".client");
        String className = metadata.entityName() + "Client";
        String entity = metadata.entityName();
        String apiPath = buildApiPath(metadata);

        StringBuilder code = new StringBuilder();

        // Package & Imports
        code.append("package ").append(packageName).append(";\n\n");
        code.append("import ").append(WEB_CLIENT_IMPORT).append(";\n");
        code.append("import ").append(WEB_CLIENT_EXCEPTION_IMPORT).append(";\n");
        code.append("import ").append(metadata.packageName()).append(".").append(entity).append(";\n");
        code.append("import java.util.List;\n");
        code.append("import java.util.Optional;\n");
        code.append("import java.util.UUID;\n\n");

        // Class JavaDoc
        code.append("/**\n");
        code.append(" * HTTP/3 Client for ").append(entity).append(" API.\n");
        code.append(" *\n");
        code.append(" * <p>Generated by Exeris Codegen. DO NOT EDIT.\n");
        code.append(" *\n");
        code.append(" * <p>Uses {@link ExerisWebClient} for HTTP/3 communication\n");
        code.append(" * with automatic JSON serialization and Virtual Thread support.\n");
        code.append(" *\n");
        code.append(" * @see ExerisWebClient\n");
        code.append(" */\n");

        // Class definition
        code.append("public class ").append(className).append(" {\n\n");

        // Fields
        code.append("    private final ExerisWebClient client;\n");
        code.append("    private static final String BASE_PATH = \"").append(apiPath).append("\";\n\n");

        // Constructor
        code.append("    /**\n");
        code.append("     * Creates a new ").append(className).append(".\n");
        code.append("     *\n");
        code.append("     * @param client the HTTP/3 web client (injected from CompositionRoot)\n");
        code.append("     */\n");
        code.append("    public ").append(className).append("(ExerisWebClient client) {\n");
        code.append("        this.client = client;\n");
        code.append("    }\n\n");

        // CRUD Methods

        // findById
        code.append("    /**\n");
        code.append("     * Finds a ").append(entity).append(" by ID.\n");
        code.append("     *\n");
        code.append("     * @param id the entity ID\n");
        code.append("     * @return the entity or empty if not found\n");
        code.append("     */\n");
        code.append("    public Optional<").append(entity).append("> findById(UUID id) {\n");
        code.append("        try {\n");
        code.append("            return Optional.ofNullable(client.get(BASE_PATH + \"/\" + id, ").append(entity).append(".class));\n");
        code.append("        } catch (WebClientException e) {\n");
        code.append("            if (e.isNotFound()) {\n");
        code.append("                return Optional.empty();\n");
        code.append("            }\n");
        code.append("            throw e;\n");
        code.append("        }\n");
        code.append("    }\n\n");

        // findAll (with pagination support)
        code.append("    /**\n");
        code.append("     * Finds all ").append(entity).append(" entities with pagination.\n");
        code.append("     *\n");
        code.append("     * @param page page number (0-based)\n");
        code.append("     * @param size page size\n");
        code.append("     * @return list of entities\n");
        code.append("     */\n");
        code.append("    @SuppressWarnings(\"unchecked\")\n");
        code.append("    public List<").append(entity).append("> findAll(int page, int size) {\n");
        code.append("        String path = BASE_PATH + \"?page=\" + page + \"&size=\" + size;\n");
        code.append("        return client.get(path, List.class);\n");
        code.append("    }\n\n");

        // findAll without pagination
        code.append("    /**\n");
        code.append("     * Finds all ").append(entity).append(" entities.\n");
        code.append("     *\n");
        code.append("     * @return list of entities\n");
        code.append("     */\n");
        code.append("    @SuppressWarnings(\"unchecked\")\n");
        code.append("    public List<").append(entity).append("> findAll() {\n");
        code.append("        return client.get(BASE_PATH, List.class);\n");
        code.append("    }\n\n");

        // create
        code.append("    /**\n");
        code.append("     * Creates a new ").append(entity).append(".\n");
        code.append("     *\n");
        code.append("     * @param entity the entity to create\n");
        code.append("     * @return the created entity\n");
        code.append("     */\n");
        code.append("    public ").append(entity).append(" create(").append(entity).append(" entity) {\n");
        code.append("        return client.post(BASE_PATH, entity, ").append(entity).append(".class);\n");
        code.append("    }\n\n");

        // update
        code.append("    /**\n");
        code.append("     * Updates an existing ").append(entity).append(".\n");
        code.append("     *\n");
        code.append("     * @param id the entity ID\n");
        code.append("     * @param entity the entity with updated data\n");
        code.append("     * @return the updated entity\n");
        code.append("     */\n");
        code.append("    public ").append(entity).append(" update(UUID id, ").append(entity).append(" entity) {\n");
        code.append("        return client.patch(BASE_PATH + \"/\" + id, entity, ").append(entity).append(".class);\n");
        code.append("    }\n\n");

        // delete
        code.append("    /**\n");
        code.append("     * Deletes a ").append(entity).append(" by ID.\n");
        code.append("     *\n");
        code.append("     * @param id the entity ID\n");
        code.append("     */\n");
        code.append("    public void delete(UUID id) {\n");
        code.append("        client.delete(BASE_PATH + \"/\" + id, Void.class);\n");
        code.append("    }\n");

        code.append("}\n");

        return new GeneratedFile(packageName, className, code.toString(), ArtifactType.CLIENT);
    }

    private String buildApiPath(DomainMetadata metadata) {
        String entityName = metadata.entityName();
        String kebabName = toKebabCase(entityName);

        // Build from apiVersion + path
        String apiVersion = metadata.apiVersion() != null ? metadata.apiVersion() : "v1";
        String path = metadata.path() != null ? metadata.path() : "/" + kebabName + "s";

        return "/api/" + apiVersion + path;
    }

    private String toKebabCase(String str) {
        return str.replaceAll("([a-z])([A-Z])", "$1-$2").toLowerCase();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.CLIENT;
    }
}
