package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainEventMetadata;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.FieldMetadata;

import javax.lang.model.element.Modifier;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates domain event classes and event publisher for Exeris Kernel.
 *
 * <p>For each {@code @DomainEvent} annotation on the domain entity, generates:
 * <ul>
 *   <li>Event record class (immutable, serializable)</li>
 *   <li>Event publisher (integrates with kernel events module)</li>
 * </ul>
 *
 * <p>Phase 4c of ADR-015: emission is JavaPoet-based via Palantir's fork
 * (records require {@link TypeSpec#recordBuilder(String)}, only present in
 * Palantir 0.15.0+).
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelEventGenerator implements KernelArtifactGenerator {

    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName INSTANT = ClassName.get("java.time", "Instant");
    private static final ClassName HASH_MAP = ClassName.get("java.util", "HashMap");
    private static final ClassName MAP = ClassName.get("java.util", "Map");
    private static final ClassName LIST = ClassName.get("java.util", "List");
    private static final ClassName SLF4J_LOGGER = ClassName.get("org.slf4j", "Logger");
    private static final ClassName SLF4J_LOGGER_FACTORY = ClassName.get("org.slf4j", "LoggerFactory");
    private static final ClassName DOMAIN_EVENT = ClassName.get("eu.exeris.kernel.events.store", "DomainEvent");
    private static final ClassName EVENT_STORE = ClassName.get("eu.exeris.kernel.events.store", "EventStore");
    private static final ClassName OUTBOX_SIGNAL = ClassName.get("eu.exeris.kernel.events.outbox", "OutboxSignal");
    private static final ClassName SECURITY_CONTEXT = ClassName.get("eu.exeris.kernel.security.context", "SecurityContext");
    private static final ClassName TENANT_CONTEXT = ClassName.get("eu.exeris.kernel.security.context", "TenantContext");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        if (!metadata.hasEvents()) {
            return null;
        }

        String packageName = metadata.packageName().replace(".domain", ".event");
        String className = metadata.entityName() + "Events";
        String entity = metadata.entityName();
        ClassName entityType = ClassName.get(metadata.packageName(), entity);
        ClassName selfType = ClassName.get(packageName, className);

        TypeSpec.Builder builder = KernelScaffold.publicClass(className)
                .addModifiers(Modifier.FINAL)
                .addJavadoc("Domain events and publisher for $L.\n", entity)
                .addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addJavadoc("\n")
                .addJavadoc("@see $L\n", metadata.fullyQualifiedName())
                .addField(FieldSpec.builder(SLF4J_LOGGER, "LOG",
                                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$T.getLogger($T.class)", SLF4J_LOGGER_FACTORY, selfType)
                        .build());

        List<FieldMetadata> payloadFields = getPayloadFields(metadata);

        for (DomainEventMetadata event : metadata.events()) {
            builder.addType(buildEventRecord(event, metadata, entityType, payloadFields));
        }

        builder.addType(buildPublisher(metadata, entityType));

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, builder.build()), ArtifactType.EVENT);
    }

    private TypeSpec buildEventRecord(DomainEventMetadata event, DomainMetadata metadata,
                                       ClassName entityType, List<FieldMetadata> payloadFields) {
        String eventName = getEventName(event, metadata);

        MethodSpec.Builder ctor = MethodSpec.constructorBuilder()
                .addParameter(UUID, "eventId")
                .addParameter(INSTANT, "occurredAt")
                .addParameter(UUID, "aggregateId");
        for (FieldMetadata field : payloadFields) {
            if (skipPayloadField(field, metadata)) continue;
            ctor.addParameter(toTypeName(field.type()), field.name());
        }

        ClassName selfRecordType = ClassName.bestGuess(eventName);
        MethodSpec.Builder factory = MethodSpec.methodBuilder("from")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfRecordType)
                .addParameter(entityType, "entity");
        CodeBlock.Builder factoryBody = CodeBlock.builder()
                .add("return new $T(\n", selfRecordType)
                .indent().indent()
                .add("$T.randomUUID(),\n", UUID)
                .add("$T.now(),\n", INSTANT)
                .add("entity.getId()");
        for (FieldMetadata field : payloadFields) {
            if (skipPayloadField(field, metadata)) continue;
            factoryBody.add(",\n").add("entity.$L()", "get" + capitalize(field.name()));
        }
        factoryBody.add("\n").unindent().unindent().add(");\n");
        factory.addCode(factoryBody.build());

        MethodSpec aggregateType = MethodSpec.methodBuilder("aggregateType")
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", metadata.entityName())
                .build();

        MethodSpec eventType = MethodSpec.methodBuilder("eventType")
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", eventName)
                .build();

        TypeSpec.Builder record = TypeSpec.recordBuilder(eventName)
                .addModifiers(Modifier.PUBLIC)
                .recordConstructor(ctor.build())
                .addMethod(factory.build())
                .addMethod(aggregateType)
                .addMethod(eventType);

        if (event.description() != null && !event.description().isBlank()) {
            record.addJavadoc("$L\n", event.description());
        } else {
            record.addJavadoc("Domain event: $L\n", eventName);
        }
        if (event.topic() != null && !event.topic().isBlank()) {
            record.addJavadoc("<p>Topic: {@code $L}\n", event.topic());
        }

        return record.build();
    }

    private TypeSpec buildPublisher(DomainMetadata metadata, ClassName entityType) {
        String entity = metadata.entityName();

        TypeSpec.Builder publisher = TypeSpec.classBuilder("Publisher")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Publisher for $L domain events.\n", entity)
                .addJavadoc("<p>Uses transactional outbox pattern for reliable delivery.\n")
                .addField(FieldSpec.builder(EVENT_STORE, "eventStore", Modifier.PRIVATE, Modifier.FINAL).build())
                .addField(FieldSpec.builder(OUTBOX_SIGNAL, "outboxSignal", Modifier.PRIVATE, Modifier.FINAL).build())
                .addMethod(MethodSpec.constructorBuilder()
                        .addModifiers(Modifier.PUBLIC)
                        .addParameter(EVENT_STORE, "eventStore")
                        .addParameter(OUTBOX_SIGNAL, "outboxSignal")
                        .addStatement("this.eventStore = eventStore")
                        .addStatement("this.outboxSignal = outboxSignal")
                        .build());

        for (DomainEventMetadata event : metadata.events()) {
            publisher.addMethod(buildPublishMethod(event, metadata));
        }

        publisher.addMethod(buildPublishCreatedShortcut(entity, entityType));
        return publisher.build();
    }

    private MethodSpec buildPublishMethod(DomainEventMetadata event, DomainMetadata metadata) {
        String eventName = getEventName(event, metadata);
        String methodName = "publish" + eventName.replace("Event", "");
        ClassName eventClass = ClassName.bestGuess(eventName);
        TypeName mapStringObject = ParameterizedTypeName.get(MAP, ClassName.get(String.class), ClassName.get(Object.class));
        TypeName listOfDomainEvent = ParameterizedTypeName.get(LIST, DOMAIN_EVENT);

        return MethodSpec.methodBuilder(methodName)
                .addJavadoc("Publishes $L to the event store.\n", eventName)
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(eventClass, "event")
                .addStatement("LOG.debug($S, event.eventType(), event.aggregateId())",
                        "Publishing {}: aggregateId={}")
                .addStatement("$T ctx = $T.currentTenant()", TENANT_CONTEXT, SECURITY_CONTEXT)
                .addStatement("$T tenantId = ctx != null ? ctx.tenantId() : null", UUID)
                .addStatement("$T payload = new $T<>()", mapStringObject, HASH_MAP)
                .addStatement("payload.put($S, event.eventType())", "eventType")
                .addStatement("payload.put($S, event.aggregateId().toString())", "aggregateId")
                .addStatement("payload.put($S, event.occurredAt().toString())", "occurredAt")
                .addStatement("long currentVersion = eventStore.getStreamVersion(event.aggregateId(), tenantId)")
                .addCode(CodeBlock.builder()
                        .add("var domainEvent = $T.builder()\n", DOMAIN_EVENT)
                        .add("        .eventId(event.eventId())\n")
                        .add("        .streamId(event.aggregateId())\n")
                        .add("        .aggregateType(event.aggregateType())\n")
                        .add("        .aggregateId(event.aggregateId())\n")
                        .add("        .eventType(event.eventType())\n")
                        .add("        .payload(payload)\n")
                        .add("        .tenantId(tenantId)\n")
                        .add("        .occurredAt(event.occurredAt())\n")
                        .add("        .build();\n")
                        .build())
                .addStatement("eventStore.append(event.aggregateId(), currentVersion, $T.of(domainEvent))", LIST)
                .addStatement("outboxSignal.signalNewData()")
                .build();
    }

    private MethodSpec buildPublishCreatedShortcut(String entity, ClassName entityType) {
        // Mirrors legacy emission: assumes a `<Entity>CreatedEvent` exists.
        // If the entity has no Created event, the resulting reference is a known
        // pre-existing latent bug — preserved here for byte-equivalence.
        ClassName createdEventClass = ClassName.bestGuess(entity + "CreatedEvent");
        return MethodSpec.methodBuilder("publishCreated")
                .addJavadoc("Publishes a created event for the entity.\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(ParameterSpec.builder(entityType, "entity").build())
                .addStatement("publish$LCreated($T.from(entity))", entity, createdEventClass)
                .build();
    }

    private List<FieldMetadata> getPayloadFields(DomainMetadata metadata) {
        if (metadata.fields() == null) {
            return List.of();
        }
        return metadata.fields().stream()
                .filter(f -> !isSystemField(f.name()))
                .filter(f -> f.searchable() || f.required())
                .limit(8)
                .collect(Collectors.toList());
    }

    private boolean skipPayloadField(FieldMetadata field, DomainMetadata metadata) {
        return field.name().equals("tenantId") && metadata.entityName().equals("Tenant");
    }

    private boolean isSystemField(String name) {
        return name.equals("id") || name.equals("createdAt") || name.equals("updatedAt")
                || name.equals("createdBy") || name.equals("updatedBy") || name.equals("version")
                || name.equals("deletedAt") || name.equals("deletedBy");
    }

    private String getEventName(DomainEventMetadata event, DomainMetadata metadata) {
        String eventName = event.name();
        if (eventName == null || eventName.isBlank()) {
            eventName = metadata.entityName() + "Event";
        }
        if (!eventName.endsWith("Event")) {
            eventName = eventName + "Event";
        }
        return eventName;
    }

    private TypeName toTypeName(String type) {
        if (type == null) return ClassName.get(Object.class);
        return switch (type.toLowerCase()) {
            case "string" -> ClassName.get(String.class);
            case "uuid" -> UUID;
            case "int", "integer" -> ClassName.get(Integer.class);
            case "long" -> ClassName.get(Long.class);
            case "boolean" -> ClassName.get(Boolean.class);
            case "instant", "datetime", "timestamp" -> INSTANT;
            case "bigdecimal", "decimal" -> ClassName.get("java.math", "BigDecimal");
            default -> ClassName.bestGuess(type);
        };
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.EVENT;
    }
}
