package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.FieldMetadata;
import eu.exeris.sdk.sourcemodel.ast.RelationshipMetadata;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Kernel Service Generator.
 *
 * <p>Generates a CRUD service class delegating to the corresponding
 * {@code *Repository}. Pure POJO — no direct Kernel API surface and no
 * cross-cutting concerns. Domain-event publishing on lifecycle changes
 * is intentionally out of scope; the {@code *EventPublisher} emitted by
 * {@link KernelEventGenerator} owns that responsibility and is wired
 * separately by the application bootstrap (saga / event-handler /
 * direct callers).
 *
 * @implNote Emission is JavaPoet-based (ADR-015).
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelServiceGenerator implements KernelArtifactGenerator {

    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName OPTIONAL = ClassName.get("java.util", "Optional");
    private static final ClassName LIST = ClassName.get("java.util", "List");
    private static final ClassName BIG_DECIMAL = ClassName.get("java.math", "BigDecimal");
    private static final ClassName INSTANT = ClassName.get("java.time", "Instant");
    private static final ClassName LOCAL_DATE = ClassName.get("java.time", "LocalDate");
    private static final ClassName LOCAL_DATE_TIME = ClassName.get("java.time", "LocalDateTime");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        String packageName = metadata.packageName().replace(".domain", ".service");
        String entity = metadata.entityName();
        String className = entity + "Service";
        String repoName = entity + "Repository";

        ClassName entityType = ClassName.get(metadata.packageName(), entity);
        ClassName repoType = ClassName.get(
                metadata.packageName().replace(".domain", ".repository"), repoName);
        TypeName optionalOfEntity = ParameterizedTypeName.get(OPTIONAL, entityType);
        TypeName listOfEntity = ParameterizedTypeName.get(LIST, entityType);

        TypeSpec.Builder builder = KernelScaffold.publicClass(className)
                .addJavadoc("Service for $L domain operations.\n", entity)
                .addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addField(FieldSpec.builder(repoType, "repository",
                        Modifier.PRIVATE, Modifier.FINAL).build());

        builder.addMethod(buildConstructor(repoType))
                .addMethod(buildFindById(optionalOfEntity))
                .addMethod(buildFindAll(listOfEntity));

        // T8: delegating finders mirroring the repository surface (parity), in
        // the same stable sorted order — filterable fields by name, then
        // MANY_TO_ONE FK finders by relationship name.
        for (MethodSpec finder : buildFinders(metadata, listOfEntity)) {
            builder.addMethod(finder);
        }

        builder.addMethod(buildSave(entityType))
                .addMethod(buildUpdate(entityType))
                .addMethod(buildDelete())
                .addMethod(buildCount());

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, builder.build()), ArtifactType.SERVICE);
    }

    /**
     * T8: delegating finders for filterable fields and MANY_TO_ONE FK columns.
     * Emitted in the same byte-deterministic order as the repository so the two
     * surfaces stay aligned: filterable fields sorted by name, then FK finders
     * sorted by relationship name.
     */
    private List<MethodSpec> buildFinders(DomainMetadata metadata, TypeName listOfEntity) {
        List<MethodSpec> finders = new ArrayList<>();

        metadata.fields().stream()
                .filter(FieldMetadata::filterable)
                .sorted(Comparator.comparing(FieldMetadata::name))
                .forEach(f -> finders.add(buildFindByField(listOfEntity, f)));

        if (metadata.hasRelationships()) {
            metadata.relationships().stream()
                    .filter(r -> r.type() == RelationshipMetadata.RelationType.MANY_TO_ONE)
                    .sorted(Comparator.comparing(RelationshipMetadata::name))
                    .forEach(r -> finders.add(buildFindByForeignKey(listOfEntity, r)));
        }
        return finders;
    }

    private MethodSpec buildFindByField(TypeName listOfEntity, FieldMetadata field) {
        String name = "findBy" + capitalize(field.name());
        return MethodSpec.methodBuilder(name)
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfEntity)
                .addParameter(typeNameOf(field.type()), field.name())
                .addStatement("return repository.$L($L)", name, field.name())
                .build();
    }

    private MethodSpec buildFindByForeignKey(TypeName listOfEntity, RelationshipMetadata rel) {
        String paramName = foreignKeyBase(rel.name()) + "Id";
        String name = "findBy" + capitalize(foreignKeyBase(rel.name())) + "Id";
        return MethodSpec.methodBuilder(name)
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfEntity)
                .addParameter(UUID, paramName)
                .addStatement("return repository.$L($L)", name, paramName)
                .build();
    }

    private MethodSpec buildConstructor(ClassName repoType) {
        return MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(repoType, "repository")
                .addStatement("this.repository = repository")
                .build();
    }

    private MethodSpec buildFindById(TypeName optionalOfEntity) {
        return MethodSpec.methodBuilder("findById")
                .addModifiers(Modifier.PUBLIC)
                .returns(optionalOfEntity)
                .addParameter(UUID, "id")
                .addStatement("return repository.findById(id)")
                .build();
    }

    private MethodSpec buildFindAll(TypeName listOfEntity) {
        return MethodSpec.methodBuilder("findAll")
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfEntity)
                .addStatement("return repository.findAll()")
                .build();
    }

    private MethodSpec buildSave(ClassName entityType) {
        return MethodSpec.methodBuilder("save")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(entityType, "entity")
                .addStatement("$T saved = repository.save(entity)", entityType)
                .addStatement("return saved")
                .build();
    }

    private MethodSpec buildUpdate(ClassName entityType) {
        return MethodSpec.methodBuilder("update")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(UUID, "id")
                .addParameter(entityType, "entity")
                .addStatement("$T updated = repository.update(id, entity)", entityType)
                .addStatement("return updated")
                .build();
    }

    private MethodSpec buildDelete() {
        return MethodSpec.methodBuilder("delete")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(UUID, "id")
                .addStatement("repository.deleteById(id)")
                .build();
    }

    private MethodSpec buildCount() {
        return MethodSpec.methodBuilder("count")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.LONG)
                .addStatement("return repository.count()")
                .build();
    }

    /**
     * Maps a field type string to a JavaPoet parameter {@link TypeName} — must
     * stay in lock-step with {@code KernelRepositoryGenerator.typeNameOf} so the
     * delegating service signature matches the repository method it calls.
     */
    private static TypeName typeNameOf(String type) {
        return switch (type) {
            case "boolean" -> TypeName.BOOLEAN;
            case "int" -> TypeName.INT;
            case "long" -> TypeName.LONG;
            case "double" -> TypeName.DOUBLE;
            case "BigDecimal" -> BIG_DECIMAL;
            case "Instant" -> INSTANT;
            case "LocalDate" -> LOCAL_DATE;
            case "LocalDateTime" -> LOCAL_DATE_TIME;
            default -> {
                int lt = type.indexOf('<');
                yield ClassName.bestGuess(lt >= 0 ? type.substring(0, lt) : type);
            }
        };
    }

    /**
     * Base name for a FK finder, stripping a trailing {@code Id} so the
     * explicit-UUID-FK style ({@code customerId}) and the entity-typed style
     * ({@code customer}) both reduce to {@code customer} — identical to
     * {@code KernelRepositoryGenerator.foreignKeyBase}.
     */
    private static String foreignKeyBase(String relationshipName) {
        if (relationshipName.length() > 2 && relationshipName.endsWith("Id")) {
            return relationshipName.substring(0, relationshipName.length() - 2);
        }
        return relationshipName;
    }

    private static String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.SERVICE;
    }
}
