package eu.exeris.tooling.codegen.java.kernel;

import eu.exeris.tooling.codegen.core.generator.BackendGenerator;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.SagaMetadata;
import eu.exeris.sdk.sourcemodel.ast.SagaStepMetadata;

import java.util.List;

/**
 * Generates saga orchestration classes for Exeris Kernel.
 *
 * <p>For entities annotated with {@code @Saga}, generates:
 * <ul>
 *   <li>Saga definition class (steps, compensation, timeouts)</li>
 *   <li>Saga state class (immutable record for saga state)</li>
 *   <li>Saga executor (registers with SagaEngine)</li>
 * </ul>
 *
 * <p>Integrates with {@code eu.exeris.kernel.flow.SagaEngine} for
 * distributed saga orchestration with compensation support.
 *
 * @author Exeris Team
 * @since 0.1.0
 * @see eu.exeris.kernel.flow.SagaEngine
 */
public class KernelSagaGenerator implements BackendGenerator {

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        if (!metadata.isSaga()) {
            return null; // No saga metadata - skip
        }

        SagaMetadata saga = metadata.sagaMetadata();
        String packageName = metadata.packageName().replace(".domain", ".saga");
        String sagaName = saga.name() != null ? saga.name() : metadata.entityName() + "Saga";
        String className = sagaName;
        String entity = metadata.entityName();
        String lowerEntity = entity.substring(0, 1).toLowerCase() + entity.substring(1);

        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");

        // Imports
        code.append("import ").append(metadata.packageName()).append(".").append(entity).append(";\n");
        code.append("import ").append(metadata.packageName().replace(".domain", ".repository")).append(".").append(entity).append("Repository;\n");
        code.append("import eu.exeris.kernel.flow.SagaEngine;\n");
        code.append("import eu.exeris.kernel.flow.SagaBuilder;\n");
        code.append("import eu.exeris.kernel.flow.model.SagaDefinition;\n");
        code.append("import eu.exeris.kernel.flow.model.SagaStep;\n");
        code.append("import eu.exeris.kernel.flow.model.StepAction;\n");
        code.append("import eu.exeris.kernel.flow.model.StepResult;\n");
        code.append("import eu.exeris.kernel.flow.model.SagaSnapshot;\n");
        code.append("import eu.exeris.kernel.events.store.EventStore;\n");
        code.append("import org.slf4j.Logger;\n");
        code.append("import org.slf4j.LoggerFactory;\n");
        code.append("import tools.jackson.databind.ObjectMapper;\n");
        code.append("import tools.jackson.databind.json.JsonMapper;\n");
        code.append("import tools.jackson.databind.JsonNode;\n\n");
        code.append("import java.time.Duration;\n");
        code.append("import java.time.Instant;\n");
        code.append("import java.util.Map;\n");
        code.append("import java.util.UUID;\n");
        code.append("import java.util.Optional;\n");
        code.append("import java.util.function.Function;\n\n");

        // Class header
        code.append("/**\n");
        code.append(" * Saga orchestration for ").append(entity).append(".\n");
        if (saga.description() != null && !saga.description().isBlank()) {
            code.append(" * <p>").append(saga.description()).append("\n");
        }
        code.append(" *\n");
        code.append(" * <p>Timeout: ").append(saga.timeout() != null ? saga.timeout() : "PT30M").append("\n");
        code.append(" * <p>Max retries: ").append(saga.maxRetries()).append("\n");
        code.append(" * <p>Compensation: ").append(saga.compensationStrategy()).append("\n");
        code.append(" * <p>Generated by Exeris Codegen. DO NOT EDIT.\n");
        code.append(" *\n");
        code.append(" * @see ").append(metadata.fullyQualifiedName()).append("\n");
        code.append(" * @see SagaEngine\n");
        code.append(" */\n");
        code.append("public class ").append(className).append(" {\n\n");

        code.append("    private static final Logger LOG = LoggerFactory.getLogger(").append(className).append(".class);\n");
        code.append("    private static final String SAGA_NAME = \"").append(sagaName).append("\";\n");
        code.append("    private static final ObjectMapper MAPPER = JsonMapper.builder().build();\n");

        // Parse timeout
        String timeout = saga.timeout() != null ? saga.timeout() : "PT30M";
        code.append("    private static final Duration TIMEOUT = Duration.parse(\"").append(timeout).append("\");\n\n");

        // Dependencies
        code.append("    private final SagaEngine sagaEngine;\n");
        code.append("    private final EventStore eventStore;\n");
        code.append("    private final ").append(entity).append("Repository repository;\n\n");

        // Constructor
        code.append("    public ").append(className).append("(SagaEngine sagaEngine, EventStore eventStore, ").append(entity).append("Repository repository) {\n");
        code.append("        this.sagaEngine = sagaEngine;\n");
        code.append("        this.eventStore = eventStore;\n");
        code.append("        this.repository = repository;\n");
        code.append("        registerSaga();\n");
        code.append("    }\n\n");

        // Generate State record
        generateStateRecord(code, saga, entity);

        // Generate saga definition
        generateSagaDefinition(code, saga, entity);

        // Generate step handlers
        generateStepHandlers(code, saga, entity);

        // Generate compensation handlers
        generateCompensationHandlers(code, saga, entity);

        // Generate start method
        generateStartMethod(code, saga, entity);

        code.append("}\n");

        return new GeneratedFile(packageName, className, code.toString(), ArtifactType.SAGA);
    }

    private void generateStateRecord(StringBuilder code, SagaMetadata saga, String entity) {
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Saga State\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Immutable saga state record.\n");
        code.append("     * <p>Persisted to saga store for recovery.\n");
        code.append("     */\n");
        code.append("    public record State(\n");
        code.append("            UUID sagaId,\n");
        code.append("            UUID entityId,\n");
        code.append("            UUID tenantId,\n");
        code.append("            String currentStep,\n");
        code.append("            Instant startedAt,\n");
        code.append("            Map<String, Object> stepData\n");
        code.append("    ) {\n");
        code.append("        public static State initial(UUID entityId, UUID tenantId) {\n");
        code.append("            return new State(\n");
        code.append("                    UUID.randomUUID(),\n");
        code.append("                    entityId,\n");
        code.append("                    tenantId,\n");
        code.append("                    \"start\",\n");
        code.append("                    Instant.now(),\n");
        code.append("                    Map.of()\n");
        code.append("            );\n");
        code.append("        }\n\n");
        code.append("        public State withStep(String step) {\n");
        code.append("            return new State(sagaId, entityId, tenantId, step, startedAt, stepData);\n");
        code.append("        }\n\n");
        code.append("        public State withData(String key, Object value) {\n");
        code.append("            var newData = new java.util.HashMap<>(stepData);\n");
        code.append("            newData.put(key, value);\n");
        code.append("            return new State(sagaId, entityId, tenantId, currentStep, startedAt, Map.copyOf(newData));\n");
        code.append("        }\n");
        code.append("    }\n\n");
    }

    private void generateSagaDefinition(StringBuilder code, SagaMetadata saga, String entity) {
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Saga Definition\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Registers saga definition with the engine.\n");
        code.append("     */\n");
        code.append("    private void registerSaga() {\n");
        code.append("        LOG.info(\"Registering saga: {}\", SAGA_NAME);\n\n");

        code.append("        var definition = SagaBuilder.create(SAGA_NAME)\n");
        code.append("                .timeout(TIMEOUT)\n");
        code.append("                .maxRetries(").append(saga.maxRetries()).append(")\n");

        // Get steps - either from annotation or generate entity-specific defaults
        List<SagaStepMetadata> steps = saga.hasSteps() ? saga.steps() : getEntityDefaultSteps(entity);

        for (SagaStepMetadata step : steps) {
            String stepName = step.name();
            code.append("                .step(\"").append(stepName).append("\")\n");
            code.append("                    .action(this::execute").append(capitalize(stepName)).append(")\n");
            code.append("                    .compensation(this::compensate").append(capitalize(stepName)).append(")\n");
            code.append("                    .timeout(Duration.parse(\"").append(step.timeout() != null ? step.timeout() : "PT1M").append("\"))\n");
            if (step.maxRetries() > 0) {
                code.append("                    .retries(").append(step.maxRetries()).append(")\n");
            }
            code.append("                .and()\n");
        }

        code.append("                .build();\n\n");
        code.append("        sagaEngine.register(definition);\n");
        code.append("    }\n\n");
    }

    private void generateStepHandlers(StringBuilder code, SagaMetadata saga, String entity) {
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Step Handlers\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        List<SagaStepMetadata> steps = saga.hasSteps() ? saga.steps() : getEntityDefaultSteps(entity);

        for (SagaStepMetadata step : steps) {
            String stepName = step.name();
            String methodName = "execute" + capitalize(stepName);

            code.append("    /**\n");
            code.append("     * Executes step: ").append(stepName).append("\n");
            if (step.description() != null && !step.description().isBlank()) {
                code.append("     * <p>").append(step.description()).append("\n");
            }
            code.append("     */\n");
            code.append("    private StepResult ").append(methodName).append("(SagaSnapshot snapshot) {\n");
            code.append("        LOG.debug(\"Executing step '{}' for saga: {}\", \"").append(stepName).append("\", snapshot.sagaIdMost());\n\n");

            code.append("        try {\n");

            // Generate step-specific logic based on step name pattern
            generateStepLogic(code, stepName, entity, step);

            code.append("            return StepResult.CONTINUE;\n");
            code.append("        } catch (Exception e) {\n");
            code.append("            LOG.error(\"Step '{}' failed for saga\", \"").append(stepName).append("\", e);\n");
            code.append("            return StepResult.FAIL;\n");
            code.append("        }\n");
            code.append("    }\n\n");
        }
    }

    private void generateStepLogic(StringBuilder code, String stepName, String entity, SagaStepMetadata step) {
        String lowerStep = stepName.toLowerCase();

        if (lowerStep.contains("validate")) {
            code.append("            // Extract and validate entity\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            if (entityId == null) {\n");
            code.append("                throw new IllegalArgumentException(\"Entity ID is required\");\n");
            code.append("            }\n\n");
            code.append("            // Verify entity exists\n");
            code.append("            Optional<").append(entity).append("> entity = repository.findById(entityId);\n");
            code.append("            if (entity.isEmpty()) {\n");
            code.append("                throw new IllegalStateException(\"").append(entity).append(" not found: \" + entityId);\n");
            code.append("            }\n");
            code.append("            LOG.info(\"Validated ").append(entity.toLowerCase()).append(": {}\", entityId);\n\n");
        } else if (lowerStep.contains("execute") || lowerStep.contains("logic") || lowerStep.contains("process")) {
            code.append("            // Load entity and execute business logic\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            ").append(entity).append(" entity = repository.findById(entityId)\n");
            code.append("                    .orElseThrow(() -> new IllegalStateException(\"").append(entity).append(" not found: \" + entityId));\n\n");
            code.append("            // Execute domain-specific business logic\n");
            code.append("            LOG.info(\"Executing business logic for ").append(entity.toLowerCase()).append(": {}\", entityId);\n");
            code.append("            // entity.activate(); // Example: activate the entity\n");
            code.append("            // entity.setStatus(Status.PROCESSING);\n\n");
        } else if (lowerStep.contains("persist") || lowerStep.contains("save")) {
            code.append("            // Persist entity changes\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            ").append(entity).append(" entity = repository.findById(entityId)\n");
            code.append("                    .orElseThrow(() -> new IllegalStateException(\"").append(entity).append(" not found: \" + entityId));\n\n");
            code.append("            // Save updated entity\n");
            code.append("            repository.save(entity);\n");
            code.append("            LOG.info(\"Persisted ").append(entity.toLowerCase()).append(": {}\", entityId);\n\n");
        } else if (lowerStep.contains("notify") || lowerStep.contains("email") || lowerStep.contains("welcome")) {
            code.append("            // Send completion notification\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            LOG.info(\"Sending notification for ").append(entity.toLowerCase()).append(": {}\", entityId);\n\n");
            code.append("            // Notification logic - fire and forget, failures should not rollback saga\n");
            code.append("            // notificationService.sendWelcomeEmail(entityId);\n\n");
        } else if (lowerStep.contains("provision") || lowerStep.contains("schema")) {
            code.append("            // Provision resources\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            UUID tenantId = getContextUUID(snapshot, \"tenantId\");\n");
            code.append("            LOG.info(\"Provisioning resources for ").append(entity.toLowerCase()).append(": {} in tenant: {}\", entityId, tenantId);\n\n");
            code.append("            // Resource provisioning logic\n");
            code.append("            // schemaService.provision(tenantId);\n\n");
        } else {
            // Generic step
            code.append("            // Execute step: ").append(stepName).append("\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            LOG.info(\"Executing step '").append(stepName).append("' for ").append(entity.toLowerCase()).append(": {}\", entityId);\n\n");
        }
    }

    private void generateCompensationHandlers(StringBuilder code, SagaMetadata saga, String entity) {
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Compensation Handlers\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        List<SagaStepMetadata> steps = saga.hasSteps() ? saga.steps() : getEntityDefaultSteps(entity);

        for (SagaStepMetadata step : steps) {
            String stepName = step.name();
            String methodName = "compensate" + capitalize(stepName);

            code.append("    /**\n");
            code.append("     * Compensates step: ").append(stepName).append("\n");
            code.append("     * <p>Called on saga failure to rollback this step.\n");
            code.append("     */\n");
            code.append("    private StepResult ").append(methodName).append("(SagaSnapshot snapshot) {\n");
            code.append("        LOG.warn(\"Compensating step '{}' for saga\", \"").append(stepName).append("\");\n\n");

            code.append("        try {\n");

            // Generate compensation logic based on step type
            generateCompensationLogic(code, stepName, entity, step);

            code.append("            return StepResult.CONTINUE;\n");
            code.append("        } catch (Exception e) {\n");
            code.append("            LOG.error(\"Compensation '{}' failed\", \"").append(stepName).append("\", e);\n");
            code.append("            return StepResult.FAIL;\n");
            code.append("        }\n");
            code.append("    }\n\n");
        }
    }

    private void generateCompensationLogic(StringBuilder code, String stepName, String entity, SagaStepMetadata step) {
        String lowerStep = stepName.toLowerCase();

        if (lowerStep.contains("validate")) {
            code.append("            // Validation has no side effects - nothing to compensate\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            LOG.info(\"Validation compensation (no-op) for ").append(entity.toLowerCase()).append(": {}\", entityId);\n\n");
        } else if (lowerStep.contains("execute") || lowerStep.contains("logic") || lowerStep.contains("process")) {
            code.append("            // Rollback business logic changes\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            ").append(entity).append(" entity = repository.findById(entityId).orElse(null);\n");
            code.append("            if (entity != null) {\n");
            code.append("                // Revert entity to previous state\n");
            code.append("                // entity.setStatus(Status.PENDING);\n");
            code.append("                repository.save(entity);\n");
            code.append("                LOG.info(\"Rolled back business logic for ").append(entity.toLowerCase()).append(": {}\", entityId);\n");
            code.append("            }\n\n");
        } else if (lowerStep.contains("persist") || lowerStep.contains("save")) {
            code.append("            // Delete the persisted entity (hard delete on saga failure)\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            if (entityId != null) {\n");
            code.append("                repository.deleteById(entityId);\n");
            code.append("                LOG.info(\"Deleted ").append(entity.toLowerCase()).append(" on compensation: {}\", entityId);\n");
            code.append("            }\n\n");
        } else if (lowerStep.contains("notify") || lowerStep.contains("email") || lowerStep.contains("welcome")) {
            code.append("            // Notifications cannot be recalled - log compensation event\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            LOG.warn(\"Notification was sent for ").append(entity.toLowerCase()).append(": {} - cannot be undone\", entityId);\n");
            code.append("            // Optionally publish a compensation event for audit\n");
            code.append("            // eventStore.append(entityId, new NotificationCompensationEvent(entityId));\n\n");
        } else if (lowerStep.contains("provision") || lowerStep.contains("schema")) {
            code.append("            // Rollback provisioned resources\n");
            code.append("            UUID tenantId = getContextUUID(snapshot, \"tenantId\");\n");
            code.append("            if (tenantId != null) {\n");
            code.append("                LOG.info(\"Rolling back provisioning for tenant: {}\", tenantId);\n");
            code.append("                // schemaService.deprovision(tenantId);\n");
            code.append("            }\n\n");
        } else {
            // Generic compensation
            code.append("            // Generic compensation for step: ").append(stepName).append("\n");
            code.append("            UUID entityId = getContextUUID(snapshot, \"entityId\");\n");
            code.append("            LOG.info(\"Compensating step '").append(stepName).append("' for ").append(entity.toLowerCase()).append(": {}\", entityId);\n\n");
        }
    }

    private void generateStartMethod(StringBuilder code, SagaMetadata saga, String entity) {
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Public API\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Starts a new saga instance.\n");
        code.append("     *\n");
        code.append("     * @param entityId the entity ID triggering this saga\n");
        code.append("     * @param tenantId the tenant context\n");
        code.append("     * @return saga execution ID\n");
        code.append("     */\n");
        code.append("    public UUID start(UUID entityId, UUID tenantId) {\n");
        code.append("        LOG.info(\"Starting saga '{}' for entity: {}\", SAGA_NAME, entityId);\n\n");

        code.append("        State initialState = State.initial(entityId, tenantId);\n\n");

        code.append("        return sagaEngine.start(\n");
        code.append("                SAGA_NAME,\n");
        code.append("                initialState.sagaId(),\n");
        code.append("                Map.of(\n");
        code.append("                        \"entityId\", entityId.toString(),\n");
        code.append("                        \"tenantId\", tenantId.toString(),\n");
        code.append("                        \"startedAt\", initialState.startedAt().toString()\n");
        code.append("                )\n");
        code.append("        );\n");
        code.append("    }\n\n");

        code.append("    /**\n");
        code.append("     * Starts saga from an entity.\n");
        code.append("     */\n");
        code.append("    public UUID start(").append(entity).append(" entity) {\n");
        // For Tenant entity, there's no getTenantId() - the entity IS the tenant
        if (entity.equals("Tenant")) {
            code.append("        return start(entity.getId(), entity.getId());\n");
        } else {
            code.append("        return start(entity.getId(), entity.getTenantId());\n");
        }
        code.append("    }\n\n");

        code.append("    /**\n");
        code.append("     * Gets saga status.\n");
        code.append("     */\n");
        code.append("    public SagaSnapshot getStatus(UUID sagaId) {\n");
        code.append("        return sagaEngine.getSnapshot(sagaId).orElse(null);\n");
        code.append("    }\n\n");

        // Generate helper methods
        generateHelperMethods(code);
    }

    private void generateHelperMethods(StringBuilder code) {
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Helper Methods\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Extracts a string value from the saga context (JSON stored in opaqueState).\n");
        code.append("     */\n");
        code.append("    private String getContextValue(SagaSnapshot snapshot, String key) {\n");
        code.append("        byte[] opaqueState = snapshot.opaqueState();\n");
        code.append("        if (opaqueState == null || opaqueState.length == 0) {\n");
        code.append("            return null;\n");
        code.append("        }\n");
        code.append("        try {\n");
        code.append("            JsonNode root = MAPPER.readTree(opaqueState);\n");
        code.append("            JsonNode node = root.get(key);\n");
        code.append("            return node != null && !node.isNull() ? node.asText() : null;\n");
        code.append("        } catch (Exception e) {\n");
        code.append("            LOG.warn(\"Failed to parse context value '{}': {}\", key, e.getMessage());\n");
        code.append("            return null;\n");
        code.append("        }\n");
        code.append("    }\n\n");

        code.append("    /**\n");
        code.append("     * Extracts a UUID value from the saga context.\n");
        code.append("     */\n");
        code.append("    private UUID getContextUUID(SagaSnapshot snapshot, String key) {\n");
        code.append("        String value = getContextValue(snapshot, key);\n");
        code.append("        if (value == null || value.isBlank()) {\n");
        code.append("            return null;\n");
        code.append("        }\n");
        code.append("        try {\n");
        code.append("            return UUID.fromString(value);\n");
        code.append("        } catch (IllegalArgumentException e) {\n");
        code.append("            LOG.warn(\"Invalid UUID in context '{}': {}\", key, value);\n");
        code.append("            return null;\n");
        code.append("        }\n");
        code.append("    }\n");
    }

    /**
     * Generates default saga steps for an entity when no @SagaStep methods are defined.
     *
     * <p>These are generic template steps that the developer MUST implement.
     * The steps follow a standard saga pattern:
     * <ol>
     *   <li>validate - Validate input and preconditions</li>
     *   <li>execute - Execute the main business logic</li>
     *   <li>persist - Persist changes to the database</li>
     *   <li>notify - Send notifications/events</li>
     * </ol>
     *
     * @param entity the entity name (used in step descriptions)
     * @return list of default saga steps
     */
    private List<SagaStepMetadata> getEntityDefaultSteps(String entity) {
        return List.of(
                SagaStepMetadata.builder("validate" + entity, 0)
                        .description("Validate " + entity + " input and preconditions")
                        .command("Validate" + entity + "Command")
                        .compensation("Revert" + entity + "ValidationCommand")
                        .timeout("PT30S")
                        .build(),
                SagaStepMetadata.builder("execute" + entity + "Logic", 1)
                        .description("Execute main " + entity + " business logic")
                        .command("Execute" + entity + "Command")
                        .compensation("Rollback" + entity + "Command")
                        .timeout("PT2M")
                        .build(),
                SagaStepMetadata.builder("persist" + entity, 2)
                        .description("Persist " + entity + " changes to database")
                        .command("Persist" + entity + "Command")
                        .compensation("Delete" + entity + "Command")
                        .timeout("PT1M")
                        .build(),
                SagaStepMetadata.builder("notify" + entity + "Complete", 3)
                        .description("Send " + entity + " completion notifications")
                        .command("Notify" + entity + "Command")
                        .compensation("LogNotificationSkipped")
                        .timeout("PT30S")
                        .build()
        );
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String uncapitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.SAGA;
    }
}

