package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.FieldMetadata;
import eu.exeris.sdk.sourcemodel.ast.GraphMetadata;
import eu.exeris.sdk.sourcemodel.ast.GraphEdgeMetadata;

import javax.lang.model.element.Modifier;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates graph synchronization service for Exeris Kernel.
 *
 * <p>For entities annotated with {@code @Graph}, generates a class that
 * maintains consistency between SQL table and graph representation, mapping
 * entity fields to graph properties and relationships to graph edges.
 *
 * <p>Phase 4 of ADR-015: emission is JavaPoet-based.
 *
 * @author Exeris Team
 * @since 0.1.0
 * @see eu.exeris.kernel.graph.sync.GraphSyncService
 */
public class KernelGraphSyncGenerator implements KernelArtifactGenerator {

    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName MAP = ClassName.get("java.util", "Map");
    private static final ClassName HASH_MAP = ClassName.get("java.util", "HashMap");
    private static final ClassName GRAPH_SERVICE = ClassName.get("eu.exeris.kernel.graph", "GraphService");
    private static final ClassName GRAPH_NODE_METADATA =
            ClassName.get("eu.exeris.kernel.graph.model", "GraphNodeMetadata");
    private static final ClassName GRAPH_SESSION = ClassName.get("eu.exeris.kernel.graph.spi", "GraphSession");
    private static final ClassName SLF4J_LOGGER = ClassName.get("org.slf4j", "Logger");
    private static final ClassName SLF4J_LOGGER_FACTORY = ClassName.get("org.slf4j", "LoggerFactory");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        if (!metadata.hasGraphMetadata()) {
            return null;
        }

        GraphMetadata graph = metadata.graphMetadata();
        String packageName = metadata.packageName().replace(".domain", ".graph");
        String entity = metadata.entityName();
        String className = entity + "GraphSync";
        String nodeLabel = graph.label() != null ? graph.label() : entity;
        boolean hasEdges = graph.edges() != null && !graph.edges().isEmpty();

        ClassName entityType = ClassName.get(metadata.packageName(), entity);
        ClassName selfType = ClassName.get(packageName, className);
        TypeName mapStringObject = ParameterizedTypeName.get(MAP,
                ClassName.get(String.class), ClassName.get(Object.class));

        TypeSpec.Builder builder = KernelScaffold.publicClass(className)
                .addJavadoc("Graph synchronization for $L entities.\n", entity)
                .addJavadoc("<p>Maintains consistency between SQL table and graph representation.\n")
                .addJavadoc("\n")
                .addJavadoc("<p>Node label: {@code $L}\n", nodeLabel)
                .addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addJavadoc("\n")
                .addJavadoc("@see $L\n", metadata.fullyQualifiedName())
                .addJavadoc("@see $T\n", ClassName.get("eu.exeris.kernel.graph.sync", "GraphSyncService"))
                .addField(FieldSpec.builder(SLF4J_LOGGER, "LOG",
                                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$T.getLogger($T.class)", SLF4J_LOGGER_FACTORY, selfType)
                        .build())
                .addField(FieldSpec.builder(String.class, "NODE_LABEL",
                                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$S", nodeLabel)
                        .build())
                .addField(FieldSpec.builder(GRAPH_SERVICE, "graphService",
                        Modifier.PRIVATE, Modifier.FINAL).build())
                .addMethod(MethodSpec.constructorBuilder()
                        .addModifiers(Modifier.PUBLIC)
                        .addParameter(GRAPH_SERVICE, "graphService")
                        .addStatement("this.graphService = graphService")
                        .build())
                .addMethod(buildSyncToGraph(entity, entityType, hasEdges))
                .addMethod(buildDeleteFromGraph());

        if (hasEdges) {
            builder.addMethod(buildSyncEdges(entityType, graph));
        }

        builder.addMethod(buildBuildNodeProperties(entity, entityType, mapStringObject, metadata, graph))
                .addMethod(buildNodeMetadata(metadata, graph));

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, builder.build()), ArtifactType.GRAPH_SYNC);
    }

    private MethodSpec buildSyncToGraph(String entity, ClassName entityType, boolean hasEdges) {
        MethodSpec.Builder sync = MethodSpec.methodBuilder("syncToGraph")
                .addJavadoc("Synchronizes entity to graph as a node.\n")
                .addJavadoc("Creates node if not exists, updates properties if exists.\n")
                .addJavadoc("\n")
                .addJavadoc("@param entity the entity to sync\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(entityType, "entity")
                .addStatement("LOG.debug($S, NODE_LABEL, entity.getId())",
                        "Syncing {} to graph: id={}")
                .beginControlFlow("try (var session = graphService.openSession())")
                .addStatement("$T<String, Object> properties = buildNodeProperties(entity)", MAP)
                .addCode(CodeBlock.builder()
                        .add("session.upsertNode(\n")
                        .indent()
                        .add("NODE_LABEL,\n")
                        .add("entity.getId().toString(),\n")
                        .add("properties\n")
                        .unindent()
                        .addStatement(")")
                        .build());
        if (hasEdges) {
            sync.addStatement("syncEdges(session, entity)");
        }
        return sync.addStatement("LOG.debug($S, entity.getId())", "Successfully synced {} to graph")
                .nextControlFlow("catch (Exception e)")
                .addStatement("LOG.error($S, NODE_LABEL, entity.getId(), e)",
                        "Failed to sync {} to graph: id={}")
                .addStatement("throw new RuntimeException($S, e)", "Graph sync failed")
                .endControlFlow()
                .build();
    }

    private MethodSpec buildDeleteFromGraph() {
        return MethodSpec.methodBuilder("deleteFromGraph")
                .addJavadoc("Removes entity from graph (deletes node and connected edges).\n")
                .addJavadoc("\n")
                .addJavadoc("@param entityId the entity ID to remove\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(UUID, "entityId")
                .addStatement("LOG.debug($S, NODE_LABEL, entityId)",
                        "Deleting {} from graph: id={}")
                .beginControlFlow("try (var session = graphService.openSession())")
                .addStatement("session.deleteNode(NODE_LABEL, entityId.toString())")
                .addStatement("LOG.debug($S, entityId)", "Successfully deleted {} from graph")
                .nextControlFlow("catch (Exception e)")
                .addStatement("LOG.error($S, NODE_LABEL, entityId, e)",
                        "Failed to delete {} from graph: id={}")
                .addStatement("throw new RuntimeException($S, e)", "Graph delete failed")
                .endControlFlow()
                .build();
    }

    private MethodSpec buildSyncEdges(ClassName entityType, GraphMetadata graph) {
        MethodSpec.Builder sync = MethodSpec.methodBuilder("syncEdges")
                .addJavadoc("Synchronizes edges for the entity.\n")
                .addModifiers(Modifier.PRIVATE)
                .returns(TypeName.VOID)
                .addParameter(GRAPH_SESSION, "session")
                .addParameter(entityType, "entity");

        for (GraphEdgeMetadata edge : graph.edges()) {
            String edgeType = edge.relationType() != null ? edge.relationType() : "RELATES_TO";
            String edgeName = edge.name();
            String targetLabel = edge.targetLabel() != null ? edge.targetLabel() : "Node";
            String capName = capitalize(edgeName);

            sync.addCode("// Edge: $L ($L)\n", edgeType, edgeName);
            sync.beginControlFlow("if (entity.get$L() != null)", capName);
            sync.addCode(CodeBlock.builder()
                    .add("session.upsertEdge(\n")
                    .indent()
                    .add("NODE_LABEL,\n")
                    .add("entity.getId().toString(),\n")
                    .add("$S,\n", edgeType)
                    .add("$S,\n", targetLabel)
                    .add("entity.get$L().toString(),\n", capName)
                    .add("$T.of()\n", MAP)
                    .unindent()
                    .addStatement(")")
                    .build());
            sync.endControlFlow();
        }
        return sync.build();
    }

    private MethodSpec buildBuildNodeProperties(String entity, ClassName entityType, TypeName mapStringObject,
                                                DomainMetadata metadata, GraphMetadata graph) {
        MethodSpec.Builder build = MethodSpec.methodBuilder("buildNodeProperties")
                .addJavadoc("Builds node properties from entity.\n")
                .addModifiers(Modifier.PRIVATE)
                .returns(mapStringObject)
                .addParameter(entityType, "entity")
                .addStatement("$T<String, Object> props = new $T<>()", MAP, HASH_MAP);

        List<FieldMetadata> graphFields = getGraphFields(metadata, graph);
        for (FieldMetadata field : graphFields) {
            String getter = "get" + capitalize(field.name()) + "()";
            String propName = toSnakeCase(field.name());

            build.beginControlFlow("if (entity.$L != null)", getter);
            if (isTemporalType(field.type()) || field.type().equalsIgnoreCase("uuid")) {
                build.addStatement("props.put($S, entity.$L.toString())", propName, getter);
            } else {
                build.addStatement("props.put($S, entity.$L)", propName, getter);
            }
            build.endControlFlow();
        }
        return build.addStatement("return props").build();
    }

    private MethodSpec buildNodeMetadata(DomainMetadata metadata, GraphMetadata graph) {
        String nodeLabel = graph.label() != null ? graph.label() : metadata.entityName();

        CodeBlock.Builder body = CodeBlock.builder()
                .add("return $T.builder()\n", GRAPH_NODE_METADATA)
                .indent()
                .add(".nodeLabel($S)\n", nodeLabel);

        List<FieldMetadata> graphFields = getGraphFields(metadata, graph);
        for (FieldMetadata field : graphFields) {
            if (field.indexed() || field.name().equals("id")) {
                body.add(".property($S, true)\n", toSnakeCase(field.name()));
            }
        }
        body.addStatement(".build()").unindent();

        return MethodSpec.methodBuilder("nodeMetadata")
                .addJavadoc("Returns node metadata for schema initialization.\n")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(GRAPH_NODE_METADATA)
                .addCode(body.build())
                .build();
    }

    private List<FieldMetadata> getGraphFields(DomainMetadata metadata, GraphMetadata graph) {
        if (metadata.fields() == null) {
            return List.of();
        }
        if (graph.properties() != null && !graph.properties().isEmpty()) {
            List<String> propNames = graph.properties().stream()
                    .map(p -> p.name())
                    .collect(Collectors.toList());
            return metadata.fields().stream()
                    .filter(f -> propNames.contains(f.name()))
                    .collect(Collectors.toList());
        }
        return metadata.fields().stream()
                .filter(f -> f.searchable() || f.indexed() || f.sortable())
                .filter(f -> !isSystemField(f.name()))
                .collect(Collectors.toList());
    }

    private boolean isSystemField(String name) {
        return name.equals("createdAt") || name.equals("updatedAt")
                || name.equals("createdBy") || name.equals("updatedBy")
                || name.equals("deletedAt") || name.equals("deletedBy") || name.equals("version");
    }

    private boolean isTemporalType(String type) {
        if (type == null) return false;
        String lower = type.toLowerCase();
        return lower.equals("instant") || lower.equals("datetime") || lower.equals("timestamp")
                || lower.equals("localdate") || lower.equals("localdatetime");
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String toSnakeCase(String s) {
        if (s == null || s.isBlank()) return "";
        return s.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.GRAPH_SYNC;
    }
}
