package eu.exeris.tooling.codegen.java.kernel;

import eu.exeris.tooling.codegen.core.PluggableBackend;
import eu.exeris.tooling.codegen.core.generator.BackendGenerator;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.sdk.sourcemodel.ast.DomainEventMetadata;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.FieldMetadata;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates domain event classes and event publisher for Exeris Kernel.
 *
 * <p>For each {@code @DomainEvent} annotation on the domain entity, generates:
 * <ul>
 *   <li>Event record class (immutable, serializable)</li>
 *   <li>Event publisher (integrates with kernel events module)</li>
 * </ul>
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelEventGenerator implements BackendGenerator {

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        if (!metadata.hasEvents()) {
            return null; // No events to generate
        }

        String packageName = metadata.packageName().replace(".domain", ".event");
        String className = metadata.entityName() + "Events";
        String entity = metadata.entityName();

        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");

        // Imports
        code.append("import ").append(metadata.packageName()).append(".").append(entity).append(";\n");
        code.append("import eu.exeris.kernel.events.store.DomainEvent;\n");
        code.append("import eu.exeris.kernel.events.store.EventStore;\n");
        code.append("import eu.exeris.kernel.events.outbox.OutboxSignal;\n");
        code.append("import eu.exeris.kernel.security.context.SecurityContext;\n");
        code.append("import eu.exeris.kernel.security.context.TenantContext;\n");
        code.append("import org.slf4j.Logger;\n");
        code.append("import org.slf4j.LoggerFactory;\n\n");
        code.append("import java.time.Instant;\n");
        code.append("import java.util.HashMap;\n");
        code.append("import java.util.List;\n");
        code.append("import java.util.Map;\n");
        code.append("import java.util.UUID;\n\n");

        // Class header
        code.append("/**\n");
        code.append(" * Domain events and publisher for ").append(entity).append(".\n");
        code.append(" * <p>Generated by Exeris Codegen. DO NOT EDIT.\n");
        code.append(" *\n");
        code.append(" * @see ").append(metadata.fullyQualifiedName()).append("\n");
        code.append(" */\n");
        code.append("public final class ").append(className).append(" {\n\n");
        code.append("    private static final Logger LOG = LoggerFactory.getLogger(").append(className).append(".class);\n\n");

        // Generate event record classes
        for (DomainEventMetadata event : metadata.events()) {
            generateEventRecord(code, event, metadata);
        }

        // Generate Publisher inner class
        generatePublisher(code, metadata);

        code.append("}\n");

        return new GeneratedFile(packageName, className, code.toString(), ArtifactType.EVENT);
    }

    private void generateEventRecord(StringBuilder code, DomainEventMetadata event, DomainMetadata metadata) {
        String eventName = event.name();
        if (eventName == null || eventName.isBlank()) {
            eventName = metadata.entityName() + "Event";
        }
        // Ensure it ends with "Event"
        if (!eventName.endsWith("Event")) {
            eventName = eventName + "Event";
        }

        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // ").append(eventName).append("\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        if (event.description() != null && !event.description().isBlank()) {
            code.append("     * ").append(event.description()).append("\n");
        } else {
            code.append("     * Domain event: ").append(eventName).append("\n");
        }
        if (event.topic() != null && !event.topic().isBlank()) {
            code.append("     * <p>Topic: {@code ").append(event.topic()).append("}\n");
        }
        code.append("     */\n");

        code.append("    public record ").append(eventName).append("(\n");
        code.append("            UUID eventId,\n");
        code.append("            Instant occurredAt,\n");
        code.append("            UUID aggregateId,\n");

        // Add entity-specific payload fields (subset of main fields)
        List<FieldMetadata> payloadFields = getPayloadFields(metadata);
        for (int i = 0; i < payloadFields.size(); i++) {
            FieldMetadata field = payloadFields.get(i);
            // Skip tenantId if it's a Tenant entity to avoid self-reference
            if (field.name().equals("tenantId") && metadata.entityName().equals("Tenant")) {
                continue;
            }
            code.append("            ").append(mapJavaType(field.type())).append(" ").append(field.name());
            if (i < payloadFields.size() - 1) {
                code.append(",");
            }
            code.append("\n");
        }

        code.append("    ) {\n\n");

        // Factory method from entity
        code.append("        public static ").append(eventName).append(" from(").append(metadata.entityName()).append(" entity) {\n");
        code.append("            return new ").append(eventName).append("(\n");
        code.append("                    UUID.randomUUID(),\n");
        code.append("                    Instant.now(),\n");
        code.append("                    entity.getId(),\n");
        for (int i = 0; i < payloadFields.size(); i++) {
            FieldMetadata field = payloadFields.get(i);
            if (field.name().equals("tenantId") && metadata.entityName().equals("Tenant")) {
                continue;
            }
            String getter = "get" + capitalize(field.name()) + "()";
            code.append("                    entity.").append(getter);
            if (i < payloadFields.size() - 1) {
                code.append(",");
            }
            code.append("\n");
        }
        code.append("            );\n");
        code.append("        }\n\n");

        // Convenience methods for DomainEvent construction
        code.append("        public String aggregateType() { return \"").append(metadata.entityName()).append("\"; }\n");
        code.append("        public String eventType() { return \"").append(eventName).append("\"; }\n");

        code.append("    }\n\n");
    }

    private void generatePublisher(StringBuilder code, DomainMetadata metadata) {
        String entity = metadata.entityName();

        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Event Publisher\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");

        code.append("    /**\n");
        code.append("     * Publisher for ").append(entity).append(" domain events.\n");
        code.append("     * <p>Uses transactional outbox pattern for reliable delivery.\n");
        code.append("     */\n");
        code.append("    public static class Publisher {\n\n");
        code.append("        private final EventStore eventStore;\n");
        code.append("        private final OutboxSignal outboxSignal;\n\n");

        code.append("        public Publisher(EventStore eventStore, OutboxSignal outboxSignal) {\n");
        code.append("            this.eventStore = eventStore;\n");
        code.append("            this.outboxSignal = outboxSignal;\n");
        code.append("        }\n\n");

        // Generate publish methods for each event
        for (DomainEventMetadata event : metadata.events()) {
            String eventName = getEventName(event, metadata);
            String methodName = "publish" + eventName.replace("Event", "");

            code.append("        /**\n");
            code.append("         * Publishes ").append(eventName).append(" to the event store.\n");
            code.append("         */\n");
            code.append("        public void ").append(methodName).append("(").append(eventName).append(" event) {\n");
            code.append("            LOG.debug(\"Publishing {}: aggregateId={}\", event.eventType(), event.aggregateId());\n");
            code.append("            \n");
            code.append("            // Get tenant from security context\n");
            code.append("            TenantContext ctx = SecurityContext.currentTenant();\n");
            code.append("            UUID tenantId = ctx != null ? ctx.tenantId() : null;\n");
            code.append("            \n");
            code.append("            // Build payload from event fields\n");
            code.append("            Map<String, Object> payload = new HashMap<>();\n");
            code.append("            payload.put(\"eventType\", event.eventType());\n");
            code.append("            payload.put(\"aggregateId\", event.aggregateId().toString());\n");
            code.append("            payload.put(\"occurredAt\", event.occurredAt().toString());\n");
            code.append("            \n");
            code.append("            // Get current stream version (use -1 for new streams)\n");
            code.append("            long currentVersion = eventStore.getStreamVersion(event.aggregateId(), tenantId);\n");
            code.append("            \n");
            code.append("            var domainEvent = DomainEvent.builder()\n");
            code.append("                    .eventId(event.eventId())\n");
            code.append("                    .streamId(event.aggregateId())\n");
            code.append("                    .aggregateType(event.aggregateType())\n");
            code.append("                    .aggregateId(event.aggregateId())\n");
            code.append("                    .eventType(event.eventType())\n");
            code.append("                    .payload(payload)\n");
            code.append("                    .tenantId(tenantId)\n");
            code.append("                    .occurredAt(event.occurredAt())\n");
            code.append("                    .build();\n");
            code.append("            \n");
            code.append("            eventStore.append(event.aggregateId(), currentVersion, List.of(domainEvent));\n");
            code.append("            outboxSignal.signalNewData();\n");
            code.append("        }\n\n");
        }

        // Convenience method to publish from entity
        code.append("        /**\n");
        code.append("         * Publishes a created event for the entity.\n");
        code.append("         */\n");
        code.append("        public void publishCreated(").append(entity).append(" entity) {\n");
        String createdEventName = entity + "CreatedEvent";
        code.append("            publish").append(entity).append("Created(").append(createdEventName).append(".from(entity));\n");
        code.append("        }\n\n");

        code.append("    }\n\n");
    }

    private List<FieldMetadata> getPayloadFields(DomainMetadata metadata) {
        if (metadata.fields() == null) {
            return List.of();
        }
        // Include key business fields, exclude system fields
        return metadata.fields().stream()
                .filter(f -> !isSystemField(f.name()))
                .filter(f -> f.searchable() || f.required())
                .limit(8) // Limit payload size
                .collect(Collectors.toList());
    }

    private boolean isSystemField(String name) {
        return name.equals("id") || name.equals("createdAt") || name.equals("updatedAt")
                || name.equals("createdBy") || name.equals("updatedBy") || name.equals("version")
                || name.equals("deletedAt") || name.equals("deletedBy");
    }

    private String getEventName(DomainEventMetadata event, DomainMetadata metadata) {
        String eventName = event.name();
        if (eventName == null || eventName.isBlank()) {
            eventName = metadata.entityName() + "Event";
        }
        if (!eventName.endsWith("Event")) {
            eventName = eventName + "Event";
        }
        return eventName;
    }

    private String mapJavaType(String type) {
        if (type == null) return "Object";
        return switch (type.toLowerCase()) {
            case "string" -> "String";
            case "uuid" -> "UUID";
            case "int", "integer" -> "Integer";
            case "long" -> "Long";
            case "boolean" -> "Boolean";
            case "instant", "datetime", "timestamp" -> "Instant";
            case "bigdecimal", "decimal" -> "java.math.BigDecimal";
            default -> type;
        };
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    @Override
    public PluggableBackend backend() {
        return PluggableBackend.KERNEL;
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.EVENT;
    }
}

