package eu.exeris.tooling.codegen.java.kernel;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.tooling.codegen.java.support.KernelScaffold;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;

import javax.lang.model.element.Modifier;

/**
 * Kernel Client Generator.
 *
 * <p>Generates clients for service-to-service communication. The generated
 * code uses {@code KernelWebClient}; the underlying transport (H1/H2/H3) is
 * an internal detail of the Kernel runtime and tier-dependent — Community
 * runs over H1/H2, the H3 path is Enterprise-only.
 *
 * <p>FQN target updated per ADR-034 (Client-Side Body Codec SPI +
 * {@code KernelWebClient} facade), which supersedes ADR-026. The facade
 * lives in {@code eu.exeris.kernel.core.http.client} — tier-neutral by
 * design so generated application source never encodes Community /
 * Enterprise tier identity.
 *
 * <p>Client-side retry (ADR-045) is a composition-root concern: the policy is
 * constructor-injected into {@code KernelWebClient} like the ADR-032 enricher,
 * so the emitted per-entity client carries no retry code. The emitted
 * constructor Javadoc shows the {@code CommunityHttpRetryPolicy} wiring as
 * documentation only — plain Javadoc text, never an import — so the generated
 * source stays tier-neutral (The Wall).
 *
 * @implNote Emission is JavaPoet-based (ADR-015).
 *
 * @see "docs/adr/ADR-034.link.md — link stub; kernel-side
 *      authoritative copy in exeris-kernel/docs/adr/. Target symbol:
 *      KernelWebClient (eu.exeris.kernel.core.http.client)."
 * @see "docs/adr/ADR-045.link.md — link stub; kernel-side
 *      authoritative copy in exeris-kernel/docs/adr/. Target symbol:
 *      HttpRetryPolicy (eu.exeris.kernel.spi.http), wired at the
 *      composition root, not per entity."
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelClientGenerator implements KernelArtifactGenerator {

    private static final ClassName WEB_CLIENT =
            ClassName.get("eu.exeris.kernel.core.http.client", "KernelWebClient");
    private static final ClassName WEB_CLIENT_EXCEPTION =
            ClassName.get("eu.exeris.kernel.core.http.client", "KernelWebClient", "WebClientException");
    private static final ClassName UUID = ClassName.get("java.util", "UUID");
    private static final ClassName OPTIONAL = ClassName.get("java.util", "Optional");
    private static final ClassName LIST = ClassName.get("java.util", "List");
    private static final ClassName VOID = ClassName.get("java.lang", "Void");

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        String packageName = metadata.packageName().replace(".domain", ".client");
        String entity = metadata.entityName();
        String className = entity + "Client";
        String apiPath = buildApiPath(metadata);

        ClassName entityType = ClassName.get(metadata.packageName(), entity);
        TypeName optionalOfEntity = ParameterizedTypeName.get(OPTIONAL, entityType);
        TypeName listOfEntity = ParameterizedTypeName.get(LIST, entityType);

        AnnotationSpec uncheckedSuppression = AnnotationSpec.builder(SuppressWarnings.class)
                .addMember("value", "$S", "unchecked")
                .build();

        TypeSpec client = KernelScaffold.publicClass(className)
                .addJavadoc("Generated client for the $L API.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("<p>Generated by Exeris Codegen. DO NOT EDIT.\n")
                .addJavadoc("\n")
                .addJavadoc("<p>Uses {@link $T} for service-to-service communication\n", WEB_CLIENT)
                .addJavadoc("with automatic JSON serialization and Virtual Thread support.\n")
                .addJavadoc("\n")
                .addJavadoc("@see $T\n", WEB_CLIENT)
                .addField(FieldSpec.builder(String.class, "BASE_PATH",
                                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("$S", apiPath)
                        .build())
                .addField(FieldSpec.builder(WEB_CLIENT, "client", Modifier.PRIVATE, Modifier.FINAL).build())
                .addMethod(buildConstructor(className))
                .addMethod(buildFindById(entity, entityType, optionalOfEntity))
                .addMethod(buildFindAllPaged(entity, listOfEntity, uncheckedSuppression))
                .addMethod(buildFindAll(entity, listOfEntity, uncheckedSuppression))
                .addMethod(buildCreate(entity, entityType))
                .addMethod(buildUpdate(entity, entityType))
                .addMethod(buildDelete(entity))
                .build();

        return new GeneratedFile(packageName, className,
                KernelScaffold.render(packageName, client), ArtifactType.CLIENT);
    }

    private MethodSpec buildConstructor(String className) {
        // ADR-045 composition-root example: retry is opt-in on the shared
        // KernelWebClient, never per-entity. CommunityHttpRetryPolicy and
        // HttpRetryPolicy appear as plain Javadoc text (no $T) so no import —
        // and no tier identity — lands in the compiled surface (The Wall).
        return MethodSpec.constructorBuilder()
                .addJavadoc("Creates a new $L.\n", className)
                .addJavadoc("\n")
                .addJavadoc("<p>Composition-root example (ADR-045): construct one shared\n")
                .addJavadoc("{@link $T} with a retry policy and every generated client\n", WEB_CLIENT)
                .addJavadoc("inherits retry semantics — no per-entity retry configuration:\n")
                .addJavadoc("<pre>{@code\n")
                .addJavadoc("var webClient = new KernelWebClient(engine, allocator,\n")
                .addJavadoc("        requestEncoders, responseDecoders,\n")
                .addJavadoc("        HttpClientRequestEnricher.noop(),\n")
                .addJavadoc("        new eu.exeris.kernel.community.http.CommunityHttpRetryPolicy());\n")
                .addJavadoc("var client = new $L(webClient);\n", className)
                .addJavadoc("}</pre>\n")
                .addJavadoc("Omit the policy argument (or pass {@code HttpRetryPolicy.none()})\n")
                .addJavadoc("to keep the no-implicit-retry default (ADR-026).\n")
                .addJavadoc("\n")
                .addJavadoc("@param client the web client (injected from CompositionRoot)\n")
                .addModifiers(Modifier.PUBLIC)
                .addParameter(WEB_CLIENT, "client")
                .addStatement("this.client = client")
                .build();
    }

    private MethodSpec buildFindById(String entity, ClassName entityType, TypeName optionalOfEntity) {
        return MethodSpec.methodBuilder("findById")
                .addJavadoc("Finds a $L by ID.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param id the entity ID\n")
                .addJavadoc("@return the entity or empty if not found\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(optionalOfEntity)
                .addParameter(UUID, "id")
                .beginControlFlow("try")
                .addStatement("return $T.ofNullable(client.get(BASE_PATH + $S + id, $T.class))",
                        OPTIONAL, "/", entityType)
                .nextControlFlow("catch ($T e)", WEB_CLIENT_EXCEPTION)
                .beginControlFlow("if (e.isNotFound())")
                .addStatement("return $T.empty()", OPTIONAL)
                .endControlFlow()
                .addStatement("throw e")
                .endControlFlow()
                .build();
    }

    private MethodSpec buildFindAllPaged(String entity, TypeName listOfEntity,
                                         AnnotationSpec uncheckedSuppression) {
        return MethodSpec.methodBuilder("findAll")
                .addJavadoc("Finds all $L entities with pagination.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param page page number (0-based)\n")
                .addJavadoc("@param size page size\n")
                .addJavadoc("@return list of entities\n")
                .addAnnotation(uncheckedSuppression)
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfEntity)
                .addParameter(TypeName.INT, "page")
                .addParameter(TypeName.INT, "size")
                .addStatement("String path = BASE_PATH + $S + page + $S + size", "?page=", "&size=")
                .addStatement("return client.get(path, $T.class)", LIST)
                .build();
    }

    private MethodSpec buildFindAll(String entity, TypeName listOfEntity,
                                    AnnotationSpec uncheckedSuppression) {
        return MethodSpec.methodBuilder("findAll")
                .addJavadoc("Finds all $L entities.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@return list of entities\n")
                .addAnnotation(uncheckedSuppression)
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfEntity)
                .addStatement("return client.get(BASE_PATH, $T.class)", LIST)
                .build();
    }

    private MethodSpec buildCreate(String entity, ClassName entityType) {
        return MethodSpec.methodBuilder("create")
                .addJavadoc("Creates a new $L.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param entity the entity to create\n")
                .addJavadoc("@return the created entity\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(entityType, "entity")
                .addStatement("return client.post(BASE_PATH, entity, $T.class)", entityType)
                .build();
    }

    private MethodSpec buildUpdate(String entity, ClassName entityType) {
        return MethodSpec.methodBuilder("update")
                .addJavadoc("Updates an existing $L.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param id the entity ID\n")
                .addJavadoc("@param entity the entity with updated data\n")
                .addJavadoc("@return the updated entity\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(UUID, "id")
                .addParameter(entityType, "entity")
                .addStatement("return client.patch(BASE_PATH + $S + id, entity, $T.class)", "/", entityType)
                .build();
    }

    private MethodSpec buildDelete(String entity) {
        return MethodSpec.methodBuilder("delete")
                .addJavadoc("Deletes a $L by ID.\n", entity)
                .addJavadoc("\n")
                .addJavadoc("@param id the entity ID\n")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(UUID, "id")
                .addStatement("client.delete(BASE_PATH + $S + id, $T.class)", "/", VOID)
                .build();
    }

    private String buildApiPath(DomainMetadata metadata) {
        String apiVersion = metadata.apiVersion() != null ? metadata.apiVersion() : "v1";
        // effectivePath() is the SDK-canonical derivation shared by every other
        // generator (OpenAPI, Application, DSL): explicit path, else "/" + kebab + "s".
        // Reusing it fixes the previously-dead fallback (the Builder defaults path to
        // "", so a hand-rolled `path() != null` guard never fired and a path-less
        // entity emitted a useless /api/<ver> root client) and keeps the client's base
        // path consistent with the rest of the generator suite.
        return "/api/" + apiVersion + metadata.effectivePath();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.CLIENT;
    }
}
