package eu.exeris.tooling.codegen.java.kernel;

import eu.exeris.tooling.codegen.core.generator.BackendGenerator;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.sdk.sourcemodel.ast.DomainEventMetadata;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;
import eu.exeris.sdk.sourcemodel.ast.SagaMetadata;

/**
 * Generates event handlers that trigger sagas based on domain events.
 *
 * <p>For each entity with both events and saga trigger configuration,
 * generates an event handler that:
 * <ul>
 *   <li>Listens for specific domain events</li>
 *   <li>Triggers the corresponding saga on event receipt</li>
 *   <li>Integrates with kernel event store</li>
 * </ul>
 *
 * @author Exeris Team
 * @since 0.1.0
 */
public class KernelEventHandlerGenerator implements BackendGenerator {

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        // Only generate if entity has saga with event trigger
        if (!metadata.isSaga() || metadata.sagaMetadata() == null) {
            return null;
        }

        SagaMetadata saga = metadata.sagaMetadata();
        // Check if saga has event-based trigger
        // For now, we generate for all sagas that have associated events
        if (!metadata.hasEvents()) {
            return null;
        }

        String packageName = metadata.packageName().replace(".domain", ".event");
        String className = metadata.entityName() + "EventHandler";
        String entity = metadata.entityName();
        String sagaName = saga.name() != null ? saga.name() : entity + "Saga";

        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");

        // Imports
        code.append("import ").append(metadata.packageName()).append(".").append(entity).append(";\n");
        code.append("import ").append(metadata.packageName().replace(".domain", ".saga")).append(".").append(sagaName).append(";\n");
        code.append("import eu.exeris.kernel.events.store.DomainEvent;\n");
        code.append("import eu.exeris.kernel.events.store.EventStore;\n");
        code.append("import org.slf4j.Logger;\n");
        code.append("import org.slf4j.LoggerFactory;\n\n");
        code.append("import java.util.Map;\n");
        code.append("import java.util.UUID;\n");
        code.append("import java.util.function.Consumer;\n\n");

        // Class header
        code.append("/**\n");
        code.append(" * Event handler for ").append(entity).append(" domain events.\n");
        code.append(" * <p>Triggers sagas and other reactions to domain events.\n");
        code.append(" * <p>Generated by Exeris Codegen. DO NOT EDIT.\n");
        code.append(" *\n");
        code.append(" * @see ").append(metadata.fullyQualifiedName()).append("\n");
        code.append(" * @see ").append(sagaName).append("\n");
        code.append(" */\n");
        code.append("public class ").append(className).append(" implements Consumer<DomainEvent> {\n\n");

        code.append("    private static final Logger LOG = LoggerFactory.getLogger(").append(className).append(".class);\n\n");

        // Dependencies
        code.append("    private final ").append(sagaName).append(" saga;\n");
        code.append("    private final EventStore eventStore;\n\n");

        // Constructor
        code.append("    public ").append(className).append("(").append(sagaName).append(" saga, EventStore eventStore) {\n");
        code.append("        this.saga = saga;\n");
        code.append("        this.eventStore = eventStore;\n");
        code.append("    }\n\n");

        // Main handler method
        code.append("    @Override\n");
        code.append("    public void accept(DomainEvent event) {\n");
        code.append("        if (!\"").append(entity).append("\".equals(event.aggregateType())) {\n");
        code.append("            return; // Not our event\n");
        code.append("        }\n\n");
        code.append("        LOG.debug(\"Handling event: {} for aggregate: {}\", event.eventType(), event.aggregateId());\n\n");

        // Route to specific handlers based on event type
        code.append("        switch (event.eventType()) {\n");
        for (DomainEventMetadata eventMeta : metadata.events()) {
            String eventName = getEventName(eventMeta, metadata);
            String handlerMethod = "handle" + eventName;
            code.append("            case \"").append(eventName).append("\" -> ").append(handlerMethod).append("(event);\n");
        }
        code.append("            default -> LOG.trace(\"Unhandled event type: {}\", event.eventType());\n");
        code.append("        }\n");
        code.append("    }\n\n");

        // Generate individual event handlers
        for (DomainEventMetadata eventMeta : metadata.events()) {
            generateEventHandler(code, eventMeta, metadata, sagaName);
        }

        // Event type constants
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n");
        code.append("    // Event Type Constants\n");
        code.append("    // ═══════════════════════════════════════════════════════════════════════════\n\n");
        for (DomainEventMetadata eventMeta : metadata.events()) {
            String eventName = getEventName(eventMeta, metadata);
            String constName = toConstantCase(eventName);
            code.append("    public static final String ").append(constName).append(" = \"").append(eventName).append("\";\n");
        }
        code.append("\n");

        // Topic constants
        code.append("    // Topics\n");
        for (DomainEventMetadata eventMeta : metadata.events()) {
            if (eventMeta.topic() != null && !eventMeta.topic().isBlank()) {
                String eventName = getEventName(eventMeta, metadata);
                String constName = toConstantCase(eventName) + "_TOPIC";
                code.append("    public static final String ").append(constName).append(" = \"").append(eventMeta.topic()).append("\";\n");
            }
        }

        code.append("}\n");

        return new GeneratedFile(packageName, className, code.toString(), ArtifactType.EVENT_HANDLER);
    }

    private void generateEventHandler(StringBuilder code, DomainEventMetadata eventMeta,
                                       DomainMetadata metadata, String sagaName) {
        String eventName = getEventName(eventMeta, metadata);
        String handlerMethod = "handle" + eventName;

        code.append("    /**\n");
        code.append("     * Handles ").append(eventName).append(".\n");
        if (eventMeta.description() != null && !eventMeta.description().isBlank()) {
            code.append("     * <p>").append(eventMeta.description()).append("\n");
        }
        code.append("     */\n");
        code.append("    private void ").append(handlerMethod).append("(DomainEvent event) {\n");
        code.append("        LOG.info(\"Processing {}: aggregateId={}\", event.eventType(), event.aggregateId());\n\n");

        // Check if this event should trigger the saga
        if (eventName.endsWith("CreatedEvent")) {
            // Created events typically trigger onboarding sagas
            code.append("        // Trigger saga on creation\n");
            code.append("        UUID entityId = event.aggregateId();\n");
            code.append("        UUID tenantId = event.tenantId();\n");
            code.append("        \n");
            code.append("        try {\n");
            code.append("            UUID sagaId = saga.start(entityId, tenantId != null ? tenantId : entityId);\n");
            code.append("            if (sagaId != null) {\n");
            code.append("                LOG.info(\"Started saga '{}' with ID: {} for entity: {}\", \n");
            code.append("                        \"").append(sagaName).append("\", sagaId, entityId);\n");
            code.append("            } else {\n");
            code.append("                LOG.warn(\"Saga '{}' already exists or could not be started for entity: {}\", \n");
            code.append("                        \"").append(sagaName).append("\", entityId);\n");
            code.append("            }\n");
            code.append("        } catch (Exception e) {\n");
            code.append("            LOG.error(\"Failed to start saga for event: {}\", event.eventType(), e);\n");
            code.append("        }\n");
        } else {
            // Other events - log and potentially trigger other actions
            code.append("        // Process event - implement custom logic as needed\n");
            code.append("        Map<String, Object> payload = event.payload();\n");
            code.append("        LOG.debug(\"Event payload: {}\", payload);\n");
            code.append("        \n");
            code.append("        // TODO: Add custom handling for ").append(eventName).append("\n");
        }

        code.append("    }\n\n");
    }

    private String getEventName(DomainEventMetadata event, DomainMetadata metadata) {
        String eventName = event.name();
        if (eventName == null || eventName.isBlank()) {
            eventName = metadata.entityName() + "Event";
        }
        if (!eventName.endsWith("Event")) {
            eventName = eventName + "Event";
        }
        return eventName;
    }

    private String toConstantCase(String s) {
        if (s == null || s.isEmpty()) return s;
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                result.append('_');
            }
            result.append(Character.toUpperCase(c));
        }
        return result.toString();
    }

    @Override
    public ArtifactType artifactType() {
        return ArtifactType.EVENT_HANDLER;
    }
}

