package eu.exeris.tooling.codegen.java.kernel;

import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator;
import eu.exeris.tooling.codegen.core.generator.KernelArtifactGenerator.ArtifactType;
import eu.exeris.tooling.codegen.core.generator.GeneratedFile;
import eu.exeris.sdk.sourcemodel.ast.DomainMetadata;

public class KernelServiceGenerator implements KernelArtifactGenerator {

    @Override
    public GeneratedFile generate(DomainMetadata metadata) {
        String packageName = metadata.packageName().replace(".domain", ".service");
        String className = metadata.entityName() + "Service";
        String repoName = metadata.entityName() + "Repository";
        String entity = metadata.entityName();
        boolean hasEvents = metadata.hasEvents();

        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");

        // Imports
        code.append("import ").append(metadata.packageName()).append(".").append(entity).append(";\n");
        code.append("import ").append(metadata.packageName().replace(".domain", ".repository")).append(".").append(repoName).append(";\n");
        if (hasEvents) {
            code.append("import ").append(metadata.packageName().replace(".domain", ".event")).append(".").append(entity).append("Events;\n");
        }
        code.append("import java.util.List;\n");
        code.append("import java.util.Optional;\n");
        code.append("import java.util.UUID;\n\n");

        // Javadoc
        code.append("/**\n");
        code.append(" * Service for ").append(entity).append(" domain operations.\n");
        if (hasEvents) {
            code.append(" * <p>Publishes domain events on entity lifecycle changes.\n");
        }
        code.append(" * <p>Generated by Exeris Codegen. DO NOT EDIT.\n");
        code.append(" */\n");

        code.append("public class ").append(className).append(" {\n\n");

        // Fields
        code.append("    private final ").append(repoName).append(" repository;\n");
        if (hasEvents) {
            code.append("    private final ").append(entity).append("Events.Publisher eventPublisher;\n");
        }
        code.append("\n");

        // Constructor
        if (hasEvents) {
            code.append("    public ").append(className).append("(").append(repoName).append(" repository, ")
                .append(entity).append("Events.Publisher eventPublisher) {\n");
            code.append("        this.repository = repository;\n");
            code.append("        this.eventPublisher = eventPublisher;\n");
            code.append("    }\n\n");
        } else {
            code.append("    public ").append(className).append("(").append(repoName).append(" repository) {\n");
            code.append("        this.repository = repository;\n");
            code.append("    }\n\n");
        }

        // CRUD methods
        code.append("    public Optional<").append(entity).append("> findById(UUID id) {\n");
        code.append("        return repository.findById(id);\n");
        code.append("    }\n\n");

        code.append("    public List<").append(entity).append("> findAll() {\n");
        code.append("        return repository.findAll();\n");
        code.append("    }\n\n");

        // Save with event publishing
        code.append("    public ").append(entity).append(" save(").append(entity).append(" entity) {\n");
        code.append("        ").append(entity).append(" saved = repository.save(entity);\n");
        if (hasEvents) {
            code.append("        eventPublisher.publishCreated(saved);\n");
        }
        code.append("        return saved;\n");
        code.append("    }\n\n");

        // Update (optionally with event)
        code.append("    public ").append(entity).append(" update(UUID id, ").append(entity).append(" entity) {\n");
        code.append("        ").append(entity).append(" updated = repository.update(id, entity);\n");
        code.append("        return updated;\n");
        code.append("    }\n\n");

        // Delete with event publishing
        code.append("    public void delete(UUID id) {\n");
        code.append("        repository.deleteById(id);\n");
        code.append("    }\n\n");

        code.append("    public long count() {\n");
        code.append("        return repository.count();\n");
        code.append("    }\n");

        code.append("}\n");

        return new GeneratedFile(packageName, className, code.toString(), ArtifactType.SERVICE);
    }

    @Override
    public ArtifactType artifactType() { return ArtifactType.SERVICE; }
}

